import { CertQuestion } from '../types';

export const ARCHITECT_AUTOMATION_QUESTIONS: CertQuestion[] = [
  {
    id: 'mstr_auto_01',
    section: 'automation',
    prompt: 'In high-scale enterprise systems, what is the risk of "cascading AI failures" across deeply interconnected agent microservices?',
    options: [
      { id: 'a', label: 'An early agent\'s undetected hallucination or format mutation propagates through downstream automated tools, causing systemic data corruption or unintended transactions.' },
      { id: 'b', label: 'Hardware cooling fans running at variable revolutions per minute.' },
      { id: 'c', label: 'Client web browsers resetting their theme settings.' },
      { id: 'd', label: 'Employees forgetting their single sign-on credentials.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_02',
    section: 'automation',
    prompt: 'How should an AI Architect implement "Circuit Breakers" in autonomous multi-agent pipelines?',
    options: [
      { id: 'a', label: 'Physical fuse boxes installed in workstation electrical outlets.' },
      { id: 'b', label: 'Erasing the git repository whenever a unit test fails in CI.' },
      { id: 'c', label: 'Permanently disconnecting internet access from the corporate campus.' },
      { id: 'd', label: 'Automatic kill-switches that halt agent execution and alert human operators when anomaly thresholds (e.g. error rate > 5%, cost spike > $50/min, unexpected API loop) are triggered.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_auto_03',
    section: 'automation',
    prompt: 'What is "vendor lock-in mitigation" in enterprise AI infrastructure?',
    options: [
      { id: 'a', label: 'Entering into 10-year exclusive enterprise licensing agreements with a single model vendor.' },
      { id: 'b', label: 'Abstracting model interactions behind a unified API interface layer (e.g. LiteLLM, LangChain/LlamaIndex providers) to allow swapping underlying model providers without rewriting business logic.' },
      { id: 'c', label: 'Refusing to use any third-party cloud infrastructure.' },
      { id: 'd', label: 'Locking server room doors with physical mechanical keys.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_auto_04',
    section: 'automation',
    prompt: 'When evaluating the total cost of ownership (TCO) between building custom agent pipelines in-house vs buying a commercial SaaS AI platform, what factors matter most?',
    options: [
      { id: 'a', label: 'Only the initial invoice price displayed on the vendor pricing webpage.' },
      { id: 'b', label: 'The number of animations on the vendor\'s landing page.' },
      { id: 'c', label: 'Maintenance overhead, integration complexity with core systems, proprietary data security, speed-to-market, and long-term differentiation vs commodity functionality.' },
      { id: 'd', label: 'The physical location of the vendor\'s headquarters.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_auto_05',
    section: 'automation',
    prompt: 'How should an organization manage "Prompt Versioning & CI/CD" across distributed product teams?',
    options: [
      { id: 'a', label: 'Treat prompts as version-controlled code artifacts (Git), run automated regression evaluations in CI pipelines before deployment, and support instant rollbacks.' },
      { id: 'b', label: 'Allow developers to modify production system prompts live in production web consoles.' },
      { id: 'c', label: 'Store system prompts exclusively in personal temporary browser tabs.' },
      { id: 'd', label: 'Freeze prompts permanently and forbid updates after the initial release.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_06',
    section: 'automation',
    prompt: 'What is the role of "Shadow Deployment" when introducing a major prompt or model upgrade in production?',
    options: [
      { id: 'a', label: 'Deploying software at night to reduce visibility among internal stakeholders.' },
      { id: 'b', label: 'Hiding release notes from executive leadership.' },
      { id: 'c', label: 'Running server instances with all monitor screens powered down.' },
      { id: 'd', label: 'Route real user traffic in parallel to the new model variant silently in the background, comparing its performance/latency against production without affecting live users.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_auto_07',
    section: 'automation',
    prompt: 'How does an Architect prevent "Context Window Bloat" from destroying pipeline economics in multi-turn customer sessions?',
    options: [
      { id: 'a', label: 'Terminating customer chat sessions unconditionally after 2 messages.' },
      { id: 'b', label: 'Implement structured hierarchical state compression: maintain a rolling high-density summary and key entity ledger rather than passing the raw transcript forever.' },
      { id: 'c', label: 'Requiring end-users to provide payment per token in real time.' },
      { id: 'd', label: 'Passing the full unbounded conversation history to the model on every single turn.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_auto_08',
    section: 'automation',
    prompt: 'What is the primary operational challenge of running local on-premise open-weight LLM clusters compared to managed cloud APIs?',
    options: [
      { id: 'a', label: 'Open-weight models cannot execute on Linux operating systems.' },
      { id: 'b', label: 'Local servers cannot establish standard TCP/IP network sockets.' },
      { id: 'c', label: 'High upfront hardware capital expenditure, complex GPU driver/vLLM orchestration, scaling bottlenecks during traffic spikes, and ongoing maintenance overhead.' },
      { id: 'd', label: 'Managed cloud APIs guarantee 100% zero latency under all worldwide traffic loads.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_auto_09',
    section: 'automation',
    prompt: 'In an autonomous agent architecture, why should tool execution logs be cryptographically signed or immutable?',
    options: [
      { id: 'a', label: 'Provides non-repudiable audit trails for compliance, security forensics, and legal accountability if an agent executes an unauthorized or erroneous state change.' },
      { id: 'b', label: 'Reduces database storage size by 99%.' },
      { id: 'c', label: 'Enables 3D graphical rendering of execution logs.' },
      { id: 'd', label: 'Converts log files automatically into encrypted audio tracks.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_10',
    section: 'automation',
    prompt: 'What is the primary indicator that an automated AI pipeline is ready for full production scale?',
    options: [
      { id: 'a', label: 'The pipeline executed without errors during a single internal demo meeting.' },
      { id: 'b', label: 'The marketing department published an official press release.' },
      { id: 'c', label: 'Executive management approved the feature concept.' },
      { id: 'd', label: 'Consistent passing of automated regression evals, bounded worst-case latency/cost, graceful error fallbacks, and validated guardrails under peak synthetic loads.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_auto_11',
    section: 'automation',
    prompt: 'In mission-critical financial automation, how does an Architect implement "Two-Phase Commit" (2PC) state validation for agentic operations?',
    options: [
      { id: 'a', label: 'Running the prompt through two separate browsers at the same time.' },
      { id: 'b', label: 'Phase 1 (Prepare): Agent generates and validates the proposed transaction ledger, asserting all pre-conditions; Phase 2 (Commit): External verified coordinator executes and seals the state mutation only after multi-factor human/system verification.' },
      { id: 'c', label: 'Deleting all database transaction logs after 1 millisecond.' },
      { id: 'd', label: 'Requiring developers to sign physical paper receipts.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_auto_12',
    section: 'automation',
    prompt: 'When building an automated multi-tenant SaaS platform where agents execute custom Python code, what is the safest execution model?',
    options: [
      { id: 'a', label: 'Execute code directly on the primary application server using `eval()` in Python.' },
      { id: 'b', label: 'Rely solely on regex filters to block malicious Python syntax.' },
      { id: 'c', label: 'MicroVM-isolated, ephemeral execution environments (e.g. AWS Firecracker, Fly Machines, gVisor) with network egress firewalls, strict memory/CPU caps, and instant teardown after execution.' },
      { id: 'd', label: 'Store all tenant code in a shared global namespace.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_auto_13',
    section: 'automation',
    prompt: 'How should an Architect design "Graceful Degradation" for a global customer service agent during a major cloud provider API outage?',
    options: [
      { id: 'a', label: 'Completely disconnect the corporate website from the internet.' },
      { id: 'b', label: 'Display a raw internal stack trace to all end users.' },
      { id: 'c', label: 'Instruct users to fix the cloud provider\'s servers.' },
      { id: 'd', label: 'Multi-tiered fallback: switch traffic automatically to a secondary cross-region LLM endpoint; if third-party APIs fail completely, degrade to deterministic FAQ search and enqueue inquiries into an urgent human queue with context intact.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_auto_14',
    section: 'automation',
    prompt: 'What is "Semantic Cache Invalidation" and how should it be governed in dynamic enterprise knowledge bases?',
    options: [
      { id: 'a', label: 'When underlying knowledge base articles or policies are updated, event triggers must immediately purge or re-index affected semantic vector clusters and cached prompt embeddings to prevent stale answers.' },
      { id: 'b', label: 'Deleting all database records at midnight every Sunday.' },
      { id: 'c', label: 'Asking users to clear their browser history.' },
      { id: 'd', label: 'Allowing models to return outdated answers forever.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_15',
    section: 'automation',
    prompt: 'In large-scale agent pipelines, what is "Agent Thundering Herd Problem" and how is it mitigated?',
    options: [
      { id: 'a', label: 'Too many developers typing prompts at the same time.' },
      { id: 'b', label: 'When thousands of concurrent agents experience simultaneous rate limits or cache misses and retry API endpoints synchronously; mitigated by exponential backoff with full jitter and request queuing.' },
      { id: 'c', label: 'Computer fans making excessive noise in the server room.' },
      { id: 'd', label: 'A sudden spike in user registration emails.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_auto_16',
    section: 'automation',
    prompt: 'Why is "Speculative Execution / Speculative Decoding" utilized in high-throughput LLM serving infrastructure (e.g. vLLM, TensorRT-LLM)?',
    options: [
      { id: 'a', label: 'To speculate on cryptocurrency financial markets.' },
      { id: 'b', label: 'To delete slow models from the cluster.' },
      { id: 'c', label: 'Using a small, ultra-fast draft model to generate candidate token sequences, verified in parallel by the target large model in a single forward pass, reducing generation latency by 2-3x.' },
      { id: 'd', label: 'To disable GPU tensor cores.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_auto_17',
    section: 'automation',
    prompt: 'How should an Architect structure an "Agent Tool Registry" for an organization with 500+ microservice endpoints?',
    options: [
      { id: 'a', label: 'Put all 500 tools into every prompt indiscriminately.' },
      { id: 'b', label: 'Hardcode tool definitions directly inside client HTML files.' },
      { id: 'c', label: 'Forbid agents from using more than 1 tool.' },
      { id: 'd', label: 'A centralized schema registry with RBAC authorization scopes, OpenAPI auto-generation, semantic search retrieval of tools relevant to active user intent, and telemetry logging on invocation.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_auto_18',
    section: 'automation',
    prompt: 'What constitutes an "Anti-Pattern" in automated Agent State Graph design?',
    options: [
      { id: 'a', label: 'Creating cyclic unbounded state transitions without explicit loop counter guards, termination conditions, or cycle-detection timeouts.' },
      { id: 'b', label: 'Enforcing strict Pydantic validation on node outputs.' },
      { id: 'c', label: 'Maintaining an immutable state history log.' },
      { id: 'd', label: 'Adding human approval checkpoints for irreversible mutations.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_19',
    section: 'automation',
    prompt: 'When evaluating "Self-Hosted Open-Weight Models (e.g. Llama-3-70B)" vs "Proprietary Hosted APIs", what architectural cost inflection point matters?',
    options: [
      { id: 'a', label: 'Self-hosting is always 100% cheaper regardless of request volume.' },
      { id: 'b', label: 'At low-to-medium query volume, managed APIs offer lower TCO and zero ops overhead; at steady-state millions of daily tokens with strict data-residency mandates, dedicated GPU clusters become cost-efficient and compliant.' },
      { id: 'c', label: 'Proprietary APIs cannot be called from Python code.' },
      { id: 'd', label: 'Self-hosted models cannot output JSON syntax.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_auto_20',
    section: 'automation',
    prompt: 'What is the ultimate milestone of an Architect-grade automated AI ecosystem?',
    options: [
      { id: 'a', label: 'Replacing all human employees with unmonitored scripts.' },
      { id: 'b', label: 'Maximizing the number of API calls per second regardless of business utility.' },
      { id: 'c', label: 'A resilient, observable, cost-calibrated, and secure autonomous infrastructure where AI amplifies enterprise velocity while maintaining strict human-in-the-loop governance and zero data loss.' },
      { id: 'd', label: 'Writing prompts using only emoji icons.' },
    ],
    correctOptionId: 'c',
  },
];

