import { CertQuestion } from '../types';

export const ARCHITECT_GROWTH_QUESTIONS: CertQuestion[] = [
  {
    id: 'mstr_gro_01',
    section: 'growth',
    prompt: 'What is the ultimate responsibility of a Jnachi Master (Architect) within an organization or community?',
    options: [
      { id: 'a', label: 'To lead with critical judgment—elevating team AI literacy, championing ethical and robust architectures, knowing when NOT to use AI, and unlocking sustainable human-AI momentum.' },
      { id: 'b', label: 'To replace all human employees with autonomous scripts regardless of performance.' },
      { id: 'c', label: 'To memorize the highest number of prompt templates without implementing systems.' },
      { id: 'd', label: 'To draft the longest system prompt strings possible.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_02',
    section: 'growth',
    prompt: 'How should an AI Architect design an ongoing continuous learning culture in a fast-evolving AI landscape?',
    options: [
      { id: 'a', label: 'Mandate that engineering teams read only 10-year-old textbooks.' },
      { id: 'b', label: 'Establish weekly practical hackathons, empirical benchmark reviews of new model capabilities, shared prompt repository audits, and cross-team knowledge sharing.' },
      { id: 'c', label: 'Prohibit all internal research into newly released open-weight model architectures.' },
      { id: 'd', label: 'Rely solely on marketing brochures from external commercial vendors.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_gro_03',
    section: 'growth',
    prompt: 'When an executive asks: "Can we replace our entire customer support staff with an LLM by next month?", what is the Master Architect\'s response?',
    options: [
      { id: 'a', label: '"Yes, let\'s terminate all customer support contracts immediately without testing."' },
      { id: 'b', label: '"No, AI will never be able to assist in customer support under any circumstance."' },
      { id: 'c', label: '"Let\'s purchase 10,000 servers before conducting any prompt testing."' },
      { id: 'd', label: 'Provide an evidence-based roadmap: start with human-in-the-loop agent copilot tooling, measure deflection vs escalation accuracy, establish guardrails, and scale incrementally based on data.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_gro_04',
    section: 'growth',
    prompt: 'How does an Architect evaluate whether an AI feature delivers genuine ROI vs superficial novelty?',
    options: [
      { id: 'a', label: 'Count the frequency of AI marketing buzzwords on promotional material.' },
      { id: 'b', label: 'Assume all generative features produce positive financial returns automatically.' },
      { id: 'c', label: 'Measure concrete business metrics: task completion velocity, error reduction rate, cost per resolved transaction, and net user satisfaction against the total operational expenditure.' },
      { id: 'd', label: 'Monitor social media impression counts exclusively.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_gro_05',
    section: 'growth',
    prompt: 'What is "model calibration drift" and how does an Architect detect it before it affects customers?',
    options: [
      { id: 'a', label: 'When the statistical distribution of real-world inputs shifts away from the validation dataset, causing confidence scores and accuracy to decouple; detected via continuous distribution monitoring.' },
      { id: 'b', label: 'When server hardware cooling fans run at lower RPM during winter.' },
      { id: 'c', label: 'When user input devices lose Bluetooth wireless connection.' },
      { id: 'd', label: 'When cloud billing tokens run out unexpectedly.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_06',
    section: 'growth',
    prompt: 'In high-reliability organizations, what is the concept of "Graceful Degradation" for AI systems?',
    options: [
      { id: 'a', label: 'The screen slowly fading to black upon network disconnection.' },
      { id: 'b', label: 'Erasing customer records gracefully to prevent database bloat.' },
      { id: 'c', label: 'Displaying decorative poetry to users during application crashes.' },
      { id: 'd', label: 'When AI models experience API timeouts or high error rates, the system seamlessly falls back to rule-based heuristics or manual human queues without crashing or losing user state.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_gro_07',
    section: 'growth',
    prompt: 'How should an AI Master handle disagreement among team members regarding which model provider to standardize on?',
    options: [
      { id: 'a', label: 'Select whichever vendor has the largest advertisement billboard.' },
      { id: 'b', label: 'Conduct an empirical bake-off using the team\'s specific domain test suite, comparing accuracy, latency, cost per 1k tokens, uptime SLA, and contract terms objectively.' },
      { id: 'c', label: 'Permit the most senior engineer to decide based solely on personal intuition.' },
      { id: 'd', label: 'Switch between model providers randomly on every HTTP request.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_gro_08',
    section: 'growth',
    prompt: 'Why is "Mentorship and Talent Uplift" a core pillar of the Jnachi Master Architect credential?',
    options: [
      { id: 'a', label: 'To hoard architectural knowledge within an isolated elite group.' },
      { id: 'b', label: 'To offload all implementation tasks to entry-level engineers.' },
      { id: 'c', label: 'True mastery is measured not just by individual skill, but by the ability to systematically elevate organizational capability, instill critical thinking, and build a high-momentum team.' },
      { id: 'd', label: 'To present executive keynotes without engaging in system design.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_gro_09',
    section: 'growth',
    prompt: 'What is the relationship between AI capability and human domain expertise?',
    options: [
      { id: 'a', label: 'AI acts as a cognitive lever: the deeper the human\'s domain expertise and critical discernment, the more transformative and effective the AI acceleration becomes.' },
      { id: 'b', label: 'AI eliminates the necessity for human domain expertise completely.' },
      { id: 'c', label: 'Deep human domain expertise impedes effective AI model reasoning.' },
      { id: 'd', label: 'Generative models perform optimally when configured by users with zero context.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_10',
    section: 'growth',
    prompt: 'What is the Jnachi motto that encapsulates the entire 4-tier journey?',
    options: [
      { id: 'a', label: 'Hype it. Buy it. Forget it.' },
      { id: 'b', label: 'Prompt it. Trust it. Deploy it.' },
      { id: 'c', label: 'Automate everything blindly.' },
      { id: 'd', label: 'Know it. Use it. Prove it.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_gro_11',
    section: 'growth',
    prompt: 'When evaluating "AI Readiness" across an enterprise with 50 disparate business units, what architectural framework should the Architect use?',
    options: [
      { id: 'a', label: 'Mandating that all 50 units immediately adopt the exact same chatbot tool on day one.' },
      { id: 'b', label: 'A tiered maturity matrix evaluating data cleanliness & accessibility, process standardization, risk exposure/compliance constraints, and staff baseline AI fluency.' },
      { id: 'c', label: 'Assigning AI readiness scores based on unit budget size alone.' },
      { id: 'd', label: 'Waiting until all competitors have completed full digital transformation.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_gro_12',
    section: 'growth',
    prompt: 'How should an Architect prevent the "Pilot Purgatory" trap (where dozens of AI POCs are built but none achieve production scale)?',
    options: [
      { id: 'a', label: 'Ban all prototyping and proof-of-concept experiments.' },
      { id: 'b', label: 'Allow prototypes to run indefinitely without production SLAs.' },
      { id: 'c', label: 'Establish strict graduation criteria at inception: clear business KPI targets, production security/data review gates, target unit economics, and executive business sponsor commitment.' },
      { id: 'd', label: 'Increase the number of POCs to 500 simultaneously.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_gro_13',
    section: 'growth',
    prompt: 'In high-velocity engineering organizations, what is the role of an "Internal AI Center of Excellence" (CoE)?',
    options: [
      { id: 'a', label: 'To act as a bureaucratic bottleneck that rejects all software pull requests.' },
      { id: 'b', label: 'To hoard AI licenses for executive staff only.' },
      { id: 'c', label: 'To write all prompt strings for the entire enterprise manually.' },
      { id: 'd', label: 'To standardize best practices, curate shared prompt/tool libraries, establish security/evaluation baselines, conduct internal upskilling, and accelerate high-impact cross-team initiatives.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_gro_14',
    section: 'growth',
    prompt: 'When an organization experiences an unexpected surge in AI compute expenses ("Cloud Bill Shock"), what immediate intervention protocol should an Architect initiate?',
    options: [
      { id: 'a', label: 'Audit telemetry traces to identify high-token runaway loops, enforce semantic caching, implement model tier cascading (route 80% of volume to small/fast models), and establish per-tenant rate/budget caps.' },
      { id: 'b', label: 'Terminate all corporate cloud subscriptions immediately and cancel the project.' },
      { id: 'c', label: 'Ignore the bill until the end of the fiscal year.' },
      { id: 'd', label: 'Ask developers to stop typing in complete sentences.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_15',
    section: 'growth',
    prompt: 'How should an AI Architect foster psychological safety and constructive inquiry when junior team members encounter unexpected model hallucinations?',
    options: [
      { id: 'a', label: 'Reprimand the engineer publicly and forbid them from experimenting.' },
      { id: 'b', label: 'Conduct blameless post-mortems: analyze the failure as a systemic context/retrieval or guardrail flaw, turn it into a shared test case in the golden eval suite, and celebrate rigorous debugging.' },
      { id: 'c', label: 'Hide the hallucination incident from other team members.' },
      { id: 'd', label: 'Assign blame to the foundation model company exclusively.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_gro_16',
    section: 'growth',
    prompt: 'What is the strategic value of "Open-Source / Open-Weight AI Sovereignty" for nations and regulated multinational enterprises?',
    options: [
      { id: 'a', label: 'Open-weight models are always 100% free of any compute hosting costs.' },
      { id: 'b', label: 'Open-weight models eliminate the need for software engineering teams.' },
      { id: 'c', label: 'Complete data privacy, immunity from third-party vendor policy changes or sudden price hikes, on-premise air-gapped security, and jurisdictional compliance control.' },
      { id: 'd', label: 'Open-weight models require zero GPU hardware to run.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_gro_17',
    section: 'growth',
    prompt: 'When architecting systems around rapidly shifting frontier model capabilities, what design philosophy ensures long-term system durability?',
    options: [
      { id: 'a', label: 'Hardcoding business logic around one specific model\'s exact quirks.' },
      { id: 'b', label: 'Writing prompt strings that exceed 100,000 words.' },
      { id: 'c', label: 'Refusing to upgrade models after initial release.' },
      { id: 'd', label: 'Decoupled, modular architecture: clean abstraction boundaries between business logic, orchestration graphs, evaluation harnesses, and interchangeable model providers.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_gro_18',
    section: 'growth',
    prompt: 'How does an Architect cultivate "Systems Thinking" in software engineers transitioning from traditional CRUD development to AI engineering?',
    options: [
      { id: 'a', label: 'Shifting mindsets from deterministic input/output assumptions to probabilistic distributions, statistical evaluation suites, feedback loops, guardrails, and graceful failure handling.' },
      { id: 'b', label: 'Teaching them how to write longer SQL queries.' },
      { id: 'c', label: 'Forbidding them from using version control systems.' },
      { id: 'd', label: 'Requiring them to memorize machine code binary tables.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_19',
    section: 'growth',
    prompt: 'What role does an AI Architect play in shaping ethical public AI literacy and community standards?',
    options: [
      { id: 'a', label: 'Promoting sensationalized apocalyptic or utopian AI clickbait on social media.' },
      { id: 'b', label: 'Demystifying AI hype, advocating for evidence-based governance, mentoring diverse newcomers, and demonstrating that true technological mastery serves human flourishing.' },
      { id: 'c', label: 'Keeping all AI knowledge secret from the broader public.' },
      { id: 'd', label: 'Encouraging uncritical adoption of every new AI software product.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_gro_20',
    section: 'growth',
    prompt: 'What is the pinnacle definition of reaching the Jnachi Master (Architect) tier?',
    options: [
      { id: 'a', label: 'Having the highest prompt generation speed in words per minute.' },
      { id: 'b', label: 'Owning the most expensive GPU workstations.' },
      { id: 'c', label: 'A verified master practitioner who combines deep technical craftsmanship, rigorous architectural discipline, unwavering ethical judgment, and transformative leadership that elevates teams from AI curiosity to world-class mastery.' },
      { id: 'd', label: 'Replacing human thought with unverified automated generation.' },
    ],
    correctOptionId: 'c',
  },
];

