import { CertQuestion, CertSection } from '../types';
import { ARCHITECT_LITERACY_QUESTIONS } from './literacy';
import { ARCHITECT_AUTOMATION_QUESTIONS } from './automation';
import { ARCHITECT_PRIVACY_QUESTIONS } from './privacy';
import { ARCHITECT_GROWTH_QUESTIONS } from './growth';

export {
  ARCHITECT_LITERACY_QUESTIONS,
  ARCHITECT_AUTOMATION_QUESTIONS,
  ARCHITECT_PRIVACY_QUESTIONS,
  ARCHITECT_GROWTH_QUESTIONS,
};

export const ARCHITECT_QUESTIONS_BY_SECTION: Record<CertSection, CertQuestion[]> = {
  literacy: ARCHITECT_LITERACY_QUESTIONS,
  automation: ARCHITECT_AUTOMATION_QUESTIONS,
  privacy: ARCHITECT_PRIVACY_QUESTIONS,
  growth: ARCHITECT_GROWTH_QUESTIONS,
};

export const ALL_ARCHITECT_QUESTIONS: CertQuestion[] = [
  ...ARCHITECT_LITERACY_QUESTIONS,
  ...ARCHITECT_AUTOMATION_QUESTIONS,
  ...ARCHITECT_PRIVACY_QUESTIONS,
  ...ARCHITECT_GROWTH_QUESTIONS,
];

// Aliases for Master tier terminology
export const MASTER_QUESTIONS_BY_SECTION = ARCHITECT_QUESTIONS_BY_SECTION;
export const ALL_MASTER_QUESTIONS = ALL_ARCHITECT_QUESTIONS;
