import { CertQuestion } from '../types';

export const ARCHITECT_LITERACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'mstr_lit_01',
    section: 'literacy',
    prompt: 'Under what conditions should an AI Architect advise an enterprise team to EXPLICITLY NOT use a generative AI model for a software feature?',
    options: [
      { id: 'a', label: 'When the problem requires deterministic 100% mathematical precision, has strict legal liability for any non-auditable error, and can be solved by classic algorithms or database queries.' },
      { id: 'b', label: 'Whenever the application has a large infrastructure budget.' },
      { id: 'c', label: 'Exclusively when cloud servers operate under high load.' },
      { id: 'd', label: 'Generative AI should always be used for 100% of software features without exception.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_02',
    section: 'literacy',
    prompt: 'What is "model collapse" in synthetic AI training loops?',
    options: [
      { id: 'a', label: 'Physical server hardware failure in enterprise GPU racks.' },
      { id: 'b', label: 'A GPU thermal throttling event during gradient descent backpropagation.' },
      { id: 'c', label: 'A sudden decline in customer adoption of a SaaS platform.' },
      { id: 'd', label: 'Degeneration in model output diversity and accuracy when future generations of models are recursively trained on synthetic data produced by earlier models without sufficient human ground truth.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_lit_03',
    section: 'literacy',
    prompt: 'How should an AI Architect design an automated auditing framework for detecting subtle semantic drift in mission-critical prompts?',
    options: [
      { id: 'a', label: 'Wait for customer legal complaints before initiating prompt reviews.' },
      { id: 'b', label: 'Continuous shadow evaluation: run a golden test dataset through production prompts daily, asserting semantic similarity against canonical embeddings and statistical variance thresholds.' },
      { id: 'c', label: 'Visually inspect prompt string definitions once every two years.' },
      { id: 'd', label: 'Assume system prompts never drift if the underlying model name remains unchanged.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_lit_04',
    section: 'literacy',
    prompt: 'What is the risk of "cognitive offloading" when engineering teams rely excessively on automated AI generation without critical code reviews?',
    options: [
      { id: 'a', label: 'Engineers increase their typing velocity beyond operating system thresholds.' },
      { id: 'b', label: 'Generated software takes up less binary storage space on disk.' },
      { id: 'c', label: 'Erosion of deep domain understanding, inability to debug subtle architectural flaws, and accumulation of fragile technical debt.' },
      { id: 'd', label: 'Automated compilers terminate without logging output.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_lit_05',
    section: 'literacy',
    prompt: 'In prompt security, what is "jailbreaking via token smuggling / base64 obfuscation"?',
    options: [
      { id: 'a', label: 'Adversaries encode harmful payloads into alternative formats (Base64, rot13, foreign languages) to bypass shallow string-matching safety filters during input ingestion.' },
      { id: 'b', label: 'Physical theft of GPU accelerator cards from server centers.' },
      { id: 'c', label: 'Passing cryptographic security keys through URL query strings.' },
      { id: 'd', label: 'Clearing browser cookies and cache files during active sessions.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_06',
    section: 'literacy',
    prompt: 'How should an Architect mentor junior engineers who treat LLM outputs as infallible ground truth?',
    options: [
      { id: 'a', label: 'Instruct them to disable all automated unit tests in CI/CD.' },
      { id: 'b', label: 'Validate their belief that frontier models never produce hallucinated logic.' },
      { id: 'c', label: 'Encourage them to deploy uninspected code directly to production.' },
      { id: 'd', label: 'Establish a "Zero Trust" verification protocol: require evidence citations, cross-verification with deterministic tests, and rigorous edge-case exploration.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_lit_07',
    section: 'literacy',
    prompt: 'What is the difference between "epistemic uncertainty" (lack of knowledge) and "aleatoric uncertainty" (inherent randomness) in LLM evaluations?',
    options: [
      { id: 'a', label: 'They are identical statistical terms with zero practical distinction in machine learning.' },
      { id: 'b', label: 'Epistemic uncertainty can be reduced by providing relevant retrieved context; aleatoric uncertainty stems from probabilistic token generation across valid alternative phrasings.' },
      { id: 'c', label: 'Aleatoric uncertainty is resolved exclusively by provisioning additional CPU memory.' },
      { id: 'd', label: 'Epistemic uncertainty occurs only in non-relational database schemas.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_lit_08',
    section: 'literacy',
    prompt: 'When evaluating multi-billion parameter frontier models vs compact edge models, what architectural trade-off governs the decision?',
    options: [
      { id: 'a', label: 'Compact models are unconditionally superior across all complex reasoning domains.' },
      { id: 'b', label: 'Frontier models cannot execute in enterprise cloud environments.' },
      { id: 'c', label: 'Frontier models provide supreme generalized reasoning and world knowledge; compact models offer low latency, deterministic throughput, on-prem privacy, and predictable unit cost.' },
      { id: 'd', label: 'Edge models require zero electrical power to perform inference.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_lit_09',
    section: 'literacy',
    prompt: 'What constitutes an effective "Red Teaming" exercise for an enterprise customer-facing AI agent?',
    options: [
      { id: 'a', label: 'Adversarial human and automated testing designed to probe for prompt injections, data extraction, toxic outputs, competitor endorsement, and safety boundary violations.' },
      { id: 'b', label: 'Testing the agent using only compliant, friendly user queries in staging.' },
      { id: 'c', label: 'Painting workstation monitors and physical server racks red.' },
      { id: 'd', label: 'Limiting agent access strictly to internal marketing staff.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_10',
    section: 'literacy',
    prompt: 'How does an Architect establish a formal "AI Style & Ethics Guide" for an organization?',
    options: [
      { id: 'a', label: 'Prohibit all employees from utilizing digital communication tools.' },
      { id: 'b', label: 'Delegate all governance decisions to autonomous chatbot agents.' },
      { id: 'c', label: 'Permit individual teams to deploy unvetted AI tools without central guidelines.' },
      { id: 'd', label: 'Define brand voice parameters, mandatory citation rules, safety guardrails, copyright attribution protocols, and clear escalation paths for ambiguous outputs.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_lit_11',
    section: 'literacy',
    prompt: 'When evaluating a proposed enterprise AI initiative, how should an Architect assess "Technical Debt Accumulation" in probabilistic software?',
    options: [
      { id: 'a', label: 'Technical debt only exists in legacy COBOL systems and cannot occur in AI.' },
      { id: 'b', label: 'AI technical debt stems from non-deterministic glue code, hidden feedback loops, pipeline jungles, data drift vulnerability, and unversioned prompt dependencies.' },
      { id: 'c', label: 'Technical debt is eliminated completely by buying higher tier API subscriptions.' },
      { id: 'd', label: 'Technical debt can be measured solely by counting lines of Python code.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_lit_12',
    section: 'literacy',
    prompt: 'What is the "Curse of Recursion" in automated synthetic feedback loops (e.g. RLHF/RLAIF on AI-generated labels)?',
    options: [
      { id: 'a', label: 'A recursion error in Python call stacks when functions exceed 1,000 frames.' },
      { id: 'b', label: 'Computers running out of hard drive space when saving log files.' },
      { id: 'c', label: 'When models are trained iteratively on their own synthetic critiques, idiosyncratic biases, linguistic quirks, and blind spots amplify exponentially while factual ground-truth fidelity degrades.' },
      { id: 'd', label: 'A database deadlocking on concurrent transaction updates.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_lit_13',
    section: 'literacy',
    prompt: 'How should an AI Architect design a "Disaster Recovery & Non-AI Fallback Architecture" for a mission-critical automated healthcare triage pipeline?',
    options: [
      { id: 'a', label: 'Assume the AI cloud provider maintains 100.000% uptime with zero outages.' },
      { id: 'b', label: 'If the AI API fails, shut down the hospital registration desk.' },
      { id: 'c', label: 'Route all patients to emergency surgery upon API timeout.' },
      { id: 'd', label: 'Maintain a deterministic rules engine (e.g., standard clinical triage protocols) that activates instantly upon AI API timeout, circuit-breaker trip, or latency threshold breach.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_lit_14',
    section: 'literacy',
    prompt: 'In frontier LLM alignment research, what is "Superficial Alignment Hypothesis"?',
    options: [
      { id: 'a', label: 'The hypothesis that pre-training learns almost all knowledge and reasoning capabilities, while post-training alignment (RLHF/SFT) mostly teaches style, formatting, and sub-distribution selection.' },
      { id: 'b', label: 'The idea that AI models should only be used for superficial cosmetic tasks.' },
      { id: 'c', label: 'The belief that GPU servers must be cleaned daily to prevent dust.' },
      { id: 'd', label: 'The assumption that all models think identically to humans.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_15',
    section: 'literacy',
    prompt: 'When evaluating "Goodhart\'s Law" in LLM automated benchmark evaluation ("When a measure becomes a target, it ceases to be a good measure"), what risk must architects anticipate?',
    options: [
      { id: 'a', label: 'Benchmark tests running out of electrical battery power.' },
      { id: 'b', label: 'Model developers and prompt engineers optimizing narrow benchmark metrics (e.g. MMLU, GSM8k) through test-set contamination or overfitting, while real-world production generalization remains brittle.' },
      { id: 'c', label: 'Benchmarks deleting all user chat histories.' },
      { id: 'd', label: 'Software compilers refusing to run benchmark evaluation scripts.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_lit_16',
    section: 'literacy',
    prompt: 'How should an Architect approach the trade-off between "Model Latency Budget" and "Chain-of-Thought Reasoning Depth"?',
    options: [
      { id: 'a', label: 'Always force maximum 10,000-token reasoning traces for simple binary yes/no questions.' },
      { id: 'b', label: 'Never allow models to generate reasoning tokens under any circumstances.' },
      { id: 'c', label: 'Calibrate reasoning budget by task complexity: use direct zero-shot classification for low-latency interactive UI loops (<200ms SLA), and allocate deep CoT/agentic search only for asynchronous high-judgment analytical workflows.' },
      { id: 'd', label: 'Latency has zero relationship with generated output token count.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_lit_17',
    section: 'literacy',
    prompt: 'What constitutes an "Anti-Pattern" in enterprise AI Knowledge Management?',
    options: [
      { id: 'a', label: 'Indexing verified, versioned documentation in a vector database.' },
      { id: 'b', label: 'Enforcing RBAC access controls on confidential intellectual property.' },
      { id: 'c', label: 'Tracking context retrieval precision and recall metrics.' },
      { id: 'd', label: 'Dumping raw uncurated Slack channels, duplicate outdated wikis, and draft notes into a monolithic RAG index without document lifecycle curation or authority ranking.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_lit_18',
    section: 'literacy',
    prompt: 'What is "Prompt Inversion / Extraction Defense" in commercial proprietary agent products?',
    options: [
      { id: 'a', label: 'Techniques including system prompt token scrambling, post-processing output monitors for leakage phrases, and parameterizing core IP into backend external microservices rather than exposing business logic in plaintext system prompts.' },
      { id: 'b', label: 'Encrypting the user\'s keyboard hardware.' },
      { id: 'c', label: 'Refusing to answer any customer queries.' },
      { id: 'd', label: 'Deleting the product source code from GitHub.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_19',
    section: 'literacy',
    prompt: 'When presenting an AI architecture roadmap to non-technical C-suite executives, what narrative structure is most effective?',
    options: [
      { id: 'a', label: 'Explaining transformer multi-head self-attention matrix equations in technical detail.' },
      { id: 'b', label: 'Framing capabilities around strategic business outcomes, risk governance, operational unit economics (ROI/cost-per-work-unit), and human-in-the-loop accountability.' },
      { id: 'c', label: 'Promising that AI will replace 100% of human staff within 3 months.' },
      { id: 'd', label: 'Demanding an unlimited open-ended budget without milestone deliverables.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_lit_20',
    section: 'literacy',
    prompt: 'What distinguishes the judgment of a Jnachi Master / Architect from all preceding tiers?',
    options: [
      { id: 'a', label: 'They know how to write basic prompt templates.' },
      { id: 'b', label: 'They have memorized the API parameters of common cloud LLMs.' },
      { id: 'c', label: 'They possess supreme systems judgment: knowing when NOT to use AI, architecting resilient multi-agent ecosystems, enforcing ethical safety boundaries, and guiding organizational transformation with sustainable rigor.' },
      { id: 'd', label: 'They believe artificial intelligence is omnipotent and requires no human oversight.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_lit_21',
    section: 'literacy',
    prompt: 'When deciding whether to adopt a proprietary Closed-Weight API (e.g. OpenAI / Anthropic) vs self-hosting an Open-Weight Model (e.g. Llama 3 / Mistral), what key strategic factor governs TCO (Total Cost of Ownership)?',
    options: [
      { id: 'a', label: 'Query volume scale break-even: APIs are cheapest at low/variable volumes with zero operational DevOps overhead; self-hosted clusters become cost-effective only when sustained token volume justifies dedicated GPU cluster amortization.' },
      { id: 'b', label: 'Open-weight models never require GPU hardware.' },
      { id: 'c', label: 'Proprietary APIs are always legally illegal in enterprise settings.' },
      { id: 'd', label: 'There is no difference in cost or operational complexity.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_22',
    section: 'literacy',
    prompt: 'In enterprise cognitive architecture, what is "Compound AI Systems" paradigm (Zaharia et al., Berkeley BAIR)?',
    options: [
      { id: 'a', label: 'State-of-the-art results are achieved not by a single monolithic LLM, but by modular systems combining multiple interacting components (retrievers, code sandboxes, verifiers, multi-model pipelines, and state stores).' },
      { id: 'b', label: 'A chemical compound synthesis simulator.' },
      { id: 'c', label: 'Connecting two computer mice to the same screen.' },
      { id: 'd', label: 'Running AI models solely on financial compound interest calculations.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_23',
    section: 'literacy',
    prompt: 'What is the "Capabilities vs Alignment Tax" in enterprise frontier model deployments?',
    options: [
      { id: 'a', label: 'The slight latency, token cost, or creative restriction introduced when applying safety guardrails, constitutional AI rules, and moderation filters to raw model reasoning.' },
      { id: 'b', label: 'A federal tax paid to government revenue authorities for every API call.' },
      { id: 'c', label: 'A discount offered to enterprise customers.' },
      { id: 'd', label: 'A fee charged for downloading model weights.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_24',
    section: 'literacy',
    prompt: 'How should an enterprise Chief AI Architect establish an "AI Technology Radar" for quarterly vendor evaluations?',
    options: [
      { id: 'a', label: 'Categorizing tools into Adopt / Trial / Assess / Hold rings based on internal automated eval benchmarks, data sovereignty compliance, vendor lock-in risk, and API stability metrics.' },
      { id: 'b', label: 'Copying marketing lists from social media influencers without testing.' },
      { id: 'c', label: 'Banning all new software releases permanently.' },
      { id: 'd', label: 'Relying exclusively on 10-year vendor contracts.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_25',
    section: 'literacy',
    prompt: 'What is "Test-Time Compute Scaling" (e.g. OpenAI o1 / o3 reasoning models), and how does it shift token economics?',
    options: [
      { id: 'a', label: 'Allowing the model to spend variable reasoning tokens generating internal Chain-of-Thought search trees before returning the final answer, trading latency/inference cost for dramatically higher factual accuracy.' },
      { id: 'b', label: 'Running hardware stress tests on the user local computer.' },
      { id: 'c', label: 'Billing users by the minute instead of by token.' },
      { id: 'd', label: 'A technique for reducing server room cooling costs.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_26',
    section: 'literacy',
    prompt: 'What constitutes "Model Fragility / Semantic Regression" when a cloud AI vendor silently updates a hosted foundation model checkpoint?',
    options: [
      { id: 'a', label: 'Subtle changes in probability distributions or alignment tuning that cause previously working prompt templates or JSON parsers in production to suddenly fail or output altered formats.' },
      { id: 'b', label: 'The physical server chassis cracking under pressure.' },
      { id: 'c', label: 'The internet cable being disconnected.' },
      { id: 'd', label: 'A user account being suspended for non-payment.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_27',
    section: 'literacy',
    prompt: 'In architectural decision records (ADRs), why is "Deterministic Rule Engine First, LLM Second" recommended for compliance-critical pipelines?',
    options: [
      { id: 'a', label: 'Hardcoded business logic handles 100% deterministic validations instantly with 0ms latency and 0 cost, reserving non-deterministic probabilistic LLMs only for ambiguous semantic interpretation.' },
      { id: 'b', label: 'LLMs are prohibited by law from executing in web applications.' },
      { id: 'c', label: 'Deterministic rule engines cannot run on modern cloud servers.' },
      { id: 'd', label: 'LLMs must always be used for all operations regardless of complexity.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_28',
    section: 'literacy',
    prompt: 'What is "Epistemic Humility" in autonomous decision-making systems architecture?',
    options: [
      { id: 'a', label: 'Designing AI agents that explicitly calculate and quantify their own uncertainty, delegating to human operators or secondary verifiers when confidence drops below safe operational boundaries.' },
      { id: 'b', label: 'A philosophical concept unrelated to engineering systems.' },
      { id: 'c', label: 'Forcing the model to apologize in every response.' },
      { id: 'd', label: 'A technique for deleting user chat history.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_29',
    section: 'literacy',
    prompt: 'How does an Enterprise AI Architect evaluate the "Token Velocity (Tokens Per Second)" requirements for interactive voice AI agents?',
    options: [
      { id: 'a', label: 'Interactive voice requires ultra-low Time-to-First-Token (TTFT < 300ms) and streaming generation > 20 tokens/sec to match natural human conversational cadence and enable real-time audio synthesis.' },
      { id: 'b', label: 'Voice agents require zero network bandwidth.' },
      { id: 'c', label: 'Voice models generate audio without tokens.' },
      { id: 'd', label: 'Voice agents only work on landline phones.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_30',
    section: 'literacy',
    prompt: 'What is the "Reversible vs Irreversible Decisions" framework (Bezos Two-Way Doors) applied to AI Autonomous Agent tooling?',
    options: [
      { id: 'a', label: 'Two-way door actions (drafting emails, analyzing data) are executed autonomously; one-way door actions (sending external payments, deleting production databases) require mandatory human authorization gates.' },
      { id: 'b', label: 'Building physical double doors in the server room.' },
      { id: 'c', label: 'Reversing the order of words in prompt text.' },
      { id: 'd', label: 'An architecture where no AI actions are permitted.' },
    ],
    correctOptionId: 'a',
  },
];


