import { CertQuestion } from '../types';

export const ARCHITECT_PRIVACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'mstr_priv_01',
    section: 'privacy',
    prompt: 'Under emerging global AI regulations (e.g. EU AI Act), what category of AI systems carries mandatory conformity assessments and fundamental rights impact assessments?',
    options: [
      { id: 'a', label: 'High-Risk AI systems (e.g. critical infrastructure, education scoring, employment recruitment, essential public services, law enforcement).' },
      { id: 'b', label: 'Casual consumer video game NPC dialogue bots.' },
      { id: 'c', label: 'Personal todo-list and note-taking productivity extensions.' },
      { id: 'd', label: 'Local weather summary widgets on operating system desktops.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_02',
    section: 'privacy',
    prompt: 'What is "differential privacy" in AI model training and data aggregation?',
    options: [
      { id: 'a', label: 'Restricting sensitive database records to a secondary internal folder structure.' },
      { id: 'b', label: 'Applying dual-factor authentication on all developer account logins.' },
      { id: 'c', label: 'Sharing anonymized datasets exclusively with verified business partners.' },
      { id: 'd', label: 'A mathematical framework introducing calibrated statistical noise to ensure individual records cannot be reverse-engineered or inferred from aggregate outputs.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_priv_03',
    section: 'privacy',
    prompt: 'How should an AI Architect handle the "Right to be Forgotten" (GDPR Article 17) if personal data was accidentally included in a model\'s fine-tuning weights?',
    options: [
      { id: 'a', label: 'Inform the data subject that neural networks are legally exempt from data privacy regulations.' },
      { id: 'b', label: 'Recognize that parameter extraction/unlearning is notoriously difficult; retrain the model from clean data checkpoints or implement strict output filter guardrails.' },
      { id: 'c', label: 'Delete the user\'s record from customer support ticket histories only.' },
      { id: 'd', label: 'Perform a standard web server reboot.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_priv_04',
    section: 'privacy',
    prompt: 'What constitutes an "Adversarial Extraction / Model Inversion" attack?',
    options: [
      { id: 'a', label: 'Physical theft of storage media from a third-party colocation data facility.' },
      { id: 'b', label: 'Inverting system display color profiles on developer workstations.' },
      { id: 'c', label: 'Carefully crafted querying sequences designed to reconstruct training data, proprietary system prompts, or hidden fine-tuning details from model output probabilities.' },
      { id: 'd', label: 'Downloading a public open-source foundation model repository from Hugging Face.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_priv_05',
    section: 'privacy',
    prompt: 'When establishing an internal "AI Governance Board", who are the essential stakeholders?',
    options: [
      { id: 'a', label: 'Cross-functional representatives: AI Engineering Leads, Legal/Compliance Counsel, Data Security Officers, Product Managers, and Domain Ethics Specialists.' },
      { id: 'b', label: 'Exclusively representatives from the external marketing and public relations team.' },
      { id: 'c', label: 'A single individual software engineer with no organizational oversight.' },
      { id: 'd', label: 'Third-party hardware vendors with no access to internal workflows.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_06',
    section: 'privacy',
    prompt: 'What is the risk of "Automation Bias" in professional decision-makers (doctors, underwriters, judges)?',
    options: [
      { id: 'a', label: 'Domain professionals refusing to use any automated productivity tooling.' },
      { id: 'b', label: 'Automated server instances restarting during operating hours.' },
      { id: 'c', label: 'Software package managers taking longer than expected to resolve dependencies.' },
      { id: 'd', label: 'Humans uncritically deferring to automated AI recommendations and ignoring contradictory real-world evidence or clinical intuition.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_priv_07',
    section: 'privacy',
    prompt: 'How should an organization protect its proprietary trade secrets when deploying customized AI tools across global teams?',
    options: [
      { id: 'a', label: 'Rely solely on verbal trust that staff will never paste trade secrets into consumer tools.' },
      { id: 'b', label: 'Enforce enterprise Zero Data Retention agreements, strict IAM role-based prompt access, client-side data masking, and network egress firewalls.' },
      { id: 'c', label: 'Publish company trade secrets to open forums to eliminate secrecy concerns.' },
      { id: 'd', label: 'Prohibit international business units from utilizing company laptops.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_priv_08',
    section: 'privacy',
    prompt: 'What is the ethical responsibility of an AI leader when a deployed AI feature exhibits disparate impact or demographic bias in production?',
    options: [
      { id: 'a', label: 'Suppress internal audit reports and dismiss user feedback.' },
      { id: 'b', label: 'Blame foundation model providers publicly without conducting an internal investigation.' },
      { id: 'c', label: 'Immediately halt or throttle the affected pipeline, conduct transparent root-cause analysis, remediate data imbalance, and publish corrective audit findings.' },
      { id: 'd', label: 'Continue scaling the biased feature until formal regulatory penalties are levied.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_priv_09',
    section: 'privacy',
    prompt: 'What is "Watermarking" for AI-generated multimedia and text, and what are its current technological limits?',
    options: [
      { id: 'a', label: 'Embedding statistical or visual signatures into outputs; effective for provenance tracking but susceptible to removal via re-encoding, paraphrasing, or editing.' },
      { id: 'b', label: 'Physical water cooling applied to high-density GPU server clusters.' },
      { id: 'c', label: 'An unbreakable cryptographic digital lock that permanently protects generated strings.' },
      { id: 'd', label: 'A digital copyright stamp applicable strictly to PDF document formats.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_10',
    section: 'privacy',
    prompt: 'How should an enterprise AI strategy balance rapid innovation with ethical stewardship?',
    options: [
      { id: 'a', label: 'Halt all artificial intelligence exploration permanently to eliminate organizational risk.' },
      { id: 'b', label: 'Deploy unvetted experimental models directly into customer-facing production with zero guardrails.' },
      { id: 'c', label: 'Delegate all corporate governance and liability to external closed-source AI vendors.' },
      { id: 'd', label: 'By building guardrails into the software development lifecycle, establishing transparent review gates, and fostering an organizational culture of accountable experimentation.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_priv_11',
    section: 'privacy',
    prompt: 'Under the US NIST AI Risk Management Framework (AI RMF), what are the four core functions for managing enterprise AI risks?',
    options: [
      { id: 'a', label: 'Buy, Deploy, Forget, Upgrade' },
      { id: 'b', label: 'GOVERN, MAP, MEASURE, MANAGE' },
      { id: 'c', label: 'Prompt, Generate, Discard, Repeat' },
      { id: 'd', label: 'Audit, Penalize, Ban, Report' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_priv_12',
    section: 'privacy',
    prompt: 'What is "Synthetic Identity Fraud" powered by GenAI, and how must enterprise KYC systems adapt?',
    options: [
      { id: 'a', label: 'Creating fake accounts on video game servers.' },
      { id: 'b', label: 'Generating imaginary product names in marketing brochures.' },
      { id: 'c', label: 'Combining real and synthetic PII (stolen SSNs + AI-generated deepfake facial images/voice) to open fraudulent accounts; mitigated by multi-factor biometric liveness checks and behavioral risk graphs.' },
      { id: 'd', label: 'Using a pseudonym on social media.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_priv_13',
    section: 'privacy',
    prompt: 'How does an Architect establish an "AI Bill of Materials" (AIBOM) for supply chain transparency in mission-critical applications?',
    options: [
      { id: 'a', label: 'Printing paper invoices for GPU hardware purchases.' },
      { id: 'b', label: 'Listing all employee laptop serial numbers.' },
      { id: 'c', label: 'Keeping a list of favorite prompt templates on a whiteboard.' },
      { id: 'd', label: 'Documenting the full lineage of base models, pre-training/fine-tuning dataset origins, license obligations, guardrail dependencies, evaluation benchmarks, and known vulnerability disclosures.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_priv_14',
    section: 'privacy',
    prompt: 'When auditing "Disparate Impact" in algorithmic hiring algorithms under EEOC guidelines, what is the "Four-Fifths (80%) Rule"?',
    options: [
      { id: 'a', label: 'A selection rate for any demographic group which is less than four-fifths (80%) of the rate for the group with the highest selection rate constitutes evidence of adverse impact.' },
      { id: 'b', label: 'At least 80% of lines of code must be written by human developers.' },
      { id: 'c', label: '80% of applicant resumes must be rejected within 5 seconds.' },
      { id: 'd', label: 'Hiring committees must meet for 80 minutes every week.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_15',
    section: 'privacy',
    prompt: 'What constitutes a "Sleeper Agent / Backdoor Attack" in foundation model supply chain security?',
    options: [
      { id: 'a', label: 'A developer falling asleep during a meeting.' },
      { id: 'b', label: 'A fine-tuned or open-weight model engineered to behave normally and pass standard safety evals on 99.9% of prompts, but execute hidden malicious or exploitative actions when triggered by a specific secret key phrase or date.' },
      { id: 'c', label: 'A computer power supply shutting off during nighttime.' },
      { id: 'd', label: 'A browser plugin displaying slow loading animations.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_priv_16',
    section: 'privacy',
    prompt: 'Why is "Confidential Computing" (e.g. AWS Nitro Enclaves, Azure Confidential GPUs) essential for processing sovereign multi-party datasets with AI?',
    options: [
      { id: 'a', label: 'To make model generation 10x faster.' },
      { id: 'b', label: 'To eliminate all internet connection fees.' },
      { id: 'c', label: 'Hardware-enforced cryptographic isolation ensures data and model weights remain encrypted in memory during active processing, preventing even cloud hypervisors and root administrators from accessing plaintext data.' },
      { id: 'd', label: 'To permanently disable server log files.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'mstr_priv_17',
    section: 'privacy',
    prompt: 'What is the "Dual-Use Dilemma" in advanced AI frontier research (e.g., biological/chemical synthesis capabilities)?',
    options: [
      { id: 'a', label: 'Using a model on both mobile phones and desktop computers.' },
      { id: 'b', label: 'Writing code in both Python and TypeScript.' },
      { id: 'c', label: 'Running models on both CPUs and GPUs.' },
      { id: 'd', label: 'The reality that foundational capabilities designed for beneficial scientific discovery (e.g. molecular drug discovery) can be inverted by bad actors to design novel toxins, requiring strict capability threshold evaluations and access controls.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'mstr_priv_18',
    section: 'privacy',
    prompt: 'How should an AI Architect establish an "Emergency Kill-Switch & Model Rollback Protocol"?',
    options: [
      { id: 'a', label: 'A deterministic control plane allowing designated security officers to instantly decouple AI endpoints, redirect traffic to pre-validated deterministic rules engines, and revoke agent tool credentials within seconds of a detected breach.' },
      { id: 'b', label: 'Physically smashing office computers with a hammer.' },
      { id: 'c', label: 'Sending an email to customer support asking them to look into the issue next week.' },
      { id: 'd', label: 'Hoping the AI model self-corrects after an hour.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_19',
    section: 'privacy',
    prompt: 'When training internal foundation models, how does "Machine Unlearning" (Selective Forgetting) differ from simple output filtering?',
    options: [
      { id: 'a', label: 'Output filtering permanently erases neural parameters from memory.' },
      { id: 'b', label: 'Output filtering catches sensitive topics at inference time but the information remains encoded in weights; Machine Unlearning mathematically adjusts model weights to remove the influence of specific training records while retaining overall model utility.' },
      { id: 'c', label: 'Machine Unlearning is accomplished by deleting the user\'s email address.' },
      { id: 'd', label: 'There is zero difference between the two approaches.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'mstr_priv_20',
    section: 'privacy',
    prompt: 'What is the ethical cornerstone of the Jnachi Master / Architect credential regarding societal impact?',
    options: [
      { id: 'a', label: 'Accelerating AI autonomy at all costs, regardless of human displacement or ethical harm.' },
      { id: 'b', label: 'Ignoring privacy regulations in pursuit of maximum operational velocity.' },
      { id: 'c', label: 'Upholding unwavering commitment to human dignity, transparent accountability, rigorous safety verification, and building AI systems that elevate and empower humanity responsibly.' },
      { id: 'd', label: 'Treating ethics solely as an impediment to quarterly profitability.' },
    ],
    correctOptionId: 'c',
  },
];

