import { CertQuestion } from '../types';

export const BEGINNER_AUTOMATION_QUESTIONS: CertQuestion[] = [
  {
    id: 'beg_auto_01',
    section: 'automation',
    prompt: 'What is a "micro-task audit" when looking for opportunities to automate daily work with AI?',
    options: [
      { id: 'a', label: 'Auditing microprocessors and cache utilization on employee workstations.' },
      { id: 'b', label: 'Deconstructing your weekly routine into discrete 2–10 minute cognitive tasks (drafting emails, formatting meeting notes, extracting action items) that AI can accelerate.' },
      { id: 'c', label: 'Measuring the total number of keystrokes and mouse movements per hour.' },
      { id: 'd', label: 'Conducting formal audits of minor accounting receipts under $10.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_auto_02',
    section: 'automation',
    prompt: 'What is the concept of "Clay Drafting" in content creation workflows?',
    options: [
      { id: 'a', label: 'Sculpting physical prototypes for 3D computer vision scanners.' },
      { id: 'b', label: 'Publishing unedited, fully autonomous AI articles directly to production feeds.' },
      { id: 'c', label: 'Restricting content prompts exclusively to short, one-word commands.' },
      { id: 'd', label: 'Using AI to quickly produce rough, unpolished first drafts (raw clay) that you then shape, fact-check, and refine with human judgment.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_auto_03',
    section: 'automation',
    prompt: 'Why should a professional maintain a personal or team "Prompt Library"?',
    options: [
      { id: 'a', label: 'To reuse tested, high-performing prompt templates with parameterized variables ({name}, {context}) instead of reinventing prompts from scratch every time.' },
      { id: 'b', label: 'To store internal system credentials and API tokens in plain text.' },
      { id: 'c', label: 'To prevent teammates from accessing generative AI tools independently.' },
      { id: 'd', label: 'To bypass the need for human review on all downstream deliverables.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_auto_04',
    section: 'automation',
    prompt: 'When automating the extraction of key meeting action items from a 60-minute transcript, what is the best strategy?',
    options: [
      { id: 'a', label: 'Submit the prompt: "What happened today?" with no explicit structure or guidelines.' },
      { id: 'b', label: 'Instruct the model to guess attendees\' unspoken thoughts and intentions.' },
      { id: 'c', label: 'Feed the clean transcript and request structured output with columns: [Action Item], [Owner], [Deadline], and [Context Quote].' },
      { id: 'd', label: 'Convert the entire transcript into an image before prompting.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_auto_05',
    section: 'automation',
    prompt: 'What is "prompt chaining" in workflow design?',
    options: [
      { id: 'a', label: 'Sending identical prompts across 10 different browser tabs simultaneously.' },
      { id: 'b', label: 'Breaking a complex multi-stage job into a sequence of smaller, focused prompts where the output of Prompt 1 becomes the input for Prompt 2.' },
      { id: 'c', label: 'Restricting prompt inputs to a maximum of 25 characters.' },
      { id: 'd', label: 'Running an infinite recursive loop that generates text indefinitely without human intervention.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_auto_06',
    section: 'automation',
    prompt: 'Why is it risky to ask an AI to execute a complex 10-step analytical project in a single prompt?',
    options: [
      { id: 'a', label: 'Because LLMs will automatically refuse any prompt with more than 3 bullet points.' },
      { id: 'b', label: 'Single prompts cause immediate network packet loss on client computers.' },
      { id: 'c', label: 'It requires enterprise root permissions to execute multi-step calculations.' },
      { id: 'd', label: 'Monolithic prompts overload attention mechanisms, leading to missed steps, diluted focus, and unspotted hallucinations.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_auto_07',
    section: 'automation',
    prompt: 'When using AI to reformat messy customer survey data into a clean spreadsheet, what is the safest approach?',
    options: [
      { id: 'a', label: 'Have the AI output a structured CSV format, spot-check a sample of rows against original records, and verify column alignment before importing.' },
      { id: 'b', label: 'Ingest raw AI output directly into production accounting systems without human spot-checking.' },
      { id: 'c', label: 'Assume the AI corrected all data inaccuracies without requiring source verification.' },
      { id: 'd', label: 'Permanently delete original raw surveys prior to running the AI transformation.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_auto_08',
    section: 'automation',
    prompt: 'How can custom instructions (or system prompts) save time in daily AI use?',
    options: [
      { id: 'a', label: 'By increasing the local GPU clock speed of the user device.' },
      { id: 'b', label: 'By eliminating the need to provide data inputs for any prompt.' },
      { id: 'c', label: 'By pre-configuring your persistent context, target audience, role, and formatting rules so you do not have to re-type them in every new session.' },
      { id: 'd', label: 'By overriding third-party copyright laws.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_auto_09',
    section: 'automation',
    prompt: 'What type of task is LEAST suitable for pure AI automation without human oversight?',
    options: [
      { id: 'a', label: 'High-stakes legal compliance filings, medical diagnosis notes, or irreversible financial transfers.' },
      { id: 'b', label: 'Drafting 5 alternative subject lines for a general newsletter.' },
      { id: 'c', label: 'Summarizing a publicly published tech industry blog post.' },
      { id: 'd', label: 'Translating a common conversational phrase into German.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_auto_10',
    section: 'automation',
    prompt: 'What is the primary objective of applied AI workflow automation?',
    options: [
      { id: 'a', label: 'To eliminate all human staff and automate corporate decision-making without oversight.' },
      { id: 'b', label: 'To flood external channels with unverified high-volume synthetic content.' },
      { id: 'c', label: 'To maximize total API credit expenditure on daily operations.' },
      { id: 'd', label: 'To eliminate repetitive cognitive friction and empower professionals to focus on high-judgment, creative, and strategic problem-solving.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_auto_11',
    section: 'automation',
    prompt: 'In a spreadsheet-based AI workflow, what is the advantage of using AI formula functions (like AI.TRANSLATE or AI.CLASSIFY)?',
    options: [
      { id: 'a', label: 'It guarantees that formulas will run offline without any internet connection.' },
      { id: 'b', label: 'It enables batch processing and transformation of hundreds of row entries concurrently inside familiar data grids.' },
      { id: 'c', label: 'It deletes all duplicate cells without checking criteria.' },
      { id: 'd', label: 'It permanently locks the spreadsheet from being edited by coworkers.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_auto_12',
    section: 'automation',
    prompt: 'When building a prompt template to process incoming customer support inquiries, what is the best way to handle dynamic inputs?',
    options: [
      { id: 'a', label: 'Hardcode one specific customer\'s name directly into the template codebase.' },
      { id: 'b', label: 'Delete all instructions and only pass raw customer text.' },
      { id: 'c', label: 'Use structured delimiter tags or variables like {{customer_message}} and {{ticket_category}} to clearly separate input data from instructions.' },
      { id: 'd', label: 'Run the prompt through an image generator first.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_auto_13',
    section: 'automation',
    prompt: 'What is a webhook trigger in the context of no-code AI automation workflows?',
    options: [
      { id: 'a', label: 'An automated event notification that sends real-time payload data to start an AI execution flow when an action occurs in another service.' },
      { id: 'b', label: 'A physical security key plugged into a computer USB port.' },
      { id: 'c', label: 'A design stylesheet used exclusively for website buttons.' },
      { id: 'd', label: 'A method for compressing MP3 audio files.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_auto_14',
    section: 'automation',
    prompt: 'When automating email drafting with an LLM, what is the most safe and reliable implementation strategy?',
    options: [
      { id: 'a', label: 'Configure the LLM to automatically send all generated emails to clients without any delay or human check.' },
      { id: 'b', label: 'Never allow AI to read or write any text related to email communications.' },
      { id: 'c', label: 'Send every draft to an external public forum for community review before delivery.' },
      { id: 'd', label: 'Generate email drafts into a "Drafts" folder with pre-filled context, requiring a human user to review and click "Send".' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_auto_15',
    section: 'automation',
    prompt: 'What is an "AI Agent" in modern automation terminology compared to a simple static prompt?',
    options: [
      { id: 'a', label: 'A physical robot that replaces office furniture.' },
      { id: 'b', label: 'An autonomous system that uses an LLM for reasoning, plan generation, tool/API execution, and iterative goal evaluation.' },
      { id: 'c', label: 'A human customer support representative working remotely.' },
      { id: 'd', label: 'A standard SQL query that runs on a schedule.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_auto_16',
    section: 'automation',
    prompt: 'Why is JSON (JavaScript Object Notation) the preferred output format when connecting LLMs to downstream software automations?',
    options: [
      { id: 'a', label: 'Because JSON files are encrypted with military-grade quantum keys automatically.' },
      { id: 'b', label: 'Because JSON requires zero token cost on all cloud providers.' },
      { id: 'c', label: 'Because JSON provides predictable, machine-readable structured syntax that downstream code and APIs can reliably parse.' },
      { id: 'd', label: 'Because LLMs cannot output plain English text.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_auto_17',
    section: 'automation',
    prompt: 'What happens if an automated AI workflow encounters an API rate limit error from the model provider?',
    options: [
      { id: 'a', label: 'The automation should implement exponential backoff retry logic to pause briefly before trying the request again.' },
      { id: 'b', label: 'The user account is permanently deleted by the provider.' },
      { id: 'c', label: 'The system must immediately delete the entire database.' },
      { id: 'd', label: 'The server reboots into safe mode.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_auto_18',
    section: 'automation',
    prompt: 'In a multi-step automation workflow, why should you validate the AI\'s output before passing it to an external database?',
    options: [
      { id: 'a', label: 'Validation is unnecessary because AI outputs are always syntactically and logically flawless.' },
      { id: 'b', label: 'To deliberately slow down server throughput.' },
      { id: 'c', label: 'To convert all numbers into Roman numerals.' },
      { id: 'd', label: 'To catch schema mismatches, null values, or hallucinations before corrupting production database records.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_auto_19',
    section: 'automation',
    prompt: 'What is the function of "fallback mechanisms" in automated AI workflows?',
    options: [
      { id: 'a', label: 'They automatically post error messages to social media.' },
      { id: 'b', label: 'They provide alternative pathways (e.g. routing to human queue or secondary model) when the primary AI call fails or times out.' },
      { id: 'c', label: 'They restart the client computer whenever an email arrives.' },
      { id: 'd', label: 'They reduce the screen brightness during nighttime hours.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_auto_20',
    section: 'automation',
    prompt: 'Which metric is most useful for evaluating whether an AI automation workflow is delivering genuine business value?',
    options: [
      { id: 'a', label: 'The total number of emojis used in system logs.' },
      { id: 'b', label: 'The physical weight of the office computers.' },
      { id: 'c', label: 'Task completion time savings, accuracy rates, and reduction in human manual toil vs. operational cost.' },
      { id: 'd', label: 'The length of the prompt template measured in characters.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_auto_21',
    section: 'automation',
    prompt: 'An operations team builds a daily Zapier/Make pipeline where an AI classifies incoming vendor invoices. What architecture ensures financial errors do not trigger unauthorized payments?',
    options: [
      { id: 'a', label: 'Human-in-the-Loop (HITL) approval gate: Auto-process low-risk metadata, but route all dollar amount disbursements above a threshold for manual review.' },
      { id: 'b', label: 'Allow the AI full direct API execution privileges to the company bank account.' },
      { id: 'c', label: 'Instruct the AI prompt: "Always guarantee 100% financial accuracy".' },
      { id: 'd', label: 'Run the prompt twice and pick whichever result executes faster.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_auto_22',
    section: 'automation',
    prompt: 'When parsing messy customer support emails into structured Jira ticket tickets via webhook automation, what is the best schema validation practice?',
    options: [
      { id: 'a', label: 'Pass the raw unparsed LLM text directly to the database without validation.' },
      { id: 'b', label: 'Use JSON Schema validation with a strict parser (e.g., Zod / Pydantic) to verify required fields (priority, category, customer_id) before API insertion.' },
      { id: 'c', label: 'Disable database primary key constraints so malformed JSON does not cause errors.' },
      { id: 'd', label: 'Rely on the Jira database to automatically fix invalid data types.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_auto_23',
    section: 'automation',
    prompt: 'In a multi-step prompt chaining workflow (Draft Outline -> Section Expansion -> Editor Review), why is passing only relevant outputs between steps superior to passing the entire conversation history?',
    options: [
      { id: 'a', label: 'It minimizes context window bloat, reduces token cost, and prevents earlier conversational noise from distracting downstream specialized prompt steps.' },
      { id: 'b', label: 'Passing full history is completely prohibited by cloud API security protocols.' },
      { id: 'c', label: 'It forces the AI model to run exclusively in offline mode.' },
      { id: 'd', label: 'It prevents the output from being readable by human engineers.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_auto_24',
    section: 'automation',
    prompt: 'What is the primary function of "Retry Logic with Exponential Backoff" when orchestrating production AI API calls?',
    options: [
      { id: 'a', label: 'It reboots the application server whenever a request completes.' },
      { id: 'b', label: 'It handles transient HTTP 429 (Rate Limit) and HTTP 503 (Overloaded) errors gracefully by progressively increasing wait intervals before retrying.' },
      { id: 'c', label: 'It automatically upgrades the account to an enterprise billing plan.' },
      { id: 'd', label: 'It permanently suppresses all error messages from application logs.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_auto_25',
    section: 'automation',
    prompt: 'A marketing team wants to automate personalized email outreach for 500 webinar attendees. How should they construct the dynamic template?',
    options: [
      { id: 'a', label: 'Send 500 identical generic emails without variables.' },
      { id: 'b', label: 'Use structured prompt variables (e.g., {{Attendee_Name}}, {{Company_Industry}}, {{Attended_Session}}) populated dynamically from the CRM database.' },
      { id: 'c', label: 'Ask the LLM to invent fictional job titles and company names for every attendee.' },
      { id: 'd', label: 'Run a single interactive prompt session and manually paste 500 records into one text box.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_auto_26',
    section: 'automation',
    prompt: 'What is an "Idempotency Key" in automated workflow systems that trigger AI-powered actions?',
    options: [
      { id: 'a', label: 'A secret password required to log into the cloud management console.' },
      { id: 'b', label: 'A unique request identifier that ensures executing the same workflow trigger multiple times does not result in duplicate actions or duplicate billing.' },
      { id: 'c', label: 'A hardware decryption key stored on local USB drives.' },
      { id: 'd', label: 'The total number of CPU cycles consumed during model inference.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_auto_27',
    section: 'automation',
    prompt: 'When building an automated document ingestion pipeline, why is text chunking necessary prior to embedding generation?',
    options: [
      { id: 'a', label: 'Large documents exceed embedding model token limits, and smaller semantically cohesive chunks preserve localized meaning for precise retrieval.' },
      { id: 'b', label: 'Vector databases reject documents that contain more than 10 words.' },
      { id: 'c', label: 'Chunking automatically translates the document into machine code.' },
      { id: 'd', label: 'Chunking reduces the physical storage drive size to zero bytes.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_auto_28',
    section: 'automation',
    prompt: 'What role does a "Golden Evaluation Dataset" play in automated AI workflow maintenance?',
    options: [
      { id: 'a', label: 'It is a benchmark set of verified input/expected-output test cases used to validate that prompt revisions or model upgrades do not degrade performance.' },
      { id: 'b', label: 'It is a backup copy of all user credit card numbers.' },
      { id: 'c', label: 'It automatically calculates sales tax for ecommerce stores.' },
      { id: 'd', label: 'It provides free cloud hosting credits.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_auto_29',
    section: 'automation',
    prompt: 'How should an automated customer service triage bot handle a user query expressing extreme frustration or legal threats?',
    options: [
      { id: 'a', label: 'Argue with the customer using assertive counter-prompts.' },
      { id: 'b', label: 'Automatically disconnect the user chat immediately.' },
      { id: 'c', label: 'Detect negative sentiment and legal keywords via classification prompts and immediately escalate the session with chat logs to a human tier-2 support specialist.' },
      { id: 'd', label: 'Offer an infinite loop of simulated apology messages without action.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_auto_30',
    section: 'automation',
    prompt: 'In automated batch processing workflows, what is the primary benefit of asynchronous processing (Queue + Worker) over synchronous blocking calls?',
    options: [
      { id: 'a', label: 'It prevents client timeouts, handles API rate throttling smoothly, and decouples user requests from long-running model generation tasks.' },
      { id: 'b', label: 'It guarantees that all AI responses are generated in under 1 millisecond.' },
      { id: 'c', label: 'It eliminates the need for database storage.' },
      { id: 'd', label: 'It allows bypassing software license restrictions.' },
    ],
    correctOptionId: 'a',
  },
];


