import { CertQuestion } from '../types';

export const BEGINNER_GROWTH_QUESTIONS: CertQuestion[] = [
  {
    id: 'beg_gro_01',
    section: 'growth',
    prompt: 'How does using an AI as a "Cognitive Sparring Partner" differ from using it as a passive answer generator?',
    options: [
      { id: 'a', label: 'You instruct the AI to agree enthusiastically with every statement you write.' },
      { id: 'b', label: 'You prompt the model to challenge your logic, identify blind spots in your plan, and play devil\'s advocate rather than just validating your initial assumptions.' },
      { id: 'c', label: 'You use speech-to-text to talk with the model continuously without a specific objective.' },
      { id: 'd', label: 'You delegate all strategic personal decisions entirely to model outputs.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_gro_02',
    section: 'growth',
    prompt: 'What is "Sycophancy" in AI assistants, and why is it dangerous for decision-making?',
    options: [
      { id: 'a', label: 'A state where the model encounters out-of-memory errors on long conversations.' },
      { id: 'b', label: 'A defensive guardrail where the model refuses to answer contentious political topics.' },
      { id: 'c', label: 'The tendency of models to overly agree with the user\'s leading questions or biases, creating a false sense of validation for flawed proposals.' },
      { id: 'd', label: 'A technical failure in temperature sampling causing incoherent punctuation.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_gro_03',
    section: 'growth',
    prompt: 'When evaluating new AI tools, what is an effective "Anti-Hype Filter"?',
    options: [
      { id: 'a', label: 'Focusing on whether the tool actually solves a painful bottleneck in your workflow better/faster than a standard template, rather than marketing claims.' },
      { id: 'b', label: 'Purchasing licenses for any AI product featured on top tech trend newsletters.' },
      { id: 'c', label: 'Relying exclusively on the number of marketing keywords listed on a product page.' },
      { id: 'd', label: 'Assuming proprietary AI wrappers are fundamentally superior to frontier base models.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_gro_04',
    section: 'growth',
    prompt: 'How can multimodal AI (uploading screenshots, diagrams, photos) accelerate problem solving?',
    options: [
      { id: 'a', label: 'By increasing the local monitor refresh rate and rendering speed.' },
      { id: 'b', label: 'By bypassing standard optical character recognition and database lookups.' },
      { id: 'c', label: 'By converting 2D images directly into physical 3D manufacturing files.' },
      { id: 'd', label: 'By enabling the AI to directly analyze complex visual data—like UI layout bugs, chart trends, or whiteboard sketches—without tedious manual transcription.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_gro_05',
    section: 'growth',
    prompt: 'What is "calibration" in human-AI collaboration?',
    options: [
      { id: 'a', label: 'Developing accurate intuition for what tasks an AI excels at (summarizing, reformatting, brainstorming) vs where it struggles (complex math, strict citations).' },
      { id: 'b', label: 'Adjusting hardware display gamma curves to view diagrams accurately.' },
      { id: 'c', label: 'Synchronizing client workstation system clocks to UTC server time.' },
      { id: 'd', label: 'Setting the temperature parameter strictly to 0.5 across all interactions.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_gro_06',
    section: 'growth',
    prompt: 'When an AI model produces citations, numbers, or URLs, what is the mandatory professional rule?',
    options: [
      { id: 'a', label: 'Assume the AI has verified all hyperlinks through real-time web crawlers.' },
      { id: 'b', label: 'Omit all references and present numbers as your own unassisted research.' },
      { id: 'c', label: 'Zero Trust Verification: Always independently verify facts, links, and calculation results before sharing or publishing.' },
      { id: 'd', label: 'Only check citations if the text length exceeds 1,000 words.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_gro_07',
    section: 'growth',
    prompt: 'What is the hallmark of high "AI Momentum"?',
    options: [
      { id: 'a', label: 'Purchasing multiple enterprise licenses that remain unused by team members.' },
      { id: 'b', label: 'Regularly putting verified prompt techniques and workflows into real practice, measuring time saved, and continuously refining your approach.' },
      { id: 'c', label: 'Reading daily AI social media announcements without testing tools in real workflows.' },
      { id: 'd', label: 'Replacing human quality assurance entirely with uninspected automated scripts.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_gro_08',
    section: 'growth',
    prompt: 'How should you prompt an AI when learning a completely unfamiliar, complex subject?',
    options: [
      { id: 'a', label: '"Generate 100 pages of advanced academic literature with no explanations."' },
      { id: 'b', label: '"Explain everything about this topic in a single 5-word sentence."' },
      { id: 'c', label: '"Pretend you are an unhelpful critic and refuse to answer."' },
      { id: 'd', label: '"Explain this concept using simple real-world analogies, outline the 3 key principles, and test my understanding with 2 quiz scenarios."' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_gro_09',
    section: 'growth',
    prompt: 'What is the Jnachi motto that guides all four competency tracks?',
    options: [
      { id: 'a', label: 'Know it. Use it. Prove it.' },
      { id: 'b', label: 'Hype it. Buy it. Forget it.' },
      { id: 'c', label: 'Prompt it. Trust it. Deploy it.' },
      { id: 'd', label: 'Automate everything blindly.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_gro_10',
    section: 'growth',
    prompt: 'What distinguishes someone who has earned the Jnachi Certified AI Foundations credential?',
    options: [
      { id: 'a', label: 'They have memorized theoretical AI vocabulary without testing prompt workflows.' },
      { id: 'b', label: 'They possess verified foundational fluency—knowing how to craft robust prompts, automate daily micro-tasks, safeguard sensitive data, and critically evaluate outputs.' },
      { id: 'c', label: 'They rely exclusively on default zero-shot single-sentence queries for complex problems.' },
      { id: 'd', label: 'They believe generative models are infallible and require no human-in-the-loop oversight.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_gro_11',
    section: 'growth',
    prompt: 'When using AI to help brainstorm innovative product ideas, what prompt technique breaks conventional repetitive thinking?',
    options: [
      { id: 'a', label: 'Ask the model to list the top 3 most common ideas found on Google.' },
      { id: 'b', label: 'Provide no constraints and keep the prompt to one word.' },
      { id: 'c', label: 'Apply constraint-inversion prompting (e.g. "What if budget was $0?" or "Design a solution assuming no smartphones exist").' },
      { id: 'd', label: 'Ask the AI to repeat the problem statement 5 times.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_gro_12',
    section: 'growth',
    prompt: 'How should an employee respond when a generative AI model outputs an analysis that contradicts verifiable corporate sales data?',
    options: [
      { id: 'a', label: 'Assume the AI has discovered secret trends that the internal data missed.' },
      { id: 'b', label: 'Override the AI output with verified ground truth data, diagnose the prompt grounding error, and document the discrepancy.' },
      { id: 'c', label: 'Forward the AI output to executives immediately without mentioning the discrepancy.' },
      { id: 'd', label: 'Delete the internal database to align with the AI recommendation.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_gro_13',
    section: 'growth',
    prompt: 'Which habit best ensures sustained skill growth when working with generative AI tools across evolving models?',
    options: [
      { id: 'a', label: 'Using only one fixed prompt template for the next five years.' },
      { id: 'b', label: 'Actively testing new prompting techniques, measuring output quality, cataloging edge cases, and adhering to latest safety guidelines.' },
      { id: 'c', label: 'Avoiding all prompt adjustments once an output is minimally readable.' },
      { id: 'd', label: 'Delegating all strategic thinking to automated chatbot outputs.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_gro_14',
    section: 'growth',
    prompt: 'When using AI to help resolve a heated workplace communication dispute, what is the best approach?',
    options: [
      { id: 'a', label: 'Instruct the AI to generate an aggressive, confrontational demand letter.' },
      { id: 'b', label: 'Prompt the AI to analyze both viewpoints objectively, identify shared underlying goals, and draft empathetic, non-violent communication framing.' },
      { id: 'c', label: 'Post the full private conversation to a public community forum for voting.' },
      { id: 'd', label: 'Have the AI impersonate executive leadership and mandate a solution.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_gro_15',
    section: 'growth',
    prompt: 'How does an effective practitioner stay updated with rapid advancements in AI capabilities and tooling?',
    options: [
      { id: 'a', label: 'By assuming AI models will never change after their release date.' },
      { id: 'b', label: 'By relying strictly on textbooks published over five years ago.' },
      { id: 'c', label: 'By regularly testing new model releases, reviewing technical changelogs, experimenting with workflow updates, and participating in peer learning communities.' },
      { id: 'd', label: 'By waiting until all AI tools are completely discontinued.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_gro_16',
    section: 'growth',
    prompt: 'When an AI tool gives a plausible answer that contradicts your professional domain intuition, what should you do?',
    options: [
      { id: 'a', label: 'Blindly override your intuition because AI is always mathematically superior.' },
      { id: 'b', label: 'Delete the AI software immediately and never use technology again.' },
      { id: 'c', label: 'Share the unverified AI output with your client immediately.' },
      { id: 'd', label: 'Investigate the discrepancy, ask the AI to show its underlying calculations/assumptions, and cross-reference with authoritative primary source documentation.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_gro_17',
    section: 'growth',
    prompt: 'What is the concept of "Cognitive Offloading" when using AI, and how should it be balanced?',
    options: [
      { id: 'a', label: 'Delegating routine low-level friction (formatting, boilerplate, initial synthesis) to AI while preserving deep human judgment, critical verification, and strategic vision.' },
      { id: 'b', label: 'Stopping all human learning and allowing AI to make every personal life decision.' },
      { id: 'c', label: 'Shutting down computers during peak business hours.' },
      { id: 'd', label: 'Replacing human team members with automated email auto-responders.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_gro_18',
    section: 'growth',
    prompt: 'Why is documenting and sharing successful "Prompt Patterns" across a team valuable for organizational growth?',
    options: [
      { id: 'a', label: 'It fills up hard drive space quickly.' },
      { id: 'b', label: 'It standardizes high-performing workflows, scales institutional best practices, and prevents redundant trial-and-error among colleagues.' },
      { id: 'c', label: 'It guarantees that all team members will receive immediate pay increases.' },
      { id: 'd', label: 'It eliminates the need for software licenses.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_gro_19',
    section: 'growth',
    prompt: 'When utilizing AI for self-directed technical upskilling (like learning Python or SQL), which prompting structure accelerates skill acquisition most effectively?',
    options: [
      { id: 'a', label: 'Asking the AI to write entire applications without providing any explanations.' },
      { id: 'b', label: 'Asking for 100 pages of raw syntax reference guides without examples.' },
      { id: 'c', label: 'Interactive project-based Socratic tutoring: building small real-world components, receiving guided code challenges, and debugging errors collaboratively.' },
      { id: 'd', label: 'Memorizing dictionary terms without writing any code.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_gro_20',
    section: 'growth',
    prompt: 'What is the overarching goal of progressing from Jnachi Beginner to Practitioner, Builder, and Master?',
    options: [
      { id: 'a', label: 'Collecting digital badges without applying skills to real-world problems.' },
      { id: 'b', label: 'Transitioning completely from human work to unmonitored autonomous bots.' },
      { id: 'c', label: 'Learning to write prompts solely for entertainment and social media memes.' },
      { id: 'd', label: 'Systematically developing end-to-end AI capability—from baseline fluency to production workflow automation, multi-agent systems, and ethical strategic leadership.' },
    ],
    correctOptionId: 'd',
  },
];

