import { CertQuestion } from '../types';

export const BEGINNER_LITERACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'beg_lit_01',
    section: 'literacy',
    prompt: 'What are the three essential components of a well-structured prompt anatomy for business tasks?',
    options: [
      { id: 'a', label: 'Polite greeting, keyword repetition, and emotional appeals' },
      { id: 'b', label: 'Model temperature, API secret keys, and billing tier settings' },
      { id: 'c', label: 'Context & Role, Clear Task/Instruction, and Desired Output Format/Constraints' },
      { id: 'd', label: 'A single open-ended sentence requesting general help' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_lit_02',
    section: 'literacy',
    prompt: 'Why is defining a specific persona (e.g., "Act as a senior cybersecurity auditor") effective in prompt engineering?',
    options: [
      { id: 'a', label: 'It activates relevant domain-specific vocabulary, reasoning patterns, and perspective biases in the model’s attention weights.' },
      { id: 'b', label: 'It permanently overrides the model safety filters and content boundaries.' },
      { id: 'c', label: 'It reduces the total number of API tokens billed for the response.' },
      { id: 'd', label: 'It forces the AI to search live internal enterprise databases without authentication.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_lit_03',
    section: 'literacy',
    prompt: 'What is a "hallucination" in the context of Large Language Models (LLMs)?',
    options: [
      { id: 'a', label: 'A server connection timeout caused by high network traffic.' },
      { id: 'b', label: 'A syntax error when compiling generated programming code.' },
      { id: 'c', label: 'An intentional security guardrail triggered by harmful prompts.' },
      { id: 'd', label: 'When a model generates plausible-sounding but factually false, ungrounded, or fabricated information with high apparent confidence.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_lit_04',
    section: 'literacy',
    prompt: 'What is the primary benefit of "few-shot" prompting over "zero-shot" prompting?',
    options: [
      { id: 'a', label: 'It modifies the foundation model weights permanently on the server.' },
      { id: 'b', label: 'Providing 1-3 concrete input/output examples teaches the model the exact formatting style, tone, and edge-case handling you expect.' },
      { id: 'c', label: 'It eliminates the need to provide any task instructions.' },
      { id: 'd', label: 'It decreases model processing latency to zero.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_lit_05',
    section: 'literacy',
    prompt: 'When you need an AI to produce output in a strict machine-readable format, which approach is most reliable?',
    options: [
      { id: 'a', label: 'Ask the model casually in conversational text and hope for clean parsing' },
      { id: 'b', label: 'Provide an explicit JSON or CSV schema, require raw output only, and forbid conversational preamble or markdown wrappers' },
      { id: 'c', label: 'Capitalize all keywords in the prompt' },
      { id: 'd', label: 'Increase the model temperature to its maximum value' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_lit_06',
    section: 'literacy',
    prompt: 'What happens when you use positive instructions (what to do) instead of solely negative constraints (what not to do)?',
    options: [
      { id: 'a', label: 'LLMs follow positive guidance with significantly higher accuracy because it provides the token predictor with a clear operational pathway.' },
      { id: 'b', label: 'The model rejects the prompt as contradictory.' },
      { id: 'c', label: 'The token consumption doubles unnecessarily.' },
      { id: 'd', label: 'There is no measurable difference in output precision or compliance.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_lit_07',
    section: 'literacy',
    prompt: 'What is the "context window" in large language models?',
    options: [
      { id: 'a', label: 'The visual window size of your web browser interface.' },
      { id: 'b', label: 'The time window during which the API servers accept incoming requests.' },
      { id: 'c', label: 'The maximum capacity of tokens (input plus output) the model can process and retain in active memory during a single interaction.' },
      { id: 'd', label: 'The number of days an enterprise subscription remains active.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_lit_08',
    section: 'literacy',
    prompt: 'When an AI provides an answer that is 80% accurate but contains minor tone flaws or missing details, what is the best next step?',
    options: [
      { id: 'a', label: 'Discard the draft completely and start over with a brand new conversation.' },
      { id: 'b', label: 'Accept the draft as final and distribute it without human review.' },
      { id: 'c', label: 'Re-submit the exact same initial prompt without changes.' },
      { id: 'd', label: 'Iterative calibration: provide targeted feedback specifying which sections to refine, tone adjustments, and missing constraints.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_lit_09',
    section: 'literacy',
    prompt: 'What does the "temperature" parameter generally control in LLMs?',
    options: [
      { id: 'a', label: 'The hardware thermal throttling of the underlying GPU server cluster.' },
      { id: 'b', label: 'The degree of randomness in next-token probability distribution (lower = deterministic/focused; higher = diverse/creative).' },
      { id: 'c', label: 'The speed of network packet transmission between client and server.' },
      { id: 'd', label: 'The maximum allowed length of generated sentences.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_lit_10',
    section: 'literacy',
    prompt: 'Why should complex multi-step reasoning tasks include instructions like "Think step-by-step before answering"?',
    options: [
      { id: 'a', label: 'It encourages Chain-of-Thought reasoning, generating intermediate reasoning tokens that substantially improve analytical and factual accuracy.' },
      { id: 'b', label: 'It forces the AI to output responses in bullet points exclusively.' },
      { id: 'c', label: 'It enables external web search integration automatically.' },
      { id: 'd', label: 'It prevents the model from consuming context window tokens.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_lit_11',
    section: 'literacy',
    prompt: 'When prompting an LLM to extract structured key-value pairs from messy unstructured text, what technique ensures highest reliability?',
    options: [
      { id: 'a', label: 'Use informal emotional persuasion words to ask the model to be very careful.' },
      { id: 'b', label: 'Ask the model to produce poetic summaries of the text.' },
      { id: 'c', label: 'Provide an explicit JSON schema or format blueprint with strict key names and type definitions.' },
      { id: 'd', label: 'Increase model temperature to 1.5 to maximize data extraction variability.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_lit_12',
    section: 'literacy',
    prompt: 'What is the primary benefit of including negative constraints (e.g., "Do not mention competitor brand names") in a prompt?',
    options: [
      { id: 'a', label: 'It compresses the token size of the user prompt by 50%.' },
      { id: 'b', label: 'It permanently erases the prohibited concepts from the base model training weights.' },
      { id: 'c', label: 'It disables all content moderation filters in the LLM.' },
      { id: 'd', label: 'It delineates clear output boundaries and eliminates unwanted digressions or forbidden content.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_lit_13',
    section: 'literacy',
    prompt: 'What happens when a conversation exceeds the maximum context window capacity of an LLM?',
    options: [
      { id: 'a', label: 'Earliest conversation messages get truncated or dropped, causing the model to lose earlier context or constraints.' },
      { id: 'b', label: 'The model crashes and permanently corrupts its base training weights.' },
      { id: 'c', label: 'The model switches into an uncapped external database automatically.' },
      { id: 'd', label: 'The model outputs binary code instead of natural language.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_lit_14',
    section: 'literacy',
    prompt: 'What is the primary purpose of a "System Prompt" (or Developer Instructions) compared to a standard User Message?',
    options: [
      { id: 'a', label: 'It is only used to charge the user credit card for API usage.' },
      { id: 'b', label: 'It establishes persistent baseline rules, persona, formatting rules, and safety boundaries for the entire session.' },
      { id: 'c', label: 'It executes local operating system shell scripts on the client machine.' },
      { id: 'd', label: 'It bypasses all network latency checks during generation.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_lit_15',
    section: 'literacy',
    prompt: 'If you need an LLM to evaluate customer support transcripts against a 5-point quality rubric, what is the best strategy?',
    options: [
      { id: 'a', label: 'Ask the LLM "Is this good or bad?" without providing criteria.' },
      { id: 'b', label: 'Prompt the model to write an apology poem to the customer.' },
      { id: 'c', label: 'Provide the full rubric with criteria for each rating level and request a justification before assigning the score.' },
      { id: 'd', label: 'Instruct the model to guess the score using random generation.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_lit_16',
    section: 'literacy',
    prompt: 'Which of the following is a classic indicator that an AI output might contain a hallucination?',
    options: [
      { id: 'a', label: 'The output contains correct grammatical spelling throughout.' },
      { id: 'b', label: 'The output strictly follows the requested JSON format.' },
      { id: 'c', label: 'The response matches verified primary documentation word-for-word.' },
      { id: 'd', label: 'The output cites highly specific URL links, research paper titles, or case laws that do not actually exist upon verification.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_lit_17',
    section: 'literacy',
    prompt: 'What does "Few-Shot Prompting" specifically involve?',
    options: [
      { id: 'a', label: 'Providing a few high-quality input-output demonstration examples directly within the prompt before asking for the target result.' },
      { id: 'b', label: 'Running the prompt through multiple distinct AI models at the same time.' },
      { id: 'c', label: 'Retrying the same prompt 3 times when an error occurs.' },
      { id: 'd', label: 'Fine-tuning model weights with millions of training records on dedicated GPUs.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_lit_18',
    section: 'literacy',
    prompt: 'When asking an AI to summarize a 20-page financial quarterly earnings report, which approach yields the most accurate summary?',
    options: [
      { id: 'a', label: 'Ask "Summarize everything in 2 words".' },
      { id: 'b', label: 'Provide the document text and specify key focus areas such as revenue growth, EBITDA margin, and risk factors.' },
      { id: 'c', label: 'Ask the AI to guess the revenue numbers without reading the document.' },
      { id: 'd', label: 'Instruct the AI to ignore all tables and numeric figures.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_lit_19',
    section: 'literacy',
    prompt: 'Why is conversational context chaining useful in complex analytical tasks?',
    options: [
      { id: 'a', label: 'It guarantees zero token usage across API calls.' },
      { id: 'b', label: 'It allows the AI to run hardware tests on the host machine.' },
      { id: 'c', label: 'It allows breaking down a complex multi-stage objective into sequential iterative turns (outline -> draft -> review -> finalize).' },
      { id: 'd', label: 'It forces the AI to always agree with the user regardless of facts.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_lit_20',
    section: 'literacy',
    prompt: 'What role does "Role Prompting" (e.g., "Act as a Senior Compliance Officer") play in model outputs?',
    options: [
      { id: 'a', label: 'It legally transfers liability of the advice to the AI company.' },
      { id: 'b', label: 'It speeds up server response time by 80%.' },
      { id: 'c', label: 'It gives the AI real-time administrator privileges to local corporate software.' },
      { id: 'd', label: 'It primes the model\'s probabilistic focus toward specialized vocabulary, domain assumptions, and relevant industry perspectives.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_lit_21',
    section: 'literacy',
    prompt: 'A student asks an LLM to generate a literature review bibliography and receives 5 formatted citations. How should the student verify these sources before submission?',
    options: [
      { id: 'a', label: 'Assume the citations are valid if they include DOI numbers and standard academic formatting.' },
      { id: 'b', label: 'Directly search academic index databases (e.g., Google Scholar, PubMed) to confirm each paper, author, and journal actually exists.' },
      { id: 'c', label: 'Ask the same LLM in a new chat if the bibliography it generated was real.' },
      { id: 'd', label: 'Increase the model temperature to 1.0 to regenerate identical citations for cross-checking.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_lit_22',
    section: 'literacy',
    prompt: 'When crafting prompts for multilingual translation of legal contracts, what instruction best preserves technical intent?',
    options: [
      { id: 'a', label: 'Specify the source jurisdiction, legal domain glossary, and instruct the model to flag untranslatable jurisdictional concepts in bracketed annotations.' },
      { id: 'b', label: 'Ask the AI to simplify the legal wording into casual everyday conversational slang.' },
      { id: 'c', label: 'Translate each sentence individually in isolated sessions without sharing contract context.' },
      { id: 'd', label: 'Request poetic phrasing to make the contract text more engaging for readers.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_lit_23',
    section: 'literacy',
    prompt: 'What is the primary operational consequence of the "Lost in the Middle" phenomenon in large context windows?',
    options: [
      { id: 'a', label: 'The middle section of the model neural network shuts down to conserve GPU power.' },
      { id: 'b', label: 'LLMs retrieve and recall information placed at the very beginning and very end of long contexts with much higher fidelity than information placed in the middle.' },
      { id: 'c', label: 'The model reverses the chronological order of generated paragraphs.' },
      { id: 'd', label: 'Tokens in the middle of a document are automatically billed at triple the normal rate.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_lit_24',
    section: 'literacy',
    prompt: 'When using Delimiters (such as triple backticks ``` or XML tags <context>) in prompt design, what core problem is solved?',
    options: [
      { id: 'a', label: 'It compresses input text to reduce token counts by 50%.' },
      { id: 'b', label: 'It clearly separates operational system instructions from variable user data, mitigating accidental prompt injection and confusion.' },
      { id: 'c', label: 'It unlocks access to private external API databases.' },
      { id: 'd', label: 'It prevents the client browser from timing out during long requests.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_lit_25',
    section: 'literacy',
    prompt: 'Which strategy most effectively prevents an AI model from guessing answers when uncertain about proprietary internal data?',
    options: [
      { id: 'a', label: 'Set model temperature to 0.0 and explicitly instruct: "If the answer cannot be strictly derived from the provided context, respond with \'I do not have sufficient information\'".' },
      { id: 'b', label: 'Instruct the model to search external social media forums whenever data is missing.' },
      { id: 'c', label: 'Use emotional pleas asking the model to promise not to lie.' },
      { id: 'd', label: 'Remove all system instructions so the model operates with baseline autonomy.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_lit_26',
    section: 'literacy',
    prompt: 'What distinguishes a "Zero-Shot" prompt from a "One-Shot" prompt in generative AI workflows?',
    options: [
      { id: 'a', label: 'Zero-shot requires no API authentication, whereas one-shot requires an OAuth token.' },
      { id: 'b', label: 'Zero-shot provides only task instructions with no examples; one-shot provides exactly one exemplary input-output demonstration pair.' },
      { id: 'c', label: 'Zero-shot runs locally on device; one-shot requires cloud server GPUs.' },
      { id: 'd', label: 'Zero-shot generates binary output; one-shot generates natural language.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_lit_27',
    section: 'literacy',
    prompt: 'If an AI assistant generates code with deprecated library functions, what is the root cause and recommended remediation?',
    options: [
      { id: 'a', label: 'Hardware memory corruption; restart the host computer immediately.' },
      { id: 'b', label: 'Training knowledge cutoff limitations; explicitly specify the target modern library version and provide current API method signatures in the prompt context.' },
      { id: 'c', label: 'The AI model is refusing compliance due to copyright filters; switch to another language.' },
      { id: 'd', label: 'The prompt used incorrect punctuation; capitalize all variable names.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_lit_28',
    section: 'literacy',
    prompt: 'In prompt engineering, what does "Chain-of-Density" summarization achieve?',
    options: [
      { id: 'a', label: 'It increases token latency to reduce bandwidth costs.' },
      { id: 'b', label: 'It progressively adds missing entity details over iterative rewrite passes without increasing total summary length, maximizing information density.' },
      { id: 'c', label: 'It encrypts the summary output using cryptographic hashes.' },
      { id: 'd', label: 'It translates the summary into five languages simultaneously.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_lit_29',
    section: 'literacy',
    prompt: 'Why should numerical calculations in complex financial models be delegated to code execution (e.g., Python tool calling) rather than relying solely on pure next-token text prediction?',
    options: [
      { id: 'a', label: 'LLMs predict tokens probabilistically and can make arithmetic calculation errors on multi-digit multiplication or compounding calculations.' },
      { id: 'b', label: 'LLM tokenizers cannot process Arabic numerals 0 through 9.' },
      { id: 'c', label: 'Financial calculation prompts are automatically blocked by safety moderation filters.' },
      { id: 'd', label: 'Python tools consume zero server resources compared to LLM text generation.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_lit_30',
    section: 'literacy',
    prompt: 'What is the function of "Top-P" (nucleus sampling) when tuning generative AI outputs?',
    options: [
      { id: 'a', label: 'It restricts token selection to the cumulative probability mass P, dynamically pruning low-probability long-tail tokens.' },
      { id: 'b', label: 'It sets the maximum physical CPU thread count allocated to the model.' },
      { id: 'c', label: 'It determines the total dollar billing cap per API request.' },
      { id: 'd', label: 'It forces the model to only output capitalized alphanumeric characters.' },
    ],
    correctOptionId: 'a',
  },
];


