import { CertQuestion } from '../types';

export const BEGINNER_PRIVACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'beg_priv_01',
    section: 'privacy',
    prompt: 'What is the crucial privacy difference between free consumer AI web chats and enterprise AI API services?',
    options: [
      { id: 'a', label: 'Enterprise services run locally without using any internet connection or cloud processing.' },
      { id: 'b', label: 'Consumer tiers are completely anonymous and never log any telemetry or prompt data.' },
      { id: 'c', label: 'Free consumer tiers typically retain user prompts to train future foundation models, while enterprise agreements provide Zero Data Retention (ZDR) and strict confidentiality.' },
      { id: 'd', label: 'Consumer tiers encrypt data with government keys, while enterprise tiers make prompts public.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_priv_02',
    section: 'privacy',
    prompt: 'What constitutes Personally Identifiable Information (PII) that should NEVER be pasted into unvetted consumer AI tools?',
    options: [
      { id: 'a', label: 'Social Security / national ID numbers, financial account details, medical records, and private customer contact databases.' },
      { id: 'b', label: 'Public Wikipedia reference articles and open encyclopedias.' },
      { id: 'c', label: 'Open-source software documentation and public repository links.' },
      { id: 'd', label: 'Standard dictionary definitions of English vocabulary words.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_03',
    section: 'privacy',
    prompt: 'What is a "personal red line" in ethical AI usage?',
    options: [
      { id: 'a', label: 'A mechanical circuit limit on GPU computing clusters.' },
      { id: 'b', label: 'A red underline in text editors indicating grammar errors.' },
      { id: 'c', label: 'A firewall setting that blocks all outbound internet traffic.' },
      { id: 'd', label: 'A conscious, non-negotiable boundary defining decisions or sensitive topics where you will never delegate authority to an AI system.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_priv_04',
    section: 'privacy',
    prompt: 'Before uploading an internal company report to an AI tool, what safety check should an employee perform?',
    options: [
      { id: 'a', label: 'Rename the file extension so security scanners do not recognize the format.' },
      { id: 'b', label: 'Verify company authorized AI tool lists, check data classification policies, and scrub confidential client names or proprietary trade secrets.' },
      { id: 'c', label: 'Upload the document immediately as long as it is done during non-business hours.' },
      { id: 'd', label: 'Assume all commercial AI services automatically comply with your employer\'s specific security policy.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_05',
    section: 'privacy',
    prompt: 'What does "Zero Data Retention" (ZDR) mean in an AI enterprise contract?',
    options: [
      { id: 'a', label: 'The vendor processes the prompt in volatile memory for inference and does not persist, log, or train on the input/output after the request completes.' },
      { id: 'b', label: 'The model has zero memory during a single conversational exchange.' },
      { id: 'c', label: 'The customer agrees to delete all local corporate backups every 30 days.' },
      { id: 'd', label: 'The API provider delivers inference results free of charge.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_06',
    section: 'privacy',
    prompt: 'Why is client-side data anonymization (e.g. replacing "Alice Smith at Acme Corp" with "[Client_A] at [Company_X]") a best practice?',
    options: [
      { id: 'a', label: 'It guarantees the generated text will be 100% grammatically correct.' },
      { id: 'b', label: 'It reduces the latency of the model inference by 50%.' },
      { id: 'c', label: 'If sensitive identifiers are never sent over the network to the AI provider, privacy breaches or training data leaks are completely prevented.' },
      { id: 'd', label: 'It converts the model output directly into encrypted bytecode.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_priv_07',
    section: 'privacy',
    prompt: 'What is the risk of asking an AI tool to write performance reviews or evaluation feedback for colleagues using real names?',
    options: [
      { id: 'a', label: 'The AI service will automatically send the draft to the colleague via email.' },
      { id: 'b', label: 'Potential leakage of sensitive HR personnel records to external vendor servers, violating workplace privacy policies.' },
      { id: 'c', label: 'It causes the user\'s local disk drive to become corrupted.' },
      { id: 'd', label: 'The AI model will refuse to generate any text containing human names.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_08',
    section: 'privacy',
    prompt: 'How can an employee opt-out of model training on their data in major consumer AI tools (like ChatGPT or Claude)?',
    options: [
      { id: 'a', label: 'Include "PLEASE DO NOT TRAIN ON THIS" at the start of every chat message.' },
      { id: 'b', label: 'Use an incognito browser window without changing any platform settings.' },
      { id: 'c', label: 'Disconnect from the internet immediately after clicking generate.' },
      { id: 'd', label: 'Navigate to Data Controls / Privacy Settings in the app and disable "Improve the model for everyone" or turn off chat history training.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_priv_09',
    section: 'privacy',
    prompt: 'What is "algorithmic bias" in AI model outputs?',
    options: [
      { id: 'a', label: 'Systematic, unfair skews or stereotypes in model behavior reflecting demographic prejudices or imbalances present in historical training datasets.' },
      { id: 'b', label: 'A hardware arithmetic error that occurs when dividing by zero.' },
      { id: 'c', label: 'A user\'s personal subjective opinion about the aesthetics of an AI interface.' },
      { id: 'd', label: 'An intentional security measure to restrict model access by IP address.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_10',
    section: 'privacy',
    prompt: 'Who bears final legal and professional accountability for errors, copyright violations, or privacy leaks in AI-assisted work?',
    options: [
      { id: 'a', label: 'The cloud service provider hosting the AI hardware infrastructure.' },
      { id: 'b', label: 'The open-source algorithm authors who created the neural network architecture.' },
      { id: 'c', label: 'The human professional who submitted the prompt and reviewed, approved, or published the final output.' },
      { id: 'd', label: 'The AI model itself through its registered corporate entity.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_priv_11',
    section: 'privacy',
    prompt: 'What does "Data Minimization" mean when preparing inputs for an external AI platform?',
    options: [
      { id: 'a', label: 'Deleting all sentences that contain more than 10 words.' },
      { id: 'b', label: 'Stripping out unnecessary personal, sensitive, or confidential identifiers and only submitting the bare minimum text required for the task.' },
      { id: 'c', label: 'Converting all text into lower-case before submission.' },
      { id: 'd', label: 'Submitting only numbers without any words.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_12',
    section: 'privacy',
    prompt: 'Under regulations like GDPR or CCPA, why is inputting customer identifiable information (PII) into an unvetted public AI tool risky?',
    options: [
      { id: 'a', label: 'It constitutes an unauthorized third-party data disclosure that could breach customer consent agreements and trigger regulatory penalties.' },
      { id: 'b', label: 'It automatically disables SSL encryption on the user\'s router.' },
      { id: 'c', label: 'It causes the customer\'s credit score to immediately drop.' },
      { id: 'd', label: 'It deletes the customer\'s account from all social networks.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_13',
    section: 'privacy',
    prompt: 'What is "Prompt Injection" in the context of AI application security?',
    options: [
      { id: 'a', label: 'Injecting medicine into a computer power supply.' },
      { id: 'b', label: 'A method for accelerating model inference through GPU overclocking.' },
      { id: 'c', label: 'Creating multiple user profiles on a chat platform.' },
      { id: 'd', label: 'An attack technique where adversarial user input overrides developer instructions and forces the model to ignore safety guardrails.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_priv_14',
    section: 'privacy',
    prompt: 'How should an organization handle proprietary source code when developers use AI coding assistants?',
    options: [
      { id: 'a', label: 'Publish the entire codebase to public forums for open-source review.' },
      { id: 'b', label: 'Allow developers to use any free, personal-tier AI plugins without IT approval.' },
      { id: 'c', label: 'Establish an enterprise agreement with zero-data-retention guarantees and configure IDE extensions to exclude sensitive repos/keys.' },
      { id: 'd', label: 'Forbid developers from writing any comments in their code.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_priv_15',
    section: 'privacy',
    prompt: 'What is a "Data Processing Agreement" (DPA) and why is it required before enterprise deployment of AI models?',
    options: [
      { id: 'a', label: 'A binding contract specifying how vendor systems handle, store, protect, and legally segregate customer data during model processing.' },
      { id: 'b', label: 'A software license for operating system fonts.' },
      { id: 'c', label: 'A receipt for hardware server purchases.' },
      { id: 'd', label: 'A marketing newsletter signup form.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_16',
    section: 'privacy',
    prompt: 'If you must analyze customer feedback containing names and phone numbers using AI, what is the best practice before prompting?',
    options: [
      { id: 'a', label: 'Submit the full data as-is without alterations.' },
      { id: 'b', label: 'Anonymize or pseudonymize the records by replacing names with placeholders like [Customer_A] and masking phone numbers.' },
      { id: 'c', label: 'Ask the AI to promise not to remember the names.' },
      { id: 'd', label: 'Translate the phone numbers into hexadecimal code.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_17',
    section: 'privacy',
    prompt: 'What is the risk of "Membership Inference" or training data extraction attacks against LLMs?',
    options: [
      { id: 'a', label: 'The model might delete its own weights during inference.' },
      { id: 'b', label: 'The computer fan might spin too fast.' },
      { id: 'c', label: 'The model might refuse to answer mathematical questions.' },
      { id: 'd', label: 'Adversaries may craft queries designed to reconstruct private individual records or secrets memorized during model pre-training.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_priv_18',
    section: 'privacy',
    prompt: 'When using AI-generated marketing copy, what copyright consideration must teams keep in mind?',
    options: [
      { id: 'a', label: 'AI text is universally protected by global copyright with zero verification needed.' },
      { id: 'b', label: 'No AI-generated text can ever be read by consumers legally.' },
      { id: 'c', label: 'Unedited raw AI outputs may lack copyright protection in many jurisdictions, and could inadvertently reproduce existing copyrighted phrasing.' },
      { id: 'd', label: 'AI models automatically own trademark rights to all generated slogans.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_priv_19',
    section: 'privacy',
    prompt: 'What is an "AI Watermark" or provenance metadata in synthetic media (images, audio, video)?',
    options: [
      { id: 'a', label: 'Embedded cryptographic signatures or steganographic markers (like C2PA) indicating that the content was generated or altered by AI.' },
      { id: 'b', label: 'A physical stamp placed on paper documents.' },
      { id: 'c', label: 'A blue badge displayed on a user\'s profile picture.' },
      { id: 'd', label: 'An error banner indicating server maintenance.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_20',
    section: 'privacy',
    prompt: 'Why should teams maintain an "AI Usage Policy" in their workplace handbook?',
    options: [
      { id: 'a', label: 'To discourage employees from using modern technology entirely.' },
      { id: 'b', label: 'To define approved tools, acceptable data classification tiers, mandatory human verification steps, and ethical guidelines.' },
      { id: 'c', label: 'To increase the length of company documentation.' },
      { id: 'd', label: 'To transfer internal IT responsibilities to third-party chatbots.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_21',
    section: 'privacy',
    prompt: 'An employee copies confidential source code containing production API secret keys into a public free AI chatbot for debugging. What immediate security breach has occurred?',
    options: [
      { id: 'a', label: 'No breach occurred because all chatbots run in isolated local browser sandboxes.' },
      { id: 'b', label: 'Exposure of proprietary credentials and IP that may be logged, retained for model retraining, or viewed by third-party vendor review teams; keys must be revoked and rotated immediately.' },
      { id: 'c', label: 'The employee workstation will instantly shut down automatically.' },
      { id: 'd', label: 'The API provider will automatically delete the secret keys within 1 millisecond.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_22',
    section: 'privacy',
    prompt: 'Under GDPR and CCPA regulations, what right does a consumer have regarding automated decision-making and profiling systems powered by AI?',
    options: [
      { id: 'a', label: 'Consumers have no legal rights regarding automated algorithmic scoring.' },
      { id: 'b', label: 'The right to be informed of automated processing, the right to meaningful explanation of logic involved, and the right to human intervention/review for significant legal/financial decisions.' },
      { id: 'c', label: 'The right to receive free hardware from the AI developer company.' },
      { id: 'd', label: 'The right to force the AI model source code to be publicly open-sourced.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_23',
    section: 'privacy',
    prompt: 'What is "Data Poisoning" in the context of machine learning and generative AI security?',
    options: [
      { id: 'a', label: 'Physically damaging the server hard drives with corrosive chemicals.' },
      { id: 'b', label: 'An adversarial attack where malicious, biased, or corrupted data is deliberately injected into training or fine-tuning datasets to compromise model behavior or introduce backdoors.' },
      { id: 'c', label: 'Exceeding the daily token usage limit on an enterprise account.' },
      { id: 'd', label: 'A database query that takes longer than 5 seconds to execute.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_24',
    section: 'privacy',
    prompt: 'When integrating a cloud AI vendor for medical healthcare data processing, which legal agreement is strictly mandatory in the United States under HIPAA?',
    options: [
      { id: 'a', label: 'Business Associate Agreement (BAA) with zero-data retention commitments and encryption guarantees.' },
      { id: 'b', label: 'A standard consumer Terms of Service clickwrap agreement.' },
      { id: 'c', label: 'A social media marketing endorsement agreement.' },
      { id: 'd', label: 'No legal agreement is required if the model runs via HTTPS.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_25',
    section: 'privacy',
    prompt: 'What constitutes an "Indirect Prompt Injection" attack in production AI applications?',
    options: [
      { id: 'a', label: 'A user typing password reset commands in the main chat box.' },
      { id: 'b', label: 'An attacker embedding hidden adversarial instructions inside untrusted third-party content (e.g., a webpage, PDF, or email) that gets ingested and parsed by the AI agent, hijacking its execution.' },
      { id: 'c', label: 'A physical hardware disconnect of network cables.' },
      { id: 'd', label: 'A SQL injection attack targeting traditional relational database tables directly.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_26',
    section: 'privacy',
    prompt: 'What is the function of "Data Anonymization vs Pseudonymization" when preparing data for AI modeling?',
    options: [
      { id: 'a', label: 'Anonymization irreversibly removes all personal identifiers so re-identification is impossible; pseudonymization replaces identifiers with artificial pseudonyms that can be linked back using a separate key.' },
      { id: 'b', label: 'Both terms mean deleting the entire database permanently.' },
      { id: 'c', label: 'Pseudonymization is used exclusively for audio files; anonymization is for text.' },
      { id: 'd', label: 'Anonymization is prohibited under all privacy regulations.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_27',
    section: 'privacy',
    prompt: 'Why is "Shadow AI" (employees using unvetted consumer AI tools on personal accounts for work tasks) a major compliance risk?',
    options: [
      { id: 'a', label: 'It causes office printers to malfunction.' },
      { id: 'b', label: 'It bypasses enterprise data loss prevention (DLP), audit logging, zero-retention policies, and regulatory data sovereignty controls.' },
      { id: 'c', label: 'It increases internet bandwidth consumption by 10%.' },
      { id: 'd', label: 'It automatically revokes the company business license.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_28',
    section: 'privacy',
    prompt: 'What is a "System Card" or "Model Card" published by responsible AI foundation model providers?',
    options: [
      { id: 'a', label: 'A plastic ID card issued to employees of AI laboratories.' },
      { id: 'b', label: 'A technical document disclosing model architecture, intended use cases, training data provenance, evaluation benchmarks, known limitations, and safety testing results.' },
      { id: 'c', label: 'A credit card used to pay monthly cloud billing fees.' },
      { id: 'd', label: 'A promotional marketing flyer given out at developer conferences.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_29',
    section: 'privacy',
    prompt: 'What is the primary risk of using synthetic AI-generated avatars or cloned voices in customer communication without disclosure?',
    options: [
      { id: 'a', label: 'It consumes too many CPU cycles on client mobile devices.' },
      { id: 'b', label: 'Deception risk, potential violation of deepfake disclosure laws (e.g., EU AI Act), and severe degradation of consumer brand trust.' },
      { id: 'c', label: 'Cloned voices cannot be played over standard telephone lines.' },
      { id: 'd', label: 'Avatars are automatically blocked by internet service providers.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_30',
    section: 'privacy',
    prompt: 'What does "Zero Data Retention" (ZDR) guarantee in enterprise LLM API service level agreements?',
    options: [
      { id: 'a', label: 'The vendor stores prompt inputs and generated outputs exclusively in RAM during processing and commits to not logging or saving them to persistent disk storage.' },
      { id: 'b', label: 'The client application deletes all local databases every 24 hours.' },
      { id: 'c', label: 'The vendor provides zero customer support during outages.' },
      { id: 'd', label: 'The model has zero memory of its base training weights.' },
    ],
    correctOptionId: 'a',
  },
];


