import { CertQuestion } from '../types';

export const BEGINNER_PRIVACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'beg_priv_01',
    section: 'privacy',
    prompt: 'What is the crucial privacy difference between free consumer AI web chats and enterprise AI API services?',
    options: [
      { id: 'a', label: 'Enterprise services run locally without using any internet connection or cloud processing.' },
      { id: 'b', label: 'Consumer tiers are completely anonymous and never log any telemetry or prompt data.' },
      { id: 'c', label: 'Free consumer tiers typically retain user prompts to train future foundation models, while enterprise agreements provide Zero Data Retention (ZDR) and strict confidentiality.' },
      { id: 'd', label: 'Consumer tiers encrypt data with government keys, while enterprise tiers make prompts public.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_priv_02',
    section: 'privacy',
    prompt: 'What constitutes Personally Identifiable Information (PII) that should NEVER be pasted into unvetted consumer AI tools?',
    options: [
      { id: 'a', label: 'Social Security / national ID numbers, financial account details, medical records, and private customer contact databases.' },
      { id: 'b', label: 'Public Wikipedia reference articles and open encyclopedias.' },
      { id: 'c', label: 'Open-source software documentation and public repository links.' },
      { id: 'd', label: 'Standard dictionary definitions of English vocabulary words.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_03',
    section: 'privacy',
    prompt: 'What is a "personal red line" in ethical AI usage?',
    options: [
      { id: 'a', label: 'A mechanical circuit limit on GPU computing clusters.' },
      { id: 'b', label: 'A red underline in text editors indicating grammar errors.' },
      { id: 'c', label: 'A firewall setting that blocks all outbound internet traffic.' },
      { id: 'd', label: 'A conscious, non-negotiable boundary defining decisions or sensitive topics where you will never delegate authority to an AI system.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_priv_04',
    section: 'privacy',
    prompt: 'Before uploading an internal company report to an AI tool, what safety check should an employee perform?',
    options: [
      { id: 'a', label: 'Rename the file extension so security scanners do not recognize the format.' },
      { id: 'b', label: 'Verify company authorized AI tool lists, check data classification policies, and scrub confidential client names or proprietary trade secrets.' },
      { id: 'c', label: 'Upload the document immediately as long as it is done during non-business hours.' },
      { id: 'd', label: 'Assume all commercial AI services automatically comply with your employer\'s specific security policy.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_05',
    section: 'privacy',
    prompt: 'What does "Zero Data Retention" (ZDR) mean in an AI enterprise contract?',
    options: [
      { id: 'a', label: 'The vendor processes the prompt in volatile memory for inference and does not persist, log, or train on the input/output after the request completes.' },
      { id: 'b', label: 'The model has zero memory during a single conversational exchange.' },
      { id: 'c', label: 'The customer agrees to delete all local corporate backups every 30 days.' },
      { id: 'd', label: 'The API provider delivers inference results free of charge.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_06',
    section: 'privacy',
    prompt: 'Why is client-side data anonymization (e.g. replacing "Alice Smith at Acme Corp" with "[Client_A] at [Company_X]") a best practice?',
    options: [
      { id: 'a', label: 'It guarantees the generated text will be 100% grammatically correct.' },
      { id: 'b', label: 'It reduces the latency of the model inference by 50%.' },
      { id: 'c', label: 'If sensitive identifiers are never sent over the network to the AI provider, privacy breaches or training data leaks are completely prevented.' },
      { id: 'd', label: 'It converts the model output directly into encrypted bytecode.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_priv_07',
    section: 'privacy',
    prompt: 'What is the risk of asking an AI tool to write performance reviews or evaluation feedback for colleagues using real names?',
    options: [
      { id: 'a', label: 'The AI service will automatically send the draft to the colleague via email.' },
      { id: 'b', label: 'Potential leakage of sensitive HR personnel records to external vendor servers, violating workplace privacy policies.' },
      { id: 'c', label: 'It causes the user\'s local disk drive to become corrupted.' },
      { id: 'd', label: 'The AI model will refuse to generate any text containing human names.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_08',
    section: 'privacy',
    prompt: 'How can an employee opt-out of model training on their data in major consumer AI tools (like ChatGPT or Claude)?',
    options: [
      { id: 'a', label: 'Include "PLEASE DO NOT TRAIN ON THIS" at the start of every chat message.' },
      { id: 'b', label: 'Use an incognito browser window without changing any platform settings.' },
      { id: 'c', label: 'Disconnect from the internet immediately after clicking generate.' },
      { id: 'd', label: 'Navigate to Data Controls / Privacy Settings in the app and disable "Improve the model for everyone" or turn off chat history training.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_priv_09',
    section: 'privacy',
    prompt: 'What is "algorithmic bias" in AI model outputs?',
    options: [
      { id: 'a', label: 'Systematic, unfair skews or stereotypes in model behavior reflecting demographic prejudices or imbalances present in historical training datasets.' },
      { id: 'b', label: 'A hardware arithmetic error that occurs when dividing by zero.' },
      { id: 'c', label: 'A user\'s personal subjective opinion about the aesthetics of an AI interface.' },
      { id: 'd', label: 'An intentional security measure to restrict model access by IP address.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_10',
    section: 'privacy',
    prompt: 'Who bears final legal and professional accountability for errors, copyright violations, or privacy leaks in AI-assisted work?',
    options: [
      { id: 'a', label: 'The cloud service provider hosting the AI hardware infrastructure.' },
      { id: 'b', label: 'The open-source algorithm authors who created the neural network architecture.' },
      { id: 'c', label: 'The human professional who submitted the prompt and reviewed, approved, or published the final output.' },
      { id: 'd', label: 'The AI model itself through its registered corporate entity.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_priv_11',
    section: 'privacy',
    prompt: 'What does "Data Minimization" mean when preparing inputs for an external AI platform?',
    options: [
      { id: 'a', label: 'Deleting all sentences that contain more than 10 words.' },
      { id: 'b', label: 'Stripping out unnecessary personal, sensitive, or confidential identifiers and only submitting the bare minimum text required for the task.' },
      { id: 'c', label: 'Converting all text into lower-case before submission.' },
      { id: 'd', label: 'Submitting only numbers without any words.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_12',
    section: 'privacy',
    prompt: 'Under regulations like GDPR or CCPA, why is inputting customer identifiable information (PII) into an unvetted public AI tool risky?',
    options: [
      { id: 'a', label: 'It constitutes an unauthorized third-party data disclosure that could breach customer consent agreements and trigger regulatory penalties.' },
      { id: 'b', label: 'It automatically disables SSL encryption on the user\'s router.' },
      { id: 'c', label: 'It causes the customer\'s credit score to immediately drop.' },
      { id: 'd', label: 'It deletes the customer\'s account from all social networks.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_13',
    section: 'privacy',
    prompt: 'What is "Prompt Injection" in the context of AI application security?',
    options: [
      { id: 'a', label: 'Injecting medicine into a computer power supply.' },
      { id: 'b', label: 'A method for accelerating model inference through GPU overclocking.' },
      { id: 'c', label: 'Creating multiple user profiles on a chat platform.' },
      { id: 'd', label: 'An attack technique where adversarial user input overrides developer instructions and forces the model to ignore safety guardrails.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_priv_14',
    section: 'privacy',
    prompt: 'How should an organization handle proprietary source code when developers use AI coding assistants?',
    options: [
      { id: 'a', label: 'Publish the entire codebase to public forums for open-source review.' },
      { id: 'b', label: 'Allow developers to use any free, personal-tier AI plugins without IT approval.' },
      { id: 'c', label: 'Establish an enterprise agreement with zero-data-retention guarantees and configure IDE extensions to exclude sensitive repos/keys.' },
      { id: 'd', label: 'Forbid developers from writing any comments in their code.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_priv_15',
    section: 'privacy',
    prompt: 'What is a "Data Processing Agreement" (DPA) and why is it required before enterprise deployment of AI models?',
    options: [
      { id: 'a', label: 'A binding contract specifying how vendor systems handle, store, protect, and legally segregate customer data during model processing.' },
      { id: 'b', label: 'A software license for operating system fonts.' },
      { id: 'c', label: 'A receipt for hardware server purchases.' },
      { id: 'd', label: 'A marketing newsletter signup form.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_16',
    section: 'privacy',
    prompt: 'If you must analyze customer feedback containing names and phone numbers using AI, what is the best practice before prompting?',
    options: [
      { id: 'a', label: 'Submit the full data as-is without alterations.' },
      { id: 'b', label: 'Anonymize or pseudonymize the records by replacing names with placeholders like [Customer_A] and masking phone numbers.' },
      { id: 'c', label: 'Ask the AI to promise not to remember the names.' },
      { id: 'd', label: 'Translate the phone numbers into hexadecimal code.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'beg_priv_17',
    section: 'privacy',
    prompt: 'What is the risk of "Membership Inference" or training data extraction attacks against LLMs?',
    options: [
      { id: 'a', label: 'The model might delete its own weights during inference.' },
      { id: 'b', label: 'The computer fan might spin too fast.' },
      { id: 'c', label: 'The model might refuse to answer mathematical questions.' },
      { id: 'd', label: 'Adversaries may craft queries designed to reconstruct private individual records or secrets memorized during model pre-training.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'beg_priv_18',
    section: 'privacy',
    prompt: 'When using AI-generated marketing copy, what copyright consideration must teams keep in mind?',
    options: [
      { id: 'a', label: 'AI text is universally protected by global copyright with zero verification needed.' },
      { id: 'b', label: 'No AI-generated text can ever be read by consumers legally.' },
      { id: 'c', label: 'Unedited raw AI outputs may lack copyright protection in many jurisdictions, and could inadvertently reproduce existing copyrighted phrasing.' },
      { id: 'd', label: 'AI models automatically own trademark rights to all generated slogans.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'beg_priv_19',
    section: 'privacy',
    prompt: 'What is an "AI Watermark" or provenance metadata in synthetic media (images, audio, video)?',
    options: [
      { id: 'a', label: 'Embedded cryptographic signatures or steganographic markers (like C2PA) indicating that the content was generated or altered by AI.' },
      { id: 'b', label: 'A physical stamp placed on paper documents.' },
      { id: 'c', label: 'A blue badge displayed on a user\'s profile picture.' },
      { id: 'd', label: 'An error banner indicating server maintenance.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'beg_priv_20',
    section: 'privacy',
    prompt: 'Why should teams maintain an "AI Usage Policy" in their workplace handbook?',
    options: [
      { id: 'a', label: 'To discourage employees from using modern technology entirely.' },
      { id: 'b', label: 'To define approved tools, acceptable data classification tiers, mandatory human verification steps, and ethical guidelines.' },
      { id: 'c', label: 'To increase the length of company documentation.' },
      { id: 'd', label: 'To transfer internal IT responsibilities to third-party chatbots.' },
    ],
    correctOptionId: 'b',
  },
];

