import { CertQuestion } from '../types';

export const BOOMI_LITERACY_QUESTIONS: CertQuestion[] = [
  {
    "id": "boomi_lit_01",
    "section": "literacy",
    "prompt": "In Boomi AtomSphere architecture, what is an \"Atom\"?",
    "options": [
      {
        "id": "a",
        "label": "A hardware computer chip manufactured by Boomi"
      },
      {
        "id": "b",
        "label": "A lightweight, single-tenant Java runtime engine that executes integration processes on-premises, in a private cloud, or hosted in the Boomi public cloud"
      },
      {
        "id": "c",
        "label": "A single line of JavaScript code in a map function"
      },
      {
        "id": "d",
        "label": "A relational database table containing user accounts"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "boomi_lit_02",
    "section": "literacy",
    "prompt": "What is the primary difference between a Boomi Atom and a Boomi Molecule?",
    "options": [
      {
        "id": "a",
        "label": "An Atom only runs in the cloud; a Molecule only runs on Windows 10"
      },
      {
        "id": "b",
        "label": "A Molecule cannot process XML files"
      },
      {
        "id": "c",
        "label": "An Atom is a single-node runtime; a Molecule is a multi-node, clustered runtime architecture that shares a common file system for high availability and load distribution"
      },
      {
        "id": "d",
        "label": "An Atom does not require Java"
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "boomi_lit_03",
    "section": "literacy",
    "prompt": "What is a \"Document\" in Boomi process execution context?",
    "options": [
      {
        "id": "a",
        "label": "The discrete unit of data (e.g. a single record, an XML payload, a JSON object, a CSV row, or a binary file) flowing through shapes in a process execution"
      },
      {
        "id": "b",
        "label": "A PDF user manual generated by Boomi"
      },
      {
        "id": "c",
        "label": "The source code of the integration process saved to disk"
      },
      {
        "id": "d",
        "label": "An invoice sent to accounting for cloud usage"
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "boomi_lit_04",
    "section": "literacy",
    "prompt": "In Boomi, what is the fundamental difference between a \"Document Property\" (or Dynamic Document Property) and a \"Process Property\" (or Dynamic Process Property)?",
    "options": [
      {
        "id": "a",
        "label": "Process Properties are deleted immediately after reading; Document Properties persist forever in the database"
      },
      {
        "id": "b",
        "label": "Document Properties can only store numbers; Process Properties only store strings"
      },
      {
        "id": "c",
        "label": "Document Properties require an external LDAP server"
      },
      {
        "id": "d",
        "label": "Document Properties travel with and are unique to individual documents; Process Properties are global variables scoped to the entire process execution across all documents"
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "boomi_lit_05",
    "section": "literacy",
    "prompt": "Which shape in a Boomi process transforms data from a source Profile structure into a target Profile structure?",
    "options": [
      {
        "id": "a",
        "label": "Branch Shape"
      },
      {
        "id": "b",
        "label": "Decision Shape"
      },
      {
        "id": "c",
        "label": "Map Shape"
      },
      {
        "id": "d",
        "label": "Notify Shape"
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "boomi_lit_06",
    "section": "literacy",
    "prompt": "What is the function of the Boomi \"Branch\" shape?",
    "options": [
      {
        "id": "a",
        "label": "It executes multiple processing paths sequentially: Branch 1 processes all documents to completion before Branch 2 receives the original documents"
      },
      {
        "id": "b",
        "label": "It executes multiple branches simultaneously in parallel worker threads"
      },
      {
        "id": "c",
        "label": "It creates a git branch in the version control repository"
      },
      {
        "id": "d",
        "label": "It splits a single document into 10 smaller documents"
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "boomi_lit_07",
    "section": "literacy",
    "prompt": "What is a \"Profile\" component in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "The user account settings and contact information of a developer"
      },
      {
        "id": "b",
        "label": "A hardware configuration template for server provisioning"
      },
      {
        "id": "c",
        "label": "A security certificate issued by a CA"
      },
      {
        "id": "d",
        "label": "A reusable component that defines the structure and data format (XML, JSON, Flat File, Database, or EDI) of documents processed by Boomi"
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "boomi_lit_08",
    "section": "literacy",
    "prompt": "How does the \"Decision\" shape evaluate documents in a Boomi process?",
    "options": [
      {
        "id": "a",
        "label": "It splits documents into 10 equal parts"
      },
      {
        "id": "b",
        "label": "It evaluates a true/false condition on each document, routing matching documents down the True path and non-matching documents down the False path"
      },
      {
        "id": "c",
        "label": "It sends an email prompt to the system administrator asking for a decision"
      },
      {
        "id": "d",
        "label": "It restarts the process if any field contains an error"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "boomi_lit_09",
    "section": "literacy",
    "prompt": "In Boomi, what two reusable components make up a Connector?",
    "options": [
      {
        "id": "a",
        "label": "Source and Target"
      },
      {
        "id": "b",
        "label": "Input and Output"
      },
      {
        "id": "c",
        "label": "Listener and Speaker"
      },
      {
        "id": "d",
        "label": "Connection (which specifies where and how to connect, e.g. URL and credentials) and Operation (which specifies what action to perform, e.g. Get, Query, Create, Upsert)"
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "boomi_lit_10",
    "section": "literacy",
    "prompt": "What is the function of the \"Set Properties\" shape in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "To change the operating system file permissions on the Atom host"
      },
      {
        "id": "b",
        "label": "To set or modify Document Properties, Dynamic Document Properties, Dynamic Process Properties, or Process Properties using static values, profile elements, or functions"
      },
      {
        "id": "c",
        "label": "To format text into HTML format"
      },
      {
        "id": "d",
        "label": "To create new user accounts in Boomi AtomSphere"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "boomi_lit_11",
    "section": "literacy",
    "prompt": "What is the purpose of the \"Start\" shape in a Boomi integration process?",
    "options": [
      {
        "id": "a",
        "label": "It turns on the power of the server hardware"
      },
      {
        "id": "b",
        "label": "It initializes the local Git repository"
      },
      {
        "id": "c",
        "label": "It defines how the process is triggered (e.g. via an Inbound Connector, Web Services Server, or \"No Data\" for scheduled/sub-process triggers)"
      },
      {
        "id": "d",
        "label": "It prompts the user to enter a license key"
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "boomi_lit_12",
    "section": "literacy",
    "prompt": "What is a \"Boomi Cloud\" (or Atom Cloud)?",
    "options": [
      {
        "id": "a",
        "label": "A multi-tenant, hosted Boomi runtime infrastructure where multiple customer accounts can deploy and execute integration processes in isolated Cloud Atoms without managing infrastructure"
      },
      {
        "id": "b",
        "label": "A weather forecasting service integrated with Boomi"
      },
      {
        "id": "c",
        "label": "A private cloud storage bucket hosted on AWS S3"
      },
      {
        "id": "d",
        "label": "An offline development environment"
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "boomi_lit_13",
    "section": "literacy",
    "prompt": "What is the purpose of the \"Route\" shape in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "It evaluates document property or profile field values against multiple conditional comparison rules and routes documents down matching path branches"
      },
      {
        "id": "b",
        "label": "It calculates the shortest driving distance between two addresses using GPS"
      },
      {
        "id": "c",
        "label": "It generates network routing tables for Cisco routers"
      },
      {
        "id": "d",
        "label": "It sends documents to the recycle bin"
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "boomi_lit_14",
    "section": "literacy",
    "prompt": "What is the function of the \"Notify\" shape in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "To pop up an alert window on the client computer screen"
      },
      {
        "id": "b",
        "label": "To ring an alarm bell in the data center"
      },
      {
        "id": "c",
        "label": "To send a text message via SMS to the CEO"
      },
      {
        "id": "d",
        "label": "To generate custom log messages, execution alerts, and audit trail notifications that are recorded in the execution log and can be sent as email alerts"
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "boomi_lit_15",
    "section": "literacy",
    "prompt": "In Boomi, what is the role of a \"Component\"?",
    "options": [
      {
        "id": "a",
        "label": "A physical RAM chip on the server motherboard"
      },
      {
        "id": "b",
        "label": "A reusable, version-controlled integration artifact (such as a Process, Map, Profile, Connection, Operation, or Certificate) stored in the Component Explorer"
      },
      {
        "id": "c",
        "label": "A third-party plugin purchased from a software store"
      },
      {
        "id": "d",
        "label": "An executable file installed in Windows Program Files"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "boomi_lit_16",
    "section": "literacy",
    "prompt": "What is the difference between \"Test Mode\" and \"Deployed Execution\" in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "Test Mode is free while Deployed Execution requires immediate credit card payment"
      },
      {
        "id": "b",
        "label": "Test Mode only runs on Linux; Deployed Execution runs on Windows"
      },
      {
        "id": "c",
        "label": "Test Mode executes within the UI designer with a maximum limit of 100 documents / 10 MB for interactive debugging; Deployed Execution runs automatically on scheduled/listener runtimes without limits"
      },
      {
        "id": "d",
        "label": "Test Mode deletes data permanently from target databases"
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "boomi_lit_17",
    "section": "literacy",
    "prompt": "What is the function of the \"Stop\" shape in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "It shuts down the Atom operating system immediately"
      },
      {
        "id": "b",
        "label": "It terminates a branch execution cleanly and can optionally be configured to \"Continue execution other branches\" or mark the document as failed"
      },
      {
        "id": "c",
        "label": "It deletes all files in the current work directory"
      },
      {
        "id": "d",
        "label": "It disconnects the network cable"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "boomi_lit_18",
    "section": "literacy",
    "prompt": "What is the purpose of the \"Exception\" shape in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "It terminates the process execution for arriving documents and flags the process execution status as an Error, generating an exception message in execution history"
      },
      {
        "id": "b",
        "label": "It skips the next 5 shapes in the flow"
      },
      {
        "id": "c",
        "label": "It grants the document immunity from validation errors"
      },
      {
        "id": "d",
        "label": "It converts the error into a success message"
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "boomi_lit_19",
    "section": "literacy",
    "prompt": "What type of Profile in Boomi is used to represent delimiter-separated values (like CSV) or fixed-width text records?",
    "options": [
      {
        "id": "a",
        "label": "XML Profile"
      },
      {
        "id": "b",
        "label": "JSON Profile"
      },
      {
        "id": "c",
        "label": "Database Profile"
      },
      {
        "id": "d",
        "label": "Flat File Profile"
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "boomi_lit_20",
    "section": "literacy",
    "prompt": "What is the purpose of a \"Database Profile\" in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "It stores the database administrator password"
      },
      {
        "id": "b",
        "label": "It defines the physical hard disk partition size for SQL Server"
      },
      {
        "id": "c",
        "label": "It defines the SQL statement parameters and result set column structures for Database connector Read, Write, and Stored Procedure operations"
      },
      {
        "id": "d",
        "label": "It creates a database backup file on AWS S3"
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "boomi_lit_21",
    "section": "literacy",
    "prompt": "What is the role of an \"Environment\" in Boomi AtomSphere?",
    "options": [
      {
        "id": "a",
        "label": "The physical weather climate of the server facility"
      },
      {
        "id": "b",
        "label": "The operating system environment variables of the client laptop"
      },
      {
        "id": "c",
        "label": "A logical deployment stage (e.g. Development, Test, Production) to which Atoms/Molecules are attached and integration packages are deployed with environment-specific extensions"
      },
      {
        "id": "d",
        "label": "A programming language compiler configuration"
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "boomi_lit_22",
    "section": "literacy",
    "prompt": "Which shape allows executing a sub-process synchronously or asynchronously from within a parent Boomi process?",
    "options": [
      {
        "id": "a",
        "label": "Map Shape"
      },
      {
        "id": "b",
        "label": "Notify Shape"
      },
      {
        "id": "c",
        "label": "Data Process Shape"
      },
      {
        "id": "d",
        "label": "Process Call Shape"
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "boomi_lit_23",
    "section": "literacy",
    "prompt": "In Boomi, how does an Atom communicate with the AtomSphere cloud platform?",
    "options": [
      {
        "id": "a",
        "label": "The Atom initiates outbound HTTPS (port 443) communication to AtomSphere web services periodically for health pings, deployment retrieval, and tracking logs without requiring inbound firewall openings"
      },
      {
        "id": "b",
        "label": "AtomSphere initiates inbound SSH connections to port 22 on the Atom server"
      },
      {
        "id": "c",
        "label": "Through unencrypted UDP broadcast packets"
      },
      {
        "id": "d",
        "label": "Via direct database connections to Oracle"
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "boomi_lit_24",
    "section": "literacy",
    "prompt": "What is the purpose of the \"Cleanse\" shape in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "It deletes virus files from the hard disk"
      },
      {
        "id": "b",
        "label": "It validates incoming document fields against rules defined in a Profile (e.g. mandatory fields, data types, lengths) and splits valid and invalid documents into separate paths"
      },
      {
        "id": "c",
        "label": "It scrubs sensitive passwords from source code files"
      },
      {
        "id": "d",
        "label": "It flushes the JVM garbage collection heap"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "boomi_lit_25",
    "section": "literacy",
    "prompt": "What is the function of the \"Find Changes\" shape in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "It finds spelling mistakes in documentation"
      },
      {
        "id": "b",
        "label": "It compares Git commits between two branches"
      },
      {
        "id": "c",
        "label": "It calculates currency exchange rate changes"
      },
      {
        "id": "d",
        "label": "It compares incoming documents against a historical snapshot to identify added, modified, or deleted records, routing each change category to different paths"
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "boomi_lit_26",
    "section": "literacy",
    "prompt": "What type of component in Boomi is used to map and transform EDI standard documents (such as X12 or EDIFACT)?",
    "options": [
      {
        "id": "a",
        "label": "JSON Profile and REST Client"
      },
      {
        "id": "b",
        "label": "Database Profile and Stored Procedure"
      },
      {
        "id": "c",
        "label": "EDI Profile and Trading Partner component"
      },
      {
        "id": "d",
        "label": "Flat File Profile with tab delimiters"
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "boomi_lit_27",
    "section": "literacy",
    "prompt": "What is the function of the \"Return Documents\" shape in a child sub-process?",
    "options": [
      {
        "id": "a",
        "label": "It emails documents back to the customer"
      },
      {
        "id": "b",
        "label": "It sends the processed documents from the sub-process back to the calling parent Process Call shape for continued execution"
      },
      {
        "id": "c",
        "label": "It deletes documents from memory"
      },
      {
        "id": "d",
        "label": "It rolls back the database transaction"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "boomi_lit_28",
    "section": "literacy",
    "prompt": "What is the purpose of the \"Message\" shape in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "To generate a new document payload or transform an existing document by combining static template text with dynamic parameters and variables"
      },
      {
        "id": "b",
        "label": "To send a Slack instant message"
      },
      {
        "id": "c",
        "label": "To post an announcement on the company intranet"
      },
      {
        "id": "d",
        "label": "To convert XML into binary bytecode"
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "boomi_lit_29",
    "section": "literacy",
    "prompt": "What is the role of the \"Web Services Server\" connector in Boomi?",
    "options": [
      {
        "id": "a",
        "label": "It enables an Atom or Molecule to act as an HTTP web server, listening for real-time inbound REST, SOAP, or raw HTTP API requests"
      },
      {
        "id": "b",
        "label": "It downloads web pages from external websites"
      },
      {
        "id": "c",
        "label": "It configures Apache Tomcat server files manually"
      },
      {
        "id": "d",
        "label": "It acts as an SMTP mail server"
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "boomi_lit_30",
    "section": "literacy",
    "prompt": "What is the difference between \"Execution Status: Pending\" and \"Execution Status: Complete\" in Process Reporting?",
    "options": [
      {
        "id": "a",
        "label": "`Pending` means the process was cancelled by an admin"
      },
      {
        "id": "b",
        "label": "`Pending` indicates the process is currently executing on the Atom runtime; `Complete` indicates the execution has finished successfully"
      },
      {
        "id": "c",
        "label": "`Complete` means the server has been turned off"
      },
      {
        "id": "d",
        "label": "`Pending` means the license has expired"
      }
    ],
    "correctOptionId": "b"
  }
];
