import { Question } from '../../certTypes';

export const boomiLiteracyQuestions: Question[] = [
  {
    id: 'boomi_lit_01',
    domain: 'literacy',
    text: 'In Boomi AtomSphere architecture, what is an "Atom"?',
    options: {
      a: 'A lightweight, single-tenant Java runtime engine that executes integration processes on-premises, in a private cloud, or hosted in the Boomi public cloud',
      b: 'A hardware computer chip manufactured by Boomi',
      c: 'A single line of JavaScript code in a map function',
      d: 'A relational database table containing user accounts'
    },
    correctAnswer: 'a',
    explanation: 'An Atom is Boomi\'s runtime engine—a single Java virtual machine (JVM) process that executes integration processes, manages connections, and communicates with the AtomSphere platform.'
  },
  {
    id: 'boomi_lit_02',
    domain: 'literacy',
    text: 'What is the primary difference between a Boomi Atom and a Boomi Molecule?',
    options: {
      a: 'An Atom is a single-node runtime; a Molecule is a multi-node, clustered runtime architecture that shares a common file system for high availability and load distribution',
      b: 'An Atom only runs in the cloud; a Molecule only runs on Windows 10',
      c: 'A Molecule cannot process XML files',
      d: 'An Atom does not require Java'
    },
    correctAnswer: 'a',
    explanation: 'A Molecule is a clustered group of Atoms running on multiple nodes/servers that share a single storage directory, providing automated failover and distributed parallel execution.'
  },
  {
    id: 'boomi_lit_03',
    domain: 'literacy',
    text: 'What is a "Document" in Boomi process execution context?',
    options: {
      a: 'The discrete unit of data (e.g. a single record, an XML payload, a JSON object, a CSV row, or a binary file) flowing through shapes in a process execution',
      b: 'A PDF user manual generated by Boomi',
      c: 'The source code of the integration process saved to disk',
      d: 'An invoice sent to accounting for cloud usage'
    },
    correctAnswer: 'a',
    explanation: 'In Boomi, a Document is a discrete packet of data (record, transaction, or file) that passes through the process flow shapes.'
  },
  {
    id: 'boomi_lit_04',
    domain: 'literacy',
    text: 'In Boomi, what is the fundamental difference between a "Document Property" (or Dynamic Document Property) and a "Process Property" (or Dynamic Process Property)?',
    options: {
      a: 'Document Properties travel with and are unique to individual documents; Process Properties are global variables scoped to the entire process execution across all documents',
      b: 'Process Properties are deleted immediately after reading; Document Properties persist forever in the database',
      c: 'Document Properties can only store numbers; Process Properties only store strings',
      d: 'Document Properties require an external LDAP server'
    },
    correctAnswer: 'a',
    explanation: 'Dynamic Document Properties (DDP) are attached to individual documents and track data per document, while Dynamic Process Properties (DPP) are global to the entire execution instance.'
  },
  {
    id: 'boomi_lit_05',
    domain: 'literacy',
    text: 'Which shape in a Boomi process transforms data from a source Profile structure into a target Profile structure?',
    options: {
      a: 'Map Shape',
      b: 'Branch Shape',
      c: 'Decision Shape',
      d: 'Notify Shape'
    },
    correctAnswer: 'a',
    explanation: 'The Map shape references a Map component to transform fields, elements, and formats from a Source Profile to a Target Profile using mapping functions.'
  },
  {
    id: 'boomi_lit_06',
    domain: 'literacy',
    text: 'What is the function of the Boomi "Branch" shape?',
    options: {
      a: 'It executes multiple processing paths sequentially: Branch 1 processes all documents to completion before Branch 2 receives the original documents',
      b: 'It executes multiple branches simultaneously in parallel worker threads',
      c: 'It creates a git branch in the version control repository',
      d: 'It splits a single document into 10 smaller documents'
    },
    correctAnswer: 'a',
    explanation: 'The Branch shape executes branches in strict sequential order (Branch 1, Branch 2, etc.), with each branch receiving a fresh copy of the documents entering the Branch shape.'
  },
  {
    id: 'boomi_lit_07',
    domain: 'literacy',
    text: 'What is a "Profile" component in Boomi?',
    options: {
      a: 'A reusable component that defines the structure and data format (XML, JSON, Flat File, Database, or EDI) of documents processed by Boomi',
      b: 'The user account settings and contact information of a developer',
      c: 'A hardware configuration template for server provisioning',
      d: 'A security certificate issued by a CA'
    },
    correctAnswer: 'a',
    explanation: 'Profiles define the schema layout, data types, field lengths, and hierarchical structure of datasets (XML, JSON, Flat File, Database, or EDI).'
  },
  {
    id: 'boomi_lit_08',
    domain: 'literacy',
    text: 'How does the "Decision" shape evaluate documents in a Boomi process?',
    options: {
      a: 'It evaluates a true/false condition on each document, routing matching documents down the True path and non-matching documents down the False path',
      b: 'It splits documents into 10 equal parts',
      c: 'It sends an email prompt to the system administrator asking for a decision',
      d: 'It restarts the process if any field contains an error'
    },
    correctAnswer: 'a',
    explanation: 'The Decision shape compares two values (First Value vs Second Value using an operator like equals, greater than, matches regex) and routes each document to True or False.'
  },
  {
    id: 'boomi_lit_09',
    domain: 'literacy',
    text: 'In Boomi, what two reusable components make up a Connector?',
    options: {
      a: 'Connection (which specifies where and how to connect, e.g. URL and credentials) and Operation (which specifies what action to perform, e.g. Get, Query, Create, Upsert)',
      b: 'Source and Target',
      c: 'Input and Output',
      d: 'Listener and Speaker'
    },
    correctAnswer: 'a',
    explanation: 'Every Boomi Connector is built from a Connection component (endpoint details, authentication) and an Operation component (action, object type, request/response profile).'
  },
  {
    id: 'boomi_lit_10',
    domain: 'literacy',
    text: 'What is the function of the "Set Properties" shape in Boomi?',
    options: {
      a: 'To set or modify Document Properties, Dynamic Document Properties, Dynamic Process Properties, or Process Properties using static values, profile elements, or functions',
      b: 'To change the operating system file permissions on the Atom host',
      c: 'To format text into HTML format',
      d: 'To create new user accounts in Boomi AtomSphere'
    },
    correctAnswer: 'a',
    explanation: 'The Set Properties shape assigns values to metadata properties (such as file names, HTTP headers, Dynamic Document Properties, or Dynamic Process Properties).'
  },
  {
    id: 'boomi_lit_11',
    domain: 'literacy',
    text: 'What is the purpose of the "Start" shape in a Boomi integration process?',
    options: {
      a: 'It defines how the process is triggered (e.g. via an Inbound Connector, Web Services Server, or "No Data" for scheduled/sub-process triggers)',
      b: 'It turns on the power of the server hardware',
      c: 'It initializes the local Git repository',
      d: 'It prompts the user to enter a license key'
    },
    correctAnswer: 'a',
    explanation: 'The Start shape is the entry point of every process, configuring whether data is retrieved from an inbound connector or triggered with "No Data".'
  },
  {
    id: 'boomi_lit_12',
    domain: 'literacy',
    text: 'What is a "Boomi Cloud" (or Atom Cloud)?',
    options: {
      a: 'A multi-tenant, hosted Boomi runtime infrastructure where multiple customer accounts can deploy and execute integration processes in isolated Cloud Atoms without managing infrastructure',
      b: 'A weather forecasting service integrated with Boomi',
      c: 'A private cloud storage bucket hosted on AWS S3',
      d: 'An offline development environment'
    },
    correctAnswer: 'a',
    explanation: 'An Atom Cloud is a shared, multi-tenant clustered runtime managed by Boomi or a partner, where tenants execute integrations within isolated JVM worker containers.'
  },
  {
    id: 'boomi_lit_13',
    domain: 'literacy',
    text: 'What is the purpose of the "Route" shape in Boomi?',
    options: {
      a: 'It evaluates document property or profile field values against multiple conditional comparison rules and routes documents down matching path branches',
      b: 'It calculates the shortest driving distance between two addresses using GPS',
      c: 'It generates network routing tables for Cisco routers',
      d: 'It sends documents to the recycle bin'
    },
    correctAnswer: 'a',
    explanation: 'The Route shape provides multi-way branching, routing documents to specific output paths based on profile element or property criteria (similar to a switch/case statement).'
  },
  {
    id: 'boomi_lit_14',
    domain: 'literacy',
    text: 'What is the function of the "Notify" shape in Boomi?',
    options: {
      a: 'To generate custom log messages, execution alerts, and audit trail notifications that are recorded in the execution log and can be sent as email alerts',
      b: 'To pop up an alert window on the client computer screen',
      c: 'To ring an alarm bell in the data center',
      d: 'To send a text message via SMS to the CEO'
    },
    correctAnswer: 'a',
    explanation: 'The Notify shape writes formatted log entries with static text and dynamic parameters to the process execution logs and event alert feeds.'
  },
  {
    id: 'boomi_lit_15',
    domain: 'literacy',
    text: 'In Boomi, what is the role of a "Component"?',
    options: {
      a: 'A reusable, version-controlled integration artifact (such as a Process, Map, Profile, Connection, Operation, or Certificate) stored in the Component Explorer',
      b: 'A physical RAM chip on the server motherboard',
      c: 'A third-party plugin purchased from a software store',
      d: 'An executable file installed in Windows Program Files'
    },
    correctAnswer: 'a',
    explanation: 'In Boomi AtomSphere, all design assets (processes, maps, profiles, connections, operations) are versioned, reusable Components managed in the Component Explorer.'
  },
  {
    id: 'boomi_lit_16',
    domain: 'literacy',
    text: 'What is the difference between "Test Mode" and "Deployed Execution" in Boomi?',
    options: {
      a: 'Test Mode executes within the UI designer with a maximum limit of 100 documents / 10 MB for interactive debugging; Deployed Execution runs automatically on scheduled/listener runtimes without limits',
      b: 'Test Mode is free while Deployed Execution requires immediate credit card payment',
      c: 'Test Mode only runs on Linux; Deployed Execution runs on Windows',
      d: 'Test Mode deletes data permanently from target databases'
    },
    correctAnswer: 'a',
    explanation: 'Test Mode allows interactive step-by-step process testing with execution previews and a 100-document limit, whereas deployed processes run autonomously in production.'
  },
  {
    id: 'boomi_lit_17',
    domain: 'literacy',
    text: 'What is the function of the "Stop" shape in Boomi?',
    options: {
      a: 'It terminates a branch execution cleanly and can optionally be configured to "Continue execution other branches" or mark the document as failed',
      b: 'It shuts down the Atom operating system immediately',
      c: 'It deletes all files in the current work directory',
      d: 'It disconnects the network cable'
    },
    correctAnswer: 'a',
    explanation: 'The Stop shape ends execution for documents arriving at the end of a branch, with options to treat the termination as a success or as an unrecoverable failure.'
  },
  {
    id: 'boomi_lit_18',
    domain: 'literacy',
    text: 'What is the purpose of the "Exception" shape in Boomi?',
    options: {
      a: 'It terminates the process execution for arriving documents and flags the process execution status as an Error, generating an exception message in execution history',
      b: 'It skips the next 5 shapes in the flow',
      c: 'It grants the document immunity from validation errors',
      d: 'It converts the error into a success message'
    },
    correctAnswer: 'a',
    explanation: 'The Exception shape halts processing for arriving documents and triggers error logging and alerting by failing the execution path.'
  },
  {
    id: 'boomi_lit_19',
    domain: 'literacy',
    text: 'What type of Profile in Boomi is used to represent delimiter-separated values (like CSV) or fixed-width text records?',
    options: {
      a: 'Flat File Profile',
      b: 'XML Profile',
      c: 'JSON Profile',
      d: 'Database Profile'
    },
    correctAnswer: 'a',
    explanation: 'Flat File Profiles model structured text files including comma/tab-delimited records (CSV/TSV) and fixed-length positional records.'
  },
  {
    id: 'boomi_lit_20',
    domain: 'literacy',
    text: 'What is the purpose of a "Database Profile" in Boomi?',
    options: {
      a: 'It defines the SQL statement parameters and result set column structures for Database connector Read, Write, and Stored Procedure operations',
      b: 'It stores the database administrator password',
      c: 'It defines the physical hard disk partition size for SQL Server',
      d: 'It creates a database backup file on AWS S3'
    },
    correctAnswer: 'a',
    explanation: 'Database Profiles structure SQL query inputs (parameters), output result sets (fields), and stored procedure parameters.'
  },
  {
    id: 'boomi_lit_21',
    domain: 'literacy',
    text: 'What is the role of an "Environment" in Boomi AtomSphere?',
    options: {
      a: 'A logical deployment stage (e.g. Development, Test, Production) to which Atoms/Molecules are attached and integration packages are deployed with environment-specific extensions',
      b: 'The physical weather climate of the server facility',
      c: 'The operating system environment variables of the client laptop',
      d: 'A programming language compiler configuration'
    },
    correctAnswer: 'a',
    explanation: 'Environments represent deployment tiers (Dev, QA, Prod) where runtimes are bound and process packages are deployed with environment extensions.'
  },
  {
    id: 'boomi_lit_22',
    domain: 'literacy',
    text: 'Which shape allows executing a sub-process synchronously or asynchronously from within a parent Boomi process?',
    options: {
      a: 'Process Call Shape',
      b: 'Map Shape',
      c: 'Notify Shape',
      d: 'Data Process Shape'
    },
    correctAnswer: 'a',
    explanation: 'The Process Call shape invokes child processes, with options to wait for process completion (synchronous) or execute asynchronously in a separate thread.'
  },
  {
    id: 'boomi_lit_23',
    domain: 'literacy',
    text: 'In Boomi, how does an Atom communicate with the AtomSphere cloud platform?',
    options: {
      a: 'The Atom initiates outbound HTTPS (port 443) communication to AtomSphere web services periodically for health pings, deployment retrieval, and tracking logs without requiring inbound firewall openings',
      b: 'AtomSphere initiates inbound SSH connections to port 22 on the Atom server',
      c: 'Through unencrypted UDP broadcast packets',
      d: 'Via direct database connections to Oracle'
    },
    correctAnswer: 'a',
    explanation: 'Boomi Atoms only make outbound connections over HTTPS (port 443) to the AtomSphere cloud platform, meaning zero inbound firewall ports need to be opened for process execution and management.'
  },
  {
    id: 'boomi_lit_24',
    domain: 'literacy',
    text: 'What is the purpose of the "Cleanse" shape in Boomi?',
    options: {
      a: 'It validates incoming document fields against rules defined in a Profile (e.g. mandatory fields, data types, lengths) and splits valid and invalid documents into separate paths',
      b: 'It deletes virus files from the hard disk',
      c: 'It scrubs sensitive passwords from source code files',
      d: 'It flushes the JVM garbage collection heap'
    },
    correctAnswer: 'a',
    explanation: 'The Cleanse shape evaluates documents against Profile field constraints, routing compliant records down the Clean path and non-compliant records down the Rejected path.'
  },
  {
    id: 'boomi_lit_25',
    domain: 'literacy',
    text: 'What is the function of the "Find Changes" shape in Boomi?',
    options: {
      a: 'It compares incoming documents against a historical snapshot to identify added, modified, or deleted records, routing each change category to different paths',
      b: 'It finds spelling mistakes in documentation',
      c: 'It compares Git commits between two branches',
      d: 'It calculates currency exchange rate changes'
    },
    correctAnswer: 'a',
    explanation: 'The Find Changes shape tracks state across executions, detecting whether records are New, Updated, Unchanged, or Deleted based on key comparisons.'
  },
  {
    id: 'boomi_lit_26',
    domain: 'literacy',
    text: 'What type of component in Boomi is used to map and transform EDI standard documents (such as X12 or EDIFACT)?',
    options: {
      a: 'EDI Profile and Trading Partner component',
      b: 'JSON Profile and REST Client',
      c: 'Database Profile and Stored Procedure',
      d: 'Flat File Profile with tab delimiters'
    },
    correctAnswer: 'a',
    explanation: 'Boomi provides dedicated EDI Profiles (supporting ANSI X12, EDIFACT, HL7, RosettaNet) and Trading Partner components for B2B supply chain integration.'
  },
  {
    id: 'boomi_lit_27',
    domain: 'literacy',
    text: 'What is the function of the "Return Documents" shape in a child sub-process?',
    options: {
      a: 'It sends the processed documents from the sub-process back to the calling parent Process Call shape for continued execution',
      b: 'It emails documents back to the customer',
      c: 'It deletes documents from memory',
      d: 'It rolls back the database transaction'
    },
    correctAnswer: 'a',
    explanation: 'The Return Documents shape passes documents output from a child process back to the calling Process Call shape in the parent process.'
  },
  {
    id: 'boomi_lit_28',
    domain: 'literacy',
    text: 'What is the purpose of the "Message" shape in Boomi?',
    options: {
      a: 'To generate a new document payload or transform an existing document by combining static template text with dynamic parameters and variables',
      b: 'To send a Slack instant message',
      c: 'To post an announcement on the company intranet',
      d: 'To convert XML into binary bytecode'
    },
    correctAnswer: 'a',
    explanation: 'The Message shape creates or replaces document content using parameterized templates (e.g. `{"id": "{1}", "status": "{2}"}` where `{1}` and `{2}` are variables).'
  },
  {
    id: 'boomi_lit_29',
    domain: 'literacy',
    text: 'What is the role of the "Web Services Server" connector in Boomi?',
    options: {
      a: 'It enables an Atom or Molecule to act as an HTTP web server, listening for real-time inbound REST, SOAP, or raw HTTP API requests',
      b: 'It downloads web pages from external websites',
      c: 'It configures Apache Tomcat server files manually',
      d: 'It acts as an SMTP mail server'
    },
    correctAnswer: 'a',
    explanation: 'The Web Services Server (WSS) connector creates real-time HTTP listener endpoints on the Atom/Molecule, turning integration processes into callable REST/SOAP APIs.'
  },
  {
    id: 'boomi_lit_30',
    domain: 'literacy',
    text: 'What is the difference between "Execution Status: Pending" and "Execution Status: Complete" in Process Reporting?',
    options: {
      a: '`Pending` indicates the process is currently executing on the Atom runtime; `Complete` indicates the execution has finished successfully',
      b: '`Pending` means the process was cancelled by an admin',
      c: '`Complete` means the server has been turned off',
      d: '`Pending` means the license has expired'
    },
    correctAnswer: 'a',
    explanation: 'Process Reporting tracks execution state in real time: `Pending` signifies active in-flight execution, and `Complete` confirms successful termination.'
  }
];
