import { CertQuestion, CertSection } from '../types';
import { COMPUTER_BASICS_LITERACY_QUESTIONS } from './literacy';
import { COMPUTER_BASICS_AUTOMATION_QUESTIONS } from './automation';
import { COMPUTER_BASICS_PRIVACY_QUESTIONS } from './privacy';
import { COMPUTER_BASICS_GROWTH_QUESTIONS } from './growth';

export const COMPUTER_BASICS_QUESTIONS_BY_SECTION: Record<CertSection, CertQuestion[]> = {
  literacy: COMPUTER_BASICS_LITERACY_QUESTIONS,
  automation: COMPUTER_BASICS_AUTOMATION_QUESTIONS,
  privacy: COMPUTER_BASICS_PRIVACY_QUESTIONS,
  growth: COMPUTER_BASICS_GROWTH_QUESTIONS,
};

export const ALL_COMPUTER_BASICS_QUESTIONS: CertQuestion[] = [
  ...COMPUTER_BASICS_LITERACY_QUESTIONS,
  ...COMPUTER_BASICS_AUTOMATION_QUESTIONS,
  ...COMPUTER_BASICS_PRIVACY_QUESTIONS,
  ...COMPUTER_BASICS_GROWTH_QUESTIONS,
];
