import { CertSection, CertQuestion } from '../types';
import { SALESFORCE_INTEGRATION_LITERACY_QUESTIONS } from './literacy';
import { SALESFORCE_INTEGRATION_AUTOMATION_QUESTIONS } from './automation';
import { SALESFORCE_INTEGRATION_PRIVACY_QUESTIONS } from './privacy';
import { SALESFORCE_INTEGRATION_GROWTH_QUESTIONS } from './growth';

export const SALESFORCE_INTEGRATION_QUESTIONS_BY_SECTION: Record<CertSection, CertQuestion[]> = {
  literacy: SALESFORCE_INTEGRATION_LITERACY_QUESTIONS,
  automation: SALESFORCE_INTEGRATION_AUTOMATION_QUESTIONS,
  privacy: SALESFORCE_INTEGRATION_PRIVACY_QUESTIONS,
  growth: SALESFORCE_INTEGRATION_GROWTH_QUESTIONS,
};

export const ALL_SALESFORCE_INTEGRATION_QUESTIONS: CertQuestion[] = [
  ...SALESFORCE_INTEGRATION_LITERACY_QUESTIONS,
  ...SALESFORCE_INTEGRATION_AUTOMATION_QUESTIONS,
  ...SALESFORCE_INTEGRATION_PRIVACY_QUESTIONS,
  ...SALESFORCE_INTEGRATION_GROWTH_QUESTIONS,
];
