import { FINOPS_ARCHITECT_LITERACY_QUESTIONS } from './literacy';
import { FINOPS_ARCHITECT_AUTOMATION_QUESTIONS } from './automation';
import { FINOPS_ARCHITECT_PRIVACY_QUESTIONS } from './privacy';
import { FINOPS_ARCHITECT_GROWTH_QUESTIONS } from './growth';
import { CertSection, CertQuestion } from '../types';

export const FINOPS_ARCHITECT_QUESTIONS_BY_SECTION: Record<CertSection, CertQuestion[]> = {
  literacy: FINOPS_ARCHITECT_LITERACY_QUESTIONS,
  automation: FINOPS_ARCHITECT_AUTOMATION_QUESTIONS,
  privacy: FINOPS_ARCHITECT_PRIVACY_QUESTIONS,
  growth: FINOPS_ARCHITECT_GROWTH_QUESTIONS,
};

export const ALL_FINOPS_ARCHITECT_QUESTIONS: CertQuestion[] = [
  ...FINOPS_ARCHITECT_LITERACY_QUESTIONS,
  ...FINOPS_ARCHITECT_AUTOMATION_QUESTIONS,
  ...FINOPS_ARCHITECT_PRIVACY_QUESTIONS,
  ...FINOPS_ARCHITECT_GROWTH_QUESTIONS,
];
