import { CertQuestion } from '../certQuestionBank';

export const AUTOMATION_QUESTIONS: CertQuestion[] = [
  {
    id: 'auto_01',
    section: 'automation',
    prompt: 'When deciding whether to automate a recurring business workflow using an LLM, what is the first diagnostic step?',
    options: [
      { id: 'a', label: 'Immediately replace all human employees with an autonomous agent' },
      { id: 'b', label: 'Conduct a micro-task audit to deconstruct the workflow into deterministic steps vs cognitive judgment steps' },
      { id: 'c', label: 'Buy the most expensive enterprise subscription available' },
      { id: 'd', label: 'Post about the workflow on social media' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_02',
    section: 'automation',
    prompt: 'What is the primary risk of a "monolithic" prompt that attempts to handle extraction, sentiment analysis, translation, and email drafting in a single call?',
    options: [
      { id: 'a', label: 'It runs too quickly for the user to read' },
      { id: 'b', label: 'High failure surface area: an error in intermediate reasoning cascades into all downstream stages without modular recovery' },
      { id: 'c', label: 'It uses fewer tokens than modular pipelines' },
      { id: 'd', label: 'It violates the terms of service of all cloud providers' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_03',
    section: 'automation',
    prompt: 'What does "Human-in-the-Loop" (HITL) mean in a production AI automation pipeline?',
    options: [
      { id: 'a', label: 'A person physically holds the server cables' },
      { id: 'b', label: 'A design pattern where critical, high-impact AI outputs require explicit human review and approval before final execution' },
      { id: 'c', label: 'A system where AI monitors human employees via webcam' },
      { id: 'd', label: 'Manually typing every single token by hand' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_04',
    section: 'automation',
    prompt: 'When transforming a standard operating procedure (SOP) document into an AI prompt template, what is best practice?',
    options: [
      { id: 'a', label: 'Paste the entire 50-page employee handbook into the prompt without edits' },
      { id: 'b', label: 'Extract clear trigger conditions, structured step-by-step rules, explicit edge-case definitions, and verifiable output schemas' },
      { id: 'c', label: 'Delete all quality standards to speed up generation' },
      { id: 'd', label: 'Translate the SOP into Latin first' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_05',
    section: 'automation',
    prompt: 'In automated batch processing (e.g. processing 500 customer feedback records), what mechanism handles temporary API rate limits or network blips?',
    options: [
      { id: 'a', label: 'Immediate hard termination of the entire batch pipeline' },
      { id: 'b', label: 'Exponential backoff with retry logic and dead-letter queue logging for failed items' },
      { id: 'c', label: 'Ignoring errors and fabricating missing records' },
      { id: 'd', label: 'Refreshing the web browser page repeatedly' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_06',
    section: 'automation',
    prompt: 'What is the "first-draft clay" mental model in professional AI productivity?',
    options: [
      { id: 'a', label: 'Treating AI outputs as finished, final deliverables ready for immediate client publication' },
      { id: 'b', label: 'Treating AI outputs as rapid, workable preliminary drafts that a human practitioner sculpts, validates, and refines' },
      { id: 'c', label: 'A modeling software plugin for ceramic design' },
      { id: 'd', label: 'Refusing to use AI for any creative task' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_07',
    section: 'automation',
    prompt: 'Why should automated workflows store prompt templates in a version-controlled repository rather than hardcoding them in application logic?',
    options: [
      { id: 'a', label: 'To track prompt iterations, audit changes, enable rollbacks, and measure benchmark performance over time' },
      { id: 'b', label: 'To hide prompts from software engineers' },
      { id: 'c', label: 'Because git is mandatory for running LLM inference' },
      { id: 'd', label: 'To double the speed of network requests' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_08',
    section: 'automation',
    prompt: 'When connecting an LLM to external automation platforms (like Zapier, Make, or n8n), what format ensures seamless multi-step data mapping?',
    options: [
      { id: 'a', label: 'Unstructured natural language paragraphs' },
      { id: 'b', label: 'Valid, strongly-typed JSON with predictable key names matching downstream schema requirements' },
      { id: 'c', label: 'Audio recordings of the text' },
      { id: 'd', label: 'Scanned PDF copies' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_09',
    section: 'automation',
    prompt: 'What is "function calling" or "tool use" in automated AI agent pipelines?',
    options: [
      { id: 'a', label: 'Calling tech support on the telephone' },
      { id: 'b', label: 'A model capability to output structured JSON arguments designed to invoke specific external APIs or database routines' },
      { id: 'c', label: 'Running a grammar checker in Microsoft Word' },
      { id: 'd', label: 'Playing sound effects when a prompt finishes' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_10',
    section: 'automation',
    prompt: 'Which metric is most informative when assessing the true ROI of an AI workflow automation deployment?',
    options: [
      { id: 'a', label: 'Total number of tokens consumed in a billing cycle' },
      { id: 'b', label: 'Net time saved multiplied by hourly cost, minus review time, API expenses, and error remediation overhead' },
      { id: 'c', label: 'The number of slides in the initial management presentation' },
      { id: 'd', label: 'How many employees liked the project on internal chat' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_11',
    section: 'automation',
    prompt: 'In a multi-step prompt chain, how should data from Step 1 be passed to Step 2 for maximum reliability?',
    options: [
      { id: 'a', label: 'Rely on the model to remember it telepathically' },
      { id: 'b', label: 'Extract Step 1 output into a validated programmatic object and explicitly inject it into Step 2’s context prompt' },
      { id: 'c', label: 'Concatenate all previous conversation history indefinitely without trimming' },
      { id: 'd', label: 'Save it as a screenshot and send an image prompt' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_12',
    section: 'automation',
    prompt: 'What is a "synthetic test suite" in prompt pipeline engineering?',
    options: [
      { id: 'a', label: 'A collection of AI-generated benchmark cases used to evaluate whether a prompt handles typical, edge-case, and adversarial inputs consistently' },
      { id: 'b', label: 'A laboratory test for physical computer chips' },
      { id: 'c', label: 'An automated billing audit software' },
      { id: 'd', label: 'A computer simulation of factory machinery' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_13',
    section: 'automation',
    prompt: 'When automating email responses with an LLM, what is the safest deployment architecture for a new team?',
    options: [
      { id: 'a', label: 'Full autonomous sending directly to customers without preview' },
      { id: 'b', label: 'Draft generation mode: AI populates draft replies in the inbox, and human agents review, edit, and click send' },
      { id: 'c', label: 'Banning email and switching to telegram' },
      { id: 'd', label: 'Sending the raw prompt template to the customer' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_14',
    section: 'automation',
    prompt: 'Why is prompt chaining preferred over single large prompts when executing complex business logic?',
    options: [
      { id: 'a', label: 'It allows modular debugging, unit testing of individual steps, and targeted retries when a single component fails' },
      { id: 'b', label: 'It requires zero internet connection' },
      { id: 'c', label: 'It eliminates all API charges' },
      { id: 'd', label: 'It avoids using JSON completely' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_15',
    section: 'automation',
    prompt: 'What is a "fallback mechanism" in an automated AI pipeline?',
    options: [
      { id: 'a', label: 'A backup plan (such as routing to a deterministic rule-based script or alerting a human operator) when an LLM fails or hallucinates' },
      { id: 'b', label: 'A physical seatbelt on an office chair' },
      { id: 'c', label: 'An automatic restart of the entire computer' },
      { id: 'd', label: 'A feature that posts errors directly to Twitter' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_16',
    section: 'automation',
    prompt: 'In a document summarization pipeline, what is the best strategy to handle an incoming PDF that exceeds the model’s context window?',
    options: [
      { id: 'a', label: 'Discard the second half of the document silently' },
      { id: 'b', label: 'Chunking strategy: split into logical sections, summarize each chunk, and generate a final executive synthesis from chunk summaries' },
      { id: 'c', label: 'Compress the text by deleting all vowels' },
      { id: 'd', label: 'Wait 24 hours for the server to cool down' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_17',
    section: 'automation',
    prompt: 'What is the role of a "validator agent" or "critic step" in automated content workflows?',
    options: [
      { id: 'a', label: 'A second LLM step tasked specifically with auditing the first model’s output against compliance rules, tone guidelines, or schema validity' },
      { id: 'b', label: 'A bot that posts negative comments online' },
      { id: 'c', label: 'A program that calculates the electricity bill' },
      { id: 'd', label: 'A plugin that translates text into Morse code' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_18',
    section: 'automation',
    prompt: 'When automating data extraction from thousands of invoices, what step ensures high data integrity before database ingestion?',
    options: [
      { id: 'a', label: 'Schema validation (e.g. Zod or JSON Schema) combined with mathematical checksum checks (e.g. Subtotal + Tax = Total)' },
      { id: 'b', label: 'Assuming the model is always 100% accurate' },
      { id: 'c', label: 'Deleting the invoice images immediately' },
      { id: 'd', label: 'Setting the temperature to 1.0' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_19',
    section: 'automation',
    prompt: 'What is a "personal prompt library"?',
    options: [
      { id: 'a', label: 'A curated, organized collection of tested, high-yield prompt templates tailored to an individual’s frequent professional tasks' },
      { id: 'b', label: 'A physical library building in a university' },
      { id: 'c', label: 'A list of passwords stored in a text file' },
      { id: 'd', label: 'A collection of novel manuscripts written by AI' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_20',
    section: 'automation',
    prompt: 'Why should automated workflows avoid using "creative" LLM configurations (high temperature) for structured parsing tasks?',
    options: [
      { id: 'a', label: 'High temperature introduces variance and hallucinations, causing schema validation errors and syntax breakage' },
      { id: 'b', label: 'High temperature causes physical heat damage to client computers' },
      { id: 'c', label: 'High temperature is strictly illegal in software development' },
      { id: 'd', label: 'High temperature requires special hardware permissions' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_21',
    section: 'automation',
    prompt: 'What does "idempotency" mean when designing automated AI webhook actions?',
    options: [
      { id: 'a', label: 'Ensuring that executing the same automated action multiple times produces the exact same outcome without duplicate side effects (like sending 5 emails)' },
      { id: 'b', label: 'Running the action in less than 1 millisecond' },
      { id: 'c', label: 'Translating the output into multiple languages' },
      { id: 'd', label: 'Deleting the user database automatically' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_22',
    section: 'automation',
    prompt: 'When building an automated customer support triage bot, what is the first operational objective of the classification prompt?',
    options: [
      { id: 'a', label: 'Determining customer urgency and routing to the appropriate specialist team or automated resolution tier' },
      { id: 'b', label: 'Selling the customer a premium subscription immediately' },
      { id: 'c', label: 'Arguing with the customer about company policy' },
      { id: 'd', label: 'Printing the customer ticket on physical paper' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_23',
    section: 'automation',
    prompt: 'How can an automated workflow ensure that sensitive customer identifiers (PII) are not sent to third-party LLM providers?',
    options: [
      { id: 'a', label: 'Pre-processing redaction: running regex or a localized NER model to mask names, SSNs, and credit cards before calling the LLM API' },
      { id: 'b', label: 'Asking the LLM not to look at the numbers' },
      { id: 'c', label: 'Sending the customer’s password in plain text instead' },
      { id: 'd', label: 'There is no way to prevent PII leakage' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_24',
    section: 'automation',
    prompt: 'What is the primary advantage of using a dedicated workflow orchestrator (like LangChain, LlamaIndex, or n8n) over manual API scripts?',
    options: [
      { id: 'a', label: 'Built-in abstractions for state management, retries, vector memory, tool calling, and modular component swapping' },
      { id: 'b', label: 'It guarantees that all AI responses are 100% true' },
      { id: 'c', label: 'It eliminates the need for internet access' },
      { id: 'd', label: 'It makes LLM tokens completely free' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_25',
    section: 'automation',
    prompt: 'When an automated pipeline involves drafting weekly analytics reports, what role should the human analyst play?',
    options: [
      { id: 'a', label: 'Strategic interpretation: verifying metrics accuracy, providing executive business context, and validating strategic recommendations' },
      { id: 'b', label: 'Typing the numbers into the document manually one by one' },
      { id: 'c', label: 'Rubber-stamping without reading' },
      { id: 'd', label: 'Forwarding the raw AI output directly to the board of directors without opening it' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_26',
    section: 'automation',
    prompt: 'What is "prompt caching" and why is it valuable for high-volume automated workflows?',
    options: [
      { id: 'a', label: 'Reusing processed token states for static context prefixes to drastically reduce latency and cost on repetitive runs' },
      { id: 'b', label: 'Storing paper printouts of prompts in a filing cabinet' },
      { id: 'c', label: 'Deleting old prompt templates to save disk space' },
      { id: 'd', label: 'Hiding prompts from the finance team' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_27',
    section: 'automation',
    prompt: 'In an automated meeting notes workflow, what sequence produces the most actionable output for project managers?',
    options: [
      { id: 'a', label: 'Transcript cleaning -> Action Item Extraction (with Owner & Deadline) -> Key Decision Log -> Executive Summary' },
      { id: 'b', label: 'Poetic reinterpretation of the speaker voices' },
      { id: 'c', label: 'Deleting all dialogue except the opening greeting' },
      { id: 'd', label: 'Translating the meeting into an audio song' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_28',
    section: 'automation',
    prompt: 'What is a "guardrail" in automated LLM pipelines?',
    options: [
      { id: 'a', label: 'A software verification layer checking inputs and outputs against safety policies, PII rules, and business constraints before action execution' },
      { id: 'b', label: 'A physical fence around the computer desk' },
      { id: 'c', label: 'A password required to open the web browser' },
      { id: 'd', label: 'A hardware cooling fan limit' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_29',
    section: 'automation',
    prompt: 'When automating competitive market intelligence scanning, what is the best way to handle conflicting statements between articles?',
    options: [
      { id: 'a', label: 'Instruct the synthesis prompt to flag explicit contradictions and cite source URLs for each conflicting claim' },
      { id: 'b', label: 'Arbitrarily delete one of the articles' },
      { id: 'c', label: 'Blend both claims into a fictional compromise' },
      { id: 'd', label: 'Crash the pipeline intentionally' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_30',
    section: 'automation',
    prompt: 'Why is it critical to log inputs, prompts, outputs, and latencies across production automated workflows?',
    options: [
      { id: 'a', label: 'To facilitate error triage, monitor drift, track costs, and audit compliance when failures occur' },
      { id: 'b', label: 'To fill up database storage as quickly as possible' },
      { id: 'c', label: 'To spy on team members’ typing speeds' },
      { id: 'd', label: 'Logging is discouraged in production software' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_31',
    section: 'automation',
    prompt: 'What is the "Router" design pattern in AI automation architectures?',
    options: [
      { id: 'a', label: 'A physical Wi-Fi router on the wall' },
      { id: 'b', label: 'An initial lightweight prompt that classifies the request type and directs the payload to a specialized downstream prompt or tool' },
      { id: 'c', label: 'A software that routes emails to spam' },
      { id: 'd', label: 'A program that cuts wood' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'auto_32',
    section: 'automation',
    prompt: 'When building an automated code review bot, how can you prevent it from overwhelming developers with trivial nitpicks?',
    options: [
      { id: 'a', label: 'Constrain the prompt rubric strictly to critical security flaws, memory leaks, and architectural anti-patterns, ignoring styling issues' },
      { id: 'b', label: 'Have the bot comment on every single line of code' },
      { id: 'c', label: 'Disable code reviews entirely' },
      { id: 'd', label: 'Make the bot use angry emojis' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_33',
    section: 'automation',
    prompt: 'What is "batching" in LLM API usage, and what is its primary operational benefit?',
    options: [
      { id: 'a', label: 'Submitting non-urgent queries in bulk asynchronous jobs for significant cost discounts (e.g. 50% off) and higher rate limits' },
      { id: 'b', label: 'Baking cookies while waiting for responses' },
      { id: 'c', label: 'Sending the same prompt 100 times to see if answers change' },
      { id: 'd', label: 'Restricting API use to night hours' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_34',
    section: 'automation',
    prompt: 'Why should automated workflows test for "empty state" inputs (e.g. empty PDF, zero-length message)?',
    options: [
      { id: 'a', label: 'To ensure the pipeline gracefully handles null inputs with an appropriate error code instead of hallucinating fictional contents' },
      { id: 'b', label: 'To see if the server crashes' },
      { id: 'c', label: 'Because empty inputs cost double the tokens' },
      { id: 'd', label: 'Empty inputs are forbidden by internet protocols' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_35',
    section: 'automation',
    prompt: 'What is an "agentic loop" in modern AI automation?',
    options: [
      { id: 'a', label: 'An iterative loop where the AI observes environmental state, plans actions, calls tools, inspects tool outputs, and refines until the goal is met' },
      { id: 'b', label: 'A programming infinite loop that freezes the computer' },
      { id: 'c', label: 'A musical sound effect' },
      { id: 'd', label: 'A circular corporate org chart' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_36',
    section: 'automation',
    prompt: 'When automating social media post generation, what quality safeguard prevents brand damage?',
    options: [
      { id: 'a', label: 'An automated brand voice adherence check followed by human marketing specialist sign-off before publishing' },
      { id: 'b', label: 'Publishing automatically at 3 AM' },
      { id: 'c', label: 'Using only one-word tweets' },
      { id: 'd', label: 'Letting the AI post without any review' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_37',
    section: 'automation',
    prompt: 'What is "deterministic fallthrough" in workflow automation architecture?',
    options: [
      { id: 'a', label: 'Using traditional regex or code logic first for predictable tasks (e.g. date formatting), reserving LLMs only for ambiguous, unstructured components' },
      { id: 'b', label: 'Falling out of your chair during a presentation' },
      { id: 'c', label: 'A computer virus that deletes code' },
      { id: 'd', label: 'A failure where the system shuts down' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_38',
    section: 'automation',
    prompt: 'Why should automation pipelines avoid hardcoding API secrets into prompt templates?',
    options: [
      { id: 'a', label: 'To prevent credential leakage through API logs, user-facing prompts, or model memory cache exposure' },
      { id: 'b', label: 'Because API keys make prompts too long' },
      { id: 'c', label: 'Because LLMs will steal your bank accounts automatically' },
      { id: 'd', label: 'It has no security implications' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_39',
    section: 'automation',
    prompt: 'When automating customer refund requests, what is the best practice for financial authorizations?',
    options: [
      { id: 'a', label: 'Establish strict threshold limits: allow automated processing under $15, but require human manager approval for higher amounts' },
      { id: 'b', label: 'Allow the AI to issue unlimited refunds to anyone who asks politely' },
      { id: 'c', label: 'Deny all refund requests automatically' },
      { id: 'd', label: 'Send the customer’s bank account details to social media' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_40',
    section: 'automation',
    prompt: 'What does "structured output enforcement" (e.g. JSON mode with constrained grammar) prevent in automation pipelines?',
    options: [
      { id: 'a', label: 'JSON syntax errors, markdown wrapper bugs, and schema mismatches that crash automated parser scripts' },
      { id: 'b', label: 'Network disconnects' },
      { id: 'c', label: 'High CPU usage on the client phone' },
      { id: 'd', label: 'Model fine-tuning' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_41',
    section: 'automation',
    prompt: 'How does modular prompt architecture facilitate team collaboration?',
    options: [
      { id: 'a', label: 'Different domain experts can own, test, and improve specific prompt modules without breaking the entire organizational workflow' },
      { id: 'b', label: 'It forces everyone on the team to use the same laptop' },
      { id: 'c', label: 'It prevents team members from talking to each other' },
      { id: 'd', label: 'It eliminates the need for managers' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_42',
    section: 'automation',
    prompt: 'When automating competitor price tracking from scraped text, what check prevents false alerts?',
    options: [
      { id: 'a', label: 'Validating price formats, currency consistency, and anomaly thresholds (e.g. flagging price drops > 80% for human check)' },
      { id: 'b', label: 'Trusting whatever number the model returns' },
      { id: 'c', label: 'Rounding all prices to zero' },
      { id: 'd', label: 'Scraping only once a year' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_43',
    section: 'automation',
    prompt: 'What is the role of a "dead-letter queue" (DLQ) in automated AI data processing pipelines?',
    options: [
      { id: 'a', label: 'A quarantine holding queue for items that repeatedly failed AI extraction, allowing manual inspection without stopping the main pipeline' },
      { id: 'b', label: 'A physical postal mailbox for returned letters' },
      { id: 'c', label: 'A folder of spam emails' },
      { id: 'd', label: 'A mechanism to permanently delete corrupted hard drives' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_44',
    section: 'automation',
    prompt: 'Why is unit testing individual prompt components necessary before deploying an automated pipeline?',
    options: [
      { id: 'a', label: 'To verify each prompt satisfies its specific contract (format, edge cases, safety) in isolation before linking it into an end-to-end chain' },
      { id: 'b', label: 'Because company legal departments require 1,000 unit tests' },
      { id: 'c', label: 'To make the codebase look bigger' },
      { id: 'd', label: 'Unit testing is not used for AI prompts' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_45',
    section: 'automation',
    prompt: 'When automating customer feedback sentiment scoring, why should you track confidence ratings alongside category labels?',
    options: [
      { id: 'a', label: 'Low confidence scores can automatically trigger human review for nuanced, sarcastic, or culturally complex feedback' },
      { id: 'b', label: 'Confidence scores increase the speed of the API' },
      { id: 'c', label: 'Confidence scores are required by law' },
      { id: 'd', label: 'To make the spreadsheet look colorful' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_46',
    section: 'automation',
    prompt: 'What is the "Extract-Transform-Load" (ETL) paradigm in AI-enhanced document processing?',
    options: [
      { id: 'a', label: 'Extract raw text from sources -> Transform using LLMs for semantic restructuring -> Load verified entities into production databases' },
      { id: 'b', label: 'Erase -> Terminate -> Leave' },
      { id: 'c', label: 'A technique for designing website layouts' },
      { id: 'd', label: 'An encryption algorithm for Wi-Fi networks' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_47',
    section: 'automation',
    prompt: 'In an automated customer ticketing pipeline, what is the best approach when an incoming ticket is written in an unsupported language?',
    options: [
      { id: 'a', label: 'Route to an explicit "unsupported language" workflow queue and notify international support rather than guessing translations' },
      { id: 'b', label: 'Silently mark the ticket as resolved' },
      { id: 'c', label: 'Reply with English insults' },
      { id: 'd', label: 'Crash the server' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_48',
    section: 'automation',
    prompt: 'Why should automation architects define strict timeout limits on LLM API calls?',
    options: [
      { id: 'a', label: 'To prevent stalled network sockets from hanging background workers indefinitely during upstream provider outages' },
      { id: 'b', label: 'Because LLMs get tired after 30 seconds' },
      { id: 'c', label: 'To reduce electricity bills by 90%' },
      { id: 'd', label: 'Timeouts are only used in sports games' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_49',
    section: 'automation',
    prompt: 'When automating compliance document checks, why should the AI cite exact page and line numbers alongside each finding?',
    options: [
      { id: 'a', label: 'To enable rapid human verification and maintain an immutable audit trail for regulatory compliance' },
      { id: 'b', label: 'Because page numbers make the prompt cheaper' },
      { id: 'c', label: 'To teach the model how to count' },
      { id: 'd', label: 'Compliance regulators do not read citations' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'auto_50',
    section: 'automation',
    prompt: 'What is the primary benefit of deploying automated workflows incrementally (pilot phase with 5% traffic before 100% rollout)?',
    options: [
      { id: 'a', label: 'It exposes unexpected edge cases, model hallucinations, and cost anomalies on low-stakes volume before broad exposure' },
      { id: 'b', label: 'It hides the project from executive management' },
      { id: 'c', label: 'It guarantees that no software updates will ever be needed' },
      { id: 'd', label: 'Piloting is only for airplanes' },
    ],
    correctOptionId: 'a',
  },
];
