import { CertQuestion } from '../certQuestionBank';

export const GROWTH_QUESTIONS: CertQuestion[] = [
  {
    id: 'growth_01',
    section: 'growth',
    prompt: 'What is the primary cognitive objective of using an AI model as a "sparring partner" rather than an oracle?',
    options: [
      { id: 'a', label: 'To have the model agree with all your preconceived hypotheses without question' },
      { id: 'b', label: 'To pressure-test your strategic reasoning, uncover blind spots, and challenge underlying assumptions with rigorous counterarguments' },
      { id: 'c', label: 'To avoid writing any original thoughts yourself' },
      { id: 'd', label: 'To generate as many words as possible to look productive' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'growth_02',
    section: 'growth',
    prompt: 'When evaluating a newly released AI tool for organizational adoption, what does an "Anti-Hype Filter" prioritize?',
    options: [
      { id: 'a', label: 'The number of followers the startup has on social media' },
      { id: 'b', label: 'Verifiable benchmark utility on internal company tasks, predictable unit economics, compliance auditability, and measurable workflow ROI' },
      { id: 'c', label: 'How futuristic the tool\'s promotional video looks' },
      { id: 'd', label: 'Whether the tool has a shiny purple logo' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'growth_03',
    section: 'growth',
    prompt: 'What is "epistemic calibration" when working with probabilistic foundation models?',
    options: [
      { id: 'a', label: 'Adjusting the screen brightness on your monitor' },
      { id: 'b', label: 'Accurately matching your degree of confidence in an AI output to the model\'s true empirical reliability on that specific task domain' },
      { id: 'c', label: 'A mechanical calibration of hard drive spindles' },
      { id: 'd', label: 'Assuming the model is either omniscient or completely useless' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'growth_04',
    section: 'growth',
    prompt: 'In multimodal problem solving, how can uploading a visual architectural diagram alongside a text prompt improve strategic analysis?',
    options: [
      { id: 'a', label: 'It doubles the cost of the API call without adding value' },
      { id: 'b', label: 'It allows the model to inspect spatial relationships, dependency flows, and architectural bottlenecks that are cumbersome to describe in text alone' },
      { id: 'c', label: 'It turns the text into an animated video' },
      { id: 'd', label: 'It bypasses the need for system instructions' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'growth_05',
    section: 'growth',
    prompt: 'What is a "Pre-Mortem" prompt exercise before launching a major strategic initiative?',
    options: [
      { id: 'a', label: 'A prompt asking the model to write a fictional obituary' },
      { id: 'b', label: 'Assuming the initiative has catastrophically failed 12 months in the future, and prompting the model to diagnose the most plausible root causes' },
      { id: 'c', label: 'A medical diagnosis prompt for clinical patients' },
      { id: 'd', label: 'A retrospective meeting held after a project is finished' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'growth_06',
    section: 'growth',
    prompt: 'How can a professional prevent "cognitive atrophy" when integrating AI into their daily analytical work?',
    options: [
      { id: 'a', label: 'By never looking at the AI\'s reasoning steps' },
      { id: 'b', label: 'By actively formulating independent hypotheses and evaluating model outputs critically rather than passively accepting generated conclusions' },
      { id: 'c', label: 'By letting the AI reply to all personal messages automatically' },
      { id: 'd', label: 'By disabling human quality review entirely' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'growth_07',
    section: 'growth',
    prompt: 'When using AI to master an unfamiliar complex subject (e.g. quantum computing), which prompting framework maximizes retention and deep comprehension?',
    options: [
      { id: 'a', label: 'The Feynman Technique: prompting the model to explain the concept at multiple abstraction levels, test you with active recall questions, and diagnose gaps' },
      { id: 'b', label: 'Asking for a 10,000-word essay and skimming the first paragraph' },
      { id: 'c', label: 'Generating a generic summary poem' },
      { id: 'd', label: 'Copying the Wikipedia article into a chat window' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_08',
    section: 'growth',
    prompt: 'What is "sycophancy" in conversational LLMs, and why is it hazardous for executive decision-making?',
    options: [
      { id: 'a', label: 'The tendency of models to mirror and validate the user\'s stated opinions, reinforcing dangerous executive confirmation bias' },
      { id: 'b', label: 'A software bug that causes slow token generation' },
      { id: 'c', label: 'A model refusing to answer polite queries' },
      { id: 'd', label: 'A feature that increases API subscription fees' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_09',
    section: 'growth',
    prompt: 'How should an analytical leader construct a prompt to overcome model sycophancy?',
    options: [
      { id: 'a', label: '"Here is my plan: [plan]. Tell me why it\'s brilliant."' },
      { id: 'b', label: '"Adopt the persona of an adversarial corporate auditor or competing firm. Attack this plan: [plan]. Identify the 3 most vulnerable fatal assumptions."' },
      { id: 'c', label: '"Please agree with me on everything."' },
      { id: 'd', label: '"Output YES if you like this."' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'growth_10',
    section: 'growth',
    prompt: 'What role does "sensitivity analysis" play when modeling financial forecasts with AI assistance?',
    options: [
      { id: 'a', label: 'Prompting the model to stress-test how key financial outcomes vary under extreme volatility in inflation, churn, and customer acquisition costs' },
      { id: 'b', label: 'Checking whether the font colors are sensitive to bright lights' },
      { id: 'c', label: 'Ensuring the model speaks politely to the finance director' },
      { id: 'd', label: 'Running the prompt only on sunny days' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_11',
    section: 'growth',
    prompt: 'What is the "Socratic Method" prompting pattern for problem solving?',
    options: [
      { id: 'a', label: 'Directing the model not to give immediate answers, but to ask probing questions that guide the user to discover solutions independently' },
      { id: 'b', label: 'Speaking in ancient Greek' },
      { id: 'c', label: 'Generating philosophical quotes from famous historians' },
      { id: 'd', label: 'Giving a 50-question multiple-choice quiz every morning' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_12',
    section: 'growth',
    prompt: 'When synthesizing conflicting expert opinions on a novel industry trend, how should you prompt an LLM?',
    options: [
      { id: 'a', label: 'Ask the model to declare one expert as objectively superior' },
      { id: 'b', label: 'Construct a matrix comparing each expert\'s core thesis, underlying evidentiary assumptions, and key points of contention' },
      { id: 'c', label: 'Delete the opinions you disagree with before prompting' },
      { id: 'd', label: 'Ask for a random coin flip' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'growth_13',
    section: 'growth',
    prompt: 'What is the "Red Teaming" approach to personal professional development?',
    options: [
      { id: 'a', label: 'Using AI to roleplay challenging stakeholder objections, hostile media interviews, or tough board negotiations before they happen' },
      { id: 'b', label: 'Wearing red clothing to all company presentations' },
      { id: 'c', label: 'Joining a competitive gaming team' },
      { id: 'd', label: 'Asking an AI to critique your handwriting' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_14',
    section: 'growth',
    prompt: 'Why is an interactive dialogue loop often superior to a single "magic prompt" for strategic problem solving?',
    options: [
      { id: 'a', label: 'Iterative dialogue allows dynamic course-correction, progressive deepening of nuances, and co-evolution of ideas between human and AI' },
      { id: 'b', label: 'Interactive dialogue uses zero API tokens' },
      { id: 'c', label: 'Single prompts are banned in modern web applications' },
      { id: 'd', label: 'There is no difference in outcome' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_15',
    section: 'growth',
    prompt: 'What does "First Principles Thinking" mean when applied to AI-assisted ideation?',
    options: [
      { id: 'a', label: 'Deconstructing a business problem down to its fundamental truths and building novel solutions up from there, rather than reasoning by analogy' },
      { id: 'b', label: 'Always accepting the first answer the model gives' },
      { id: 'c', label: 'Writing prompts that only use words starting with the letter A' },
      { id: 'd', label: 'Prioritizing speed over quality' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_16',
    section: 'growth',
    prompt: 'When evaluating complex corporate strategy documents, why is it valuable to prompt the model for "unspoken assumptions"?',
    options: [
      { id: 'a', label: 'To surface hidden dependencies and premises that authors took for granted but could trigger systemic failure if invalid' },
      { id: 'b', label: 'To see if the author made grammatical spelling mistakes' },
      { id: 'c', label: 'To shorten the document length' },
      { id: 'd', label: 'To check if the author used AI' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_17',
    section: 'growth',
    prompt: 'What is the "Six Thinking Hats" prompting framework?',
    options: [
      { id: 'a', label: 'Analyzing a critical problem systematically across 6 distinct lenses: Facts (White), Emotion (Red), Caution (Black), Optimism (Yellow), Creativity (Green), and Process (Blue)' },
      { id: 'b', label: 'Shopping for accessories online' },
      { id: 'c', label: 'A technical protocol for computer networking' },
      { id: 'd', label: 'A hardware standard for audio headphones' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_18',
    section: 'growth',
    prompt: 'How can an executive use AI to audit their own cognitive biases during decision making?',
    options: [
      { id: 'a', label: 'By pasting their decision rationale and instructing the model to scan for confirmation bias, anchoring, sunk cost fallacy, or recency bias' },
      { id: 'b', label: 'By asking the model if they are smart' },
      { id: 'c', label: 'By deleting past decision logs' },
      { id: 'd', label: 'By letting the model make all final executive choices' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_19',
    section: 'growth',
    prompt: 'What is "lateral thinking" ideation with generative AI?',
    options: [
      { id: 'a', label: 'Prompting the model to draw unexpected analogies and structural parallels from completely unrelated fields (e.g. applying biomimicry to supply chains)' },
      { id: 'b', label: 'Writing text horizontally across the screen' },
      { id: 'c', label: 'Copying the competitor’s exact marketing campaigns' },
      { id: 'd', label: 'Typing with one hand' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_20',
    section: 'growth',
    prompt: 'When using an LLM to evaluate customer interview transcripts, what prompt constraint prevents false positives?',
    options: [
      { id: 'a', label: 'Requiring exact verbatim quote citations with speaker timestamps for every extracted customer pain point or feature request' },
      { id: 'b', label: 'Asking the model to guess what customers were secretly feeling' },
      { id: 'c', label: 'Deleting all negative feedback' },
      { id: 'd', label: 'Using an emoji for every customer' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_21',
    section: 'growth',
    prompt: 'What is a "Scenario Matrix" in AI-assisted strategic planning?',
    options: [
      { id: 'a', label: 'A 2x2 matrix plotting two critical market uncertainties (e.g. High vs Low Regulation, Fast vs Slow Tech Adoption) with tailored action strategies for all 4 quadrants' },
      { id: 'b', label: 'A spreadsheet of employee phone numbers' },
      { id: 'c', label: 'A movie script about artificial intelligence' },
      { id: 'd', label: 'A hardware graphics card benchmark' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_22',
    section: 'growth',
    prompt: 'Why is it dangerous to use AI as the sole judge in candidate interview scoring without human moderation?',
    options: [
      { id: 'a', label: 'AI models can penalize non-standard phrasing, exhibit hidden demographic biases, and miss vital interpersonal qualities like authentic leadership' },
      { id: 'b', label: 'Candidates always prefer speaking to robots' },
      { id: 'c', label: 'Scoring candidates takes too many GPU cycles' },
      { id: 'd', label: 'Interview scoring is not supported by API models' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_23',
    section: 'growth',
    prompt: 'What is the "Cynefin Framework" utility when deciding whether to apply generative AI to a problem?',
    options: [
      { id: 'a', label: 'Categorizing problems into Clear, Complicated, Complex, or Chaotic to determine whether AI, deterministic rules, or human leadership should lead' },
      { id: 'b', label: 'A Welsh holiday celebration' },
      { id: 'c', label: 'A computer virus detection framework' },
      { id: 'd', label: 'A method for calculating sales commissions' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_24',
    section: 'growth',
    prompt: 'How can multimodal models assist in product usability engineering?',
    options: [
      { id: 'a', label: 'By analyzing user session video recordings or wireframe screenshots to identify confusing visual hierarchies, misaligned touch targets, and friction points' },
      { id: 'b', label: 'By writing negative reviews on consumer review platforms' },
      { id: 'c', label: 'By changing website CSS styles in real time without testing' },
      { id: 'd', label: 'By playing background music during meetings' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_25',
    section: 'growth',
    prompt: 'What is "Counterfactual Reasoning" in AI-assisted root-cause analysis?',
    options: [
      { id: 'a', label: 'Asking: "What would have happened if Factor X had NOT occurred?" to isolate true causal drivers from coincidental correlation' },
      { id: 'b', label: 'Fabricating alternative facts to win an argument' },
      { id: 'c', label: 'Refusing to look at historical data' },
      { id: 'd', label: 'Deleting audit logs' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_26',
    section: 'growth',
    prompt: 'When preparing for a high-stakes negotiation, what is the best way to leverage an AI sparring partner?',
    options: [
      { id: 'a', label: 'Prompt the model to roleplay the counterparty with explicit adversarial incentives, rigid bottom lines, and resistance to standard compromises' },
      { id: 'b', label: 'Ask the model what the other person is thinking right now' },
      { id: 'c', label: 'Have the AI send threatening emails to the counterparty' },
      { id: 'd', label: 'There is no value in AI negotiation prep' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_27',
    section: 'growth',
    prompt: 'What is "mental model mapping" with AI assistance?',
    options: [
      { id: 'a', label: 'Prompting the model to evaluate a complex operational dilemma through established mental models (e.g. Second-Order Thinking, Inversion, Opportunity Cost)' },
      { id: 'b', label: 'Brain scanning technology using electrodes' },
      { id: 'c', label: 'Drawing a picture of your brain in Photoshop' },
      { id: 'd', label: 'Memorizing the names of computer parts' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_28',
    section: 'growth',
    prompt: 'Why should growth-minded professionals actively seek "edge cases" where AI models fail?',
    options: [
      { id: 'a', label: 'Understanding failure boundaries establishes realistic mental models of capability, prevents costly over-reliance, and identifies true human value' },
      { id: 'b', label: 'To complain about AI companies on public forums' },
      { id: 'c', label: 'To get refunds on subscription fees' },
      { id: 'd', label: 'To prove that technology will never work' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_29',
    section: 'growth',
    prompt: 'What is the "Inversion" problem-solving technique applied to prompt engineering?',
    options: [
      { id: 'a', label: 'Instead of asking "How do we make this product succeed?", asking "What actions would guarantee this product’s utter failure?" and mitigating them' },
      { id: 'b', label: 'Inverting the colors of the user interface' },
      { id: 'c', label: 'Typing the prompt upside down' },
      { id: 'd', label: 'Deleting the prompt after reading it' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_30',
    section: 'growth',
    prompt: 'When reading an AI-generated synthesis of complex academic literature, what validation step is non-negotiable?',
    options: [
      { id: 'a', label: 'Spot-checking primary literature sources to verify that key numerical claims, causal conclusions, and methodology nuances were accurately interpreted' },
      { id: 'b', label: 'Checking if the text has 5-star grammar' },
      { id: 'c', label: 'Translating the synthesis into Spanish' },
      { id: 'd', label: 'Printing the synthesis on glossy paper' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_31',
    section: 'growth',
    prompt: 'How can an organization design an effective "AI Sandbox" for employee experimentation?',
    options: [
      { id: 'a', label: 'A secure enterprise environment pre-configured with ZDR data protection, sample non-sensitive datasets, and clear guidelines for sharing wins' },
      { id: 'b', label: 'A physical wooden sandbox with sand in the office courtyard' },
      { id: 'c', label: 'A restricted computer that cannot connect to the internet' },
      { id: 'd', label: 'A policy banning all AI experimentation' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_32',
    section: 'growth',
    prompt: 'What is the "Second-Order Consequences" prompt pattern?',
    options: [
      { id: 'a', label: 'Prompting the model to trace the indirect, unintended, or delayed ripple effects of a proposed organizational policy over 6, 12, and 24 months' },
      { id: 'b', label: 'Placing a second order at an online retail store' },
      { id: 'c', label: 'A sorting algorithm for database records' },
      { id: 'd', label: 'A prompt that executes twice' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_33',
    section: 'growth',
    prompt: 'When using AI to help design a high-stakes customer survey, what bias should you prompt the model to detect in your questions?',
    options: [
      { id: 'a', label: 'Leading questions, acquiescence bias, and double-barreled formulations that distort authentic customer responses' },
      { id: 'b', label: 'Whether the font size is too small' },
      { id: 'c', label: 'Whether customers like reading emails' },
      { id: 'd', label: 'Whether the survey is sent on a Monday' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_34',
    section: 'growth',
    prompt: 'What is the "Devil\'s Advocate" persona prompt useful for in team strategy sessions?',
    options: [
      { id: 'a', label: 'Forcing the model to systematically defend the exact opposite position of the team\'s consensus to uncover groupthink vulnerabilities' },
      { id: 'b', label: 'Writing horror stories' },
      { id: 'c', label: 'Insulting colleagues during presentations' },
      { id: 'd', label: 'Canceling team meetings' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_35',
    section: 'growth',
    prompt: 'Why is "domain context calibration" essential when prompting an AI on niche industry problems (e.g. semiconductor manufacturing)?',
    options: [
      { id: 'a', label: 'General models default to superficial layperson summaries; providing specific industry acronyms, constraints, and baseline specs unlocks deep technical fidelity' },
      { id: 'b', label: 'Semiconductors cannot be modeled by computers' },
      { id: 'c', label: 'Domain context decreases response speed' },
      { id: 'd', label: 'Domain context is only required for medical doctors' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_36',
    section: 'growth',
    prompt: 'What is the primary indicator of high "AI Maturity" in a knowledge worker?',
    options: [
      { id: 'a', label: 'Using AI selectively for cognitive leverage while knowing exactly when to rely on deterministic tools or pure human judgment' },
      { id: 'b', label: 'Using AI for 100% of all emails and communications' },
      { id: 'c', label: 'Having 20 different AI browser extensions installed' },
      { id: 'd', label: 'Posting AI news on Twitter every morning' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_37',
    section: 'growth',
    prompt: 'When using AI to synthesize competitive intelligence, why should you instruct the model to separate "facts" from "company marketing claims"?',
    options: [
      { id: 'a', label: 'To prevent self-congratulatory corporate PR spin from being treated as objective empirical market reality' },
      { id: 'b', label: 'Because marketing claims are copyrighted' },
      { id: 'c', label: 'Because facts cost fewer tokens' },
      { id: 'd', label: 'To shorten the document' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_38',
    section: 'growth',
    prompt: 'What is "active recall testing" with an AI study coach?',
    options: [
      { id: 'a', label: 'Prompting the model to challenge you with adaptive difficulty questions and force you to retrieve concepts from memory before showing explanations' },
      { id: 'b', label: 'Calling an AI on the telephone' },
      { id: 'c', label: 'Remembering your password without a password manager' },
      { id: 'd', label: 'Rereading a textbook 5 times' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_39',
    section: 'growth',
    prompt: 'How can an executive use AI to prepare for an all-hands Q&A during a corporate restructuring?',
    options: [
      { id: 'a', label: 'Simulate the toughest, most emotionally charged employee questions and test empathetic, clear, and authentic leadership communication' },
      { id: 'b', label: 'Have the AI read the speech using an avatar while the executive stays home' },
      { id: 'c', label: 'Cancel the all-hands meeting' },
      { id: 'd', label: 'Generate automated corporate jargon to confuse employees' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_40',
    section: 'growth',
    prompt: 'What is the "Premise Stress Test" prompt pattern?',
    options: [
      { id: 'a', label: 'Identifying the 3 foundational pillars of a business strategy and testing what happens if market conditions invalidate any single pillar' },
      { id: 'b', label: 'Stress testing physical server computers' },
      { id: 'c', label: 'A fitness workout routine for programmers' },
      { id: 'd', label: 'Testing the strength of office desks' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_41',
    section: 'growth',
    prompt: 'Why should professionals maintain a "Mistake & Calibration Journal" when working extensively with AI tools?',
    options: [
      { id: 'a', label: 'To record instances where the model misled or hallucinated, cataloging recurring blind spots and personal over-trust triggers' },
      { id: 'b', label: 'To give to the police in case of a computer crime' },
      { id: 'c', label: 'Because company policy requires 100 pages of notes' },
      { id: 'd', label: 'To practice cursive handwriting' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_42',
    section: 'growth',
    prompt: 'What is "analogical problem solving" using generative AI?',
    options: [
      { id: 'a', label: 'Prompting the model to find how an analogous problem was solved in an entirely different discipline (e.g. how aviation handles checklist fatigue)' },
      { id: 'b', label: 'Using analog clocks instead of digital clocks' },
      { id: 'c', label: 'Writing code without using digital logic' },
      { id: 'd', label: 'Drawing diagrams with colored pencils' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_43',
    section: 'growth',
    prompt: 'When evaluating multiple competing vendor proposals, what prompt structure prevents subjective evaluator fatigue?',
    options: [
      { id: 'a', label: 'A standardized evaluation rubric matrix scoring each vendor on fixed criteria: Security, SLA, TCO, Integration Complexity, and Reference Checks' },
      { id: 'b', label: 'Asking the model: "Which vendor has the cooler name?"' },
      { id: 'c', label: 'Picking the vendor that sent the nicest gifts' },
      { id: 'd', label: 'Rolling a 6-sided die' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_44',
    section: 'growth',
    prompt: 'What does "Intellectual Humility" mean in the age of generative AI?',
    options: [
      { id: 'a', label: 'Recognizing that rapid, articulate AI responses can be subtly wrong, and proactively seeking disconfirming evidence before executing high-stakes bets' },
      { id: 'b', label: 'Never expressing an opinion in a meeting' },
      { id: 'c', label: 'Apologizing before speaking to colleagues' },
      { id: 'd', label: 'Assuming that all human knowledge is obsolete' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_45',
    section: 'growth',
    prompt: 'How can multimodal models accelerate engineering defect resolution from hardware photos?',
    options: [
      { id: 'a', label: 'By correlating high-res photos of solder joint fractures with operational telemetry logs to pinpoint thermal stress failure modes' },
      { id: 'b', label: 'By photoshopping the fracture to make it look smooth' },
      { id: 'c', label: 'By posting the photo to an image sharing website' },
      { id: 'd', label: 'By printing the photo in color' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_46',
    section: 'growth',
    prompt: 'What is the "Opportunity Cost" prompt check before committing team resources to a new project?',
    options: [
      { id: 'a', label: 'Prompting the model to calculate what high-yield strategic initiatives must be delayed or abandoned to free up resources for this project' },
      { id: 'b', label: 'Checking how much money is in the company bank account' },
      { id: 'c', label: 'Asking for a discount from software vendors' },
      { id: 'd', label: 'Writing a grant application' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_47',
    section: 'growth',
    prompt: 'Why is it valuable to prompt an AI: "What crucial question am I NOT asking about this strategic situation?"',
    options: [
      { id: 'a', label: 'It forces the model outside the narrow framing of your query to surface orthogonal risks, unconsidered stakeholders, and hidden blind spots' },
      { id: 'b', label: 'Because asking fewer questions makes the prompt faster' },
      { id: 'c', label: 'To see if the AI can read your mind' },
      { id: 'd', label: 'It has no practical utility' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_48',
    section: 'growth',
    prompt: 'What is "strategic synthesis" when processing 50 pages of customer discovery interviews?',
    options: [
      { id: 'a', label: 'Distilling recurring systemic patterns, latent unmet needs, and contradictory behaviors into actionable product strategy principles' },
      { id: 'b', label: 'Counting the total number of words spoken' },
      { id: 'c', label: 'Sorting customer names alphabetically' },
      { id: 'd', label: 'Deleting half the pages randomly' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_49',
    section: 'growth',
    prompt: 'When using AI to develop an executive presentation, what is the best sequence of collaboration?',
    options: [
      { id: 'a', label: 'Clarify core strategic thesis -> Outline logical narrative arc -> Spar on counter-arguments -> Draft slide bullet points -> Polish visual delivery' },
      { id: 'b', label: 'Generate 100 random slides with AI and read them aloud for the first time on stage' },
      { id: 'c', label: 'Pick a slide template before knowing what you want to say' },
      { id: 'd', label: 'Let the AI write the presentation in poetic verse' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'growth_50',
    section: 'growth',
    prompt: 'What is the ultimate measure of success for a professional who has earned the Jnachi Beginner Certification?',
    options: [
      { id: 'a', label: 'The ability to ethically, safely, and effectively apply AI to accelerate real-world workflows, solve complex problems, and create tangible value' },
      { id: 'b', label: 'Memorizing the names of all AI startups' },
      { id: 'c', label: 'Posting certification badges on every social platform without applying the skills' },
      { id: 'd', label: 'Replacing all human relationships with AI chatbots' },
    ],
    correctOptionId: 'a',
  },
];
