import { CertQuestion } from '../certQuestionBank';

export const LITERACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'lit_01',
    section: 'literacy',
    prompt: 'Which component of a prompt architecture is most critical when you need the model to follow a rigid, machine-readable output format?',
    options: [
      { id: 'a', label: 'A polite tone asking the model to do its best' },
      { id: 'b', label: 'Explicit schema definitions with field types and concrete few-shot examples' },
      { id: 'c', label: 'Repeating the prompt three times in uppercase' },
      { id: 'd', label: 'Increasing the temperature setting to 1.5' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_02',
    section: 'literacy',
    prompt: 'What is the primary technical function of "few-shot" prompting compared to zero-shot prompting?',
    options: [
      { id: 'a', label: 'It forces the model to search live external web indices' },
      { id: 'b', label: 'It provides input-output demonstration pairs that establish pattern, style, and formatting constraints' },
      { id: 'c', label: 'It permanently retrains model weights during runtime' },
      { id: 'd', label: 'It reduces API latency to zero' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_03',
    section: 'literacy',
    prompt: 'When an LLM provides a confident, well-written citation for an academic paper that does not exist, what phenomenon has occurred?',
    options: [
      { id: 'a', label: 'Token overflow error' },
      { id: 'b', label: 'Hallucination caused by probabilistic next-token generation without grounding' },
      { id: 'c', label: 'Overfitting of the local GPU cache' },
      { id: 'd', label: 'Context window compression failure' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_04',
    section: 'literacy',
    prompt: 'How does lowering the temperature parameter (e.g. from 0.8 to 0.1) affect a generative model’s output?',
    options: [
      { id: 'a', label: 'It produces more random, divergent, and creative responses' },
      { id: 'b', label: 'It restricts generation to the highest-probability tokens, making outputs more deterministic and focused' },
      { id: 'c', label: 'It disables punctuation and capital letters' },
      { id: 'd', label: 'It increases token pricing by 50%' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_05',
    section: 'literacy',
    prompt: 'What is the most reliable strategy to prevent an LLM from hallucinating facts when answering questions about proprietary internal documents?',
    options: [
      { id: 'a', label: 'Instructing the model to "be 100% accurate"' },
      { id: 'b', label: 'Grounding the prompt with retrieved source excerpts and explicitly constraining answers to the provided text only' },
      { id: 'c', label: 'Raising the max token limit' },
      { id: 'd', label: 'Using bullet points in the prompt' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_06',
    section: 'literacy',
    prompt: 'What does the term "context window" refer to in modern Large Language Models?',
    options: [
      { id: 'a', label: 'The monitor size required to view AI outputs' },
      { id: 'b', label: 'The maximum total volume of input and output tokens a model can process in a single conversational session' },
      { id: 'c', label: 'The legal timeframe in which user queries are stored' },
      { id: 'd', label: 'The speed at which tokens are rendered on screen' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_07',
    section: 'literacy',
    prompt: 'Why is Chain-of-Thought (CoT) prompting effective for complex multi-step reasoning tasks?',
    options: [
      { id: 'a', label: 'It compresses the token size of the prompt' },
      { id: 'b', label: 'It guides the model to externalize intermediate reasoning steps before arriving at a final deduction' },
      { id: 'c', label: 'It encrypts the conversation stream' },
      { id: 'd', label: 'It converts natural language directly into binary executable code' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_08',
    section: 'literacy',
    prompt: 'In role-based persona prompting, which instruction produces the highest-fidelity outputs?',
    options: [
      { id: 'a', label: 'Generic command: "Act as an expert"' },
      { id: 'b', label: 'Specific context: specifying the exact professional role, target audience, analytical perspective, and output criteria' },
      { id: 'c', label: 'Telling the model you will tip it $50' },
      { id: 'd', label: 'Providing no instructions and letting the model guess' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_09',
    section: 'literacy',
    prompt: 'What happens when a conversation exceeds the model’s maximum context window limit?',
    options: [
      { id: 'a', label: 'The model crashes and permanently deletes the account' },
      { id: 'b', label: 'Earlier conversation turns are truncated, leading to context amnesia where the model loses prior directives' },
      { id: 'c', label: 'The model automatically switches to offline mode' },
      { id: 'd', label: 'The response speed doubles automatically' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_10',
    section: 'literacy',
    prompt: 'What role does "negative prompting" or constraint specification play in production workflows?',
    options: [
      { id: 'a', label: 'It insults the model to improve performance' },
      { id: 'b', label: 'It explicitly outlines forbidden topics, unwanted formats, and out-of-scope behaviors' },
      { id: 'c', label: 'It reduces the cost per token' },
      { id: 'd', label: 'It disables temperature sampling' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_11',
    section: 'literacy',
    prompt: 'In prompt engineering, what is the key advantage of using system instructions over standard user message prompts?',
    options: [
      { id: 'a', label: 'System instructions cost half as many tokens' },
      { id: 'b', label: 'System instructions establish persistent behavioral guardrails and persona boundaries across the entire dialogue' },
      { id: 'c', label: 'System instructions guarantee 100% factual accuracy' },
      { id: 'd', label: 'System instructions bypass API rate limits' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_12',
    section: 'literacy',
    prompt: 'When asking an LLM to extract data from unformatted text, which format constraint is best suited for automated downstream parsing?',
    options: [
      { id: 'a', label: 'A flowing essay with poetic adjectives' },
      { id: 'b', label: 'A valid JSON object matching an explicit schema with defined keys' },
      { id: 'c', label: 'A screenshot image of a spreadsheet' },
      { id: 'd', label: 'A bulleted list with random indentation' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_13',
    section: 'literacy',
    prompt: 'What is a "token" in the context of Large Language Models?',
    options: [
      { id: 'a', label: 'A cryptocurrency coin used to pay API fees' },
      { id: 'b', label: 'A chunk of characters or sub-words (roughly 4 characters in English) used as the basic unit of text processing' },
      { id: 'c', label: 'A digital certificate verifying user identity' },
      { id: 'd', label: 'A hardware accelerator inside the GPU' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_14',
    section: 'literacy',
    prompt: 'Which strategy best mitigates the "lost in the middle" effect where long context models ignore information located in the center of long inputs?',
    options: [
      { id: 'a', label: 'Placing critical instructions and reference material at the very beginning or end of the prompt' },
      { id: 'b', label: 'Typing the entire text backwards' },
      { id: 'c', label: 'Increasing the top-k parameter to maximum' },
      { id: 'd', label: 'Removing all punctuation' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_15',
    section: 'literacy',
    prompt: 'What is the primary benefit of utilizing delimiters (such as ### or ```) in complex prompts?',
    options: [
      { id: 'a', label: 'They speed up inference time by 80%' },
      { id: 'b', label: 'They cleanly demarcate instructions, reference data, and output specifications so the model avoids confusion' },
      { id: 'c', label: 'They bypass content filtering filters' },
      { id: 'd', label: 'They force the model to write code' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_16',
    section: 'literacy',
    prompt: 'Which prompt formulation represents the strongest example of "task specification"?',
    options: [
      { id: 'a', label: '"Analyze this market data and tell me what you think."' },
      { id: 'b', label: '"Extract the top 3 revenue drivers from the Q3 earnings transcript below. Output as a markdown table with columns: Driver, Impact ($M), and Risk."' },
      { id: 'c', label: '"Please act like a business person and read this."' },
      { id: 'd', label: '"Summary please, make it nice."' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_17',
    section: 'literacy',
    prompt: 'How does Top-P (nucleus sampling) differ from Temperature in model generation control?',
    options: [
      { id: 'a', label: 'Top-P filters the cumulative probability cutoff of candidate tokens, whereas Temperature flattens or sharpens the distribution' },
      { id: 'b', label: 'Top-P controls output language while Temperature controls grammar' },
      { id: 'c', label: 'Top-P only applies to coding models' },
      { id: 'd', label: 'There is no difference; they are exact aliases' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_18',
    section: 'literacy',
    prompt: 'When building an automated classification prompt (e.g. sentiment: Positive, Neutral, Negative), what should you instruct the model to do if text is ambiguous?',
    options: [
      { id: 'a', label: 'Guess randomly between all available categories' },
      { id: 'b', label: 'Provide an explicit fallback category (e.g. "Ambiguous" or "Review Required") with confidence criteria' },
      { id: 'c', label: 'Invent a new classification label on the fly' },
      { id: 'd', label: 'Terminate the API session' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_19',
    section: 'literacy',
    prompt: 'What is "prompt drift" in a production environment?',
    options: [
      { id: 'a', label: 'A physical malfunction in the cooling fan of the server' },
      { id: 'b', label: 'When upstream model updates or varying user inputs cause a previously reliable prompt to yield unexpected outputs' },
      { id: 'c', label: 'The gradual increase in internet latency over a work day' },
      { id: 'd', label: 'When users accidentally delete their prompt files' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_20',
    section: 'literacy',
    prompt: 'Why should you avoid open-ended negative phrasing like "Don\'t write too much" in prompt instructions?',
    options: [
      { id: 'a', label: 'LLMs can only comprehend affirmative sentences' },
      { id: 'b', label: 'Negative commands are ambiguous; specifying an exact positive constraint (e.g. "Max 150 words") provides an unambiguous boundary' },
      { id: 'c', label: 'It causes token counter overflow' },
      { id: 'd', label: 'Negative words are blocked by safety filters' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_21',
    section: 'literacy',
    prompt: 'What is the role of Retrieval-Augmented Generation (RAG) in conversational AI systems?',
    options: [
      { id: 'a', label: 'It retrains the foundation model daily from scratch' },
      { id: 'b', label: 'It dynamically retrieves relevant documents from an external vector store and injects them into the prompt context' },
      { id: 'c', label: 'It encrypts the prompt on the client side' },
      { id: 'd', label: 'It turns text prompts into 3D animations' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_22',
    section: 'literacy',
    prompt: 'When requesting code generation, what is the best practice to ensure the code can be executed without manual cleanup?',
    options: [
      { id: 'a', label: 'Instruct the model: "Output only raw code inside a single code block without conversational chit-chat or explanations."' },
      { id: 'b', label: 'Ask the model to explain every single line of code in paragraphs first' },
      { id: 'c', label: 'Request the code in multiple different languages simultaneously' },
      { id: 'd', label: 'Ask the model to create an image of the code' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_23',
    section: 'literacy',
    prompt: 'What is "zero-shot" prompting?',
    options: [
      { id: 'a', label: 'Prompting an AI model without providing any input-output examples' },
      { id: 'b', label: 'A prompt that fails to execute because of a network error' },
      { id: 'c', label: 'A model with zero parameters' },
      { id: 'd', label: 'A prompt that uses 0 tokens' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_24',
    section: 'literacy',
    prompt: 'What is the primary danger of relying on an LLM for mathematical computations without code execution or tools?',
    options: [
      { id: 'a', label: 'LLMs do not have access to numbers' },
      { id: 'b', label: 'LLMs predict text probabilities rather than computing algebraic logic, leading to subtle calculation errors on large numbers' },
      { id: 'c', label: 'Calculators are illegal in API endpoints' },
      { id: 'd', label: 'Math problems trigger safety refusals' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_25',
    section: 'literacy',
    prompt: 'Which technique is most effective when an LLM needs to synthesize information across 10 distinct lengthy reports?',
    options: [
      { id: 'a', label: 'Dumping all 10 reports into one single unguided prompt and asking for "thoughts"' },
      { id: 'b', label: 'Map-reduce approach: summarize each report against structured criteria first, then synthesize the structured summaries' },
      { id: 'c', label: 'Translating all reports into another language first' },
      { id: 'd', label: 'Setting temperature to 1.8' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_26',
    section: 'literacy',
    prompt: 'What is a "system prompt" or "developer message" in the API request lifecycle?',
    options: [
      { id: 'a', label: 'A message sent by the operating system kernel to check server health' },
      { id: 'b', label: 'A high-priority context layer setting the operational rules, tone, and constraints before user dialogue begins' },
      { id: 'c', label: 'An automated billing notification' },
      { id: 'd', label: 'The terminal log of user errors' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_27',
    section: 'literacy',
    prompt: 'If an AI response is cut off mid-sentence, what is the most probable cause?',
    options: [
      { id: 'a', label: 'The model ran out of battery' },
      { id: 'b', label: 'The response hit the configured `max_tokens` (output token limit)' },
      { id: 'c', label: 'The user typed too quickly' },
      { id: 'd', label: 'The prompt violated local copyright' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_28',
    section: 'literacy',
    prompt: 'What is "prompt injection"?',
    options: [
      { id: 'a', label: 'A medical diagnosis algorithm' },
      { id: 'b', label: 'A security vulnerability where untrusted external user input overrides the model’s original system instructions' },
      { id: 'c', label: 'An API call that increases response speed' },
      { id: 'd', label: 'A method for accelerating tokenization' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_29',
    section: 'literacy',
    prompt: 'Which strategy best protects a customer-facing AI bot from prompt injection attacks?',
    options: [
      { id: 'a', label: 'Asking users to promise they are well-behaved' },
      { id: 'b', label: 'Strict input sanitization, clear delimiter separation, and hardened system instructions that treat user inputs as untrusted data' },
      { id: 'c', label: 'Setting temperature to 0.0' },
      { id: 'd', label: 'Only running the model on weekends' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_30',
    section: 'literacy',
    prompt: 'What does "hallucination rate" quantify in LLM benchmarks?',
    options: [
      { id: 'a', label: 'The frequency of creative metaphors generated by the model' },
      { id: 'b', label: 'The proportion of statements generated by the model that contradict grounded facts or source documents' },
      { id: 'c', label: 'The speed of token throughput per second' },
      { id: 'd', label: 'The rate of server dropouts' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_31',
    section: 'literacy',
    prompt: 'When prompting for creative marketing copy, why might you deliberately increase the temperature from 0.2 to 0.7?',
    options: [
      { id: 'a', label: 'To encourage greater vocabulary diversity, novel word combinations, and creative variety' },
      { id: 'b', label: 'To make the output 100% factually accurate' },
      { id: 'c', label: 'To reduce API costs' },
      { id: 'd', label: 'To shorten response length' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_32',
    section: 'literacy',
    prompt: 'What is the "Self-Consistency" prompting technique?',
    options: [
      { id: 'a', label: 'Generating multiple reasoning paths for the same prompt and selecting the consensus or majority answer' },
      { id: 'b', label: 'Checking if the prompt has correct spelling' },
      { id: 'c', label: 'Asking the user if they agree with the model' },
      { id: 'd', label: 'Ensuring font sizes are consistent in the UI' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_33',
    section: 'literacy',
    prompt: 'Which type of prompt structure is best suited for complex decision extraction from contracts?',
    options: [
      { id: 'a', label: 'A conversational query with emojis' },
      { id: 'b', label: 'A structured evaluation prompt defining step-by-step clause extraction criteria, risk categorization rubrics, and JSON output' },
      { id: 'c', label: 'A brief greeting' },
      { id: 'd', label: 'A prompt with no context' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_34',
    section: 'literacy',
    prompt: 'What is "context hygiene"?',
    options: [
      { id: 'a', label: 'Cleaning dust off server hardware' },
      { id: 'b', label: 'Keeping the prompt context concise, focused, and free of irrelevant conversation turns or conflicting data' },
      { id: 'c', label: 'Clearing your browser cache every hour' },
      { id: 'd', label: 'Deleting your API key regularly' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_35',
    section: 'literacy',
    prompt: 'How does an LLM handle contradictory instructions within the same prompt (e.g. "Be extremely concise" vs "Provide exhaustive detail")?',
    options: [
      { id: 'a', label: 'It sends an immediate system alert error' },
      { id: 'b', label: 'It exhibits unpredictable behavior, often compromising both goals or favoring whichever instruction appeared latest' },
      { id: 'c', label: 'It refuses to respond under all circumstances' },
      { id: 'd', label: 'It runs both instructions in parallel and combines them perfectly' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_36',
    section: 'literacy',
    prompt: 'Why is it valuable to include edge-case examples in your few-shot prompt demonstrations?',
    options: [
      { id: 'a', label: 'To teach the model how to handle anomalous, incomplete, or ambiguous inputs predictably' },
      { id: 'b', label: 'To make the prompt as long as possible' },
      { id: 'c', label: 'To trigger model errors intentionally' },
      { id: 'd', label: 'Edge-case examples should never be included in prompts' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_37',
    section: 'literacy',
    prompt: 'What is the key purpose of "evals" (prompt evaluation benchmarks) in professional prompt engineering?',
    options: [
      { id: 'a', label: 'To systematically test prompts against a standardized test set to measure accuracy, consistency, and regressions over time' },
      { id: 'b', label: 'To calculate how much energy the data center consumes' },
      { id: 'c', label: 'To check if the user is paying attention' },
      { id: 'd', label: 'To generate marketing slogans automatically' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_38',
    section: 'literacy',
    prompt: 'What is "grounding" in generative AI application architecture?',
    options: [
      { id: 'a', label: 'Connecting an electrical server chassis to physical earth' },
      { id: 'b', label: 'Connecting model outputs to verified, real-world data sources (such as enterprise databases or live search indices)' },
      { id: 'c', label: 'Punishing an AI model for poor responses' },
      { id: 'd', label: 'Limiting model execution to desktop computers' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_39',
    section: 'literacy',
    prompt: 'When specifying persona instructions, what is the impact of defining "target audience" (e.g. "Explain to a non-technical CFO")?',
    options: [
      { id: 'a', label: 'It directs the model to adapt vocabulary, abstraction level, tone, and financial relevance appropriately' },
      { id: 'b', label: 'It restricts the response to 10 words' },
      { id: 'c', label: 'It changes the currency of the response to euros' },
      { id: 'd', label: 'It disables reasoning capabilities' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_40',
    section: 'literacy',
    prompt: 'What is "ReAct" (Reason + Act) prompting?',
    options: [
      { id: 'a', label: 'A JavaScript framework for building frontend buttons' },
      { id: 'b', label: 'A prompting paradigm combining thought reasoning steps with specific tool actions and observation loops' },
      { id: 'c', label: 'Reacting with emotional emojis to AI responses' },
      { id: 'd', label: 'A technique for playing video games' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_41',
    section: 'literacy',
    prompt: 'If you want an LLM to critique a piece of writing without being overly sycophantic, what instruction should you include?',
    options: [
      { id: 'a', label: '"Tell me how wonderful this draft is."' },
      { id: 'b', label: '"Adopt an impartial, rigorous editor persona. Identify specific logical gaps, unsupported assertions, and clarity issues without generic praise."' },
      { id: 'c', label: '"Rewrite everything immediately."' },
      { id: 'd', label: '"Output 5 exclamation marks."' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'lit_42',
    section: 'literacy',
    prompt: 'What is a "stop sequence" parameter in LLM generation configuration?',
    options: [
      { id: 'a', label: 'A string or token that, when generated by the model, immediately terminates further output' },
      { id: 'b', label: 'An emergency kill switch for the GPU cluster' },
      { id: 'c', label: 'A keyboard shortcut to close the browser' },
      { id: 'd', label: 'A command to stop user input' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_43',
    section: 'literacy',
    prompt: 'Why is it dangerous to prompt an LLM: "Is this candidate qualified for the role? Answer YES or NO"?',
    options: [
      { id: 'a', label: 'It prevents the model from explaining its criteria, hiding potential biases, false assumptions, or hallucinations behind a binary label' },
      { id: 'b', label: 'LLMs cannot output binary words' },
      { id: 'c', label: 'YES and NO take up too many tokens' },
      { id: 'd', label: 'Candidates must always be approved' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_44',
    section: 'literacy',
    prompt: 'What does "multimodal" AI literacy mean for an end practitioner?',
    options: [
      { id: 'a', label: 'Understanding how to combine text, image, audio, and structured document inputs into a coherent analytical prompt' },
      { id: 'b', label: 'Using multiple monitors when working' },
      { id: 'c', label: 'Running three different chat windows simultaneously' },
      { id: 'd', label: 'Typing with both hands' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_45',
    section: 'literacy',
    prompt: 'When prompting an LLM to extract dates, why should you specify an ISO format (e.g. YYYY-MM-DD)?',
    options: [
      { id: 'a', label: 'To eliminate regional ambiguity between month-first (US) and day-first (European) date representations' },
      { id: 'b', label: 'Because LLMs only know Gregorian calendar dates' },
      { id: 'c', label: 'ISO formats reduce token pricing' },
      { id: 'd', label: 'Non-ISO dates are illegal in AI systems' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_46',
    section: 'literacy',
    prompt: 'What is the "Tree of Thoughts" (ToT) prompting framework?',
    options: [
      { id: 'a', label: 'An exploration technique where the model generates and evaluates multiple branching reasoning paths at each decision stage' },
      { id: 'b', label: 'A prompt about botany and environmental conservation' },
      { id: 'c', label: 'A visual diagram tool for drawing flowcharts' },
      { id: 'd', label: 'A recursive function that reloads the browser' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_47',
    section: 'literacy',
    prompt: 'Why is providing an explicit "unanswerable" clause (e.g. "If the context does not contain the answer, say \'NOT_FOUND\'") best practice in enterprise Q&A?',
    options: [
      { id: 'a', label: 'It prevents the model from fabricating plausible-sounding misinformation when information is genuinely missing' },
      { id: 'b', label: 'It saves server storage space' },
      { id: 'c', label: 'It makes the model appear humble' },
      { id: 'd', label: 'It reduces the number of API calls by 50%' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_48',
    section: 'literacy',
    prompt: 'What distinguishes a "system instruction" from a "user prompt" in modern API architectures?',
    options: [
      { id: 'a', label: 'System instructions define the fundamental behavior, identity, and constraints of the agent; user prompts represent task-specific inputs' },
      { id: 'b', label: 'System instructions are visible to the end-user while user prompts are secret' },
      { id: 'c', label: 'User prompts have higher authority than system instructions' },
      { id: 'd', label: 'There is no functional distinction' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_49',
    section: 'literacy',
    prompt: 'In prompt engineering, what does "temperature = 0" technically imply?',
    options: [
      { id: 'a', label: 'Greedy decoding: the model strictly selects the token with the highest predicted probability at each step' },
      { id: 'b', label: 'The model stops running to prevent overheating' },
      { id: 'c', label: 'The model produces no output at all' },
      { id: 'd', label: 'The model generates completely random output' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'lit_50',
    section: 'literacy',
    prompt: 'Which of the following is the most reliable way to enforce that an AI model does not add conversational filler (e.g. "Sure, here is your answer:")?',
    options: [
      { id: 'a', label: 'Specify: "Return only the raw output payload. Do not include introductory remarks, commentary, or conversational framing."' },
      { id: 'b', label: 'Ask the model nicely not to talk too much' },
      { id: 'c', label: 'Reduce the font size of the prompt' },
      { id: 'd', label: 'Delete the first word of the user prompt' },
    ],
    correctOptionId: 'a',
  },
];
