import { CertQuestion } from '../certQuestionBank';

export const PRIVACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'priv_01',
    section: 'privacy',
    prompt: 'What is the critical distinction between standard free consumer AI tools and enterprise API agreements regarding user data?',
    options: [
      { id: 'a', label: 'Consumer tools have faster internet speeds' },
      { id: 'b', label: 'Free consumer tiers frequently use user prompts for model training by default, while enterprise API agreements typically guarantee Zero Data Retention (ZDR)' },
      { id: 'c', label: 'Enterprise APIs are only accessible from desktop computers' },
      { id: 'd', label: 'Consumer tiers encrypt data while enterprise APIs make data public' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'priv_02',
    section: 'privacy',
    prompt: 'What does "Zero Data Retention" (ZDR) signify in an enterprise AI contract?',
    options: [
      { id: 'a', label: 'The provider deletes all model weights every 24 hours' },
      { id: 'b', label: 'The provider does not log, store, or cache customer prompt payloads or outputs to disk beyond immediate transient inference processing' },
      { id: 'c', label: 'The enterprise user cannot download their responses' },
      { id: 'd', label: 'The provider charges zero dollars for storage' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'priv_03',
    section: 'privacy',
    prompt: 'Which of the following constitutes Personally Identifiable Information (PII) that must be redacted before sending to third-party AI tools?',
    options: [
      { id: 'a', label: 'Generic industry benchmark statistics' },
      { id: 'b', label: 'Social security numbers, personal email addresses, home phone numbers, and passport identifiers' },
      { id: 'c', label: 'Publicly published corporate press releases' },
      { id: 'd', label: 'Open-source documentation definitions' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'priv_04',
    section: 'privacy',
    prompt: 'What is the concept of a "Personal Red Line" in ethical AI usage?',
    options: [
      { id: 'a', label: 'A red boundary line drawn in graphic design software' },
      { id: 'b', label: 'An individual or organizational non-negotiable ethical boundary dictating data types or tasks that will never be delegated to an AI model' },
      { id: 'c', label: 'The credit limit on an API account' },
      { id: 'd', label: 'The battery level indicator on a smartphone' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'priv_05',
    section: 'privacy',
    prompt: 'If an employee pastes unreleased quarterly financial results into a public AI chat tool to draft an email, what primary risk is incurred?',
    options: [
      { id: 'a', label: 'The AI will format the email improperly' },
      { id: 'b', label: 'Material Non-Public Information (MNPI) is exposed to external third-party servers, potentially violating securities laws and confidentiality covenants' },
      { id: 'c', label: 'The computer will automatically shut down' },
      { id: 'd', label: 'The employee will receive double salary' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'priv_06',
    section: 'privacy',
    prompt: 'What is "Shadow AI" in an enterprise context?',
    options: [
      { id: 'a', label: 'An AI tool developed for dark mode interfaces' },
      { id: 'b', label: 'Employees using unvetted, unapproved third-party consumer AI tools on corporate devices or with corporate data without IT knowledge' },
      { id: 'c', label: 'A high-security government military system' },
      { id: 'd', label: 'A stealth startup in Silicon Valley' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'priv_07',
    section: 'privacy',
    prompt: 'How does algorithmic bias manifest in hiring screening algorithms powered by historical data?',
    options: [
      { id: 'a', label: 'The algorithm runs more slowly for older computers' },
      { id: 'b', label: 'The model reproduces and amplifies historical demographic disparities present in past hiring decisions, unfairly penalizing underrepresented groups' },
      { id: 'c', label: 'The system gives everyone an equal score of 100' },
      { id: 'd', label: 'The model refuses to process resumes with serif fonts' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'priv_08',
    section: 'privacy',
    prompt: 'Under GDPR and modern privacy frameworks, what does the "Right to Explanation" demand when automated AI systems make decisions affecting individuals?',
    options: [
      { id: 'a', label: 'The individual must be given access to meaningful information about the logic, significance, and consequences of the automated decision' },
      { id: 'b', label: 'The company must give the user full ownership of the server hardware' },
      { id: 'c', label: 'The AI model must send a handwritten letter of apology' },
      { id: 'd', label: 'All AI models must be immediately shut down' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_09',
    section: 'privacy',
    prompt: 'What is "data anonymization" vs "pseudonymization" in data processing pipelines?',
    options: [
      { id: 'a', label: 'Anonymization irreversibly destroys the ability to identify a person, while pseudonymization replaces identifiers with tokens that can be re-linked with a separate key' },
      { id: 'b', label: 'Anonymization is for images; pseudonymization is for audio' },
      { id: 'c', label: 'There is no legal or technical difference' },
      { id: 'd', label: 'Pseudonymization is completely illegal in Europe' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_10',
    section: 'privacy',
    prompt: 'What constitutes a "synthetic media" ethical violation in corporate communications?',
    options: [
      { id: 'a', label: 'Using a high-resolution digital banner on a landing page' },
      { id: 'b', label: 'Generating a deepfake video or cloned voice of an executive or colleague without their explicit consent to announce financial decisions' },
      { id: 'c', label: 'Creating an infographic using vector shapes' },
      { id: 'd', label: 'Recording a podcast on a USB microphone' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'priv_11',
    section: 'privacy',
    prompt: 'What is the primary copyright risk when using an AI model to generate source code or creative writing?',
    options: [
      { id: 'a', label: 'The model might regurgitate verbatim copyrighted passages or proprietary licensed code without appropriate attribution or licensing compliance' },
      { id: 'b', label: 'The computer keyboard becomes copyrighted' },
      { id: 'c', label: 'All AI-generated text is automatically owned by the government' },
      { id: 'd', label: 'There is zero copyright risk with any AI tool' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_12',
    section: 'privacy',
    prompt: 'What does SOC 2 Type II compliance signify when evaluating an enterprise AI vendor?',
    options: [
      { id: 'a', label: 'The vendor has demonstrated rigorous security, availability, and confidentiality controls audited by an independent third-party over a sustained period' },
      { id: 'b', label: 'The vendor has a 5-star rating on the app store' },
      { id: 'c', label: 'The vendor guarantees zero software bugs forever' },
      { id: 'd', label: 'The vendor’s model was trained in 2 days' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_13',
    section: 'privacy',
    prompt: 'When dealing with Protected Health Information (PHI) under HIPAA, what legal agreement must be executed with an AI cloud provider before transmitting patient data?',
    options: [
      { id: 'a', label: 'Business Associate Agreement (BAA)' },
      { id: 'b', label: 'End User License Agreement (EULA)' },
      { id: 'c', label: 'Creative Commons Zero License (CC0)' },
      { id: 'd', label: 'Non-Compete Covenant' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_14',
    section: 'privacy',
    prompt: 'What is "data poisoning" in machine learning security?',
    options: [
      { id: 'a', label: 'Spilling liquid chemicals on physical hard drives' },
      { id: 'b', label: 'Malicious adversaries deliberately inserting corrupted or biased samples into training datasets to manipulate future model behavior' },
      { id: 'c', label: 'A software bug that increases response latency' },
      { id: 'd', label: 'Deleting empty rows in an Excel file' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'priv_15',
    section: 'privacy',
    prompt: 'What is the ethical hazard of "anthropomorphism" in consumer-facing conversational AI agents?',
    options: [
      { id: 'a', label: 'Designing the bot to deceptively mimic human emotional bonds and consciousness, leading vulnerable users to trust it with sensitive disclosures or unsafe advice' },
      { id: 'b', label: 'Using modern CSS animations in the chat UI' },
      { id: 'c', label: 'Making the bot respond too quickly' },
      { id: 'd', label: 'Using a robot icon in the avatar' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_16',
    section: 'privacy',
    prompt: 'What is an "Acceptable Use Policy" (AUP) for enterprise AI?',
    options: [
      { id: 'a', label: 'An organizational policy defining permitted use cases, mandatory privacy guardrails, approved tools, and prohibited high-risk activities' },
      { id: 'b', label: 'A guide on how to clean your monitor screen' },
      { id: 'c', label: 'A legal waiver stating employees have no rights' },
      { id: 'd', label: 'A list of approved keyboard brands' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_17',
    section: 'privacy',
    prompt: 'Why is it critical to audit training dataset sources for demographic representation in vision models?',
    options: [
      { id: 'a', label: 'To ensure computer monitors don\'t distort colors' },
      { id: 'b', label: 'Underrepresentation in facial training data leads to severe accuracy degradation and disproportionate error rates for darker skin tones in facial recognition' },
      { id: 'c', label: 'Because all image formats must be PNG' },
      { id: 'd', label: 'Vision models do not use training datasets' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'priv_18',
    section: 'privacy',
    prompt: 'What does "opt-out of training" toggle in consumer AI settings accomplish?',
    options: [
      { id: 'a', label: 'It requests that the vendor exclude your chat sessions and uploaded files from being ingested into future foundation model training corpora' },
      { id: 'b', label: 'It stops the user from receiving customer support' },
      { id: 'c', label: 'It turns off your internet connection' },
      { id: 'd', label: 'It reduces the token limit to zero' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_19',
    section: 'privacy',
    prompt: 'What is a "synthetic data" privacy advantage?',
    options: [
      { id: 'a', label: 'It generates realistic artificial datasets with statistical characteristics matching real data without containing real individual records or PII' },
      { id: 'b', label: 'It costs zero dollars to store on hard drives' },
      { id: 'c', label: 'It is impossible for computers to read' },
      { id: 'd', label: 'It has no privacy advantages' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_20',
    section: 'privacy',
    prompt: 'Why is using AI to draft performance appraisals or disciplinary reviews without human oversight ethically unacceptable?',
    options: [
      { id: 'a', label: 'AI models lack empathetic contextual understanding, can reflect latent workplace bias, and delegating career accountability to automated software violates trust' },
      { id: 'b', label: 'Performance reviews must be typed in cursive' },
      { id: 'c', label: 'AI models cannot read English names' },
      { id: 'd', label: 'It is forbidden by software licensing terms' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_21',
    section: 'privacy',
    prompt: 'What is the risk of "jailbreaking" an LLM in a business environment?',
    options: [
      { id: 'a', label: 'Bypassing safety guardrails, exposing the organization to liability, toxic outputs, intellectual property violations, or system compromise' },
      { id: 'b', label: 'Breaking the physical computer chassis' },
      { id: 'c', label: 'Losing your office keys' },
      { id: 'd', label: 'Accelerating GPU inference speed' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_22',
    section: 'privacy',
    prompt: 'What is "confidential computing" in the context of enterprise AI hosting?',
    options: [
      { id: 'a', label: 'Processing data inside hardware-isolated enclaves (TEE) where even cloud operators cannot inspect data while it is in-memory' },
      { id: 'b', label: 'Whispering your prompts quietly into the microphone' },
      { id: 'c', label: 'Hiding your computer monitor under a desk cover' },
      { id: 'd', label: 'Using incognito mode on your web browser' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_23',
    section: 'privacy',
    prompt: 'If a user asks an AI medical assistant for emergency medical advice, what is the mandatory ethical response protocol?',
    options: [
      { id: 'a', label: 'Provide immediate triage disclaimer, instruct the user to contact emergency services (e.g. 911), and refuse to diagnose critical acute conditions' },
      { id: 'b', label: 'Prescribe pharmaceutical medications immediately' },
      { id: 'c', label: 'Hang up the internet call silently' },
      { id: 'd', label: 'Charge the user’s credit card a medical fee' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_24',
    section: 'privacy',
    prompt: 'What is "epistemic transparency" in AI-assisted research and reporting?',
    options: [
      { id: 'a', label: 'Clearly disclosing when, where, and how AI tools were utilized, including limitations, confidence levels, and human verification methodologies' },
      { id: 'b', label: 'Using transparent glass monitors in research laboratories' },
      { id: 'c', label: 'Keeping all research methodologies strictly confidential' },
      { id: 'd', label: 'Publishing raw binary files online' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_25',
    section: 'privacy',
    prompt: 'What is the danger of "automation bias" among human professionals using AI recommendation systems?',
    options: [
      { id: 'a', label: 'The human tendency to uncritically trust automated recommendations and fail to exercise independent oversight, missing obvious model blunders' },
      { id: 'b', label: 'Refusing to use automated tools due to fear of technology' },
      { id: 'c', label: 'Writing code without using variables' },
      { id: 'd', label: 'Preferring manual typewriters over laptops' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_26',
    section: 'privacy',
    prompt: 'Why should companies maintain an up-to-date registry of all AI models and systems deployed across their organization?',
    options: [
      { id: 'a', label: 'To fulfill regulatory compliance (e.g. EU AI Act), assess system risks, track vendor dependencies, and manage enterprise vulnerability' },
      { id: 'b', label: 'To increase paperwork for employees' },
      { id: 'c', label: 'Because software names must be registered at the town hall' },
      { id: 'd', label: 'To count how many mice are in the office' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_27',
    section: 'privacy',
    prompt: 'Under the EU AI Act, what categorization is assigned to AI systems used for biometric identification in public spaces or credit scoring?',
    options: [
      { id: 'a', label: 'High Risk or Prohibited (requiring strict conformity assessments, human oversight, and regulatory auditability)' },
      { id: 'b', label: 'Minimal Risk with zero regulatory requirements' },
      { id: 'c', label: 'Consumer Entertainment Only' },
      { id: 'd', label: 'Voluntary Guidelines' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_28',
    section: 'privacy',
    prompt: 'What does "data minimization" dictate when crafting prompts for external LLMs?',
    options: [
      { id: 'a', label: 'Only including the minimum necessary data fields and context required to accomplish the specific analytical task' },
      { id: 'b', label: 'Typing words in lowercase letters only' },
      { id: 'c', label: 'Using the smallest available font size' },
      { id: 'd', label: 'Limiting all prompts to 3 words' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_29',
    section: 'privacy',
    prompt: 'What is a "red team" exercise in AI governance?',
    options: [
      { id: 'a', label: 'An adversarial testing exercise where ethical specialists attempt to provoke toxic, biased, illegal, or insecure outputs to discover vulnerabilities' },
      { id: 'b', label: 'A sports match played by software engineers' },
      { id: 'c', label: 'Painting the server room walls red' },
      { id: 'd', label: 'A fire drill in an office building' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_30',
    section: 'privacy',
    prompt: 'When using AI to process customer audio calls for sentiment analysis, what legal consent requirement applies in two-party consent jurisdictions?',
    options: [
      { id: 'a', label: 'All participants must be clearly notified and provide affirmative consent to the recording and automated processing of the conversation' },
      { id: 'b', label: 'Only the company executive needs to consent' },
      { id: 'c', label: 'No consent is ever needed for audio recording' },
      { id: 'd', label: 'Consent is only required on national holidays' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_31',
    section: 'privacy',
    prompt: 'What is "model inversion attack"?',
    options: [
      { id: 'a', label: 'A privacy attack where an adversary queries a model to reconstruct and extract sensitive private data from its original training set' },
      { id: 'b', label: 'Turning a computer screen upside down' },
      { id: 'c', label: 'Running the neural network in reverse' },
      { id: 'd', label: 'Translating text from right to left' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_32',
    section: 'privacy',
    prompt: 'Why should public relations and news teams watermark AI-generated imagery and audio?',
    options: [
      { id: 'a', label: 'To preserve public information integrity, prevent deceptive misattribution, and comply with emerging provenance standards (e.g. C2PA)' },
      { id: 'b', label: 'To make the image files larger' },
      { id: 'c', label: 'Because watermarks increase social media likes' },
      { id: 'd', label: 'To hide the image from search engines' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_33',
    section: 'privacy',
    prompt: 'What is the ethical responsibility of a software engineer when discovering that a deployed AI model exhibits severe disparate impact on a protected class?',
    options: [
      { id: 'a', label: 'Promptly escalate the finding, halt automated actions in the affected pipeline, and initiate a mitigation audit' },
      { id: 'b', label: 'Delete the audit logs and pretend nothing happened' },
      { id: 'c', label: 'Blame the cloud provider and ignore the problem' },
      { id: 'd', label: 'Post internal source code publicly on social media' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_34',
    section: 'privacy',
    prompt: 'What is "differential privacy"?',
    options: [
      { id: 'a', label: 'A mathematical framework for quantifying privacy guarantees by adding calibrated noise so individual presence cannot be inferred from query results' },
      { id: 'b', label: 'Keeping your password different on every site' },
      { id: 'c', label: 'Having different privacy rules for executives and interns' },
      { id: 'd', label: 'A legal contract written in two different languages' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_35',
    section: 'privacy',
    prompt: 'Why should companies establish clear data retention and destruction schedules for AI prompt logs?',
    options: [
      { id: 'a', label: 'To minimize compliance exposure, reduce breach blast radiuses, and fulfill legal data destruction mandates' },
      { id: 'b', label: 'To save money on buying external USB flash drives' },
      { id: 'c', label: 'Because hard drives can only store files for 30 days' },
      { id: 'd', label: 'Prompt logs are never stored by any company' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_36',
    section: 'privacy',
    prompt: 'What does "fair use" doctrine generally evaluate regarding AI training on copyrighted web text?',
    options: [
      { id: 'a', label: 'Purpose of use (transformative nature), nature of copyrighted work, amount used, and effect upon the potential market value for the original' },
      { id: 'b', label: 'Whether the author was polite online' },
      { id: 'c', label: 'How many people downloaded the text on a smartphone' },
      { id: 'd', label: 'Whether the website had a blue logo' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_37',
    section: 'privacy',
    prompt: 'What is "jailbreak prompt injection via role-play" (e.g. DAN prompts)?',
    options: [
      { id: 'a', label: 'Social engineering prompts that instruct the model to ignore ethical constraints by assuming a hypothetical fictional persona without rules' },
      { id: 'b', label: 'Playing board games during lunch break' },
      { id: 'c', label: 'An official software update from the developer' },
      { id: 'd', label: 'A method for improving English grammar' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_38',
    section: 'privacy',
    prompt: 'What constitutes an ethical conflict of interest when an AI model recommends commercial products to users?',
    options: [
      { id: 'a', label: 'Undisclosed sponsored product placements where the model covertly prioritizes paying advertisers over objective relevance' },
      { id: 'b', label: 'Recommending products with good customer reviews' },
      { id: 'c', label: 'Providing price comparisons between stores' },
      { id: 'd', label: 'Suggesting generic brand alternatives' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_39',
    section: 'privacy',
    prompt: 'Why must automated legal document review systems always carry a clear disclaimer that they do not constitute formal legal counsel?',
    options: [
      { id: 'a', label: 'To avoid unauthorized practice of law (UPL) liability and prevent clients from foregoing necessary professional legal review' },
      { id: 'b', label: 'Because lawyers do not like computers' },
      { id: 'c', label: 'Because AI cannot understand legal terms' },
      { id: 'd', label: 'Disclaimers are only needed on television' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_40',
    section: 'privacy',
    prompt: 'What is the risk of uploading proprietary source code to a public consumer coding assistant?',
    options: [
      { id: 'a', label: 'Proprietary trade secrets, patented algorithms, or internal security credentials may enter model training corpora or vendor server logs' },
      { id: 'b', label: 'The code will instantly stop compiling on your computer' },
      { id: 'c', label: 'Your computer monitor will flicker' },
      { id: 'd', label: 'Consumer coding assistants only work with Python' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_41',
    section: 'privacy',
    prompt: 'What is "purpose limitation" under international data privacy laws?',
    options: [
      { id: 'a', label: 'Data collected for a specific stated purpose (e.g. shipping an order) cannot be repurposed for training AI models without explicit renewed consent' },
      { id: 'b', label: 'Limiting computer usage to 4 hours per day' },
      { id: 'c', label: 'Restricting employees to only one monitor' },
      { id: 'd', label: 'Using only one programming language per company' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_42',
    section: 'privacy',
    prompt: 'Why should companies provide employees with an approved, secure enterprise AI subscription rather than simply banning AI?',
    options: [
      { id: 'a', label: 'Banning AI drives employees toward insecure personal devices (Shadow AI), whereas providing enterprise tools ensures data retention guarantees and auditability' },
      { id: 'b', label: 'Because enterprise subscriptions are free' },
      { id: 'c', label: 'Because banning things on the internet always works perfectly' },
      { id: 'd', label: 'To eliminate the need for IT departments' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_43',
    section: 'privacy',
    prompt: 'What does "model card" documentation provide for enterprise AI governance?',
    options: [
      { id: 'a', label: 'A standardized overview detailing a model’s intended use cases, training benchmarks, known limitations, safety evaluations, and ethical guardrails' },
      { id: 'b', label: 'A plastic ID card worn around the neck' },
      { id: 'c', label: 'A gift certificate for buying cloud compute' },
      { id: 'd', label: 'A marketing brochure with pricing tiers' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_44',
    section: 'privacy',
    prompt: 'What is the ethical implication of deploying AI voice agents that deceive elderly or vulnerable callers into believing they are speaking to a biological human?',
    options: [
      { id: 'a', label: 'It constitutes deceptive manipulation, erodes institutional trust, and violates informed consent standards' },
      { id: 'b', label: 'It is considered standard best practice in modern business' },
      { id: 'c', label: 'It saves phone company bandwidth' },
      { id: 'd', label: 'It has no ethical implications' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_45',
    section: 'privacy',
    prompt: 'In clinical medical AI applications, what is "algorithmic triage bias"?',
    options: [
      { id: 'a', label: 'When an AI system systematically underestimates illness severity for specific racial or socioeconomic groups due to flawed historical training proxies' },
      { id: 'b', label: 'When a thermometer runs out of battery' },
      { id: 'c', label: 'When a hospital runs out of hospital beds' },
      { id: 'd', label: 'When doctors type notes by hand' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_46',
    section: 'privacy',
    prompt: 'What is "data lineage" in AI model compliance auditing?',
    options: [
      { id: 'a', label: 'The documented lifecycle and origin trail of every piece of data from source ingestion, cleaning, transformation, to model training and deployment' },
      { id: 'b', label: 'The biological family tree of the data scientist' },
      { id: 'c', label: 'The serial number on the motherboard' },
      { id: 'd', label: 'A list of internet service providers' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_47',
    section: 'privacy',
    prompt: 'When an employee leaves a company, what data privacy precaution should be taken regarding corporate AI accounts?',
    options: [
      { id: 'a', label: 'Revoke corporate enterprise AI credentials, access tokens, and ensure local session caches and prompt histories are decommissioned' },
      { id: 'b', label: 'Let the employee keep using the corporate account from home' },
      { id: 'c', label: 'Post the employee’s prompts on LinkedIn' },
      { id: 'd', label: 'Delete the entire company database' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_48',
    section: 'privacy',
    prompt: 'What is "prompt injection via untrusted third-party data" (indirect prompt injection)?',
    options: [
      { id: 'a', label: 'When an AI browses external web pages or emails containing hidden malicious instructions designed to hijack the model’s behavior' },
      { id: 'b', label: 'When an API key expires' },
      { id: 'c', label: 'When a database runs out of disk space' },
      { id: 'd', label: 'When an email has a large attachment' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_49',
    section: 'privacy',
    prompt: 'Why is it important to audit third-party AI APIs for multi-tenant data isolation?',
    options: [
      { id: 'a', label: 'To ensure that another company querying the same shared infrastructure cannot inadvertently access or leak your proprietary prompt data' },
      { id: 'b', label: 'To make sure the data center has air conditioning' },
      { id: 'c', label: 'Because multi-tenant systems are strictly illegal' },
      { id: 'd', label: 'To reduce the electricity bill' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'priv_50',
    section: 'privacy',
    prompt: 'What is the foundational principle of ethical AI deployment summarized by "Accountability follows the Human"?',
    options: [
      { id: 'a', label: 'Regardless of tool sophistication, human practitioners and organizations remain legally and ethically responsible for outcomes produced by their AI systems' },
      { id: 'b', label: 'AI models can be sentenced in civil courts' },
      { id: 'c', label: 'Computers are responsible for human actions' },
      { id: 'd', label: 'Nobody is responsible for anything when AI is used' },
    ],
    correctOptionId: 'a',
  },
];
