import { CertQuestion, CertSection } from '../certQuestionBank';

// =========================================================================
// JNACHI PRACTITIONER QUESTION BANK (40 In-Depth Scenario Questions)
// Focus: Active workflow execution, structured JSON, deep prompting, enterprise compliance
// =========================================================================
export const PRACTITIONER_QUESTIONS: CertQuestion[] = [
  // Section: Literacy & Prompting (10 questions)
  {
    id: 'prac_lit_01',
    section: 'literacy',
    prompt: 'You are generating structured product catalogs. When using an LLM to produce valid JSON, what prompt technique best guarantees machine-parsable syntax?',
    options: [
      { id: 'a', label: 'Ask the model to format nicely with emojis and bullet points' },
      { id: 'b', label: 'Specify a strict JSON schema, supply one-shot valid JSON examples, and explicitly forbid conversational preamble or markdown codeblock wrappers if raw JSON is required' },
      { id: 'c', label: 'Set model temperature to 1.8 to encourage creative parsing' },
      { id: 'd', label: 'Submit the prompt as an unformatted run-on sentence' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_02',
    section: 'literacy',
    prompt: 'When crafting a persona prompt for financial analysis, which approach produces the most reliable, rigorous output?',
    options: [
      { id: 'a', label: '"Act as a genius investor who is never wrong."' },
      { id: 'b', label: 'Define role scope, analytical methodology (e.g. DCF, DuPont analysis), conservative bias assumptions, and mandatory risk citation steps.' },
      { id: 'c', label: 'Tell the model to give optimistic stock price predictions.' },
      { id: 'd', label: 'Use as few words as possible.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_03',
    section: 'literacy',
    prompt: 'In complex multi-document summarization, how do you prevent the "lost in the middle" phenomenon where models miss facts placed in the center of huge context windows?',
    options: [
      { id: 'a', label: 'Place key instructions and high-priority reference text near the very beginning or end of the prompt context, and prompt with step-by-step chunk extraction.' },
      { id: 'b', label: 'Always place all instructions at line 500 of the prompt.' },
      { id: 'c', label: 'Disable the model attention heads.' },
      { id: 'd', label: 'Translate the document into three languages first.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_04',
    section: 'literacy',
    prompt: 'What is the most effective way to test whether an updated system prompt has degraded existing performance across legacy edge cases?',
    options: [
      { id: 'a', label: 'Test once with a casual prompt and deploy immediately if it looks fine' },
      { id: 'b', label: 'Maintain a regression benchmark test suite of diverse input cases with expected assertion criteria and evaluate outputs deterministically' },
      { id: 'c', label: 'Ask the LLM if it thinks the new prompt is better' },
      { id: 'd', label: 'Rely solely on user complaints in production' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_05',
    section: 'literacy',
    prompt: 'Why should negative constraints (e.g., "Do NOT include greetings") be reinforced with positive guidance (e.g., "Begin directly with the raw data table")?',
    options: [
      { id: 'a', label: 'LLMs process attention tokens more reliably when provided with a clear target trajectory rather than solely unbounded negative bounds.' },
      { id: 'b', label: 'Negative words cause immediate model exceptions.' },
      { id: 'c', label: 'Positive prompts cost fewer tokens.' },
      { id: 'd', label: 'Negative words invert the model temperature.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_06',
    section: 'literacy',
    prompt: 'When summarizing a 50-page legal contract, how should a practitioner calibrate the model to prevent speculative interpretation?',
    options: [
      { id: 'a', label: 'Instruct the model to quote exact clause numbers and verbatim text excerpts for every assertion, stating "Not specified in document" when text is absent.' },
      { id: 'b', label: 'Prompt the model to fill in missing clauses using standard industry assumptions.' },
      { id: 'c', label: 'Set temperature to maximum.' },
      { id: 'd', label: 'Ask the model to rewrite the contract as a screenplay.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_07',
    section: 'literacy',
    prompt: 'What distinguishes zero-shot Chain-of-Thought ("Let\'s think step by step") from standard zero-shot prompting?',
    options: [
      { id: 'a', label: 'It encourages the model to generate intermediate reasoning tokens, significantly boosting logical and quantitative accuracy before rendering the final conclusion.' },
      { id: 'b', label: 'It bypasses model context limits entirely.' },
      { id: 'c', label: 'It executes python code in a local kernel without permission.' },
      { id: 'd', label: 'It reduces total token consumption by 50%.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_08',
    section: 'literacy',
    prompt: 'In prompt calibration, what is "prompt drift"?',
    options: [
      { id: 'a', label: 'Physical movement of servers across data centers' },
      { id: 'b', label: 'Changes in model output quality or style over time due to backend model updates, parameter fine-tuning, or shifting input distribution' },
      { id: 'c', label: 'Loss of wifi connectivity during generation' },
      { id: 'd', label: 'Exceeding the monthly subscription budget' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_09',
    section: 'literacy',
    prompt: 'How should a practitioner handle inconsistent classification tags when categorizing customer support tickets into fixed enum values?',
    options: [
      { id: 'a', label: 'Provide the exact enum list in the prompt, include 2 examples per enum category, and mandate single-word or JSON-keyed outputs matching the enum.' },
      { id: 'b', label: 'Allow the model to invent new category names as it pleases.' },
      { id: 'c', label: 'Increase prompt temperature to 1.2.' },
      { id: 'd', label: 'Ask the customer to classify their own ticket.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_10',
    section: 'literacy',
    prompt: 'When drafting automated email responses, what prevents the AI from sounding generic and boilerplate?',
    options: [
      { id: 'a', label: 'Providing a 3-tier style guide (voice, forbidden clichés, concrete sentence structure examples) and contextual variable slots.' },
      { id: 'b', label: 'Adding "Write this in a super energetic and viral style!"' },
      { id: 'c', label: 'Using all capital letters.' },
      { id: 'd', label: 'Inserting 10 emojis in every paragraph.' },
    ],
    correctOptionId: 'a',
  },

  // Section: Workflow Automation (10 questions)
  {
    id: 'prac_auto_01',
    section: 'automation',
    prompt: 'When building an automated meeting debrief workflow, what is the best practice for handling 90-minute messy transcripts?',
    options: [
      { id: 'a', label: 'A 2-stage pipeline: Stage 1 cleans transcript into speaker-tagged chronological summaries; Stage 2 extracts action items, owners, and deadlines.' },
      { id: 'b', label: 'Dump the full raw audio file directly into an image generation model.' },
      { id: 'c', label: 'Ask the model in one line: "Summarize everything."' },
      { id: 'd', label: 'Delete the transcript if it exceeds 500 words.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_02',
    section: 'automation',
    prompt: 'What constitutes an effective personal or team "Prompt Library"?',
    options: [
      { id: 'a', label: 'A collection of tested, versioned prompts with clear parameter placeholders ({variables}), expected output contracts, and usage context.' },
      { id: 'b', label: 'A messy unorganized text file of random chat URLs.' },
      { id: 'c', label: 'A single prompt used for all company tasks indiscriminately.' },
      { id: 'd', label: 'A bookmark folder of AI news articles.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_03',
    section: 'automation',
    prompt: 'When automating customer feedback extraction from hundreds of reviews, why is batch processing with JSON schema superior to free-form chat querying?',
    options: [
      { id: 'a', label: 'It produces predictable structured records (sentiment score, feature mention, bug report) that ingest directly into analytics databases.' },
      { id: 'b', label: 'It makes the model respond with humorous poems.' },
      { id: 'c', label: 'It eliminates the need for internet access.' },
      { id: 'd', label: 'It guarantees 100% positive customer reviews.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_04',
    section: 'automation',
    prompt: 'In a multi-step writing pipeline, why is "clay drafting" (drafting raw content without editing, then passing to a critique/polishing prompt) recommended?',
    options: [
      { id: 'a', label: 'Separating ideation/content generation from editorial refining prevents cognitive bottlenecks and yields significantly tighter outputs.' },
      { id: 'b', label: 'Because clay is cheaper than silicon.' },
      { id: 'c', label: 'It forces the model to use British spelling.' },
      { id: 'd', label: 'It hides prompt errors from the user.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_05',
    section: 'automation',
    prompt: 'What is the primary risk of chaining five generative prompt steps without intermediate validation schemas?',
    options: [
      { id: 'a', label: 'Error propagation: subtle hallucinations or formatting drift in step 1 compound into total output degeneration by step 5.' },
      { id: 'b', label: 'The computer fan runs slightly faster.' },
      { id: 'c', label: 'The model permanently shuts down.' },
      { id: 'd', label: 'The prompt text changes color.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_06',
    section: 'automation',
    prompt: 'When automating weekly KPI reports from raw CSV spreadsheets, how should numerical data be passed to the LLM to minimize calculation errors?',
    options: [
      { id: 'a', label: 'Pre-calculate totals, growth rates, and percentages programmatically via code/formulas, passing the calculated metrics for the LLM to synthesize narrative insights.' },
      { id: 'b', label: 'Ask the LLM to multiply 8-digit floating numbers mentally in pure text.' },
      { id: 'c', label: 'Omit all numbers from the prompt.' },
      { id: 'd', label: 'Ask the LLM to guess revenue based on vibes.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_07',
    section: 'automation',
    prompt: 'What is a "micro-task audit" in workflow automation?',
    options: [
      { id: 'a', label: 'Reviewing daily work to decompose large ambiguous jobs into discrete 2-5 minute cognitive sub-tasks suitable for AI assistance.' },
      { id: 'b', label: 'Auditing microchip inventories.' },
      { id: 'c', label: 'Tracking employee mouse clicks per second.' },
      { id: 'd', label: 'Calculating electrical wattage per token.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_08',
    section: 'automation',
    prompt: 'How can teams ensure consistency across AI-assisted customer support replies authored by multiple human agents?',
    options: [
      { id: 'a', label: 'Implement standardized prompt macros with pre-defined company tone, approved knowledge base references, and required sign-off policies.' },
      { id: 'b', label: 'Have all agents share one single login account.' },
      { id: 'c', label: 'Forbid all agents from reading the customer tickets.' },
      { id: 'd', label: 'Randomize the prompt daily.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_09',
    section: 'automation',
    prompt: 'When an automated AI script encounters an unparsable response format, what is the best architectural fallback?',
    options: [
      { id: 'a', label: 'Catch parsing error, retry once with an explicit correction prompt showing the error, or route to human review queue if retry fails.' },
      { id: 'b', label: 'Crash the entire server silently.' },
      { id: 'c', label: 'Insert dummy data into the database and ignore it.' },
      { id: 'd', label: 'Send an angry email to the AI vendor.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_10',
    section: 'automation',
    prompt: 'Why should automation prompts use structured markdown headers (e.g. # CONTEXT, # INPUT DATA, # OUTPUT SPEC) rather than unsegmented blocks?',
    options: [
      { id: 'a', label: 'Explicit structural boundaries help models segment instructions from data, reducing instruction-following errors.' },
      { id: 'b', label: 'Markdown makes the prompt download faster.' },
      { id: 'c', label: 'Headers automatically double the GPU clock speed.' },
      { id: 'd', label: 'It is required by browser HTML standards.' },
    ],
    correctOptionId: 'a',
  },

  // Section: Data Privacy & Ethics (10 questions)
  {
    id: 'prac_priv_01',
    section: 'privacy',
    prompt: 'A colleague wants to paste customer names, credit card numbers, and raw database dumps into a free public consumer AI web chat. What is the immediate correct action?',
    options: [
      { id: 'a', label: 'Intervene immediately: public consumer tiers default to training on user inputs; PII/PCI data must never be submitted without enterprise Zero Data Retention agreements.' },
      { id: 'b', label: 'Tell them to proceed as long as they delete the chat afterwards.' },
      { id: 'c', label: 'Ask them to use an incognito browser window.' },
      { id: 'd', label: 'Ignore it because AI models forget everything.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_priv_02',
    section: 'privacy',
    prompt: 'What is "Zero Data Retention" (ZDR) in enterprise AI API service agreements?',
    options: [
      { id: 'a', label: 'The provider guarantees that customer prompt and output data is neither stored persistently on server disks after inference nor used for foundation model training.' },
      { id: 'b', label: 'The company deletes its customer database every night.' },
      { id: 'c', label: 'The model has zero memory during a single prompt.' },
      { id: 'd', label: 'A policy forbidding employees from taking notes.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_priv_03',
    section: 'privacy',
    prompt: 'Before using an LLM to analyze internal company performance review feedback, what preprocessing step is mandatory?',
    options: [
      { id: 'a', label: 'Anonymize or pseudonymize all identifying employee names, specific dates, team titles, and unique private project codenames.' },
      { id: 'b', label: 'Publish the reviews on the company public blog.' },
      { id: 'c', label: 'Translate the reviews into Latin.' },
      { id: 'd', label: 'Ask the model to guess who wrote each review.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_priv_04',
    section: 'privacy',
    prompt: 'What constitutes an algorithmic bias risk when using AI to screen incoming job applicant resumes?',
    options: [
      { id: 'a', label: 'Models trained on historical hiring data may systematically favor demographic patterns, phrasing, or prestige proxies present in legacy resumes.' },
      { id: 'b', label: 'The model might run out of memory.' },
      { id: 'c', label: 'The resumes will be converted into PDF format.' },
      { id: 'd', label: 'The model might hire too many robots.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_priv_05',
    section: 'privacy',
    prompt: 'What is a "personal/organizational red line" in AI adoption?',
    options: [
      { id: 'a', label: 'Explicit boundaries defining categories of decisions (e.g., criminal sentencing, termination notices, medical diagnoses) that must NEVER be automated without direct human authority.' },
      { id: 'b', label: 'A red underline showing spelling mistakes.' },
      { id: 'c', label: 'A boundary line drawn around server racks.' },
      { id: 'd', label: 'A maximum limit on keyboard keystrokes.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_priv_06',
    section: 'privacy',
    prompt: 'Why is client-side data redaction (masking PII with tokens like [NAME_1], [COMPANY_A]) safer than asking the LLM in the prompt to "ignore private data"?',
    options: [
      { id: 'a', label: 'If PII is never transmitted to the external API, no prompt injection, logging leak, or model retention flaw can ever expose the sensitive data.' },
      { id: 'b', label: 'Redaction makes the text rhyme.' },
      { id: 'c', label: 'LLMs refuse to read unredacted text.' },
      { id: 'd', label: 'Masking reduces word count by 90%.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_priv_07',
    section: 'privacy',
    prompt: 'Under GDPR and CCPA, if an enterprise incorporates AI tools to process EU/CA citizen data, what legal document must be executed with the AI vendor?',
    options: [
      { id: 'a', label: 'A Data Processing Agreement (DPA) with standard contractual clauses governing data handling, security, and sub-processors.' },
      { id: 'b', label: 'A verbal agreement over the phone.' },
      { id: 'c', label: 'A marketing tweet.' },
      { id: 'd', label: 'No agreement is required for AI tools.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_priv_08',
    section: 'privacy',
    prompt: 'What is the risk of "data leakage" through prompt caching in multi-tenant cloud environments?',
    options: [
      { id: 'a', label: 'If prompt caches are not strictly isolated per organization or tenant, cached context might inadvertently influence or surface in another tenant\'s session.' },
      { id: 'b', label: 'Water leaking onto server hardware.' },
      { id: 'c', label: 'Browser tabs closing automatically.' },
      { id: 'd', label: 'Fonts changing unexpectedly.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_priv_09',
    section: 'privacy',
    prompt: 'How should an organization verify the copyright and licensing risks of AI-generated source code?',
    options: [
      { id: 'a', label: 'Enable public code matching/telemetry filters in AI coding assistants, and run standard dependency/license audit tools on all generated snippets.' },
      { id: 'b', label: 'Assume all AI code is public domain without verification.' },
      { id: 'c', label: 'Never compile the code.' },
      { id: 'd', label: 'Only use code generated on weekends.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_priv_10',
    section: 'privacy',
    prompt: 'When deploying an AI assistant to external users, what transparency requirement is best practice?',
    options: [
      { id: 'a', label: 'Clearly disclose to users that they are interacting with an AI system and provide straightforward avenues to reach human support.' },
      { id: 'b', label: 'Deceive users into believing the AI is a real human employee.' },
      { id: 'c', label: 'Hide all company contact info.' },
      { id: 'd', label: 'Block all user questions.' },
    ],
    correctOptionId: 'a',
  },

  // Section: Growth & Problem Solving (10 questions)
  {
    id: 'prac_gro_01',
    section: 'growth',
    prompt: 'How can an AI practitioner use an LLM as a "Cognitive Sparring Partner" when preparing for a critical executive presentation?',
    options: [
      { id: 'a', label: 'Instruct the model to adopt the persona of a skeptical CFO, stress-test your assumptions, and challenge every financial metric with counter-arguments.' },
      { id: 'b', label: 'Ask the model to agree with every slide enthusiastically.' },
      { id: 'c', label: 'Have the model write generic praise.' },
      { id: 'd', label: 'Copy-paste the presentation into an email without review.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_02',
    section: 'growth',
    prompt: 'When evaluating new third-party "AI tools" on the market, what is the best "anti-hype" evaluation filter?',
    options: [
      { id: 'a', label: 'Determine whether the tool is a thin wrapper over a basic system prompt, or if it provides defensible proprietary workflows, domain integrations, and data gravity.' },
      { id: 'b', label: 'Count how many times the word "revolutionary" appears on their website.' },
      { id: 'c', label: 'Choose whichever tool has the flashiest logo animation.' },
      { id: 'd', label: 'Pick the most expensive tool automatically.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_03',
    section: 'growth',
    prompt: 'How should a practitioner leverage multimodal vision models when debugging a complex UI/UX layout bug?',
    options: [
      { id: 'a', label: 'Provide screenshot of the broken UI alongside corresponding HTML/CSS code, asking the model to pinpoint CSS property conflicts causing the visual defect.' },
      { id: 'b', label: 'Type a 10-word vague description without screenshots.' },
      { id: 'c', label: 'Take a photo of the monitor with a smartphone from 10 feet away.' },
      { id: 'd', label: 'Convert the image into audio and listen to it.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_04',
    section: 'growth',
    prompt: 'What is the hallmark of high "AI Momentum" in an organization?',
    options: [
      { id: 'a', label: 'Teams actively integrate verified AI prompt patterns into daily workflows, measure time savings and quality improvements, and continuously share best practices.' },
      { id: 'b', label: 'Buying enterprise licenses that no employee ever logs into.' },
      { id: 'c', label: 'Writing press releases about AI without using it.' },
      { id: 'd', label: 'Replacing all human employees overnight.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_05',
    section: 'growth',
    prompt: 'When an AI model produces two contradictory answers in successive chat turns, how should a practitioner resolve the conflict?',
    options: [
      { id: 'a', label: 'Ask the model to isolate the underlying assumptions behind both conclusions, cite primary sources, and reconcile the logic against verified reference facts.' },
      { id: 'b', label: 'Flip a coin to choose which answer to believe.' },
      { id: 'c', label: 'Always trust the longer answer.' },
      { id: 'd', label: 'Restart the computer.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_06',
    section: 'growth',
    prompt: 'What is "calibration" in the context of human-AI collaboration?',
    options: [
      { id: 'a', label: 'Developing an accurate intuition for what types of cognitive tasks an LLM excels at vs where it is prone to hallucination, sycophancy, or failure.' },
      { id: 'b', label: 'Adjusting monitor brightness settings.' },
      { id: 'c', label: 'Measuring typing speed on the keyboard.' },
      { id: 'd', label: 'Setting the computer clock to UTC.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_07',
    section: 'growth',
    prompt: 'Why is "sycophancy" in LLMs a risk for strategic decision-making?',
    options: [
      { id: 'a', label: 'Models tend to agree with the user\'s leading hypotheses and confirm flawed biases rather than pointing out fatal logical gaps.' },
      { id: 'b', label: 'The model becomes excessively rude and insulting.' },
      { id: 'c', label: 'The model refuses to generate text.' },
      { id: 'd', label: 'The model drains token credits twice as fast.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_08',
    section: 'growth',
    prompt: 'How should a practitioner prompt an LLM to actively combat sycophancy and confirmational bias?',
    options: [
      { id: 'a', label: '"Adopt a steel-man posture: independently critique this strategy, outline the 3 most probable failure modes, and provide counter-evidence."' },
      { id: 'b', label: '"Tell me why my idea is the greatest in company history."' },
      { id: 'c', label: '"Be nice and agreeable."' },
      { id: 'd', label: '"Generate 5 compliments about my plan."' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_09',
    section: 'growth',
    prompt: 'When exploring an unfamiliar technical domain, how can an AI practitioner structure a 15-minute learning sprint?',
    options: [
      { id: 'a', label: 'Request a foundational concept breakdown with analogies, follow up on the 3 core bottleneck mechanisms, and test comprehension with AI-generated quiz scenarios.' },
      { id: 'b', label: 'Skim a 500-page textbook in 2 minutes.' },
      { id: 'c', label: 'Ask the AI to do all future thinking for you.' },
      { id: 'd', label: 'Memorize random acronyms without definitions.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_10',
    section: 'growth',
    prompt: 'What distinguishes a true AI Practitioner from a casual AI user?',
    options: [
      { id: 'a', label: 'A Practitioner designs repeatable, calibrated workflows, verifies critical outputs against ground truth, and treats AI as an amplifier of rigorous human judgment.' },
      { id: 'b', label: 'A Practitioner blindly trusts raw model outputs without checking.' },
      { id: 'c', label: 'A Practitioner only uses AI to write social media memes.' },
      { id: 'd', label: 'A Practitioner owns the most expensive subscription tier.' },
    ],
    correctOptionId: 'a',
  },
];

// =========================================================================
// JNACHI BUILDER QUESTION BANK (40 Advanced Technical & Pipeline Questions)
// Focus: Tool chaining, multi-step agent pipelines, function calling, schemas, error recovery
// =========================================================================
export const BUILDER_QUESTIONS: CertQuestion[] = [
  // Section: Literacy & Prompting (10 questions)
  {
    id: 'bld_lit_01',
    section: 'literacy',
    prompt: 'When configuring structured tool/function calling with LLMs, how does the model select which tool to invoke?',
    options: [
      { id: 'a', label: 'The model analyzes the tool JSON definitions, parameter types, and descriptions, generating structured arguments matching the chosen function signature.' },
      { id: 'b', label: 'It executes random code until something works.' },
      { id: 'c', label: 'It picks the function with the shortest name.' },
      { id: 'd', label: 'Tool calling is hardcoded on the user\'s local operating system.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_02',
    section: 'literacy',
    prompt: 'Why are detailed docstrings and parameter descriptions essential in function calling declarations?',
    options: [
      { id: 'a', label: 'LLMs rely directly on parameter descriptions as context cues to infer semantics, valid formats (e.g. ISO 8601 dates), and edge case constraints.' },
      { id: 'b', label: 'They make the API call execute faster.' },
      { id: 'c', label: 'They are legally required by open-source licenses.' },
      { id: 'd', label: 'Without them, the programming language will not compile.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_03',
    section: 'literacy',
    prompt: 'In complex prompt routing architectures, what is the role of a lightweight "Router" or "Classifier" model?',
    options: [
      { id: 'a', label: 'Quickly evaluate incoming user intent and dispatch the query to specialized prompt templates, tools, or domain-specific models with minimal latency/cost.' },
      { id: 'b', label: 'Connect ethernet cables in the data center.' },
      { id: 'c', label: 'Delete user session history.' },
      { id: 'd', label: 'Translate all prompts into Morse code.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_04',
    section: 'literacy',
    prompt: 'What is the purpose of system prompt modularization using templating engines (e.g., Mustache, Jinja2)?',
    options: [
      { id: 'a', label: 'Allows dynamic composition of system context, user roles, permission scopes, and real-time state variables without hardcoding monolithic prompt strings.' },
      { id: 'b', label: 'Converts English prompts into German.' },
      { id: 'c', label: 'Encrypts the prompt so the model cannot read it.' },
      { id: 'd', label: 'Reduces model temperature to zero permanently.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_05',
    section: 'literacy',
    prompt: 'When an LLM must extract 20 distinct data entities from noisy OCR receipts, which prompt pattern achieves the lowest hallucination rate?',
    options: [
      { id: 'a', label: 'Two-pass extraction: Pass 1 isolates bounding text snippets for each field; Pass 2 validates snippets into a strict typed schema with confidence scores.' },
      { id: 'b', label: 'Single prompt asking for "everything in the receipt".' },
      { id: 'c', label: 'Prompt with temperature set to 1.5.' },
      { id: 'd', label: 'Ask the model to guess missing prices.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_06',
    section: 'literacy',
    prompt: 'What is "context window pruning" in long-running conversational agent workflows?',
    options: [
      { id: 'a', label: 'Systematically summarizing older conversation turns or evicting low-relevance tool outputs to preserve token budget for crucial context and instructions.' },
      { id: 'b', label: 'Closing browser windows every 5 minutes.' },
      { id: 'c', label: 'Deleting model weights from memory.' },
      { id: 'd', label: 'Truncating all prompts to 10 tokens.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_07',
    section: 'literacy',
    prompt: 'How does constrained decoding (e.g. grammar-based sampling, JSON schema enforcement) differ from post-hoc JSON validation?',
    options: [
      { id: 'a', label: 'Constrained decoding masks invalid tokens during sampling so invalid syntax is impossible to generate, whereas post-hoc validation only catches errors after completion.' },
      { id: 'b', label: 'Constrained decoding runs in the browser only.' },
      { id: 'c', label: 'Post-hoc validation eliminates latency completely.' },
      { id: 'd', label: 'There is no difference.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_08',
    section: 'literacy',
    prompt: 'Why should builders avoid putting excessive, contradictory rules in a single 4,000-word system prompt?',
    options: [
      { id: 'a', label: 'Rule collisions lead to unpredictable instruction following, degradation of core constraints, and increased latency/token costs.' },
      { id: 'b', label: 'Because LLMs can only read up to 100 words.' },
      { id: 'c', label: 'It causes database indexes to corrupt.' },
      { id: 'd', label: 'System prompts must always be under 5 words.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_09',
    section: 'literacy',
    prompt: 'What is the role of "few-shot negative examples" in prompt engineering for code generation?',
    options: [
      { id: 'a', label: 'Demonstrating common anti-patterns or insecure implementations alongside corrected code snippets to explicitly teach the model what patterns to avoid.' },
      { id: 'b', label: 'Insulting the developer who wrote the code.' },
      { id: 'c', label: 'Generating broken code on purpose to test server crashes.' },
      { id: 'd', label: 'Decreasing model precision.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_10',
    section: 'literacy',
    prompt: 'When building an automated document classification pipeline, what metric is most critical for evaluating class imbalance?',
    options: [
      { id: 'a', label: 'F1-Score (Precision vs Recall) per category, rather than overall raw accuracy alone.' },
      { id: 'b', label: 'Total word count of the output.' },
      { id: 'c', label: 'The file size of the Python script.' },
      { id: 'd', label: 'The number of comments in the code.' },
    ],
    correctOptionId: 'a',
  },

  // Section: Workflow Automation (10 questions)
  {
    id: 'bld_auto_01',
    section: 'automation',
    prompt: 'What is the fundamental architectural loop in an autonomous AI Agent (e.g. ReAct framework)?',
    options: [
      { id: 'a', label: 'Thought (Reasoning) -> Action (Tool Call) -> Observation (Tool Output) -> Evaluation -> Loop until termination condition is met.' },
      { id: 'b', label: 'Generate text -> Delete database -> Restart.' },
      { id: 'c', label: 'Infinite while(true) loop generating random strings.' },
      { id: 'd', label: 'Single zero-shot API call with no feedback.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_02',
    section: 'automation',
    prompt: 'How do you prevent an AI agent from entering an infinite loop when a tool call repeatedly fails or returns ambiguous errors?',
    options: [
      { id: 'a', label: 'Implement hard iteration limits (e.g. max 10 steps), error escalation heuristics, and human-in-the-loop fallback breakpoints.' },
      { id: 'b', label: 'Let the agent run indefinitely until the server runs out of budget.' },
      { id: 'c', label: 'Disable all error messages.' },
      { id: 'd', label: 'Set API timeout to 1 millisecond.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_03',
    section: 'automation',
    prompt: 'In a multi-agent workflow where Agent A produces code and Agent B reviews it, what is the best strategy for state management?',
    options: [
      { id: 'a', label: 'Maintain a centralized structured state object (e.g. state graph) tracking current draft, lint errors, test results, and iteration counts.' },
      { id: 'b', label: 'Pass raw unstructured chat strings back and forth endlessly.' },
      { id: 'c', label: 'Store state only in temporary browser cookies.' },
      { id: 'd', label: 'Discard all state between agent turns.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_04',
    section: 'automation',
    prompt: 'What is Retrieval-Augmented Generation (RAG) and why is it preferred over fine-tuning for dynamic corporate knowledge bases?',
    options: [
      { id: 'a', label: 'RAG retrieves relevant up-to-date document chunks at query time and injects them into the prompt, allowing instant knowledge updates without expensive retraining.' },
      { id: 'b', label: 'RAG replaces GPUs with hard drives.' },
      { id: 'c', label: 'Fine-tuning is always free and instant.' },
      { id: 'd', label: 'RAG permanently modifies model weights on disk.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_05',
    section: 'automation',
    prompt: 'In a RAG pipeline, what is "chunking strategy" and why does chunk size matter?',
    options: [
      { id: 'a', label: 'Too large chunks dilute semantic relevance with extraneous noise; too small chunks lose context necessary for coherent reasoning.' },
      { id: 'b', label: 'Chunk size determines the color of the output text.' },
      { id: 'c', label: 'Chunking is only used for image files.' },
      { id: 'd', label: 'Every chunk must always be exactly 1 word.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_06',
    section: 'automation',
    prompt: 'How should a builder design a webhook pipeline that triggers an LLM summary when new customer support tickets arrive?',
    options: [
      { id: 'a', label: 'Use an asynchronous queue (e.g. BullMQ, SQS) with retry logic, rate limit throttling, and persistent status logging.' },
      { id: 'b', label: 'Trigger synchronous blocking HTTP requests directly in the main UI thread.' },
      { id: 'c', label: 'Poll the database every 1 millisecond in a busy-wait loop.' },
      { id: 'd', label: 'Print the ticket to paper and scan it back in.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_07',
    section: 'automation',
    prompt: 'What is the role of an "Evaluator/Critic" prompt node in an automated content generation pipeline?',
    options: [
      { id: 'a', label: 'Independently inspects generated artifacts against a predefined rubric (tone, accuracy, forbidden words) before publishing or proceeding.' },
      { id: 'b', label: 'Complains about the code without offering solutions.' },
      { id: 'c', label: 'Deletes all user accounts.' },
      { id: 'd', label: 'Slows down generation by 10 hours.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_08',
    section: 'automation',
    prompt: 'When building automated batch workflows processing 10,000 documents, how should rate limits (TPM / RPM) be handled?',
    options: [
      { id: 'a', label: 'Implement token-bucket or leaky-bucket rate limiting with exponential backoff and jitter on HTTP 429 status codes.' },
      { id: 'b', label: 'Send all 10,000 requests simultaneously in 1 millisecond.' },
      { id: 'c', label: 'Ignore rate limit errors and drop failed documents.' },
      { id: 'd', label: 'Shut down the company servers.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_09',
    section: 'automation',
    prompt: 'What is "semantic routing" in workflow automation?',
    options: [
      { id: 'a', label: 'Computing vector embedding similarity between user input and predefined intent anchors to dynamically trigger specialized sub-flows.' },
      { id: 'b', label: 'Routing internet traffic across physical routers.' },
      { id: 'c', label: 'Grammar checking in Microsoft Word.' },
      { id: 'd', label: 'Randomly assigning tasks to different employees.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_10',
    section: 'automation',
    prompt: 'Why should automated AI workflows include a "human-in-the-loop" (HITL) approval step for high-stakes actions (e.g. sending payments, deleting files)?',
    options: [
      { id: 'a', label: 'Probabilistic models can fail unexpectedly; critical state mutations must require explicit human verification to prevent irreversible harm.' },
      { id: 'b', label: 'Because robots are legally barred from typing.' },
      { id: 'c', label: 'To make the process as slow as possible.' },
      { id: 'd', label: 'HITL is only used for entertainment apps.' },
    ],
    correctOptionId: 'a',
  },

  // Section: Data Privacy & Ethics (10 questions)
  {
    id: 'bld_priv_01',
    section: 'privacy',
    prompt: 'What is a "Prompt Injection" attack (direct vs indirect)?',
    options: [
      { id: 'a', label: 'Direct: user input overrides system instructions; Indirect: untrusted third-party data (webpage, email) contains malicious instructions executed by the LLM.' },
      { id: 'b', label: 'SQL database corruption from an unescaped string.' },
      { id: 'c', label: 'Physical injection of malware into a USB port.' },
      { id: 'd', label: 'A model running out of memory.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_02',
    section: 'privacy',
    prompt: 'How can a builder mitigate indirect prompt injection when an agent reads incoming user emails or web pages?',
    options: [
      { id: 'a', label: 'Isolate untrusted data within strict XML tags (e.g. <untrusted_data>), instruct model to treat content solely as passive text, and restrict agent tool privileges.' },
      { id: 'b', label: 'Trust all emails blindly as system instructions.' },
      { id: 'c', label: 'Execute any shell commands found in email text immediately.' },
      { id: 'd', label: 'Delete the agent after reading one email.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_03',
    section: 'privacy',
    prompt: 'When building a RAG system over proprietary enterprise documents, how is "access control / ACL enforcement" properly implemented?',
    options: [
      { id: 'a', label: 'Filter vector search queries with tenant and user permission metadata so the model only retrieves documents the active user is authorized to read.' },
      { id: 'b', label: 'Rely on the LLM to remember which employee is allowed to see which file.' },
      { id: 'c', label: 'Give every employee access to the entire company database.' },
      { id: 'd', label: 'Put passwords in plaintext inside the system prompt.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_04',
    section: 'privacy',
    prompt: 'What is "Data Poisoning" in the context of custom RAG knowledge bases or fine-tuning datasets?',
    options: [
      { id: 'a', label: 'An adversary injects subtly corrupted, biased, or backdoor-laden documents into the retrieval corpus to manipulate future model outputs.' },
      { id: 'b', label: 'Spilling liquid on a server rack.' },
      { id: 'c', label: 'Deleting empty text files.' },
      { id: 'd', label: 'Upgrading the database version.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_05',
    section: 'privacy',
    prompt: 'Why must API keys for AI providers NEVER be embedded in client-side mobile or frontend browser code?',
    options: [
      { id: 'a', label: 'Anyone can inspect client bundles, extract the secret key, drain API balances, and access unauthorized company endpoints.' },
      { id: 'b', label: 'Browser JavaScript cannot send network requests.' },
      { id: 'c', label: 'API keys expire every 5 seconds on the frontend.' },
      { id: 'd', label: 'Frontend code does not support strings.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_06',
    section: 'privacy',
    prompt: 'What is the "Principle of Least Privilege" applied to AI tool / function calling capabilities?',
    options: [
      { id: 'a', label: 'Only grant the agent access to the minimal set of specific API tools, read-only permissions, and restricted scopes required for its task.' },
      { id: 'b', label: 'Give the agent root administrator access to all servers.' },
      { id: 'c', label: 'Forbid the agent from using any tools.' },
      { id: 'd', label: 'Allow the agent to delete production databases at will.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_07',
    section: 'privacy',
    prompt: 'How should sensitive personally identifiable information (PII) logs be handled in production AI observability platforms?',
    options: [
      { id: 'a', label: 'Scrub and mask PII fields before persisting traces/logs, enforce strict retention TTLs, and restrict log access via RBAC.' },
      { id: 'b', label: 'Post raw prompt logs to public Slack channels.' },
      { id: 'c', label: 'Store all logs unencrypted on public web servers.' },
      { id: 'd', label: 'Never log any errors.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_08',
    section: 'privacy',
    prompt: 'What is "membership inference attack" in machine learning?',
    options: [
      { id: 'a', label: 'An attacker queries a model to determine whether a specific individual\'s private data was part of the model\'s training dataset.' },
      { id: 'b', label: 'Joining a gym without paying membership fees.' },
      { id: 'c', label: 'Guessing a user\'s Wi-Fi password.' },
      { id: 'd', label: 'Inviting a bot to a Slack channel.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_09',
    section: 'privacy',
    prompt: 'When building AI features in healthcare applications, which compliance framework is mandatory in the United States?',
    options: [
      { id: 'a', label: 'HIPAA (with signed Business Associate Agreements ensuring encrypted, non-retained Protected Health Information handling).' },
      { id: 'b', label: 'DMCA.' },
      { id: 'c', label: 'PCI-DSS.' },
      { id: 'd', label: 'OSHA.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_10',
    section: 'privacy',
    prompt: 'What is the ethical responsibility of an engineer building automated decision-making pipelines that affect human livelihoods (e.g. credit, jobs)?',
    options: [
      { id: 'a', label: 'Ensure explainability, auditable decision logs, bias testing across demographic subgroups, and appeal mechanisms with human review.' },
      { id: 'b', label: 'Maximize automation speed regardless of error rate.' },
      { id: 'c', label: 'Hide that an algorithm made the decision.' },
      { id: 'd', label: 'Delete all logs immediately after scoring.' },
    ],
    correctOptionId: 'a',
  },

  // Section: Growth & Problem Solving (10 questions)
  {
    id: 'bld_gro_01',
    section: 'growth',
    prompt: 'When deciding whether to build a feature using LLM prompting vs deterministic code (regex, SQL, algorithms), what is the builder\'s primary rule?',
    options: [
      { id: 'a', label: 'Use deterministic code whenever mathematical precision, 100% predictability, or high-throughput low-latency is required; use LLMs for unstructured reasoning, extraction, and synthesis.' },
      { id: 'b', label: 'Always use LLMs for everything, including basic addition.' },
      { id: 'c', label: 'Never use LLMs for any software feature.' },
      { id: 'd', label: 'Flip a coin.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_02',
    section: 'growth',
    prompt: 'What is "synthetic data generation" and how can a builder use it to evaluate edge cases?',
    options: [
      { id: 'a', label: 'Using an LLM to generate diverse, realistic user prompts, adversarial attacks, and edge-case inputs to test the robustness of a production application.' },
      { id: 'b', label: 'Writing fake reviews to boost app store rankings.' },
      { id: 'c', label: 'Generating random binary garbage.' },
      { id: 'd', label: 'Faking database uptime statistics.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_03',
    section: 'growth',
    prompt: 'How does a builder calculate the Unit Economics (Cost per Transaction) of an AI pipeline?',
    options: [
      { id: 'a', label: 'Sum of input/output token costs + vector search infrastructure + compute hosting + fallback latency overhead per user workflow run.' },
      { id: 'b', label: 'The price of the laptop used by the engineer.' },
      { id: 'c', label: 'Dividing total revenue by 2.' },
      { id: 'd', label: 'Token costs are always zero.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_04',
    section: 'growth',
    prompt: 'What is "model cascading" or "tiered routing" in cost/latency optimization?',
    options: [
      { id: 'a', label: 'Using a small, fast, low-cost model (e.g. Flash/Haiku) for 80% of simple tasks, cascading to a large frontier model (e.g. Pro/Opus) only for complex reasoning.' },
      { id: 'b', label: 'Stacking physical servers vertically.' },
      { id: 'c', label: 'Running the same prompt on 100 models simultaneously.' },
      { id: 'd', label: 'Shutting down servers during lunch hours.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_05',
    section: 'growth',
    prompt: 'In LLM evaluation frameworks (e.g. Ragas, DeepEval), what does "faithfulness" measure?',
    options: [
      { id: 'a', label: 'The degree to which the generated answer is strictly supported by the retrieved context documents, without ungrounded factual hallucinations.' },
      { id: 'b', label: 'How polite the model sounds.' },
      { id: 'c', label: 'The length of the response.' },
      { id: 'd', label: 'The user\'s loyalty to the brand.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_06',
    section: 'growth',
    prompt: 'What is the primary trade-off when increasing temperature from 0.0 to 0.9 in an enterprise extraction pipeline?',
    options: [
      { id: 'a', label: 'Higher temperature increases output variance and hallucination likelihood, making strict schema extraction unreliable.' },
      { id: 'b', label: 'Higher temperature makes the server run hotter.' },
      { id: 'c', label: 'Higher temperature reduces token costs.' },
      { id: 'd', label: 'Higher temperature makes responses instantaneous.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_07',
    section: 'growth',
    prompt: 'How should a builder design a telemetry dashboard for monitoring a production LLM feature?',
    options: [
      { id: 'a', label: 'Track token usage, p50/p95/p99 latency, cost per user, schema parse failure rates, and user thumbs-up/down feedback.' },
      { id: 'b', label: 'Only monitor server power cords.' },
      { id: 'c', label: 'Count the total number of lines of code in the repository.' },
      { id: 'd', label: 'Check the dashboard once a year.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_08',
    section: 'growth',
    prompt: 'What is "A/B prompt testing" in production environments?',
    options: [
      { id: 'a', label: 'Splitting live user traffic between Prompt Variant A and Prompt Variant B to compare quantitative conversion, latency, and quality metrics.' },
      { id: 'b', label: 'Testing prompts in alphabetical order.' },
      { id: 'c', label: 'Testing only on Tuesdays.' },
      { id: 'd', label: 'Asking two friends which prompt looks cooler.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_09',
    section: 'growth',
    prompt: 'When fine-tuning a small open-weight model vs using prompt engineering with a frontier model, what is the key decision factor?',
    options: [
      { id: 'a', label: 'Fine-tuning excels at specialized formatting, latency/cost reduction, and privacy air-gaps; prompt engineering excels at broad reasoning, agility, and zero training overhead.' },
      { id: 'b', label: 'Fine-tuning is always cheaper and easier than prompt engineering.' },
      { id: 'c', label: 'Prompt engineering is only for non-engineers.' },
      { id: 'd', label: 'Open-weight models cannot read English.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_10',
    section: 'growth',
    prompt: 'What is the hallmark of a true Jnachi Builder?',
    options: [
      { id: 'a', label: 'The ability to design resilient, production-ready AI workflows from scratch, seamlessly connecting tools, managing state, and mitigating edge-case failures.' },
      { id: 'b', label: 'Copy-pasting generic ChatGPT answers into Slack.' },
      { id: 'c', label: 'Bragging about AI without building anything.' },
      { id: 'd', label: 'Memorizing prompt engineering slogans.' },
    ],
    correctOptionId: 'a',
  },
];

// =========================================================================
// JNACHI MASTER (ARCHITECT) QUESTION BANK (40 Strategic, Governance & Judgment Questions)
// Focus: Knowing when NOT to use AI, governance, model auditing, system trade-offs, mentoring
// =========================================================================
export const MASTER_QUESTIONS: CertQuestion[] = [
  // Section: Literacy & Prompting (10 questions)
  {
    id: 'mstr_lit_01',
    section: 'literacy',
    prompt: 'Under what conditions should an AI Architect advise an enterprise team to EXPLICITLY NOT use a generative AI model for a software feature?',
    options: [
      { id: 'a', label: 'When the problem requires deterministic 100% mathematical precision, has strict legal liability for any non-auditable error, and can be solved by classic algorithms or database queries.' },
      { id: 'b', label: 'Whenever the company has a large budget.' },
      { id: 'c', label: 'Only when the internet is disconnected.' },
      { id: 'd', label: 'Generative AI should be used for 100% of all software features without exception.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_02',
    section: 'literacy',
    prompt: 'What is "model collapse" in synthetic AI training loops?',
    options: [
      { id: 'a', label: 'Degeneration in model output diversity and accuracy when future generations of models are recursively trained on synthetic data produced by earlier models without sufficient human ground truth.' },
      { id: 'b', label: 'Physical server racks falling over.' },
      { id: 'c', label: 'A GPU overheating during backpropagation.' },
      { id: 'd', label: 'A sudden drop in stock price.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_03',
    section: 'literacy',
    prompt: 'How should an AI Architect design an automated auditing framework for detecting subtle semantic drift in mission-critical prompts?',
    options: [
      { id: 'a', label: 'Continuous shadow evaluation: run a golden test dataset through production prompts daily, asserting semantic similarity against canonical embeddings and statistical variance thresholds.' },
      { id: 'b', label: 'Wait for customers to file lawsuit claims.' },
      { id: 'c', label: 'Check prompt text visually once every two years.' },
      { id: 'd', label: 'Assume prompts never drift if model name is unchanged.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_04',
    section: 'literacy',
    prompt: 'What is the risk of "cognitive offloading" when engineering teams rely excessively on automated AI generation without critical code reviews?',
    options: [
      { id: 'a', label: 'Erosion of deep domain understanding, inability to debug subtle architectural flaws, and accumulation of fragile technical debt.' },
      { id: 'b', label: 'Engineers type too quickly.' },
      { id: 'c', label: 'The code takes up less disk space.' },
      { id: 'd', label: 'Computers become self-aware.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_05',
    section: 'literacy',
    prompt: 'In prompt security, what is "jailbreaking via token smuggling / base64 obfuscation"?',
    options: [
      { id: 'a', label: 'Adversaries encode harmful payloads into alternative formats (Base64, rot13, foreign languages) to bypass shallow string-matching safety filters during input ingestion.' },
      { id: 'b', label: 'Physical theft of computer hardware.' },
      { id: 'c', label: 'Smuggling physical tokens through airport security.' },
      { id: 'd', label: 'Deleting cookies from a web browser.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_06',
    section: 'literacy',
    prompt: 'How should an Architect mentor junior engineers who treat LLM outputs as infallible ground truth?',
    options: [
      { id: 'a', label: 'Establish a "Zero Trust" verification protocol: require evidence citations, cross-verification with deterministic tests, and rigorous edge-case exploration.' },
      { id: 'b', label: 'Forbid them from ever using computers.' },
      { id: 'c', label: 'Agree with them that LLMs are always right.' },
      { id: 'd', label: 'Ignore the problem.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_07',
    section: 'literacy',
    prompt: 'What is the difference between "epistemic uncertainty" (lack of knowledge) and "aleatoric uncertainty" (inherent randomness) in LLM evaluations?',
    options: [
      { id: 'a', label: 'Epistemic uncertainty can be reduced by providing relevant retrieved context; aleatoric uncertainty stems from probabilistic token generation across valid alternative phrasings.' },
      { id: 'b', label: 'They are identical medical terms.' },
      { id: 'c', label: 'Aleatoric uncertainty is solved by buying more RAM.' },
      { id: 'd', label: 'Epistemic uncertainty only occurs in Python.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_08',
    section: 'literacy',
    prompt: 'When evaluating multi-billion parameter frontier models vs compact edge models, what architectural trade-off governs the decision?',
    options: [
      { id: 'a', label: 'Frontier models provide supreme generalized reasoning and world knowledge; compact models offer low latency, deterministic throughput, on-prem privacy, and predictable unit cost.' },
      { id: 'b', label: 'Compact models are always superior for all tasks.' },
      { id: 'c', label: 'Frontier models cannot run in the cloud.' },
      { id: 'd', label: 'Compact models do not consume electricity.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_09',
    section: 'literacy',
    prompt: 'What constitutes an effective "Red Teaming" exercise for an enterprise customer-facing AI agent?',
    options: [
      { id: 'a', label: 'Adversarial human and automated testing designed to probe for prompt injections, data extraction, toxic outputs, competitor endorsement, and safety boundary violations.' },
      { id: 'b', label: 'Painting the server room walls red.' },
      { id: 'c', label: 'Testing the app with only friendly questions.' },
      { id: 'd', label: 'Sending the agent to a conference.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_lit_10',
    section: 'literacy',
    prompt: 'How does an Architect establish a formal "AI Style & Ethics Guide" for an organization?',
    options: [
      { id: 'a', label: 'Define brand voice parameters, mandatory citation rules, safety guardrails, copyright attribution protocols, and clear escalation paths for ambiguous outputs.' },
      { id: 'b', label: 'Copy-paste a generic template from the internet and never review it.' },
      { id: 'c', label: 'Let each individual employee do whatever they want with no oversight.' },
      { id: 'd', label: 'Forbid all employees from writing emails.' },
    ],
    correctOptionId: 'a',
  },

  // Section: Workflow Automation (10 questions)
  {
    id: 'mstr_auto_01',
    section: 'automation',
    prompt: 'In high-scale enterprise systems, what is the risk of "cascading AI failures" across deeply interconnected agent microservices?',
    options: [
      { id: 'a', label: 'An early agent\'s undetected hallucination or format mutation propagates through downstream automated tools, causing systemic data corruption or unintended transactions.' },
      { id: 'b', label: 'The office lights flickering.' },
      { id: 'c', label: 'Servers running out of paper.' },
      { id: 'd', label: 'All employees forgetting their passwords.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_02',
    section: 'automation',
    prompt: 'How should an AI Architect implement "Circuit Breakers" in autonomous multi-agent pipelines?',
    options: [
      { id: 'a', label: 'Automatic kill-switches that halt agent execution and alert human operators when anomaly thresholds (e.g. error rate > 5%, cost spike > $50/min, unexpected API loop) are triggered.' },
      { id: 'b', label: 'Physical fuse boxes in the office kitchen.' },
      { id: 'c', label: 'Deleting the codebase whenever an error occurs.' },
      { id: 'd', label: 'Turning off the building Wi-Fi.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_03',
    section: 'automation',
    prompt: 'What is "vendor lock-in mitigation" in enterprise AI infrastructure?',
    options: [
      { id: 'a', label: 'Abstracting model interactions behind a unified API interface layer (e.g. LiteLLM, LangChain/LlamaIndex providers) to allow swapping underlying model providers without rewriting business logic.' },
      { id: 'b', label: 'Signing 10-year exclusive contracts with a single vendor.' },
      { id: 'c', label: 'Never using any third-party software.' },
      { id: 'd', label: 'Locking server room doors with physical keys.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_04',
    section: 'automation',
    prompt: 'When evaluating the total cost of ownership (TCO) between building custom agent pipelines in-house vs buying a commercial SaaS AI platform, what factors matter most?',
    options: [
      { id: 'a', label: 'Maintenance overhead, integration complexity with core systems, proprietary data security, speed-to-market, and long-term differentiation vs commodity functionality.' },
      { id: 'b', label: 'Only the monthly software subscription fee on the invoice.' },
      { id: 'c', label: 'Whichever sales team gives the best free swag.' },
      { id: 'd', label: 'The number of slides in the vendor pitch deck.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_05',
    section: 'automation',
    prompt: 'How should an organization manage "Prompt Versioning & CI/CD" across distributed product teams?',
    options: [
      { id: 'a', label: 'Treat prompts as version-controlled code artifacts (Git), run automated regression evaluations in CI pipelines before deployment, and support instant rollbacks.' },
      { id: 'b', label: 'Edit production prompts directly in web console textareas without testing.' },
      { id: 'c', label: 'Store prompts in temporary chat windows.' },
      { id: 'd', label: 'Never update prompts once created.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_06',
    section: 'automation',
    prompt: 'What is the role of "Shadow Deployment" when introducing a major prompt or model upgrade in production?',
    options: [
      { id: 'a', label: 'Route real user traffic in parallel to the new model variant silently in the background, comparing its performance/latency against production without affecting live users.' },
      { id: 'b', label: 'Deploying software at midnight during a solar eclipse.' },
      { id: 'c', label: 'Hiding software releases from company executives.' },
      { id: 'd', label: 'Running servers in a dark room.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_07',
    section: 'automation',
    prompt: 'How does an Architect prevent "Context Window Bloat" from destroying pipeline economics in multi-turn customer sessions?',
    options: [
      { id: 'a', label: 'Implement structured hierarchical state compression: maintain a rolling high-density summary and key entity ledger rather than passing the raw transcript forever.' },
      { id: 'b', label: 'Cut off customer chats after 3 messages.' },
      { id: 'c', label: 'Ask the customer to pay per token in real-time.' },
      { id: 'd', label: 'Ignore token costs.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_08',
    section: 'automation',
    prompt: 'What is the primary operational challenge of running local on-premise open-weight LLM clusters compared to managed cloud APIs?',
    options: [
      { id: 'a', label: 'High upfront hardware capital expenditure, complex GPU driver/vLLM orchestration, scaling bottlenecks during traffic spikes, and ongoing maintenance overhead.' },
      { id: 'b', label: 'On-premise servers cannot connect to electricity.' },
      { id: 'c', label: 'Cloud APIs never experience outages.' },
      { id: 'd', label: 'Open-weight models cannot run on Linux.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_09',
    section: 'automation',
    prompt: 'In an autonomous agent architecture, why should tool execution logs be cryptographically signed or immutable?',
    options: [
      { id: 'a', label: 'Provides non-repudiable audit trails for compliance, security forensics, and legal accountability if an agent executes an unauthorized or erroneous state change.' },
      { id: 'b', label: 'Makes the log files look more colorful.' },
      { id: 'c', label: 'Compacts the log size by 99%.' },
      { id: 'd', label: 'Enables real-time video playback of the logs.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_auto_10',
    section: 'automation',
    prompt: 'What is the primary indicator that an automated AI pipeline is ready for full production scale?',
    options: [
      { id: 'a', label: 'Consistent passing of automated regression evals, bounded worst-case latency/cost, graceful error fallbacks, and validated guardrails under peak synthetic loads.' },
      { id: 'b', label: 'It worked once without errors in a demo.' },
      { id: 'c', label: 'The marketing team published a press release.' },
      { id: 'd', label: 'The CEO liked the presentation.' },
    ],
    correctOptionId: 'a',
  },

  // Section: Data Privacy & Ethics (10 questions)
  {
    id: 'mstr_priv_01',
    section: 'privacy',
    prompt: 'Under emerging global AI regulations (e.g. EU AI Act), what category of AI systems carries mandatory conformity assessments and fundamental rights impact assessments?',
    options: [
      { id: 'a', label: 'High-Risk AI systems (e.g. critical infrastructure, education scoring, employment recruitment, essential public services, law enforcement).' },
      { id: 'b', label: 'Casual video game chatbots.' },
      { id: 'c', label: 'Personal todo-list apps.' },
      { id: 'd', label: 'Weather forecast widgets.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_02',
    section: 'privacy',
    prompt: 'What is "differential privacy" in AI model training and data aggregation?',
    options: [
      { id: 'a', label: 'A mathematical framework introducing calibrated statistical noise to ensure individual records cannot be reverse-engineered or inferred from aggregate outputs.' },
      { id: 'b', label: 'Keeping private data in a different folder.' },
      { id: 'c', label: 'Encrypting files with two passwords.' },
      { id: 'd', label: 'Only sharing data with different people.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_03',
    section: 'privacy',
    prompt: 'How should an AI Architect handle the "Right to be Forgotten" (GDPR Article 17) if personal data was accidentally included in a model\'s fine-tuning weights?',
    options: [
      { id: 'a', label: 'Recognize that parameter extraction/unlearning is notoriously difficult; retrain the model from clean data checkpoints or implement strict output filter guardrails.' },
      { id: 'b', label: 'Tell the user that AI models cannot forget anything and ignore the request.' },
      { id: 'c', label: 'Delete the user\'s email address from the newsletter list.' },
      { id: 'd', label: 'Restart the web server.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_04',
    section: 'privacy',
    prompt: 'What constitutes an "Adversarial Extraction / Model Inversion" attack?',
    options: [
      { id: 'a', label: 'Carefully crafted querying sequences designed to reconstruct training data, proprietary system prompts, or hidden fine-tuning details from model output probabilities.' },
      { id: 'b', label: 'Physically stealing hard drives from a data center.' },
      { id: 'c', label: 'Inverting the monitor colors.' },
      { id: 'd', label: 'Downloading a public open-source model.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_05',
    section: 'privacy',
    prompt: 'When establishing an internal "AI Governance Board", who are the essential stakeholders?',
    options: [
      { id: 'a', label: 'Cross-functional representatives: AI Engineering Leads, Legal/Compliance Counsel, Data Security Officers, Product Managers, and Domain Ethics Specialists.' },
      { id: 'b', label: 'Only the marketing department.' },
      { id: 'c', label: 'Only external consultants with no internal knowledge.' },
      { id: 'd', label: 'A single junior developer.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_06',
    section: 'privacy',
    prompt: 'What is the risk of "Automation Bias" in professional decision-makers (doctors, underwriters, judges)?',
    options: [
      { id: 'a', label: 'Humans uncritically deferring to automated AI recommendations and ignoring contradictory real-world evidence or clinical intuition.' },
      { id: 'b', label: 'Humans refusing to use any automated tools.' },
      { id: 'c', label: 'Automated machines breaking down frequently.' },
      { id: 'd', label: 'Software updates taking too long.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_07',
    section: 'privacy',
    prompt: 'How should an organization protect its proprietary trade secrets when deploying customized AI tools across global teams?',
    options: [
      { id: 'a', label: 'Enforce enterprise Zero Data Retention agreements, strict IAM role-based prompt access, client-side data masking, and network egress firewalls.' },
      { id: 'b', label: 'Trust all employees not to share company secrets.' },
      { id: 'c', label: 'Store trade secrets on public pastebins.' },
      { id: 'd', label: 'Forbid international employees from using company computers.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_08',
    section: 'privacy',
    prompt: 'What is the ethical responsibility of an AI leader when a deployed AI feature exhibits disparate impact or demographic bias in production?',
    options: [
      { id: 'a', label: 'Immediately halt or throttle the affected pipeline, conduct transparent root-cause analysis, remediate data imbalance, and publish corrective audit findings.' },
      { id: 'b', label: 'Cover up the issue and delete customer feedback.' },
      { id: 'c', label: 'Blame the third-party AI vendor publicly without investigating.' },
      { id: 'd', label: 'Ignore the problem until legally forced.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_09',
    section: 'privacy',
    prompt: 'What is "Watermarking" for AI-generated multimedia and text, and what are its current technological limits?',
    options: [
      { id: 'a', label: 'Embedding statistical or visual signatures into outputs; effective for provenance tracking but susceptible to removal via re-encoding, paraphrasing, or editing.' },
      { id: 'b', label: 'Dipping computers in water.' },
      { id: 'c', label: 'A 100% unbreakable cryptographic lock on all words.' },
      { id: 'd', label: 'Only used for PDF documents.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_priv_10',
    section: 'privacy',
    prompt: 'How should an enterprise AI strategy balance rapid innovation with ethical stewardship?',
    options: [
      { id: 'a', label: 'By building guardrails into the software development lifecycle, establishing transparent review gates, and fostering an organizational culture of accountable experimentation.' },
      { id: 'b', label: 'By halting all technology adoption permanently.' },
      { id: 'c', label: 'By deploying unvetted experimental models directly into production with zero safeguards.' },
      { id: 'd', label: 'By delegating all ethical decisions to an AI chatbot.' },
    ],
    correctOptionId: 'a',
  },

  // Section: Growth & Problem Solving (10 questions)
  {
    id: 'mstr_gro_01',
    section: 'growth',
    prompt: 'What is the ultimate responsibility of a Jnachi Master (Architect) within an organization or community?',
    options: [
      { id: 'a', label: 'To lead with critical judgment—elevating team AI literacy, championing ethical and robust architectures, knowing when NOT to use AI, and unlocking sustainable human-AI momentum.' },
      { id: 'b', label: 'To replace all human coworkers with AI agents.' },
      { id: 'c', label: 'To memorize the most prompt keywords.' },
      { id: 'd', label: 'To write the longest prompts possible.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_02',
    section: 'growth',
    prompt: 'How should an AI Architect design an ongoing continuous learning culture in a fast-evolving AI landscape?',
    options: [
      { id: 'a', label: 'Establish weekly practical hackathons, empirical benchmark reviews of new model capabilities, shared prompt repository audits, and cross-team knowledge sharing.' },
      { id: 'b', label: 'Require everyone to read 10-year-old textbooks.' },
      { id: 'c', label: 'Ban all internal discussion about new technologies.' },
      { id: 'd', label: 'Rely solely on annual vendor webinars.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_03',
    section: 'growth',
    prompt: 'When an executive asks: "Can we replace our entire customer support staff with an LLM by next month?", what is the Master Architect\'s response?',
    options: [
      { id: 'a', label: 'Provide an evidence-based roadmap: start with human-in-the-loop agent copilot tooling, measure deflection vs escalation accuracy, establish guardrails, and scale incrementally based on data.' },
      { id: 'b', label: '"Yes, let\'s fire everyone tomorrow without testing."' },
      { id: 'c', label: '"No, AI will never be able to assist in customer support."' },
      { id: 'd', label: '"Let\'s buy 1,000 servers first."' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_04',
    section: 'growth',
    prompt: 'How does an Architect evaluate whether an AI feature delivers genuine ROI vs superficial novelty?',
    options: [
      { id: 'a', label: 'Measure concrete business metrics: task completion velocity, error reduction rate, cost per resolved transaction, and net user satisfaction against the total operational expenditure.' },
      { id: 'b', label: 'Check if the feature received likes on social media.' },
      { id: 'c', label: 'Assume all AI features are automatically profitable.' },
      { id: 'd', label: 'Count how many AI buzzwords are in the product description.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_05',
    section: 'growth',
    prompt: 'What is "model calibration drift" and how does an Architect detect it before it affects customers?',
    options: [
      { id: 'a', label: 'When the statistical distribution of real-world inputs shifts away from the validation dataset, causing confidence scores and accuracy to decouple; detected via continuous distribution monitoring.' },
      { id: 'b', label: 'When a model runs out of battery power.' },
      { id: 'c', label: 'When keyboard keys become sticky.' },
      { id: 'd', label: 'When server fans slow down.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_06',
    section: 'growth',
    prompt: 'In high-reliability organizations, what is the concept of "Graceful Degradation" for AI systems?',
    options: [
      { id: 'a', label: 'When AI models experience API timeouts or high error rates, the system seamlessly falls back to rule-based heuristics or manual human queues without crashing or losing user state.' },
      { id: 'b', label: 'The screen slowly fading to black.' },
      { id: 'c', label: 'Deleting data gracefully.' },
      { id: 'd', label: 'Displaying an apologetic poem to the user.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_07',
    section: 'growth',
    prompt: 'How should an AI Master handle disagreement among team members regarding which model provider to standardize on?',
    options: [
      { id: 'a', label: 'Conduct an empirical bake-off using the team\'s specific domain test suite, comparing accuracy, latency, cost per 1k tokens, uptime SLA, and contract terms objectively.' },
      { id: 'b', label: 'Pick whichever company has the biggest advertisement billboard.' },
      { id: 'c', label: 'Let the most senior person decide based on personal preference alone.' },
      { id: 'd', label: 'Switch model providers every day at random.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_08',
    section: 'growth',
    prompt: 'Why is "Mentorship and Talent Uplift" a core pillar of the Jnachi Master Architect credential?',
    options: [
      { id: 'a', label: 'True mastery is measured not just by individual skill, but by the ability to systematically elevate organizational capability, instill critical thinking, and build a high-momentum team.' },
      { id: 'b', label: 'To delegate all tedious work to junior developers.' },
      { id: 'c', label: 'To hoard technical knowledge exclusively.' },
      { id: 'd', label: 'To give speeches without ever writing code.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_09',
    section: 'growth',
    prompt: 'What is the relationship between AI capability and human domain expertise?',
    options: [
      { id: 'a', label: 'AI acts as a cognitive lever: the deeper the human\'s domain expertise and critical discernment, the more transformative and effective the AI acceleration becomes.' },
      { id: 'b', label: 'AI eliminates the need for any human domain expertise.' },
      { id: 'c', label: 'Human expertise is a hindrance to AI models.' },
      { id: 'd', label: 'AI models perform best when used by people with zero knowledge.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'mstr_gro_10',
    section: 'growth',
    prompt: 'What is the Jnachi motto that encapsulates the entire 4-tier journey?',
    options: [
      { id: 'a', label: 'Know it. Use it. Prove it.' },
      { id: 'b', label: 'Hype it. Buy it. Forget it.' },
      { id: 'c', label: 'Prompt it. Trust it. Deploy it.' },
      { id: 'd', label: 'Automate everything blindly.' },
    ],
    correctOptionId: 'a',
  },
];
