import { CertQuestion } from '../types';

export const BUILDER_AUTOMATION_QUESTIONS: CertQuestion[] = [
  {
    id: 'bld_auto_01',
    section: 'automation',
    prompt: 'What is the fundamental architectural loop in an autonomous AI Agent (e.g. ReAct framework)?',
    options: [
      { id: 'a', label: 'Thought (Reasoning) -> Action (Tool Call) -> Observation (Tool Output) -> Evaluation -> Loop until termination condition is met.' },
      { id: 'b', label: 'Compile Code -> Drop Database Tables -> Restart Server.' },
      { id: 'c', label: 'Infinite while(true) loop generating ungrounded string tokens.' },
      { id: 'd', label: 'Single zero-shot API call with zero tool evaluation feedback.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_02',
    section: 'automation',
    prompt: 'How do you prevent an AI agent from entering an infinite loop when a tool call repeatedly fails or returns ambiguous errors?',
    options: [
      { id: 'a', label: 'Let the agent run indefinitely until the hosting cloud account exhausts its credits.' },
      { id: 'b', label: 'Disable all error logging and exception handlers.' },
      { id: 'c', label: 'Set API connection timeout to 1 millisecond.' },
      { id: 'd', label: 'Implement hard iteration limits (e.g. max 10 steps), error escalation heuristics, and human-in-the-loop fallback breakpoints.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_auto_03',
    section: 'automation',
    prompt: 'In a multi-agent workflow where Agent A produces code and Agent B reviews it, what is the best strategy for state management?',
    options: [
      { id: 'a', label: 'Pass raw unstructured chat strings back and forth across unbounded message logs.' },
      { id: 'b', label: 'Maintain a centralized structured state object (e.g. state graph) tracking current draft, lint errors, test results, and iteration counts.' },
      { id: 'c', label: 'Store ephemeral state exclusively in short-lived browser session cookies.' },
      { id: 'd', label: 'Erase all prior agent state after each execution turn.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_auto_04',
    section: 'automation',
    prompt: 'What is Retrieval-Augmented Generation (RAG) and why is it preferred over fine-tuning for dynamic corporate knowledge bases?',
    options: [
      { id: 'a', label: 'RAG permanently alters neural network weights on hard disks during inference.' },
      { id: 'b', label: 'Fine-tuning is zero-cost and updates foundation model weights instantaneously.' },
      { id: 'c', label: 'RAG retrieves relevant up-to-date document chunks at query time and injects them into the prompt, allowing instant knowledge updates without expensive retraining.' },
      { id: 'd', label: 'RAG replaces all backend relational databases with vector embeddings exclusively.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_auto_05',
    section: 'automation',
    prompt: 'In a RAG pipeline, what is "chunking strategy" and why does chunk size matter?',
    options: [
      { id: 'a', label: 'Too large chunks dilute semantic relevance with extraneous noise; too small chunks lose context necessary for coherent reasoning.' },
      { id: 'b', label: 'Chunk size controls the physical monitor resolution required to view search results.' },
      { id: 'c', label: 'Chunking is only applicable when indexing compressed image files.' },
      { id: 'd', label: 'Every text chunk must be constrained strictly to exactly 1 single token.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_06',
    section: 'automation',
    prompt: 'How should a builder design a webhook pipeline that triggers an LLM summary when new customer support tickets arrive?',
    options: [
      { id: 'a', label: 'Execute synchronous blocking HTTP queries directly inside the primary client thread.' },
      { id: 'b', label: 'Poll the database in a tight 1ms busy-wait loop without backoff.' },
      { id: 'c', label: 'Print tickets to paper and re-scan them into an OCR pipeline.' },
      { id: 'd', label: 'Use an asynchronous queue (e.g. BullMQ, SQS) with retry logic, rate limit throttling, and persistent status logging.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_auto_07',
    section: 'automation',
    prompt: 'What is the role of an "Evaluator/Critic" prompt node in an automated content generation pipeline?',
    options: [
      { id: 'a', label: 'Deletes user database records when generation latency exceeds 2 seconds.' },
      { id: 'b', label: 'Independently inspects generated artifacts against a predefined rubric (tone, accuracy, forbidden words) before publishing or proceeding.' },
      { id: 'c', label: 'Doubles the temperature parameter on each retry attempt.' },
      { id: 'd', label: 'Sends unverified drafts immediately to public distribution channels.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_auto_08',
    section: 'automation',
    prompt: 'When building automated batch workflows processing 10,000 documents, how should rate limits (TPM / RPM) be handled?',
    options: [
      { id: 'a', label: 'Dispatch all 10,000 requests in parallel within a single millisecond burst.' },
      { id: 'b', label: 'Silently drop failed documents whenever a 429 response is encountered.' },
      { id: 'c', label: 'Implement token-bucket or leaky-bucket rate limiting with exponential backoff and jitter on HTTP 429 status codes.' },
      { id: 'd', label: 'Restart the entire batch pipeline from item #1 upon any rate limit warning.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_auto_09',
    section: 'automation',
    prompt: 'What is "semantic routing" in workflow automation?',
    options: [
      { id: 'a', label: 'Computing vector embedding similarity between user input and predefined intent anchors to dynamically trigger specialized sub-flows.' },
      { id: 'b', label: 'Routing internet packet traffic across physical hardware switches.' },
      { id: 'c', label: 'Conducting spell-checking on user prompts.' },
      { id: 'd', label: 'Randomly dispatching tasks to different workers via round-robin.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_10',
    section: 'automation',
    prompt: 'Why should automated AI workflows include a "human-in-the-loop" (HITL) approval step for high-stakes actions (e.g. sending payments, deleting files)?',
    options: [
      { id: 'a', label: 'Because automated AI agents are legally forbidden from transmitting network packets.' },
      { id: 'b', label: 'To intentionally introduce maximum latency into all operations.' },
      { id: 'c', label: 'HITL approval is only applicable in entertainment applications.' },
      { id: 'd', label: 'Probabilistic models can fail unexpectedly; critical state mutations must require explicit human verification to prevent irreversible harm.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_auto_11',
    section: 'automation',
    prompt: 'In production multi-agent architectures, what is the role of a "Memory Store" (short-term working memory vs long-term episodic memory)?',
    options: [
      { id: 'a', label: 'Short-term memory stores local disk drivers, while long-term memory replaces cloud databases.' },
      { id: 'b', label: 'Short-term memory holds active scratchpad and conversation turns within the prompt context window, while long-term memory persists user preferences and past execution learnings across sessions using vector stores.' },
      { id: 'c', label: 'Long-term memory is strictly prohibited in enterprise AI.' },
      { id: 'd', label: 'Memory stores are only used for recording audio conversations.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_auto_12',
    section: 'automation',
    prompt: 'When building a self-healing web scraper powered by LLM vision and DOM parsing, what is the primary resiliency mechanism?',
    options: [
      { id: 'a', label: 'Hardcoding static CSS selectors that never update.' },
      { id: 'b', label: 'Scraping only websites that have zero JavaScript.' },
      { id: 'c', label: 'When a static DOM selector fails due to a website redesign, the agent captures a clean screenshot and accessibility tree, using vision-language reasoning to dynamically locate the target elements.' },
      { id: 'd', label: 'Deleting the browser cookies after every click.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_auto_13',
    section: 'automation',
    prompt: 'What is "Context Compression" in advanced RAG pipelines before injecting retrieved chunks into the generation prompt?',
    options: [
      { id: 'a', label: 'Converting text files into .ZIP archives.' },
      { id: 'b', label: 'Deleting all consonants from the document.' },
      { id: 'c', label: 'Downscaling PDF images to 8-bit color.' },
      { id: 'd', label: 'Using a small summarizer or cross-encoder model to prune irrelevant sentences from retrieved chunks, maximizing prompt signal-to-noise ratio and staying within token budgets.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_auto_14',
    section: 'automation',
    prompt: 'How should an agentic orchestration framework handle tool parameter validation before invoking external third-party APIs?',
    options: [
      { id: 'a', label: 'Validate generated arguments against a strict Pydantic/Zod schema; if validation fails, reflect the validation error back to the LLM for self-correction without executing the invalid API call.' },
      { id: 'b', label: 'Send the invalid payload to the third-party API and ignore the 400 Bad Request response.' },
      { id: 'c', label: 'Terminate the server cluster immediately.' },
      { id: 'd', label: 'Convert all arguments to empty strings.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_15',
    section: 'automation',
    prompt: 'What is the purpose of "Semantic Caching" (e.g. GPTCache) in high-volume enterprise automation pipelines?',
    options: [
      { id: 'a', label: 'Caching website CSS stylesheets on local browser disks.' },
      { id: 'b', label: 'Storing vector embeddings of previous user queries so semantically identical requests return cached LLM responses without incurring model API latency or token costs.' },
      { id: 'c', label: 'Encrypting prompt strings with AES-256.' },
      { id: 'd', label: 'Automatically clearing server RAM every 10 seconds.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_auto_16',
    section: 'automation',
    prompt: 'In a multi-agent software engineering team (Product Manager Agent -> Developer Agent -> QA Agent), how should testing failures be handled?',
    options: [
      { id: 'a', label: 'Ignore test failures and deploy immediately.' },
      { id: 'b', label: 'Delete the failed test cases from the repository.' },
      { id: 'c', label: 'The QA Agent captures the test failure logs, stack trace, and assertion diff, passing them back to the Developer Agent in a feedback loop with incrementing retry counters.' },
      { id: 'd', label: 'Restart the entire operating system.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_auto_17',
    section: 'automation',
    prompt: 'What is a "Deterministic State Machine" in agentic graph workflows (e.g., LangGraph, StateGraph)?',
    options: [
      { id: 'a', label: 'A mechanical computer built with gears.' },
      { id: 'b', label: 'An unpredictable random number generator.' },
      { id: 'c', label: 'A system where LLMs make every transition without defined boundaries.' },
      { id: 'd', label: 'A structured graph where nodes represent discrete LLM or tool execution steps, and edges define explicit deterministic conditional rules for state transitions.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_auto_18',
    section: 'automation',
    prompt: 'When building an automated document extraction pipeline that handles 50-page PDF contracts, what is the best strategy to prevent context window overflow?',
    options: [
      { id: 'a', label: 'Map-Reduce or hierarchical chunking: process individual pages or sections in parallel extraction passes, then run a synthesis pass to combine structured section outputs.' },
      { id: 'b', label: 'Truncate the PDF after page 2.' },
      { id: 'c', label: 'Remove all tables and numeric figures.' },
      { id: 'd', label: 'Compress the text into an unpunctuated single-line string.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_auto_19',
    section: 'automation',
    prompt: 'What is "Dynamic Tool Filtering" in agents equipped with hundreds of API tools?',
    options: [
      { id: 'a', label: 'Deleting tools permanently when an error occurs.' },
      { id: 'b', label: 'Retrieving and injecting only the top 5-10 most relevant tool definitions into the prompt context based on the current user query embedding, avoiding prompt bloat and tool confusion.' },
      { id: 'c', label: 'Running all 100 tools concurrently on every user message.' },
      { id: 'd', label: 'Converting tool parameters into binary code.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_auto_20',
    section: 'automation',
    prompt: 'Why should enterprise AI automation pipelines include distributed tracing (e.g. OpenTelemetry, Langfuse, Arize Phoenix)?',
    options: [
      { id: 'a', label: 'To increase the length of system documentation.' },
      { id: 'b', label: 'To automatically tweet system uptime to the public.' },
      { id: 'c', label: 'To track exact token costs, latency bottlenecks, tool execution traces, and prompt version regressions across multi-step agent chains in production.' },
      { id: 'd', label: 'To disable logging across the server cluster.' },
    ],
    correctOptionId: 'c',
  },
];

