import { CertQuestion } from '../types';

export const BUILDER_GROWTH_QUESTIONS: CertQuestion[] = [
  {
    id: 'bld_gro_01',
    section: 'growth',
    prompt: 'When deciding whether to build a feature using LLM prompting vs deterministic code (regex, SQL, algorithms), what is the builder\'s primary rule?',
    options: [
      { id: 'a', label: 'Use deterministic code whenever mathematical precision, 100% predictability, or high-throughput low-latency is required; use LLMs for unstructured reasoning, extraction, and synthesis.' },
      { id: 'b', label: 'Always use LLMs for all application logic, including arithmetic and relational filtering.' },
      { id: 'c', label: 'Never integrate LLMs into software features under any circumstances.' },
      { id: 'd', label: 'Use LLMs strictly when latency constraints are under 5 milliseconds.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_02',
    section: 'growth',
    prompt: 'What is "synthetic data generation" and how can a builder use it to evaluate edge cases?',
    options: [
      { id: 'a', label: 'Fabricating user analytics data to inflate system usage metrics.' },
      { id: 'b', label: 'Using an LLM to generate diverse, realistic user prompts, adversarial attacks, and edge-case inputs to test the robustness of a production application.' },
      { id: 'c', label: 'Generating randomized binary noise to fill database storage quotas.' },
      { id: 'd', label: 'Automating marketing reviews for mobile app store rankings.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_gro_03',
    section: 'growth',
    prompt: 'How does a builder calculate the Unit Economics (Cost per Transaction) of an AI pipeline?',
    options: [
      { id: 'a', label: 'The total capital expense of developer workstations divided by user count.' },
      { id: 'b', label: 'Dividing total annual software revenue by API token count.' },
      { id: 'c', label: 'Assuming third-party inference costs remain zero in production.' },
      { id: 'd', label: 'Sum of input/output token costs + vector search infrastructure + compute hosting + fallback latency overhead per user workflow run.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_gro_04',
    section: 'growth',
    prompt: 'What is "model cascading" or "tiered routing" in cost/latency optimization?',
    options: [
      { id: 'a', label: 'Stacking physical servers vertically in the data center to improve cooling.' },
      { id: 'b', label: 'Executing the exact same prompt across 50 models simultaneously.' },
      { id: 'c', label: 'Using a small, fast, low-cost model (e.g. Flash/Haiku) for 80% of simple tasks, cascading to a large frontier model (e.g. Pro/Opus) only for complex reasoning.' },
      { id: 'd', label: 'Throttling server CPU clock rates during non-business hours.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_gro_05',
    section: 'growth',
    prompt: 'In LLM evaluation frameworks (e.g. Ragas, DeepEval), what does "faithfulness" measure?',
    options: [
      { id: 'a', label: 'The degree to which the generated answer is strictly supported by the retrieved context documents, without ungrounded factual hallucinations.' },
      { id: 'b', label: 'The degree of polite and friendly phrasing in model conversational turns.' },
      { id: 'c', label: 'The total number of sentences produced in the final response.' },
      { id: 'd', label: 'The frequency of brand keyword mentions in generated text.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_06',
    section: 'growth',
    prompt: 'What is the primary trade-off when increasing temperature from 0.0 to 0.9 in an enterprise extraction pipeline?',
    options: [
      { id: 'a', label: 'Higher temperature reduces per-token inference billing costs.' },
      { id: 'b', label: 'Higher temperature accelerates inference latency by 50%.' },
      { id: 'c', label: 'Higher temperature forces strict adherence to JSON schemas.' },
      { id: 'd', label: 'Higher temperature increases output variance and hallucination likelihood, making strict schema extraction unreliable.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_gro_07',
    section: 'growth',
    prompt: 'How should a builder design a telemetry dashboard for monitoring a production LLM feature?',
    options: [
      { id: 'a', label: 'Monitor only the total lines of source code in the git repository.' },
      { id: 'b', label: 'Track token usage, p50/p95/p99 latency, cost per user, schema parse failure rates, and user thumbs-up/down feedback.' },
      { id: 'c', label: 'Perform manual visual inspection of raw logs once every quarter.' },
      { id: 'd', label: 'Track only client browser window dimensions.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_gro_08',
    section: 'growth',
    prompt: 'What is "A/B prompt testing" in production environments?',
    options: [
      { id: 'a', label: 'Sorting prompts in alphabetical order before execution.' },
      { id: 'b', label: 'Testing prompt variations exclusively on staging environments once per year.' },
      { id: 'c', label: 'Splitting live user traffic between Prompt Variant A and Prompt Variant B to compare quantitative conversion, latency, and quality metrics.' },
      { id: 'd', label: 'Asking team developers which prompt template has the most aesthetically pleasing typography.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_gro_09',
    section: 'growth',
    prompt: 'When fine-tuning a small open-weight model vs using prompt engineering with a frontier model, what is the key decision factor?',
    options: [
      { id: 'a', label: 'Fine-tuning excels at specialized formatting, latency/cost reduction, and privacy air-gaps; prompt engineering excels at broad reasoning, agility, and zero training overhead.' },
      { id: 'b', label: 'Fine-tuning requires zero training data and zero computational resources.' },
      { id: 'c', label: 'Prompt engineering is only supported on legacy closed-source models.' },
      { id: 'd', label: 'Open-weight models cannot process structured JSON schema declarations.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_10',
    section: 'growth',
    prompt: 'What is the hallmark of a true Jnachi Builder?',
    options: [
      { id: 'a', label: 'Copying raw chatbot snippets into team chat channels without modification.' },
      { id: 'b', label: 'Memorizing marketing prompt buzzwords without writing functional code.' },
      { id: 'c', label: 'Relying exclusively on single-turn manual user interfaces for all enterprise workflows.' },
      { id: 'd', label: 'The ability to design resilient, production-ready AI workflows from scratch, seamlessly connecting tools, managing state, and mitigating edge-case failures.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_gro_11',
    section: 'growth',
    prompt: 'When evaluating RAG retrieval quality using the "Context Recall" metric, what does it quantify?',
    options: [
      { id: 'a', label: 'The speed of vector database memory allocation in milliseconds.' },
      { id: 'b', label: 'The extent to which all the ground-truth information required to answer the query was successfully retrieved in the context chunks.' },
      { id: 'c', label: 'The number of punctuation marks in the original PDF file.' },
      { id: 'd', label: 'The percentage of users who clicked the feedback thumbs-up icon.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_gro_12',
    section: 'growth',
    prompt: 'What is "Prompt Distillation" and how does a builder apply it to reduce operational costs at scale?',
    options: [
      { id: 'a', label: 'Boiling liquid cooling fluid in the server room.' },
      { id: 'b', label: 'Deleting all instructions and leaving only 1 word.' },
      { id: 'c', label: 'Using a high-capability frontier model to generate thousands of golden execution outputs, and fine-tuning an 8B/70B open-weight model on those pairs to achieve comparable domain performance at 90% lower cost and latency.' },
      { id: 'd', label: 'Translating prompts into hexadecimal strings.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_gro_13',
    section: 'growth',
    prompt: 'In continuous CI/CD evaluation for generative AI features, what is a "Golden Evaluation Dataset"?',
    options: [
      { id: 'a', label: 'A database that costs more than $1,000,000 to maintain.' },
      { id: 'b', label: 'A set of random numbers used to test database primary keys.' },
      { id: 'c', label: 'A collection of outdated marketing emails from 2010.' },
      { id: 'd', label: 'A curated, representative benchmark of production queries, ground-truth expected facts, edge cases, and safety probes used to automatically validate model/prompt updates before deployment.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_gro_14',
    section: 'growth',
    prompt: 'When designing multi-model fallback routing for high-availability production apps, how should failovers be structured?',
    options: [
      { id: 'a', label: 'Primary model -> on 5xx error or timeout -> secondary alternative provider model with standardized fallback adapter schema -> on final failure -> graceful cached response or human triage queue.' },
      { id: 'b', label: 'If the primary model times out, crash the entire web server and return HTTP 500 to all visitors.' },
      { id: 'c', label: 'Immediately bill the user twice for a failed request.' },
      { id: 'd', label: 'Silently delete the user\'s inquiry without response.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_15',
    section: 'growth',
    prompt: 'What is the "Context Relevance" metric in RAG evaluation pipelines?',
    options: [
      { id: 'a', label: 'The physical distance between the client computer and the cloud datacenter.' },
      { id: 'b', label: 'The proportion of sentences in the retrieved context that are directly relevant to the user\'s query, penalizing redundant or distracting noise.' },
      { id: 'c', label: 'The number of characters in the user\'s browser URL bar.' },
      { id: 'd', label: 'The total number of images stored in the vector database.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_gro_16',
    section: 'growth',
    prompt: 'Why is "Token Budget Management" essential when designing agents that iterate across dozens of tool execution turns?',
    options: [
      { id: 'a', label: 'Because models crash if they run for more than 10 seconds.' },
      { id: 'b', label: 'Because token counts are capped at 100 words per day.' },
      { id: 'c', label: 'Unbounded context growth degrades reasoning accuracy, increases per-turn latency linearly, and can trigger sudden context overflow exceptions or massive cost spikes.' },
      { id: 'd', label: 'Token budgets only apply to free consumer chat accounts.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_gro_17',
    section: 'growth',
    prompt: 'When building an automated AI coding assistant that submits GitHub pull requests, what guardrail ensures code quality before merging?',
    options: [
      { id: 'a', label: 'Allowing the agent to merge directly to main with `--force` bypasses.' },
      { id: 'b', label: 'Disabling all unit testing suites on agent pull requests.' },
      { id: 'c', label: 'Merging any PR that contains at least 500 lines of code.' },
      { id: 'd', label: 'Mandatory automated CI checks (lint, unit tests, security SAST scans) followed by required human senior engineer code review and approval.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_gro_18',
    section: 'growth',
    prompt: 'What is "Prompt Versioning" and why should prompt templates be treated as code in Git repositories?',
    options: [
      { id: 'a', label: 'Prompts are deterministic software components; storing them with version control enables code reviews, regression testing, rollback capabilities, and traceability across releases.' },
      { id: 'b', label: 'Because Git automatically optimizes English prompt syntax.' },
      { id: 'c', label: 'To hide prompts from other engineers on the team.' },
      { id: 'd', label: 'Because prompts cannot be executed unless committed to Git.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_gro_19',
    section: 'growth',
    prompt: 'How does an engineering team calculate "Cost-per-Success" for an autonomous multi-step agent?',
    options: [
      { id: 'a', label: 'Dividing developer salaries by the number of Git commits.' },
      { id: 'b', label: 'Total API and infrastructure costs incurred across all attempt runs divided by the number of successfully resolved tasks, accounting for failed and retried attempts.' },
      { id: 'c', label: 'Measuring only the token cost of the single final success turn.' },
      { id: 'd', label: 'Assuming all attempts succeed on turn 1.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_gro_20',
    section: 'growth',
    prompt: 'What overarching capability defines a candidate who has earned the Jnachi Builder Certification?',
    options: [
      { id: 'a', label: 'They know how to generate conversational responses in consumer chat tools.' },
      { id: 'b', label: 'They have memorized theoretical machine learning mathematics without writing software.' },
      { id: 'c', label: 'They can independently architect, build, evaluate, and scale production-grade AI systems, multi-agent workflows, and secure automated integrations with rigorous engineering standards.' },
      { id: 'd', label: 'They believe AI agents should operate in production with zero monitoring or human oversight.' },
    ],
    correctOptionId: 'c',
  },
];

