import { CertQuestion } from '../types';

export const BUILDER_LITERACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'bld_lit_01',
    section: 'literacy',
    prompt: 'When configuring structured tool/function calling with LLMs, how does the model select which tool to invoke?',
    options: [
      { id: 'a', label: 'The model analyzes the tool JSON definitions, parameter types, and descriptions, generating structured arguments matching the chosen function signature.' },
      { id: 'b', label: 'It executes random code strings in a sandbox until an execution succeeds.' },
      { id: 'c', label: 'It deterministically picks the function with the shortest identifier name.' },
      { id: 'd', label: 'Tool selection is hardcoded on the client operating system kernel.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_02',
    section: 'literacy',
    prompt: 'Why are detailed docstrings and parameter descriptions essential in function calling declarations?',
    options: [
      { id: 'a', label: 'They reduce the binary file size of the backend microservice.' },
      { id: 'b', label: 'They are strictly required by JavaScript syntax compilers.' },
      { id: 'c', label: 'LLMs rely directly on parameter descriptions as context cues to infer semantics, valid formats (e.g. ISO 8601 dates), and edge case constraints.' },
      { id: 'd', label: 'They permanently cache the function output in memory.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_lit_03',
    section: 'literacy',
    prompt: 'In complex prompt routing architectures, what is the role of a lightweight "Router" or "Classifier" model?',
    options: [
      { id: 'a', label: 'Physical routing of network packets across data center switches.' },
      { id: 'b', label: 'Translating all input prompts into binary assembly code.' },
      { id: 'c', label: 'Deleting expired user authentication tokens from Redis caches.' },
      { id: 'd', label: 'Quickly evaluate incoming user intent and dispatch the query to specialized prompt templates, tools, or domain-specific models with minimal latency/cost.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_lit_04',
    section: 'literacy',
    prompt: 'What is the purpose of system prompt modularization using templating engines (e.g., Mustache, Jinja2)?',
    options: [
      { id: 'a', label: 'Permanently locks model sampling temperature to zero.' },
      { id: 'b', label: 'Allows dynamic composition of system context, user roles, permission scopes, and real-time state variables without hardcoding monolithic prompt strings.' },
      { id: 'c', label: 'Encrypts the prompt string so the model cannot read its instructions.' },
      { id: 'd', label: 'Converts English prompt text into machine bytecode.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_lit_05',
    section: 'literacy',
    prompt: 'When an LLM must extract 20 distinct data entities from noisy OCR receipts, which prompt pattern achieves the lowest hallucination rate?',
    options: [
      { id: 'a', label: 'Two-pass extraction: Pass 1 isolates bounding text snippets for each field; Pass 2 validates snippets into a strict typed schema with confidence scores.' },
      { id: 'b', label: 'Single zero-shot prompt asking for "all data found in the image".' },
      { id: 'c', label: 'High-temperature creative sampling set to 1.8.' },
      { id: 'd', label: 'Prompt instructing the model to extrapolate missing numeric values.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_06',
    section: 'literacy',
    prompt: 'What is "context window pruning" in long-running conversational agent workflows?',
    options: [
      { id: 'a', label: 'Terminating active browser windows every 5 minutes.' },
      { id: 'b', label: 'Truncating all user inputs to a maximum of 10 tokens.' },
      { id: 'c', label: 'Deleting compiled neural network checkpoints from disk.' },
      { id: 'd', label: 'Systematically summarizing older conversation turns or evicting low-relevance tool outputs to preserve token budget for crucial context and instructions.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_lit_07',
    section: 'literacy',
    prompt: 'How does constrained decoding (e.g. grammar-based sampling, JSON schema enforcement) differ from post-hoc JSON validation?',
    options: [
      { id: 'a', label: 'Post-hoc validation completely prevents generation latency overhead.' },
      { id: 'b', label: 'Constrained decoding masks invalid tokens during sampling so invalid syntax is impossible to generate, whereas post-hoc validation only catches errors after completion.' },
      { id: 'c', label: 'Constrained decoding runs exclusively on mobile client browsers.' },
      { id: 'd', label: 'There is no difference in syntax reliability between the two methods.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_lit_08',
    section: 'literacy',
    prompt: 'Why should builders avoid putting excessive, contradictory rules in a single 4,000-word system prompt?',
    options: [
      { id: 'a', label: 'Because LLM context windows are capped at 500 characters.' },
      { id: 'b', label: 'Long prompts cause relational databases to lose index integrity.' },
      { id: 'c', label: 'Rule collisions lead to unpredictable instruction following, degradation of core constraints, and increased latency/token costs.' },
      { id: 'd', label: 'System prompts must be written entirely in uppercase.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_lit_09',
    section: 'literacy',
    prompt: 'What is the role of "few-shot negative examples" in prompt engineering for code generation?',
    options: [
      { id: 'a', label: 'Demonstrating common anti-patterns or insecure implementations alongside corrected code snippets to explicitly teach the model what patterns to avoid.' },
      { id: 'b', label: 'Generating deliberately broken code to test continuous integration failures.' },
      { id: 'c', label: 'Forcing the model to output unstructured plain text without syntax highlighting.' },
      { id: 'd', label: 'Reducing model precision to test fuzzy match parsers.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_10',
    section: 'literacy',
    prompt: 'When building an automated document classification pipeline, what metric is most critical for evaluating class imbalance?',
    options: [
      { id: 'a', label: 'Total word count of the generated response.' },
      { id: 'b', label: 'The file size of the Python script on disk.' },
      { id: 'c', label: 'Overall raw accuracy alone without class breakdown.' },
      { id: 'd', label: 'F1-Score (Precision vs Recall) per category, rather than overall raw accuracy alone.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_lit_11',
    section: 'literacy',
    prompt: 'In multi-agent systems, what is the architectural difference between a "Hierarchical Supervisor" pattern and a "Choreographed Mesh" pattern?',
    options: [
      { id: 'a', label: 'Hierarchical models only support audio inputs, while Mesh models support text.' },
      { id: 'b', label: 'A Hierarchical Supervisor uses a central orchestrator agent to plan, delegate tasks, and synthesize sub-agent outputs, while a Choreographed Mesh allows peer agents to pass state directly based on event triggers.' },
      { id: 'c', label: 'Mesh patterns require no prompt instructions.' },
      { id: 'd', label: 'Hierarchical patterns cannot invoke external APIs.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_lit_12',
    section: 'literacy',
    prompt: 'When fine-tuning vs. prompt-engineering an LLM for structured domain extraction, which factor most strongly justifies fine-tuning?',
    options: [
      { id: 'a', label: 'When you only need to process 5 documents per month.' },
      { id: 'b', label: 'When prompt instructions can be easily modified in plain English.' },
      { id: 'c', label: 'When distilling a specific rigid output style, vocabulary, or task behavior into a smaller, cheaper, lower-latency model across millions of repetitive requests.' },
      { id: 'd', label: 'When the model needs real-time live stock prices.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_lit_13',
    section: 'literacy',
    prompt: 'What is "Prompt Cache Optimization" in modern frontier LLM APIs (e.g. Claude Prompt Caching, Anthropic/OpenAI cached tokens)?',
    options: [
      { id: 'a', label: 'Storing chat history on client hard drives in plaintext.' },
      { id: 'b', label: 'Deleting the model weights from server RAM after each call.' },
      { id: 'c', label: 'Compressing all images into black-and-white thumbnails.' },
      { id: 'd', label: 'Structuring prompts with large static prefixes (system instructions, documents, tools) placed first to enable server-side KV-cache hits, drastically reducing latency and token costs.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_lit_14',
    section: 'literacy',
    prompt: 'What is the primary function of "Semantic Similarity Thresholding" in vector database retrieval pipelines?',
    options: [
      { id: 'a', label: 'Filtering out retrieved context chunks with cosine distance scores below a minimum quality threshold to prevent low-relevance noise from degrading generation.' },
      { id: 'b', label: 'Encrypting vector embeddings before network transmission.' },
      { id: 'c', label: 'Rounding all floating-point numbers to zero.' },
      { id: 'd', label: 'Counting the total number of characters in a PDF.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_15',
    section: 'literacy',
    prompt: 'In agentic workflows, what is the "ReAct" (Reasoning + Acting) loop pattern?',
    options: [
      { id: 'a', label: 'A JavaScript framework for rendering web user interfaces.' },
      { id: 'b', label: 'An iterative loop where the agent generates a thought/reasoning trace, selects and executes an action/tool, observes the result, and decides the next step until the goal is achieved.' },
      { id: 'c', label: 'A method for compressing MP4 video files.' },
      { id: 'd', label: 'A technique for restarting crashed server processes.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_lit_16',
    section: 'literacy',
    prompt: 'Why is "Hypothetical Document Embeddings" (HyDE) used in advanced RAG query expansion?',
    options: [
      { id: 'a', label: 'To delete outdated documents from the index automatically.' },
      { id: 'b', label: 'To generate fake user identities for testing.' },
      { id: 'c', label: 'Generating a hypothetical answer from the LLM first and embedding that synthetic answer to search the vector space, improving semantic alignment with stored document passages.' },
      { id: 'd', label: 'To bypass vector database search entirely.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_lit_17',
    section: 'literacy',
    prompt: 'When building a code generation agent, how do you prevent infinite loops in automated self-debugging execution cycles?',
    options: [
      { id: 'a', label: 'Never allow the agent to inspect error outputs.' },
      { id: 'b', label: 'Only run code on production servers without sandboxes.' },
      { id: 'c', label: 'Disable compiler linters.' },
      { id: 'd', label: 'Implement explicit maximum iteration bounds (e.g., max_retries = 3), state delta checks, and emergency fallback escalation to human developers.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_lit_18',
    section: 'literacy',
    prompt: 'What is the difference between "Dense Retrieval" (vector embeddings) and "Sparse Retrieval" (BM25 / Keyword search)?',
    options: [
      { id: 'a', label: 'Dense retrieval captures semantic meaning and conceptual similarity in vector space, while Sparse retrieval matches exact keyword tokens, making hybrid search ideal.' },
      { id: 'b', label: 'Sparse retrieval requires quantum computers.' },
      { id: 'c', label: 'Dense retrieval only works on spreadsheet tables.' },
      { id: 'd', label: 'There is no difference in capability between the two approaches.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_lit_19',
    section: 'literacy',
    prompt: 'In RAG pipelines, what is "Reciprocal Rank Fusion" (RRF) used for in hybrid search?',
    options: [
      { id: 'a', label: 'Encrypting search indices with private keys.' },
      { id: 'b', label: 'Combining and re-ranking ranked result lists from multiple retrieval systems (e.g. semantic vector search + BM25 keyword search) into a single optimized context list.' },
      { id: 'c', label: 'Deleting low-scoring database records permanently.' },
      { id: 'd', label: 'Measuring server temperature.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_lit_20',
    section: 'literacy',
    prompt: 'When designing tool signatures for autonomous AI agents, why is idempotent API design mandatory for destructive actions (e.g. create_invoice, refund_order)?',
    options: [
      { id: 'a', label: 'Because LLMs do not support JSON arrays.' },
      { id: 'b', label: 'To make API payloads 10x larger.' },
      { id: 'c', label: 'If an agent retries an action due to a network timeout or re-planning step, idempotent design ensures the action executes exactly once without duplicating financial or stateful mutations.' },
      { id: 'd', label: 'To disable user authentication checks.' },
    ],
    correctOptionId: 'c',
  },
];

