import { CertQuestion } from '../types';

export const FINANCE_AI_PRIVACY_QUESTIONS: CertQuestion[] = [
  {
    "id": "fin_priv_01",
    "section": "privacy",
    "prompt": "What constitutes 'Material Non-Public Information' (MNPI) when using AI in investment workflows?",
    "options": [
      {
        "id": "a",
        "label": "Public news articles published on Bloomberg."
      },
      {
        "id": "b",
        "label": "Confidential corporate information (e.g. unannounced earnings, M&A discussions, FDA approvals) that a reasonable investor would consider important in making an investment decision."
      },
      {
        "id": "c",
        "label": "Historical stock prices from 10 years ago."
      },
      {
        "id": "d",
        "label": "Company marketing blog posts."
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "fin_priv_02",
    "section": "privacy",
    "prompt": "Why is uploading unannounced corporate financial results to public consumer LLMs a severe regulatory violation?",
    "options": [
      {
        "id": "a",
        "label": "Transmits MNPI to third-party shared servers where it may be logged, cached, or leaked, violating SEC Rule 10b-5 insider trading regulations and corporate non-disclosure agreements."
      },
      {
        "id": "b",
        "label": "Because consumer LLMs cannot process numbers."
      },
      {
        "id": "c",
        "label": "Because financial files must be sent via postal mail."
      },
      {
        "id": "d",
        "label": "Because consumer LLMs only accept questions under 10 words."
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "fin_priv_03",
    "section": "privacy",
    "prompt": "How does 'SOX 404 (Sarbanes-Oxley Act) Compliance' apply to AI-generated financial reporting spreadsheets?",
    "options": [
      {
        "id": "a",
        "label": "Requires financial reports to be printed on recycled paper."
      },
      {
        "id": "b",
        "label": "Bans all computers from accounting departments."
      },
      {
        "id": "c",
        "label": "Requires CEOs to write financial formulas in handwriting."
      },
      {
        "id": "d",
        "label": "Mandates rigorous internal controls, strict access permissions, version auditing, and human sign-off verification over all financial data pipelines affecting financial statement accuracy."
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "fin_priv_04",
    "section": "privacy",
    "prompt": "What is an 'Information Barrier / Chinese Wall' in financial institution AI infrastructure?",
    "options": [
      {
        "id": "a",
        "label": "A physical brick wall built in the data center."
      },
      {
        "id": "b",
        "label": "A firewall that blocks all traffic from Asia."
      },
      {
        "id": "c",
        "label": "Strict architectural data segregation preventing confidential deal information in Investment Banking from being accessed by Public Market Equity Research or Trading desks."
      },
      {
        "id": "d",
        "label": "A password required to open Excel."
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "fin_priv_05",
    "section": "privacy",
    "prompt": "How must customer Personally Identifiable Financial Information (PIFI) be protected under the Gramm-Leach-Bliley Act (GLBA)?",
    "options": [
      {
        "id": "a",
        "label": "Sharing customer account balances with marketing affiliates freely."
      },
      {
        "id": "b",
        "label": "Enforces administrative, technical, and physical safeguards (encryption in transit/at rest, strict RBAC, data masking) to protect nonpublic personal financial records against unauthorized access."
      },
      {
        "id": "c",
        "label": "Storing customer bank details in unencrypted spreadsheets."
      },
      {
        "id": "d",
        "label": "Posting loan approval lists publicly."
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "fin_priv_06",
    "section": "privacy",
    "prompt": "In FINRA / SEC algorithmic supervision, what audit trail is required for AI-generated investment recommendations?",
    "options": [
      {
        "id": "a",
        "label": "Complete reproducible records of input market data, model version, system prompt, reasoning steps, timestamp, and the supervising licensed professional's review approval."
      },
      {
        "id": "b",
        "label": "Only the total profit or loss generated by the trade."
      },
      {
        "id": "c",
        "label": "Deleting all AI logs after 24 hours."
      },
      {
        "id": "d",
        "label": "A recording of the client's voice."
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "fin_priv_07",
    "section": "privacy",
    "prompt": "What is 'Model Hallucination Liability' in fiduciary wealth management advice?",
    "options": [
      {
        "id": "a",
        "label": "A feature that increases client returns."
      },
      {
        "id": "b",
        "label": "An insurance policy that covers all market losses."
      },
      {
        "id": "c",
        "label": "A computer hardware warranty."
      },
      {
        "id": "d",
        "label": "The legal and regulatory fiduciary liability incurred by an advisory firm if an unvalidated AI tool provides inaccurate tax, legal, or investment advice to clients."
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "fin_priv_08",
    "section": "privacy",
    "prompt": "How should sensitive payroll and executive compensation data be handled in corporate finance AI pipelines?",
    "options": [
      {
        "id": "a",
        "label": "Emailing full unencrypted payroll rosters to all employees."
      },
      {
        "id": "b",
        "label": "Storing compensation data in public vector databases."
      },
      {
        "id": "c",
        "label": "Mask individual employee names with cryptographic salt hashes, aggregate salary data into broad department bands, and restrict access to authorized HR/Finance personnel."
      },
      {
        "id": "d",
        "label": "Deleting all payroll records."
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "fin_priv_09",
    "section": "privacy",
    "prompt": "What is 'Restricted List Screening' in investment firm AI research workflows?",
    "options": [
      {
        "id": "a",
        "label": "Blocking users with low credit scores from using the app."
      },
      {
        "id": "b",
        "label": "Automatically blocking AI systems from generating research notes or trading recommendations on companies currently on the firm's confidential M&A watch list."
      },
      {
        "id": "c",
        "label": "A list of banned stock tickers that no longer exist."
      },
      {
        "id": "d",
        "label": "Restricting AI usage on weekends."
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "fin_priv_10",
    "section": "privacy",
    "prompt": "Under SEC Regulation FD (Fair Disclosure), what risk arises from AI models trained on leaked corporate communications?",
    "options": [
      {
        "id": "a",
        "label": "Trading on selective non-public disclosures before general public dissemination violates Regulation FD, exposing the firm to severe SEC enforcement penalties."
      },
      {
        "id": "b",
        "label": "Regulation FD requires all models to be trained on Twitter data."
      },
      {
        "id": "c",
        "label": "Regulation FD only applies to government agencies."
      },
      {
        "id": "d",
        "label": "There is zero legal risk."
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "fin_priv_11",
    "section": "privacy",
    "prompt": "How does 'Customer Account Number Masking' protect banking transaction logs?",
    "options": [
      {
        "id": "a",
        "label": "Deletes the entire transaction history."
      },
      {
        "id": "b",
        "label": "Replaces account numbers with random credit card numbers."
      },
      {
        "id": "c",
        "label": "Shares account numbers with third-party advertisers."
      },
      {
        "id": "d",
        "label": "Redacts account numbers to the last 4 digits (e.g. `******1234`) before passing transaction descriptions into LLMs for automated spending categorization."
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "fin_priv_12",
    "section": "privacy",
    "prompt": "What is 'Algorithmic Collusion Risk' in AI-powered pricing and valuation systems?",
    "options": [
      {
        "id": "a",
        "label": "When two computers connect to the same Wi-Fi network."
      },
      {
        "id": "b",
        "label": "When an algorithm runs too quickly."
      },
      {
        "id": "c",
        "label": "When autonomous pricing algorithms across competitor firms learn to coordinate tacit price-fixing or margin inflation, triggering antitrust regulatory scrutiny."
      },
      {
        "id": "d",
        "label": "When a database experiences a deadlock."
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "fin_priv_13",
    "section": "privacy",
    "prompt": "In M&A Virtual Data Room (VDR) AI due diligence, what security controls must be enforced?",
    "options": [
      {
        "id": "a",
        "label": "Allowing all employees to download all target company documents freely."
      },
      {
        "id": "b",
        "label": "Strict role-based access, watermarked document viewers, zero data persistence on model provider endpoints, and instantaneous revocation of access upon deal termination."
      },
      {
        "id": "c",
        "label": "Publishing due diligence memos on the public corporate website."
      },
      {
        "id": "d",
        "label": "Disabling user authentication on data rooms."
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "fin_priv_14",
    "section": "privacy",
    "prompt": "How does 'Immutable WORM (Write Once, Read Many) Storage' fulfill SEC Rule 17a-4 recordkeeping?",
    "options": [
      {
        "id": "a",
        "label": "Stores electronic financial records, model outputs, and client communications in tamper-proof, non-rewritable, non-erasable formats for mandatory 3-to-6 year retention periods."
      },
      {
        "id": "b",
        "label": "Stores files on physical rewritable USB thumb drives."
      },
      {
        "id": "c",
        "label": "Deletes all financial records after 30 days."
      },
      {
        "id": "d",
        "label": "Compresses files into encrypted MP4 videos."
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "fin_priv_15",
    "section": "privacy",
    "prompt": "What is 'Fair Lending Compliance Testing' (ECOA / CFPB) in AI credit underwriting models?",
    "options": [
      {
        "id": "a",
        "label": "Approving 100% of all loan applications regardless of creditworthiness."
      },
      {
        "id": "b",
        "label": "Charging all borrowers identical interest rates."
      },
      {
        "id": "c",
        "label": "Disabling credit checks."
      },
      {
        "id": "d",
        "label": "Auditing automated credit decision models to ensure scoring does not produce disparate impact or discriminatory rejection rates across protected demographic classes."
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "fin_priv_16",
    "section": "privacy",
    "prompt": "Why should corporate financial models avoid hardcoded external API URLs in spreadsheet formulas?",
    "options": [
      {
        "id": "a",
        "label": "Because Excel formulas cannot contain text."
      },
      {
        "id": "b",
        "label": "Because URLs increase file sizes by 100x."
      },
      {
        "id": "c",
        "label": "Prevents unauthorized formula-injection data exfiltration attacks where malicious spreadsheets transmit private cell contents to external endpoints upon recalculation."
      },
      {
        "id": "d",
        "label": "Because spreadsheets only work offline."
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "fin_priv_17",
    "section": "privacy",
    "prompt": "What is 'Automated Whistleblower and Fraud Detection Masking'?",
    "options": [
      {
        "id": "a",
        "label": "Deleting all fraud reports immediately."
      },
      {
        "id": "b",
        "label": "Scrubbing identifying metadata, timestamps, and voice/stylometry characteristics from internal fraud report submissions before routing to AI investigation triage."
      },
      {
        "id": "c",
        "label": "Posting whistleblower names on company bulletin boards."
      },
      {
        "id": "d",
        "label": "Forwarding reports to marketing teams."
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "fin_priv_18",
    "section": "privacy",
    "prompt": "How does 'Zero-Knowledge Proofs (ZKP) in Financial AI' enable privacy-preserving verification?",
    "options": [
      {
        "id": "a",
        "label": "Allows a borrower or firm to cryptographically prove that their financial ratios or reserves satisfy loan criteria without revealing exact underlying balance numbers."
      },
      {
        "id": "b",
        "label": "Proves that the borrower has zero knowledge of mathematics."
      },
      {
        "id": "c",
        "label": "Eliminates all financial verification."
      },
      {
        "id": "d",
        "label": "Requires zero passwords to access bank accounts."
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "fin_priv_19",
    "section": "privacy",
    "prompt": "In private wealth management, how must 'Client Risk Profile Data' be segregated?",
    "options": [
      {
        "id": "a",
        "label": "Sharing client wealth details with all junior financial analysts."
      },
      {
        "id": "b",
        "label": "Storing client assets in public shared spreadsheets."
      },
      {
        "id": "c",
        "label": "Deleting client records upon account opening."
      },
      {
        "id": "d",
        "label": "Segregating high-net-worth client net worth, trust structures, and tax identifiers into encrypted vaults with strict attribute-based access control (ABAC)."
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "fin_priv_20",
    "section": "privacy",
    "prompt": "What is 'Pre-Trade Compliance Gate Checking' in automated financial AI systems?",
    "options": [
      {
        "id": "a",
        "label": "Checking the weather forecast before trading."
      },
      {
        "id": "b",
        "label": "Executing all trades without any pre-trade checks."
      },
      {
        "id": "c",
        "label": "Automatically validating proposed portfolio trades against client investment mandates, ESG restrictions, leverage limits, and regulatory exposure caps prior to order execution."
      },
      {
        "id": "d",
        "label": "Asking clients to approve every microsecond trade manually."
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "fin_priv_21",
    "section": "privacy",
    "prompt": "Why must 'Automated Valuation Model (AVM) Backtesting' be audited by independent risk teams?",
    "options": [
      {
        "id": "a",
        "label": "To increase model computation time."
      },
      {
        "id": "b",
        "label": "Verifies that valuation algorithms do not overfit historical bull markets or systematically underestimate tail-risk losses during liquidity stress periods."
      },
      {
        "id": "c",
        "label": "Because algorithms cannot make mistakes."
      },
      {
        "id": "d",
        "label": "To calculate CEO stock grants."
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "fin_priv_22",
    "section": "privacy",
    "prompt": "How does 'Anonymized Transaction Hashing' protect vendor payment analytics?",
    "options": [
      {
        "id": "a",
        "label": "Hashes vendor names and account IDs before running machine learning spend categorization, preventing commercial price leakages across client organizations."
      },
      {
        "id": "b",
        "label": "Deletes all vendor payment records."
      },
      {
        "id": "c",
        "label": "Publishes all vendor contracts publicly."
      },
      {
        "id": "d",
        "label": "Pays all vendors in cryptocurrency."
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "fin_priv_23",
    "section": "privacy",
    "prompt": "What is 'Explainable AI (XAI) Attribution for Credit Denial' (Adverse Action Notice)?",
    "options": [
      {
        "id": "a",
        "label": "Sending a generic refusal email with no explanation."
      },
      {
        "id": "b",
        "label": "Telling the consumer that the AI computer made the decision."
      },
      {
        "id": "c",
        "label": "Charging a fee to explain the decision."
      },
      {
        "id": "d",
        "label": "Under the Equal Credit Opportunity Act (ECOA), providing consumers with the top 4 specific principal reasons (e.g. debt-to-income ratio, delinquencies) for credit denial."
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "fin_priv_24",
    "section": "privacy",
    "prompt": "In enterprise corporate finance, why should 'Formula Injection in CSV Exports' be actively sanitized?",
    "options": [
      {
        "id": "a",
        "label": "Because Excel cannot open CSV files."
      },
      {
        "id": "b",
        "label": "To force all files to be saved as PDF."
      },
      {
        "id": "c",
        "label": "Prevents attackers from injecting cells starting with `=`, `+`, `-`, or `@` that execute malicious DDE (Dynamic Data Exchange) commands when opened in Microsoft Excel."
      },
      {
        "id": "d",
        "label": "To reduce CSV file sizes."
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "fin_priv_25",
    "section": "privacy",
    "prompt": "How does 'Continuous Insider Trading Detection via NLP' protect financial institutions?",
    "options": [
      {
        "id": "a",
        "label": "Bans all employees from owning mobile phones."
      },
      {
        "id": "b",
        "label": "Scans employee communications for suspicious discussions about unannounced earnings or M&A code names correlating with sudden employee personal trading activity."
      },
      {
        "id": "c",
        "label": "Forces all employees to trade company stock daily."
      },
      {
        "id": "d",
        "label": "Disables all email communications."
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "fin_priv_26",
    "section": "privacy",
    "prompt": "What is 'Audit Log Integrity Verification via Merkle Trees' in financial accounting?",
    "options": [
      {
        "id": "a",
        "label": "Cryptographically chains log entries into a Merkle tree structure, ensuring that any retroactive alteration, deletion, or tampering with financial records is mathematically detectable."
      },
      {
        "id": "b",
        "label": "Planting trees to offset carbon emissions."
      },
      {
        "id": "c",
        "label": "A legacy accounting method from the 1800s."
      },
      {
        "id": "d",
        "label": "A technique for formatting financial tables."
      }
    ],
    "correctOptionId": "a"
  },
  {
    "id": "fin_priv_27",
    "section": "privacy",
    "prompt": "Why should investment banking AI models undergo 'Code Name De-identification' during early M&A exploration?",
    "options": [
      {
        "id": "a",
        "label": "Because real company names are too long."
      },
      {
        "id": "b",
        "label": "To make financial reports sound exciting."
      },
      {
        "id": "c",
        "label": "Because the SEC requires animal code names."
      },
      {
        "id": "d",
        "label": "Replaces target company real names and distinct operational clues with project code names (e.g. 'Project Falcon') to prevent accidental deal leaks during document processing."
      }
    ],
    "correctOptionId": "d"
  },
  {
    "id": "fin_priv_28",
    "section": "privacy",
    "prompt": "How does 'Role-Based Cell-Level Masking in Excel' protect sensitive salary budgets?",
    "options": [
      {
        "id": "a",
        "label": "Deletes the entire spreadsheet."
      },
      {
        "id": "b",
        "label": "Sets all salary cells to $1."
      },
      {
        "id": "c",
        "label": "Hides or encrypts individual executive compensation rows while allowing department managers to see only rolled-up total department budget figures."
      },
      {
        "id": "d",
        "label": "Makes all cells visible to all employees."
      }
    ],
    "correctOptionId": "c"
  },
  {
    "id": "fin_priv_29",
    "section": "privacy",
    "prompt": "What is 'Model Bias and Drift Governance' under Federal Reserve SR 11-7 guidelines?",
    "options": [
      {
        "id": "a",
        "label": "Requires banks to use only physical calculators."
      },
      {
        "id": "b",
        "label": "Mandates independent model risk management (MRM), rigorous conceptual validation, outcome analysis, and ongoing monitoring of all quantitative banking models."
      },
      {
        "id": "c",
        "label": "Allows banks to deploy models without testing."
      },
      {
        "id": "d",
        "label": "Bans mathematical models in banking."
      }
    ],
    "correctOptionId": "b"
  },
  {
    "id": "fin_priv_30",
    "section": "privacy",
    "prompt": "Why must 'Customer Tax Identification Numbers (TIN / SSN)' be hashed with unique per-tenant salts?",
    "options": [
      {
        "id": "a",
        "label": "Prevents rainbow table matching and cross-tenant correlation attacks if the underlying database is breached."
      },
      {
        "id": "b",
        "label": "Reduces tax liability for the company."
      },
      {
        "id": "c",
        "label": "Makes tax numbers easier to memorize."
      },
      {
        "id": "d",
        "label": "Because the IRS requires salt in all numbers."
      }
    ],
    "correctOptionId": "a"
  }
];
