import { CertQuestion } from '../types';

export const PRACTITIONER_AUTOMATION_QUESTIONS: CertQuestion[] = [
  {
    id: 'prac_auto_01',
    section: 'automation',
    prompt: 'When building an automated meeting debrief workflow, what is the best practice for handling 90-minute messy transcripts?',
    options: [
      { id: 'a', label: 'A 2-stage pipeline: Stage 1 cleans transcript into speaker-tagged chronological summaries; Stage 2 extracts action items, owners, and deadlines.' },
      { id: 'b', label: 'Send the entire unformatted transcript with a single open-ended prompt: "Summarize everything in 5 words."' },
      { id: 'c', label: 'Rely on the model to deduce missing timestamps and unstated attendee agreements.' },
      { id: 'd', label: 'Truncate the transcript at the 1,000-word mark regardless of meeting content.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_02',
    section: 'automation',
    prompt: 'What constitutes an effective personal or team "Prompt Library"?',
    options: [
      { id: 'a', label: 'An unstructured text file containing copy-pasted web chat URLs.' },
      { id: 'b', label: 'A single generic prompt template applied indiscriminately across all company tasks.' },
      { id: 'c', label: 'A collection of tested, versioned prompts with clear parameter placeholders ({variables}), expected output contracts, and usage context.' },
      { id: 'd', label: 'A list of third-party subscription passwords stored for team sharing.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_auto_03',
    section: 'automation',
    prompt: 'When automating customer feedback extraction from hundreds of reviews, why is batch processing with JSON schema superior to free-form chat querying?',
    options: [
      { id: 'a', label: 'It guarantees that 100% of customer reviews will be scored as positive sentiment.' },
      { id: 'b', label: 'It eliminates the need for internet access and cloud connectivity.' },
      { id: 'c', label: 'It forces the LLM to write poetic prose rather than analytical metrics.' },
      { id: 'd', label: 'It produces predictable structured records (sentiment score, feature mention, bug report) that ingest directly into analytics databases.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_auto_04',
    section: 'automation',
    prompt: 'In a multi-step writing pipeline, why is "clay drafting" (drafting raw content without editing, then passing to a critique/polishing prompt) recommended?',
    options: [
      { id: 'a', label: 'It hides prompt instructions from the model\'s attention mechanism.' },
      { id: 'b', label: 'Separating ideation/content generation from editorial refining prevents cognitive bottlenecks and yields significantly tighter outputs.' },
      { id: 'c', label: 'It reduces the total number of API calls to exactly one.' },
      { id: 'd', label: 'It forces the model to generate content strictly in bullet points.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_auto_05',
    section: 'automation',
    prompt: 'What is the primary risk of chaining five generative prompt steps without intermediate validation schemas?',
    options: [
      { id: 'a', label: 'Error propagation: subtle hallucinations or formatting drift in step 1 compound into total output degeneration by step 5.' },
      { id: 'b', label: 'The prompt text permanently changes its encoding to ASCII binary.' },
      { id: 'c', label: 'The server automatically doubles API token billing rates.' },
      { id: 'd', label: 'The underlying model resets its base neural weights.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_06',
    section: 'automation',
    prompt: 'When automating weekly KPI reports from raw CSV spreadsheets, how should numerical data be passed to the LLM to minimize calculation errors?',
    options: [
      { id: 'a', label: 'Prompt the LLM to calculate multi-digit matrix multiplications mentally in text.' },
      { id: 'b', label: 'Omit all concrete numerical values and ask the LLM to infer trends from company vibes.' },
      { id: 'c', label: 'Increase model temperature to 1.8 for financial calculations.' },
      { id: 'd', label: 'Pre-calculate totals, growth rates, and percentages programmatically via code/formulas, passing the calculated metrics for the LLM to synthesize narrative insights.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_auto_07',
    section: 'automation',
    prompt: 'What is a "micro-task audit" in workflow automation?',
    options: [
      { id: 'a', label: 'Auditing server CPU cache register allocation per millisecond.' },
      { id: 'b', label: 'Reviewing daily work to decompose large ambiguous jobs into discrete 2-5 minute cognitive sub-tasks suitable for AI assistance.' },
      { id: 'c', label: 'Monitoring the physical hardware temperature of workplace laptops.' },
      { id: 'd', label: 'Counting the number of characters in outgoing company emails.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_auto_08',
    section: 'automation',
    prompt: 'How can teams ensure consistency across AI-assisted customer support replies authored by multiple human agents?',
    options: [
      { id: 'a', label: 'Allow each agent to use arbitrary consumer AI tools without organizational guidelines.' },
      { id: 'b', label: 'Disable all template options and require free-form one-shot prompts.' },
      { id: 'c', label: 'Implement standardized prompt macros with pre-defined company tone, approved knowledge base references, and required sign-off policies.' },
      { id: 'd', label: 'Mandate that all customer replies be under 10 words.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_auto_09',
    section: 'automation',
    prompt: 'When an automated AI script encounters an unparsable response format, what is the best architectural fallback?',
    options: [
      { id: 'a', label: 'Catch parsing error, retry once with an explicit correction prompt showing the error, or route to human review queue if retry fails.' },
      { id: 'b', label: 'Write corrupted placeholder strings into the database without alerting operators.' },
      { id: 'c', label: 'Shut down the entire production cluster immediately.' },
      { id: 'd', label: 'Ignore the error and skip all remaining records in the queue.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_10',
    section: 'automation',
    prompt: 'Why should automation prompts use structured markdown headers (e.g. # CONTEXT, # INPUT DATA, # OUTPUT SPEC) rather than unsegmented blocks?',
    options: [
      { id: 'a', label: 'Headers double the inference processing speed on GPU clusters.' },
      { id: 'b', label: 'Unsegmented text triggers security firewalls on enterprise networks.' },
      { id: 'c', label: 'Markdown formatting eliminates all API token costs.' },
      { id: 'd', label: 'Explicit structural boundaries help models segment instructions from data, reducing instruction-following errors.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_auto_11',
    section: 'automation',
    prompt: 'When building a Retrieval-Augmented Generation (RAG) knowledge retrieval workflow for customer support, what is the role of "chunking" document text?',
    options: [
      { id: 'a', label: 'Encrypting files with SHA-256 before disk storage.' },
      { id: 'b', label: 'Splitting large documents into semantically coherent, bite-sized segments with overlap so embedding search can retrieve exact relevant passages into prompt context.' },
      { id: 'c', label: 'Deleting all non-English characters.' },
      { id: 'd', label: 'Compressing PDF images to reduce disk space.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_auto_12',
    section: 'automation',
    prompt: 'In automated batch content translation, why is maintaining a dynamic glossary lookup step prior to LLM generation recommended?',
    options: [
      { id: 'a', label: 'To eliminate all grammatical verbs from target languages.' },
      { id: 'b', label: 'To force the model to translate only one word per minute.' },
      { id: 'c', label: 'To inject exact verified domain terms, brand names, and forbidden translations directly into the generation prompt context.' },
      { id: 'd', label: 'To convert text into binary machine code.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_auto_13',
    section: 'automation',
    prompt: 'What is "Function Calling" (or Tool Calling) in automated LLM pipelines?',
    options: [
      { id: 'a', label: 'Dialing telephone numbers using cellular audio protocols.' },
      { id: 'b', label: 'Re-installing the Python runtime whenever a script executes.' },
      { id: 'c', label: 'Writing comments inside CSS stylesheets.' },
      { id: 'd', label: 'A model capability to output structured JSON function arguments chosen from a declared schema, enabling external code to execute real-time actions and return results to the model.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_auto_14',
    section: 'automation',
    prompt: 'You are deploying an automated email categorization pipeline. How do you design confidence thresholding to protect against misclassification?',
    options: [
      { id: 'a', label: 'If model classification confidence is above 90%, route automatically; if below 90% or uncertain, route to a human triage inbox for manual verification.' },
      { id: 'b', label: 'Delete all emails where classification confidence is below 100%.' },
      { id: 'c', label: 'Always execute automated actions regardless of model confidence or ambiguity.' },
      { id: 'd', label: 'Auto-reply to all ambiguous emails with an error code.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_15',
    section: 'automation',
    prompt: 'When connecting an LLM to an external CRM database via API webhooks, why must state updates be idempotent?',
    options: [
      { id: 'a', label: 'Because LLMs only support GET requests.' },
      { id: 'b', label: 'To ensure that network retries or duplicate webhook delivery do not result in repeated duplicate database records or charges.' },
      { id: 'c', label: 'To prevent users from viewing the website on mobile devices.' },
      { id: 'd', label: 'To disable logging across the server.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_auto_16',
    section: 'automation',
    prompt: 'What is the advantage of using a "Human-in-the-Loop" (HITL) approval gate for high-stakes AI automation steps?',
    options: [
      { id: 'a', label: 'It guarantees zero latency for end users.' },
      { id: 'b', label: 'It removes the need for database backups.' },
      { id: 'c', label: 'It leverages AI speed for drafting and analysis while preserving human accountability, judgment, and risk mitigation for irreversible operations.' },
      { id: 'd', label: 'It permanently disables API rate limiting.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_auto_17',
    section: 'automation',
    prompt: 'In a scheduled nightly data extraction pipeline processing 10,000 PDF invoices, what is the best strategy to manage API costs and throughput limits?',
    options: [
      { id: 'a', label: 'Submit all 10,000 requests in a single unbounded asynchronous burst.' },
      { id: 'b', label: 'Use the most expensive frontier model for every basic regex extraction task.' },
      { id: 'c', label: 'Disable all error logging to speed up execution.' },
      { id: 'd', label: 'Use asynchronous batch processing APIs with concurrency throttling, model tiering (fast model for simple parsing; heavy model for exceptions), and token caching.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_auto_18',
    section: 'automation',
    prompt: 'What does "Prompt Chaining with State Passing" mean in complex multi-stage agentic workflows?',
    options: [
      { id: 'a', label: 'Sequentially passing the structured output of step N as a validated parameter into the prompt input context of step N+1.' },
      { id: 'b', label: 'Running the same prompt on five different browsers at the same time.' },
      { id: 'c', label: 'Encrypting prompt strings using cryptographic blockchain ledgers.' },
      { id: 'd', label: 'Sending emails between team members after every prompt.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_19',
    section: 'automation',
    prompt: 'Why should automated AI workflows include a "Dead Letter Queue" (DLQ)?',
    options: [
      { id: 'a', label: 'To delete all successful records immediately.' },
      { id: 'b', label: 'To capture, isolate, and log failed job payloads that exceeded retry thresholds for developer inspection without blocking pipeline execution.' },
      { id: 'c', label: 'To store email newsletters that were rejected by spam filters.' },
      { id: 'd', label: 'To store expired API keys.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_auto_20',
    section: 'automation',
    prompt: 'When building an automated competitive intelligence monitor, what is the most effective workflow architecture?',
    options: [
      { id: 'a', label: 'Manually copy-pasting news articles into chat windows every 10 minutes.' },
      { id: 'b', label: 'Relying exclusively on social media rumors without verifying primary source URLs.' },
      { id: 'c', label: 'Scheduled RSS/API ingestion -> LLM entity and theme extraction -> deduplication filter -> structured executive alert synthesis in Slack/Teams.' },
      { id: 'd', label: 'Broadcasting unvetted raw web scrape dumps directly to executive email lists.' },
    ],
    correctOptionId: 'c',
  },
];

