import { CertQuestion } from '../types';

export const PRACTITIONER_AUTOMATION_QUESTIONS: CertQuestion[] = [
  {
    id: 'prac_auto_01',
    section: 'automation',
    prompt: 'When building an automated meeting debrief workflow, what is the best practice for handling 90-minute messy transcripts?',
    options: [
      { id: 'a', label: 'A 2-stage pipeline: Stage 1 cleans transcript into speaker-tagged chronological summaries; Stage 2 extracts action items, owners, and deadlines.' },
      { id: 'b', label: 'Send the entire unformatted transcript with a single open-ended prompt: "Summarize everything in 5 words."' },
      { id: 'c', label: 'Rely on the model to deduce missing timestamps and unstated attendee agreements.' },
      { id: 'd', label: 'Truncate the transcript at the 1,000-word mark regardless of meeting content.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_02',
    section: 'automation',
    prompt: 'What constitutes an effective personal or team "Prompt Library"?',
    options: [
      { id: 'a', label: 'An unstructured text file containing copy-pasted web chat URLs.' },
      { id: 'b', label: 'A single generic prompt template applied indiscriminately across all company tasks.' },
      { id: 'c', label: 'A collection of tested, versioned prompts with clear parameter placeholders ({variables}), expected output contracts, and usage context.' },
      { id: 'd', label: 'A list of third-party subscription passwords stored for team sharing.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_auto_03',
    section: 'automation',
    prompt: 'When automating customer feedback extraction from hundreds of reviews, why is batch processing with JSON schema superior to free-form chat querying?',
    options: [
      { id: 'a', label: 'It guarantees that 100% of customer reviews will be scored as positive sentiment.' },
      { id: 'b', label: 'It eliminates the need for internet access and cloud connectivity.' },
      { id: 'c', label: 'It forces the LLM to write poetic prose rather than analytical metrics.' },
      { id: 'd', label: 'It produces predictable structured records (sentiment score, feature mention, bug report) that ingest directly into analytics databases.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_auto_04',
    section: 'automation',
    prompt: 'In a multi-step writing pipeline, why is "clay drafting" (drafting raw content without editing, then passing to a critique/polishing prompt) recommended?',
    options: [
      { id: 'a', label: 'It hides prompt instructions from the model\'s attention mechanism.' },
      { id: 'b', label: 'Separating ideation/content generation from editorial refining prevents cognitive bottlenecks and yields significantly tighter outputs.' },
      { id: 'c', label: 'It reduces the total number of API calls to exactly one.' },
      { id: 'd', label: 'It forces the model to generate content strictly in bullet points.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_auto_05',
    section: 'automation',
    prompt: 'What is the primary risk of chaining five generative prompt steps without intermediate validation schemas?',
    options: [
      { id: 'a', label: 'Error propagation: subtle hallucinations or formatting drift in step 1 compound into total output degeneration by step 5.' },
      { id: 'b', label: 'The prompt text permanently changes its encoding to ASCII binary.' },
      { id: 'c', label: 'The server automatically doubles API token billing rates.' },
      { id: 'd', label: 'The underlying model resets its base neural weights.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_06',
    section: 'automation',
    prompt: 'When automating weekly KPI reports from raw CSV spreadsheets, how should numerical data be passed to the LLM to minimize calculation errors?',
    options: [
      { id: 'a', label: 'Prompt the LLM to calculate multi-digit matrix multiplications mentally in text.' },
      { id: 'b', label: 'Omit all concrete numerical values and ask the LLM to infer trends from company vibes.' },
      { id: 'c', label: 'Increase model temperature to 1.8 for financial calculations.' },
      { id: 'd', label: 'Pre-calculate totals, growth rates, and percentages programmatically via code/formulas, passing the calculated metrics for the LLM to synthesize narrative insights.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_auto_07',
    section: 'automation',
    prompt: 'What is a "micro-task audit" in workflow automation?',
    options: [
      { id: 'a', label: 'Auditing server CPU cache register allocation per millisecond.' },
      { id: 'b', label: 'Reviewing daily work to decompose large ambiguous jobs into discrete 2-5 minute cognitive sub-tasks suitable for AI assistance.' },
      { id: 'c', label: 'Monitoring the physical hardware temperature of workplace laptops.' },
      { id: 'd', label: 'Counting the number of characters in outgoing company emails.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_auto_08',
    section: 'automation',
    prompt: 'How can teams ensure consistency across AI-assisted customer support replies authored by multiple human agents?',
    options: [
      { id: 'a', label: 'Allow each agent to use arbitrary consumer AI tools without organizational guidelines.' },
      { id: 'b', label: 'Disable all template options and require free-form one-shot prompts.' },
      { id: 'c', label: 'Implement standardized prompt macros with pre-defined company tone, approved knowledge base references, and required sign-off policies.' },
      { id: 'd', label: 'Mandate that all customer replies be under 10 words.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_auto_09',
    section: 'automation',
    prompt: 'When an automated AI script encounters an unparsable response format, what is the best architectural fallback?',
    options: [
      { id: 'a', label: 'Catch parsing error, retry once with an explicit correction prompt showing the error, or route to human review queue if retry fails.' },
      { id: 'b', label: 'Write corrupted placeholder strings into the database without alerting operators.' },
      { id: 'c', label: 'Shut down the entire production cluster immediately.' },
      { id: 'd', label: 'Ignore the error and skip all remaining records in the queue.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_10',
    section: 'automation',
    prompt: 'Why should automation prompts use structured markdown headers (e.g. # CONTEXT, # INPUT DATA, # OUTPUT SPEC) rather than unsegmented blocks?',
    options: [
      { id: 'a', label: 'Headers double the inference processing speed on GPU clusters.' },
      { id: 'b', label: 'Unsegmented text triggers security firewalls on enterprise networks.' },
      { id: 'c', label: 'Markdown formatting eliminates all API token costs.' },
      { id: 'd', label: 'Explicit structural boundaries help models segment instructions from data, reducing instruction-following errors.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_auto_11',
    section: 'automation',
    prompt: 'When building a Retrieval-Augmented Generation (RAG) knowledge retrieval workflow for customer support, what is the role of "chunking" document text?',
    options: [
      { id: 'a', label: 'Encrypting files with SHA-256 before disk storage.' },
      { id: 'b', label: 'Splitting large documents into semantically coherent, bite-sized segments with overlap so embedding search can retrieve exact relevant passages into prompt context.' },
      { id: 'c', label: 'Deleting all non-English characters.' },
      { id: 'd', label: 'Compressing PDF images to reduce disk space.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_auto_12',
    section: 'automation',
    prompt: 'In automated batch content translation, why is maintaining a dynamic glossary lookup step prior to LLM generation recommended?',
    options: [
      { id: 'a', label: 'To eliminate all grammatical verbs from target languages.' },
      { id: 'b', label: 'To force the model to translate only one word per minute.' },
      { id: 'c', label: 'To inject exact verified domain terms, brand names, and forbidden translations directly into the generation prompt context.' },
      { id: 'd', label: 'To convert text into binary machine code.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_auto_13',
    section: 'automation',
    prompt: 'What is "Function Calling" (or Tool Calling) in automated LLM pipelines?',
    options: [
      { id: 'a', label: 'Dialing telephone numbers using cellular audio protocols.' },
      { id: 'b', label: 'Re-installing the Python runtime whenever a script executes.' },
      { id: 'c', label: 'Writing comments inside CSS stylesheets.' },
      { id: 'd', label: 'A model capability to output structured JSON function arguments chosen from a declared schema, enabling external code to execute real-time actions and return results to the model.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_auto_14',
    section: 'automation',
    prompt: 'You are deploying an automated email categorization pipeline. How do you design confidence thresholding to protect against misclassification?',
    options: [
      { id: 'a', label: 'If model classification confidence is above 90%, route automatically; if below 90% or uncertain, route to a human triage inbox for manual verification.' },
      { id: 'b', label: 'Delete all emails where classification confidence is below 100%.' },
      { id: 'c', label: 'Always execute automated actions regardless of model confidence or ambiguity.' },
      { id: 'd', label: 'Auto-reply to all ambiguous emails with an error code.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_15',
    section: 'automation',
    prompt: 'When connecting an LLM to an external CRM database via API webhooks, why must state updates be idempotent?',
    options: [
      { id: 'a', label: 'Because LLMs only support GET requests.' },
      { id: 'b', label: 'To ensure that network retries or duplicate webhook delivery do not result in repeated duplicate database records or charges.' },
      { id: 'c', label: 'To prevent users from viewing the website on mobile devices.' },
      { id: 'd', label: 'To disable logging across the server.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_auto_16',
    section: 'automation',
    prompt: 'What is the advantage of using a "Human-in-the-Loop" (HITL) approval gate for high-stakes AI automation steps?',
    options: [
      { id: 'a', label: 'It guarantees zero latency for end users.' },
      { id: 'b', label: 'It removes the need for database backups.' },
      { id: 'c', label: 'It leverages AI speed for drafting and analysis while preserving human accountability, judgment, and risk mitigation for irreversible operations.' },
      { id: 'd', label: 'It permanently disables API rate limiting.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_auto_17',
    section: 'automation',
    prompt: 'In a scheduled nightly data extraction pipeline processing 10,000 PDF invoices, what is the best strategy to manage API costs and throughput limits?',
    options: [
      { id: 'a', label: 'Submit all 10,000 requests in a single unbounded asynchronous burst.' },
      { id: 'b', label: 'Use the most expensive frontier model for every basic regex extraction task.' },
      { id: 'c', label: 'Disable all error logging to speed up execution.' },
      { id: 'd', label: 'Use asynchronous batch processing APIs with concurrency throttling, model tiering (fast model for simple parsing; heavy model for exceptions), and token caching.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_auto_18',
    section: 'automation',
    prompt: 'What does "Prompt Chaining with State Passing" mean in complex multi-stage agentic workflows?',
    options: [
      { id: 'a', label: 'Sequentially passing the structured output of step N as a validated parameter into the prompt input context of step N+1.' },
      { id: 'b', label: 'Running the same prompt on five different browsers at the same time.' },
      { id: 'c', label: 'Encrypting prompt strings using cryptographic blockchain ledgers.' },
      { id: 'd', label: 'Sending emails between team members after every prompt.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_19',
    section: 'automation',
    prompt: 'Why should automated AI workflows include a "Dead Letter Queue" (DLQ)?',
    options: [
      { id: 'a', label: 'To delete all successful records immediately.' },
      { id: 'b', label: 'To capture, isolate, and log failed job payloads that exceeded retry thresholds for developer inspection without blocking pipeline execution.' },
      { id: 'c', label: 'To store email newsletters that were rejected by spam filters.' },
      { id: 'd', label: 'To store expired API keys.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_auto_20',
    section: 'automation',
    prompt: 'When building an automated competitive intelligence monitor, what is the most effective workflow architecture?',
    options: [
      { id: 'a', label: 'Manually copy-pasting news articles into chat windows every 10 minutes.' },
      { id: 'b', label: 'Relying exclusively on social media rumors without verifying primary source URLs.' },
      { id: 'c', label: 'Scheduled RSS/API ingestion -> LLM entity and theme extraction -> deduplication filter -> structured executive alert synthesis in Slack/Teams.' },
      { id: 'd', label: 'Broadcasting unvetted raw web scrape dumps directly to executive email lists.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_auto_21',
    section: 'automation',
    prompt: 'In production agent workflows, what is the primary function of "Function Calling / Tool Use" over pure text generation?',
    options: [
      { id: 'a', label: 'The model generates structured arguments matching JSON schemas that client-side code executes against real APIs, databases, or calculations with determinism.' },
      { id: 'b', label: 'The model physically connects to and hacks external servers without credentials.' },
      { id: 'c', label: 'It eliminates all API request costs.' },
      { id: 'd', label: 'It replaces the need for internet connectivity.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_22',
    section: 'automation',
    prompt: 'An automation engineer needs to run a high-volume batch job translating 50,000 product descriptions. Which execution pattern minimizes costs while respecting rate limits?',
    options: [
      { id: 'a', label: 'OpenAI/Anthropic Batch API (50% discount with 24-hour SLA asynchronous completion).' },
      { id: 'b', label: 'Open 50,000 parallel synchronous HTTP threads from a local laptop.' },
      { id: 'c', label: 'Paste all 50,000 descriptions into a single web browser prompt.' },
      { id: 'd', label: 'Hire 1,000 manual freelancers to click generate buttons.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_23',
    section: 'automation',
    prompt: 'What constitutes an "Infinite Loop" failure mode in autonomous multi-agent systems, and how is it mitigated?',
    options: [
      { id: 'a', label: 'Agents getting stuck repeatedly delegating tasks back and forth to each other; mitigated by setting hard max-iteration caps and exit condition evaluators.' },
      { id: 'b', label: 'The CPU fan spinning too quickly; mitigated by water cooling.' },
      { id: 'c', label: 'The model forgetting its training data; mitigated by retraining.' },
      { id: 'd', label: 'Database hard drive running out of space.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_24',
    section: 'automation',
    prompt: 'When building an automated semantic cache for an AI customer support bot, what logic determines a cache hit?',
    options: [
      { id: 'a', label: 'Exact string character-by-character comparison only.' },
      { id: 'b', label: 'Cosine similarity of user query embeddings against indexed previous questions exceeding a high similarity threshold (e.g., >= 0.95).' },
      { id: 'c', label: 'Random coin toss algorithm.' },
      { id: 'd', label: 'Checking if the user name starts with the same letter.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_auto_25',
    section: 'automation',
    prompt: 'Why should automated LLM generation pipelines implement "Streaming Responses" (Server-Sent Events) in user-facing applications?',
    options: [
      { id: 'a', label: 'To drastically reduce perceived latency (Time to First Token) and improve user engagement while generation continues.' },
      { id: 'b', label: 'To reduce the model token pricing by half.' },
      { id: 'c', label: 'To encrypt text packets against wiretapping.' },
      { id: 'd', label: 'To compress video files.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_26',
    section: 'automation',
    prompt: 'In RAG document retrieval automation, what is the role of a "Re-Ranking Model" (Cross-Encoder)?',
    options: [
      { id: 'a', label: 'It takes top-K initial vector search results and re-evaluates query-document relevance with deep cross-attention, filtering out false-positive chunks.' },
      { id: 'b', label: 'It sorts files alphabetically by filename.' },
      { id: 'c', label: 'It translates all documents into Spanish.' },
      { id: 'd', label: 'It deletes outdated documents from the database.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_27',
    section: 'automation',
    prompt: 'How does an automated "Router LLM" pattern optimize cost and latency in enterprise AI systems?',
    options: [
      { id: 'a', label: 'A fast, inexpensive model (e.g., GPT-4o-mini / Claude 3.5 Haiku) classifies incoming query complexity and routes simple tasks to fast models and complex reasoning to frontier models.' },
      { id: 'b', label: 'It routes user internet traffic through a VPN server.' },
      { id: 'c', label: 'It connects the server to a physical Wi-Fi router.' },
      { id: 'd', label: 'It replaces all backend databases with text files.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_28',
    section: 'automation',
    prompt: 'What is the purpose of "Schema Self-Correction Loops" in automated data extraction pipelines?',
    options: [
      { id: 'a', label: 'If JSON schema validation fails, the validation error message is fed back to the LLM in a corrective turn to fix the malformed payload automatically.' },
      { id: 'b', label: 'The database deletes the schema and creates a new one.' },
      { id: 'c', label: 'The user is immediately logged out.' },
      { id: 'd', label: 'The server reboots to reset memory.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_29',
    section: 'automation',
    prompt: 'In automated prompt evaluation suites, what is "LLM-as-a-Judge"?',
    options: [
      { id: 'a', label: 'Using a high-capability frontier model to systematically score candidate model outputs against strict evaluation rubrics (accuracy, hallucination, tone).' },
      { id: 'b', label: 'An AI presiding over a real courtroom trial.' },
      { id: 'c', label: 'A script that generates legal court documents.' },
      { id: 'd', label: 'A program that bans abusive users automatically.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_auto_30',
    section: 'automation',
    prompt: 'When managing rate limits across multiple concurrent worker threads calling cloud LLM APIs, what architecture prevents cascading failures?',
    options: [
      { id: 'a', label: 'Token Bucket / Leaky Bucket rate limiter with distributed queue throttling (e.g., Redis rate limiting).' },
      { id: 'b', label: 'Increasing the thread count to 10,000 without throttle controls.' },
      { id: 'c', label: 'Hardcoding 1-second sleeps in every function.' },
      { id: 'd', label: 'Ignoring HTTP 429 status codes.' },
    ],
    correctOptionId: 'a',
  },
];


