import { CertQuestion } from '../types';

export const PRACTITIONER_GROWTH_QUESTIONS: CertQuestion[] = [
  {
    id: 'prac_gro_01',
    section: 'growth',
    prompt: 'How can an AI practitioner use an LLM as a "Cognitive Sparring Partner" when preparing for a critical executive presentation?',
    options: [
      { id: 'a', label: 'Ask the model to agree with every slide enthusiastically to boost confidence.' },
      { id: 'b', label: 'Instruct the model to adopt the persona of a skeptical CFO, stress-test your assumptions, and challenge every financial metric with counter-arguments.' },
      { id: 'c', label: 'Have the model generate generic motivational quotes for the conclusion.' },
      { id: 'd', label: 'Copy-paste the slide deck into an email and distribute it unreviewed.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_gro_02',
    section: 'growth',
    prompt: 'When evaluating new third-party "AI tools" on the market, what is the best "anti-hype" evaluation filter?',
    options: [
      { id: 'a', label: 'Determine whether the tool is a thin wrapper over a basic system prompt, or if it provides defensible proprietary workflows, domain integrations, and data gravity.' },
      { id: 'b', label: 'Count how many times the word "revolutionary" appears in their marketing videos.' },
      { id: 'c', label: 'Choose whichever tool has the highest price tier and slickest landing page.' },
      { id: 'd', label: 'Pick whichever tool offers the highest referral commission.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_03',
    section: 'growth',
    prompt: 'How should a practitioner leverage multimodal vision models when debugging a complex UI/UX layout bug?',
    options: [
      { id: 'a', label: 'Type a 10-word vague description of the bug without uploading any visual assets.' },
      { id: 'b', label: 'Convert the website DOM into an audio file and ask the model to listen.' },
      { id: 'c', label: 'Provide screenshot of the broken UI alongside corresponding HTML/CSS code, asking the model to pinpoint CSS property conflicts causing the visual defect.' },
      { id: 'd', label: 'Ask the model to redesign the entire operating system.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_gro_04',
    section: 'growth',
    prompt: 'What is the hallmark of high "AI Momentum" in an organization?',
    options: [
      { id: 'a', label: 'Buying enterprise licenses that no team member ever logs into.' },
      { id: 'b', label: 'Issuing press releases about AI adoption while forbidding employees from using tools.' },
      { id: 'c', label: 'Replacing entire departments overnight without piloting or accuracy testing.' },
      { id: 'd', label: 'Teams actively integrate verified AI prompt patterns into daily workflows, measure time savings and quality improvements, and continuously share best practices.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_gro_05',
    section: 'growth',
    prompt: 'When an AI model produces two contradictory answers in successive chat turns, how should a practitioner resolve the conflict?',
    options: [
      { id: 'a', label: 'Ask the model to isolate the underlying assumptions behind both conclusions, cite primary sources, and reconcile the logic against verified reference facts.' },
      { id: 'b', label: 'Select whichever response contains more complex technical vocabulary.' },
      { id: 'c', label: 'Assume the first response is always factually superior to the second.' },
      { id: 'd', label: 'Restart the browser and ignore the contradiction.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_06',
    section: 'growth',
    prompt: 'What is "calibration" in the context of human-AI collaboration?',
    options: [
      { id: 'a', label: 'Setting hardware display brightness and color temperature profiles.' },
      { id: 'b', label: 'Measuring average typing speed on external keyboards.' },
      { id: 'c', label: 'Synchronizing client server times across distributed database clusters.' },
      { id: 'd', label: 'Developing an accurate intuition for what types of cognitive tasks an LLM excels at vs where it is prone to hallucination, sycophancy, or failure.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_gro_07',
    section: 'growth',
    prompt: 'Why is "sycophancy" in LLMs a risk for strategic decision-making?',
    options: [
      { id: 'a', label: 'Models tend to agree with the user\'s leading hypotheses and confirm flawed biases rather than pointing out fatal logical gaps.' },
      { id: 'b', label: 'The model generates offensive remarks and refuses to follow instructions.' },
      { id: 'c', label: 'The model enters an unrecoverable infinite loop during output streaming.' },
      { id: 'd', label: 'The model doubles billing costs for strategic questions.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_08',
    section: 'growth',
    prompt: 'How should a practitioner prompt an LLM to actively combat sycophancy and confirmational bias?',
    options: [
      { id: 'a', label: '"Tell me why my proposal is the most innovative solution ever created."' },
      { id: 'b', label: '"Summarize this idea in as agreeable and supportive a tone as possible."' },
      { id: 'c', label: '"Adopt a steel-man posture: independently critique this strategy, outline the 3 most probable failure modes, and provide counter-evidence."' },
      { id: 'd', label: '"Reassure the board that this plan has zero risks."' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_gro_09',
    section: 'growth',
    prompt: 'When exploring an unfamiliar technical domain, how can an AI practitioner structure a 15-minute learning sprint?',
    options: [
      { id: 'a', label: 'Skim a 500-page academic textbook in 2 minutes without asking questions.' },
      { id: 'b', label: 'Request a foundational concept breakdown with analogies, follow up on the 3 core bottleneck mechanisms, and test comprehension with AI-generated quiz scenarios.' },
      { id: 'c', label: 'Instruct the model to do all domain thinking for you in the future.' },
      { id: 'd', label: 'Memorize random acronyms without understanding their underlying mechanisms.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_gro_10',
    section: 'growth',
    prompt: 'What distinguishes a true AI Practitioner from a casual AI user?',
    options: [
      { id: 'a', label: 'A Practitioner blindly accepts raw model outputs without validation.' },
      { id: 'b', label: 'A Practitioner only uses AI tools to generate social media memes.' },
      { id: 'c', label: 'A Practitioner designs repeatable, calibrated workflows, verifies critical outputs against ground truth, and treats AI as an amplifier of rigorous human judgment.' },
      { id: 'd', label: 'A Practitioner maintains the highest number of active software subscriptions.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_gro_11',
    section: 'growth',
    prompt: 'When using an LLM to conduct a "Pre-Mortem" analysis before launching a major product feature, what is the core prompting instruction?',
    options: [
      { id: 'a', label: 'Ask the model to write a congratulatory launch party announcement.' },
      { id: 'b', label: 'Assume that the launch has completely failed six months from now, and work backwards to identify the most likely technical, user adoption, and operational root causes.' },
      { id: 'c', label: 'Instruct the model to praise all project managers involved.' },
      { id: 'd', label: 'Generate 100 random user reviews with 5-star ratings.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_gro_12',
    section: 'growth',
    prompt: 'How can an engineering team prevent "AI Skill Atrophy" where junior team members lose core problem-solving fundamentals due to over-reliance on AI code generation?',
    options: [
      { id: 'a', label: 'Banning all computers and returning to handwriting code on paper.' },
      { id: 'b', label: 'Allowing junior developers to merge unreviewed code if written by an LLM.' },
      { id: 'c', label: 'Implementing pair-programming code walkthroughs where developers must explain the architecture, edge-cases, and algorithmic complexity of AI-generated logic before merging.' },
      { id: 'd', label: 'Disabling all compiler error warnings.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_gro_13',
    section: 'growth',
    prompt: 'What is the "Second-Order Thinking" prompt pattern for strategic business evaluation?',
    options: [
      { id: 'a', label: 'Repeating the prompt two times in a row.' },
      { id: 'b', label: 'Translating business plans into a second language.' },
      { id: 'c', label: 'Asking for two alternative bullet points for every decision.' },
      { id: 'd', label: 'Prompting the model to analyze not just the immediate direct consequence of a decision, but the subsequent downstream reactions of competitors, customers, and regulatory bodies ("and then what?").' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_gro_14',
    section: 'growth',
    prompt: 'When using AI to facilitate a complex stakeholder consensus meeting, what is the best facilitator prompt pattern?',
    options: [
      { id: 'a', label: 'Feed synthesized perspectives from all stakeholder groups, prompt the LLM to identify underlying common ground, surface hidden trade-offs, and suggest win-win compromise proposals.' },
      { id: 'b', label: 'Instruct the model to declare the loudest stakeholder the absolute winner.' },
      { id: 'c', label: 'Generate automated disciplinary warnings for dissenting team members.' },
      { id: 'd', label: 'Replace all human attendees with automated chatbot avatars.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_15',
    section: 'growth',
    prompt: 'How does an effective practitioner evaluate whether a complex business problem is suitable for GenAI vs traditional deterministic software engineering?',
    options: [
      { id: 'a', label: 'Always use GenAI for every task because newer technologies are universally superior.' },
      { id: 'b', label: 'Assess ambiguity, tolerance for variance, and nature of the task: use deterministic code for exact arithmetic, strict compliance rules, and stateful transactions; use GenAI for semantic synthesis, unstructured data parsing, and contextual translation.' },
      { id: 'c', label: 'Never use GenAI under any circumstances in enterprise environments.' },
      { id: 'd', label: 'Base the decision strictly on the file extension of the input data.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_gro_16',
    section: 'growth',
    prompt: 'What is "Prompt Regression Testing" and why is it essential as team workflows scale?',
    options: [
      { id: 'a', label: 'Testing whether user keyboard batteries are fully charged.' },
      { id: 'b', label: 'Deleting all system prompts at the end of each fiscal quarter.' },
      { id: 'c', label: 'Systematically running a standardized golden evaluation dataset through revised prompts to verify that improving one edge case has not broken accuracy on other critical scenarios.' },
      { id: 'd', label: 'Running prompts in reverse alphabetical order.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_gro_17',
    section: 'growth',
    prompt: 'How should a practitioner approach "contextual prompting" for specialized domain mentors (e.g. tax, regulatory, patent law)?',
    options: [
      { id: 'a', label: 'Rely solely on standard default chat instructions without specifying domain context.' },
      { id: 'b', label: 'Instruct the model to guess local jurisdiction laws without reference texts.' },
      { id: 'c', label: 'Ask the model to provide legally binding warranties for its outputs.' },
      { id: 'd', label: 'Frame explicit jurisdiction boundaries, cite applicable statutory frameworks, mandate disclaimers, and require citation to governing section codes.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_gro_18',
    section: 'growth',
    prompt: 'What is the primary indicator that an organization has advanced from "ad-hoc AI experimentation" to "institutional AI maturity"?',
    options: [
      { id: 'a', label: 'Centralized prompt governance, standardized evaluation benchmarks, documented privacy/security policies, and measurable operational ROI across core business units.' },
      { id: 'b', label: 'Every employee having 10 different personal AI browser extensions installed.' },
      { id: 'c', label: '100% of executive speeches mentioning the phrase "artificial intelligence".' },
      { id: 'd', label: 'Eliminating all human quality assurance teams.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_gro_19',
    section: 'growth',
    prompt: 'When coaching teammates who are skeptical or anxious about AI adoption, what is the most constructive leadership posture?',
    options: [
      { id: 'a', label: 'Mock their concerns and threaten replacement with automated scripts.' },
      { id: 'b', label: 'Acknowledge realistic limitations, demonstrate concrete micro-wins that eliminate tedious drudgery, and position AI as a cognitive assistant that empowers their expertise.' },
      { id: 'c', label: 'Force them to use AI tools for 8 hours a day without training.' },
      { id: 'd', label: 'Hide all AI tools from the team to avoid conflict.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_gro_20',
    section: 'growth',
    prompt: 'What is the ultimate milestone of achieving the Jnachi Certified AI Practitioner Certification?',
    options: [
      { id: 'a', label: 'Memorizing prompt templates without understanding their underlying mechanisms.' },
      { id: 'b', label: 'Writing prompts solely for entertainment.' },
      { id: 'c', label: 'Demonstrating proven capability to architect robust, calibrated, privacy-compliant, and high-impact AI workflows in real-world professional domains.' },
      { id: 'd', label: 'Relying 100% on automated decisions without human oversight.' },
    ],
    correctOptionId: 'c',
  },
];

