import { CertSection, CertQuestion } from '../types';
import { PRACTITIONER_LITERACY_QUESTIONS } from './literacy';
import { PRACTITIONER_AUTOMATION_QUESTIONS } from './automation';
import { PRACTITIONER_PRIVACY_QUESTIONS } from './privacy';
import { PRACTITIONER_GROWTH_QUESTIONS } from './growth';

export const PRACTITIONER_QUESTIONS_BY_SECTION: Record<CertSection, CertQuestion[]> = {
  literacy: PRACTITIONER_LITERACY_QUESTIONS,
  automation: PRACTITIONER_AUTOMATION_QUESTIONS,
  privacy: PRACTITIONER_PRIVACY_QUESTIONS,
  growth: PRACTITIONER_GROWTH_QUESTIONS,
};

export const ALL_PRACTITIONER_QUESTIONS: CertQuestion[] = [
  ...PRACTITIONER_LITERACY_QUESTIONS,
  ...PRACTITIONER_AUTOMATION_QUESTIONS,
  ...PRACTITIONER_PRIVACY_QUESTIONS,
  ...PRACTITIONER_GROWTH_QUESTIONS,
];
