import { CertQuestion } from '../types';

export const PRACTITIONER_LITERACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'prac_lit_01',
    section: 'literacy',
    prompt: 'You are generating structured product catalogs. When using an LLM to produce valid JSON, what prompt technique best guarantees machine-parsable syntax?',
    options: [
      { id: 'a', label: 'Ask the model to format nicely with emojis and bullet points' },
      { id: 'b', label: 'Specify a strict JSON schema, supply one-shot valid JSON examples, and explicitly forbid conversational preamble or markdown codeblock wrappers if raw JSON is required' },
      { id: 'c', label: 'Set model temperature to 1.8 to encourage creative parsing' },
      { id: 'd', label: 'Submit the prompt as an unformatted run-on sentence without schema definition' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_02',
    section: 'literacy',
    prompt: 'When crafting a persona prompt for financial analysis, which approach produces the most reliable, rigorous output?',
    options: [
      { id: 'a', label: '"Act as a genius investor who is never wrong and makes quick predictions."' },
      { id: 'b', label: 'Tell the model to give optimistic quarterly revenue projections by default.' },
      { id: 'c', label: 'Use a single-word prompt like "Finance" to avoid biasing the model.' },
      { id: 'd', label: 'Define role scope, analytical methodology (e.g. DCF, DuPont analysis), conservative bias assumptions, and mandatory risk citation steps.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_lit_03',
    section: 'literacy',
    prompt: 'In complex multi-document summarization, how do you prevent the "lost in the middle" phenomenon where models miss facts placed in the center of huge context windows?',
    options: [
      { id: 'a', label: 'Place key instructions and high-priority reference text near the very beginning or end of the prompt context, and prompt with step-by-step chunk extraction.' },
      { id: 'b', label: 'Place all critical extraction instructions exclusively in the middle 50% of the prompt.' },
      { id: 'c', label: 'Disable temperature sampling and force the model to read in reverse.' },
      { id: 'd', label: 'Compress the text into an unpunctuated single-line string.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_04',
    section: 'literacy',
    prompt: 'What is the most effective way to test whether an updated system prompt has degraded existing performance across legacy edge cases?',
    options: [
      { id: 'a', label: 'Run a single casual query and deploy immediately if the output appears reasonable.' },
      { id: 'b', label: 'Ask the LLM in a new chat if it believes the updated prompt is superior.' },
      { id: 'c', label: 'Maintain a regression benchmark test suite of diverse input cases with expected assertion criteria and evaluate outputs deterministically.' },
      { id: 'd', label: 'Rely solely on end-user complaints in production after deployment.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_lit_05',
    section: 'literacy',
    prompt: 'Why should negative constraints (e.g., "Do NOT include greetings") be reinforced with positive guidance (e.g., "Begin directly with the raw data table")?',
    options: [
      { id: 'a', label: 'LLMs process attention tokens more reliably when provided with a clear target trajectory rather than solely unbounded negative bounds.' },
      { id: 'b', label: 'Negative words trigger automatic server-side API error exceptions.' },
      { id: 'c', label: 'Positive prompts cost 50% fewer billing tokens.' },
      { id: 'd', label: 'Negative words invert the model\'s internal sampling temperature.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_06',
    section: 'literacy',
    prompt: 'When summarizing a 50-page legal contract, how should a practitioner calibrate the model to prevent speculative interpretation?',
    options: [
      { id: 'a', label: 'Prompt the model to fill in missing clauses using standard industry conventions.' },
      { id: 'b', label: 'Set temperature to maximum to encourage diverse interpretations.' },
      { id: 'c', label: 'Ask the model to rewrite the contract from memory without referencing text.' },
      { id: 'd', label: 'Instruct the model to quote exact clause numbers and verbatim text excerpts for every assertion, stating "Not specified in document" when text is absent.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_lit_07',
    section: 'literacy',
    prompt: 'What distinguishes zero-shot Chain-of-Thought ("Let\'s think step by step") from standard zero-shot prompting?',
    options: [
      { id: 'a', label: 'It completely bypasses context window token limits.' },
      { id: 'b', label: 'It encourages the model to generate intermediate reasoning tokens, significantly boosting logical and quantitative accuracy before rendering the final conclusion.' },
      { id: 'c', label: 'It automatically invokes external Python code execution without configuration.' },
      { id: 'd', label: 'It eliminates the need to provide task instructions or context.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_08',
    section: 'literacy',
    prompt: 'In prompt calibration, what is "prompt drift"?',
    options: [
      { id: 'a', label: 'Network packet delay caused by high latency server routes.' },
      { id: 'b', label: 'Loss of client authentication tokens during long sessions.' },
      { id: 'c', label: 'Changes in model output quality or style over time due to backend model updates, parameter fine-tuning, or shifting input distribution.' },
      { id: 'd', label: 'Automatic deletion of chat history after 30 days.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_lit_09',
    section: 'literacy',
    prompt: 'How should a practitioner handle inconsistent classification tags when categorizing customer support tickets into fixed enum values?',
    options: [
      { id: 'a', label: 'Allow the model to invent descriptive new category names dynamically.' },
      { id: 'b', label: 'Increase prompt temperature to 1.5 to cover unexpected categories.' },
      { id: 'c', label: 'Prompt the customer to rephrase their inquiry until it matches a single keyword.' },
      { id: 'd', label: 'Provide the exact enum list in the prompt, include 2 examples per enum category, and mandate single-word or JSON-keyed outputs matching the enum.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_lit_10',
    section: 'literacy',
    prompt: 'When drafting automated email responses, what prevents the AI from sounding generic and boilerplate?',
    options: [
      { id: 'a', label: 'Providing a 3-tier style guide (voice, forbidden clichés, concrete sentence structure examples) and contextual variable slots.' },
      { id: 'b', label: 'Adding repetitive hype phrases like "Make this viral and sensational!"' },
      { id: 'c', label: 'Increasing model temperature to 1.9.' },
      { id: 'd', label: 'Writing prompts using exclusively uppercase text.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_11',
    section: 'literacy',
    prompt: 'When designing a prompt for complex comparative analysis between two quarterly balance sheets, which architectural structure maximizes analytical depth?',
    options: [
      { id: 'a', label: 'Ask the model to declare a single "winner" company in one sentence.' },
      { id: 'b', label: 'Use structured multi-pass prompting: Pass 1 extracts raw standardized metrics into a markdown table; Pass 2 computes variance ratios; Pass 3 synthesizes strategic risk commentary.' },
      { id: 'c', label: 'Provide only the raw image screenshots of the reports without OCR text.' },
      { id: 'd', label: 'Set top_p to 0.05 to eliminate comparative metrics.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_12',
    section: 'literacy',
    prompt: 'You notice an LLM is frequently generating subtle factual inaccuracies when summarizing technical RFC specifications. Which prompting modification is most effective?',
    options: [
      { id: 'a', label: 'Tell the model that you will give it a tip of $500 if it makes zero mistakes.' },
      { id: 'b', label: 'Switch to a high temperature setting so it explores wider semantic possibilities.' },
      { id: 'c', label: 'Instruct the model to perform source-grounded extraction: quote the exact paragraph number before each summary bullet, and explicitly note if any technical metric is absent from the text.' },
      { id: 'd', label: 'Remove the RFC specification text and ask the model to summarize from memory.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_lit_13',
    section: 'literacy',
    prompt: 'What is the primary function of the "top_p" (nucleus sampling) parameter in generative AI APIs?',
    options: [
      { id: 'a', label: 'It sets the maximum token length limit for the output buffer.' },
      { id: 'b', label: 'It controls the physical memory allocation on the server GPU.' },
      { id: 'c', label: 'It encrypts the network payload with a public key.' },
      { id: 'd', label: 'It limits token selection to the smallest set whose cumulative probability reaches threshold p, pruning the long tail of unlikely tokens.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_lit_14',
    section: 'literacy',
    prompt: 'When using an LLM to generate SQL queries across a complex database schema, how do you prevent the model from hallucinating non-existent column names?',
    options: [
      { id: 'a', label: 'Provide the exact CREATE TABLE schemas (DDL), column types, and foreign key relationships directly within the system prompt.' },
      { id: 'b', label: 'Ask the model to guess column names based on common tech industry slang.' },
      { id: 'c', label: 'Instruct the AI to use `SELECT *` exclusively without specifying columns.' },
      { id: 'd', label: 'Run the prompt in all-caps.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_15',
    section: 'literacy',
    prompt: 'What is "Self-Consistency" prompting and when is it most beneficial?',
    options: [
      { id: 'a', label: 'Asking the user to repeat the prompt 5 times in the same thread.' },
      { id: 'b', label: 'Sampling multiple distinct reasoning paths from the model at non-zero temperature and selecting the majority/consensus answer across paths for complex reasoning tasks.' },
      { id: 'c', label: 'Preventing the model from using pronouns.' },
      { id: 'd', label: 'Forcing the model to output identical responses regardless of input.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_16',
    section: 'literacy',
    prompt: 'In a production prompt engineering pipeline, what is the role of an "evaluator prompt" (LLM-as-a-judge)?',
    options: [
      { id: 'a', label: 'It calculates the electric power consumption of the data center.' },
      { id: 'b', label: 'It automatically bills client payment gateways for each generated token.' },
      { id: 'c', label: 'A secondary, highly constrained prompt configured to score primary model outputs against explicit rubric criteria for quality, safety, and correctness.' },
      { id: 'd', label: 'It permanently erases rejected outputs from the training corpus.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_lit_17',
    section: 'literacy',
    prompt: 'Why is structured output mode (such as JSON Schema or Pydantic validation) superior to regex post-processing for production LLM workflows?',
    options: [
      { id: 'a', label: 'Because regex is completely unsupported in modern web servers.' },
      { id: 'b', label: 'Because structured mode forces the model to run 10x faster with zero latency.' },
      { id: 'c', label: 'Because structured mode requires no input tokens.' },
      { id: 'd', label: 'It enforces grammar and schema constraints at the token logit-bias generation level, guaranteeing schema conformity and preventing runtime parse failures.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_lit_18',
    section: 'literacy',
    prompt: 'When designing a prompt for automated translation of specialized medical jargon, what is the best practice?',
    options: [
      { id: 'a', label: 'Provide a verified bilingual glossary of approved terminology and instruct the model to prioritize these definitions over general colloquial translations.' },
      { id: 'b', label: 'Tell the model to simplify all medical terms into basic nursery rhymes.' },
      { id: 'c', label: 'Translate using a general consumer translation engine with zero context.' },
      { id: 'd', label: 'Set temperature to 2.0 to maximize phonetic variety.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_19',
    section: 'literacy',
    prompt: 'What is the danger of "sycophancy" in LLM conversational interactions?',
    options: [
      { id: 'a', label: 'The model crashing due to GPU memory overflow.' },
      { id: 'b', label: 'The model falsely validating erroneous user premises or agreeing with flawed user arguments rather than providing factually accurate pushback.' },
      { id: 'c', label: 'The model writing code exclusively in assembly language.' },
      { id: 'd', label: 'The model refusing to reply in complete sentences.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_20',
    section: 'literacy',
    prompt: 'When prompting an LLM to generate synthetic edge-case test data for software testing, what strategy creates the highest coverage?',
    options: [
      { id: 'a', label: 'Generate 1,000 identical valid email strings.' },
      { id: 'b', label: 'Only ask for random numbers between 1 and 10.' },
      { id: 'c', label: 'Explicitly prompt for boundary conditions, null inputs, unicode stress tests, SQL injection payloads, and malformed structure scenarios.' },
      { id: 'd', label: 'Ask the model to copy real production user credentials.' },
    ],
    correctOptionId: 'c',
  },
];

