import { CertQuestion } from '../types';

export const PRACTITIONER_LITERACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'prac_lit_01',
    section: 'literacy',
    prompt: 'You are generating structured product catalogs. When using an LLM to produce valid JSON, what prompt technique best guarantees machine-parsable syntax?',
    options: [
      { id: 'a', label: 'Ask the model to format nicely with emojis and bullet points' },
      { id: 'b', label: 'Specify a strict JSON schema, supply one-shot valid JSON examples, and explicitly forbid conversational preamble or markdown codeblock wrappers if raw JSON is required' },
      { id: 'c', label: 'Set model temperature to 1.8 to encourage creative parsing' },
      { id: 'd', label: 'Submit the prompt as an unformatted run-on sentence without schema definition' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_02',
    section: 'literacy',
    prompt: 'When crafting a persona prompt for financial analysis, which approach produces the most reliable, rigorous output?',
    options: [
      { id: 'a', label: '"Act as a genius investor who is never wrong and makes quick predictions."' },
      { id: 'b', label: 'Tell the model to give optimistic quarterly revenue projections by default.' },
      { id: 'c', label: 'Use a single-word prompt like "Finance" to avoid biasing the model.' },
      { id: 'd', label: 'Define role scope, analytical methodology (e.g. DCF, DuPont analysis), conservative bias assumptions, and mandatory risk citation steps.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_lit_03',
    section: 'literacy',
    prompt: 'In complex multi-document summarization, how do you prevent the "lost in the middle" phenomenon where models miss facts placed in the center of huge context windows?',
    options: [
      { id: 'a', label: 'Place key instructions and high-priority reference text near the very beginning or end of the prompt context, and prompt with step-by-step chunk extraction.' },
      { id: 'b', label: 'Place all critical extraction instructions exclusively in the middle 50% of the prompt.' },
      { id: 'c', label: 'Disable temperature sampling and force the model to read in reverse.' },
      { id: 'd', label: 'Compress the text into an unpunctuated single-line string.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_04',
    section: 'literacy',
    prompt: 'What is the most effective way to test whether an updated system prompt has degraded existing performance across legacy edge cases?',
    options: [
      { id: 'a', label: 'Run a single casual query and deploy immediately if the output appears reasonable.' },
      { id: 'b', label: 'Ask the LLM in a new chat if it believes the updated prompt is superior.' },
      { id: 'c', label: 'Maintain a regression benchmark test suite of diverse input cases with expected assertion criteria and evaluate outputs deterministically.' },
      { id: 'd', label: 'Rely solely on end-user complaints in production after deployment.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_lit_05',
    section: 'literacy',
    prompt: 'Why should negative constraints (e.g., "Do NOT include greetings") be reinforced with positive guidance (e.g., "Begin directly with the raw data table")?',
    options: [
      { id: 'a', label: 'LLMs process attention tokens more reliably when provided with a clear target trajectory rather than solely unbounded negative bounds.' },
      { id: 'b', label: 'Negative words trigger automatic server-side API error exceptions.' },
      { id: 'c', label: 'Positive prompts cost 50% fewer billing tokens.' },
      { id: 'd', label: 'Negative words invert the model\'s internal sampling temperature.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_06',
    section: 'literacy',
    prompt: 'When summarizing a 50-page legal contract, how should a practitioner calibrate the model to prevent speculative interpretation?',
    options: [
      { id: 'a', label: 'Prompt the model to fill in missing clauses using standard industry conventions.' },
      { id: 'b', label: 'Set temperature to maximum to encourage diverse interpretations.' },
      { id: 'c', label: 'Ask the model to rewrite the contract from memory without referencing text.' },
      { id: 'd', label: 'Instruct the model to quote exact clause numbers and verbatim text excerpts for every assertion, stating "Not specified in document" when text is absent.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_lit_07',
    section: 'literacy',
    prompt: 'What distinguishes zero-shot Chain-of-Thought ("Let\'s think step by step") from standard zero-shot prompting?',
    options: [
      { id: 'a', label: 'It completely bypasses context window token limits.' },
      { id: 'b', label: 'It encourages the model to generate intermediate reasoning tokens, significantly boosting logical and quantitative accuracy before rendering the final conclusion.' },
      { id: 'c', label: 'It automatically invokes external Python code execution without configuration.' },
      { id: 'd', label: 'It eliminates the need to provide task instructions or context.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_08',
    section: 'literacy',
    prompt: 'In prompt calibration, what is "prompt drift"?',
    options: [
      { id: 'a', label: 'Network packet delay caused by high latency server routes.' },
      { id: 'b', label: 'Loss of client authentication tokens during long sessions.' },
      { id: 'c', label: 'Changes in model output quality or style over time due to backend model updates, parameter fine-tuning, or shifting input distribution.' },
      { id: 'd', label: 'Automatic deletion of chat history after 30 days.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_lit_09',
    section: 'literacy',
    prompt: 'How should a practitioner handle inconsistent classification tags when categorizing customer support tickets into fixed enum values?',
    options: [
      { id: 'a', label: 'Allow the model to invent descriptive new category names dynamically.' },
      { id: 'b', label: 'Increase prompt temperature to 1.5 to cover unexpected categories.' },
      { id: 'c', label: 'Prompt the customer to rephrase their inquiry until it matches a single keyword.' },
      { id: 'd', label: 'Provide the exact enum list in the prompt, include 2 examples per enum category, and mandate single-word or JSON-keyed outputs matching the enum.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_lit_10',
    section: 'literacy',
    prompt: 'When drafting automated email responses, what prevents the AI from sounding generic and boilerplate?',
    options: [
      { id: 'a', label: 'Providing a 3-tier style guide (voice, forbidden clichés, concrete sentence structure examples) and contextual variable slots.' },
      { id: 'b', label: 'Adding repetitive hype phrases like "Make this viral and sensational!"' },
      { id: 'c', label: 'Increasing model temperature to 1.9.' },
      { id: 'd', label: 'Writing prompts using exclusively uppercase text.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_11',
    section: 'literacy',
    prompt: 'When designing a prompt for complex comparative analysis between two quarterly balance sheets, which architectural structure maximizes analytical depth?',
    options: [
      { id: 'a', label: 'Ask the model to declare a single "winner" company in one sentence.' },
      { id: 'b', label: 'Use structured multi-pass prompting: Pass 1 extracts raw standardized metrics into a markdown table; Pass 2 computes variance ratios; Pass 3 synthesizes strategic risk commentary.' },
      { id: 'c', label: 'Provide only the raw image screenshots of the reports without OCR text.' },
      { id: 'd', label: 'Set top_p to 0.05 to eliminate comparative metrics.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_12',
    section: 'literacy',
    prompt: 'You notice an LLM is frequently generating subtle factual inaccuracies when summarizing technical RFC specifications. Which prompting modification is most effective?',
    options: [
      { id: 'a', label: 'Tell the model that you will give it a tip of $500 if it makes zero mistakes.' },
      { id: 'b', label: 'Switch to a high temperature setting so it explores wider semantic possibilities.' },
      { id: 'c', label: 'Instruct the model to perform source-grounded extraction: quote the exact paragraph number before each summary bullet, and explicitly note if any technical metric is absent from the text.' },
      { id: 'd', label: 'Remove the RFC specification text and ask the model to summarize from memory.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_lit_13',
    section: 'literacy',
    prompt: 'What is the primary function of the "top_p" (nucleus sampling) parameter in generative AI APIs?',
    options: [
      { id: 'a', label: 'It sets the maximum token length limit for the output buffer.' },
      { id: 'b', label: 'It controls the physical memory allocation on the server GPU.' },
      { id: 'c', label: 'It encrypts the network payload with a public key.' },
      { id: 'd', label: 'It limits token selection to the smallest set whose cumulative probability reaches threshold p, pruning the long tail of unlikely tokens.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_lit_14',
    section: 'literacy',
    prompt: 'When using an LLM to generate SQL queries across a complex database schema, how do you prevent the model from hallucinating non-existent column names?',
    options: [
      { id: 'a', label: 'Provide the exact CREATE TABLE schemas (DDL), column types, and foreign key relationships directly within the system prompt.' },
      { id: 'b', label: 'Ask the model to guess column names based on common tech industry slang.' },
      { id: 'c', label: 'Instruct the AI to use `SELECT *` exclusively without specifying columns.' },
      { id: 'd', label: 'Run the prompt in all-caps.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_15',
    section: 'literacy',
    prompt: 'What is "Self-Consistency" prompting and when is it most beneficial?',
    options: [
      { id: 'a', label: 'Asking the user to repeat the prompt 5 times in the same thread.' },
      { id: 'b', label: 'Sampling multiple distinct reasoning paths from the model at non-zero temperature and selecting the majority/consensus answer across paths for complex reasoning tasks.' },
      { id: 'c', label: 'Preventing the model from using pronouns.' },
      { id: 'd', label: 'Forcing the model to output identical responses regardless of input.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_16',
    section: 'literacy',
    prompt: 'In a production prompt engineering pipeline, what is the role of an "evaluator prompt" (LLM-as-a-judge)?',
    options: [
      { id: 'a', label: 'It calculates the electric power consumption of the data center.' },
      { id: 'b', label: 'It automatically bills client payment gateways for each generated token.' },
      { id: 'c', label: 'A secondary, highly constrained prompt configured to score primary model outputs against explicit rubric criteria for quality, safety, and correctness.' },
      { id: 'd', label: 'It permanently erases rejected outputs from the training corpus.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_lit_17',
    section: 'literacy',
    prompt: 'Why is structured output mode (such as JSON Schema or Pydantic validation) superior to regex post-processing for production LLM workflows?',
    options: [
      { id: 'a', label: 'Because regex is completely unsupported in modern web servers.' },
      { id: 'b', label: 'Because structured mode forces the model to run 10x faster with zero latency.' },
      { id: 'c', label: 'Because structured mode requires no input tokens.' },
      { id: 'd', label: 'It enforces grammar and schema constraints at the token logit-bias generation level, guaranteeing schema conformity and preventing runtime parse failures.' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'prac_lit_18',
    section: 'literacy',
    prompt: 'When designing a prompt for automated translation of specialized medical jargon, what is the best practice?',
    options: [
      { id: 'a', label: 'Provide a verified bilingual glossary of approved terminology and instruct the model to prioritize these definitions over general colloquial translations.' },
      { id: 'b', label: 'Tell the model to simplify all medical terms into basic nursery rhymes.' },
      { id: 'c', label: 'Translate using a general consumer translation engine with zero context.' },
      { id: 'd', label: 'Set temperature to 2.0 to maximize phonetic variety.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_19',
    section: 'literacy',
    prompt: 'What is the danger of "sycophancy" in LLM conversational interactions?',
    options: [
      { id: 'a', label: 'The model crashing due to GPU memory overflow.' },
      { id: 'b', label: 'The model falsely validating erroneous user premises or agreeing with flawed user arguments rather than providing factually accurate pushback.' },
      { id: 'c', label: 'The model writing code exclusively in assembly language.' },
      { id: 'd', label: 'The model refusing to reply in complete sentences.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_20',
    section: 'literacy',
    prompt: 'When prompting an LLM to generate synthetic edge-case test data for software testing, what strategy creates the highest coverage?',
    options: [
      { id: 'a', label: 'Generate 1,000 identical valid email strings.' },
      { id: 'b', label: 'Only ask for random numbers between 1 and 10.' },
      { id: 'c', label: 'Explicitly prompt for boundary conditions, null inputs, unicode stress tests, SQL injection payloads, and malformed structure scenarios.' },
      { id: 'd', label: 'Ask the model to copy real production user credentials.' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'prac_lit_21',
    section: 'literacy',
    prompt: 'An AI engineer needs to guarantee that an LLM extracts data matching an OpenAPI JSON specification without any markdown wrapper ticks. Which technique is most robust?',
    options: [
      { id: 'a', label: 'Use structured outputs (JSON Schema mode / constrained decoding) enforcing the exact schema definition at the model sampler level.' },
      { id: 'b', label: 'Prompt the model with "Please do not use backticks pretty please".' },
      { id: 'c', label: 'Run text regex after generation and delete all vowels.' },
      { id: 'd', label: 'Increase the model temperature to 1.8.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_22',
    section: 'literacy',
    prompt: 'What distinguishes "Self-Consistency Prompting" from standard single-pass Chain-of-Thought reasoning?',
    options: [
      { id: 'a', label: 'Sampling multiple distinct reasoning paths at non-zero temperature and selecting the majority/consensus answer across all paths.' },
      { id: 'b', label: 'Forcing the model to output identical responses on every run by setting temperature to 0.' },
      { id: 'c', label: 'Asking the user to manually verify each reasoning step.' },
      { id: 'd', label: 'Running the prompt exclusively through an encrypted hardware enclave.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_23',
    section: 'literacy',
    prompt: 'When evaluating long-context document synthesis (e.g., 100k token PDF), what is the "Needle In A Haystack" (NIAH) benchmark metric measuring?',
    options: [
      { id: 'a', label: 'The network latency of downloading the PDF file.' },
      { id: 'b', label: 'The model ability to accurately locate, retrieve, and reason over small target facts placed at various depth percentages within a massive context window.' },
      { id: 'c', label: 'The physical temperature of the server rack.' },
      { id: 'd', label: 'The total number of images embedded inside the PDF.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_24',
    section: 'literacy',
    prompt: 'Why is "Negative Constraint Failure" common in LLMs (e.g., model still mentions pink elephants when told "Do not mention pink elephants")?',
    options: [
      { id: 'a', label: 'Negative keywords prime the attention mechanism and semantic token associations, inadvertently increasing the probability of generating related concepts.' },
      { id: 'b', label: 'The model has an adversarial virus.' },
      { id: 'c', label: 'LLMs cannot process the English word "not".' },
      { id: 'd', label: 'Negative constraints violate cloud provider safety rules.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_25',
    section: 'literacy',
    prompt: 'What is "Context Compression" in advanced prompt engineering pipelines?',
    options: [
      { id: 'a', label: 'Converting text files into .zip archives before sending them over HTTP.' },
      { id: 'b', label: 'Algorithmic or LLM-based reduction of source context to remove redundant tokens while preserving essential semantic facts, reducing latency and cost.' },
      { id: 'c', label: 'Deleting all spaces and punctuation from the prompt.' },
      { id: 'd', label: 'Lowering the audio volume of voice models.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_26',
    section: 'literacy',
    prompt: 'How does "Tree-of-Thoughts" (ToT) prompting expand beyond Chain-of-Thought (CoT)?',
    options: [
      { id: 'a', label: 'It explores multiple branching reasoning paths simultaneously, evaluating intermediate heuristics, and backtracking when a path fails.' },
      { id: 'b', label: 'It structures output in biological taxonomy diagrams.' },
      { id: 'c', label: 'It runs the prompt exclusively in forest conservation databases.' },
      { id: 'd', label: 'It limits the prompt to 3 sentences.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_27',
    section: 'literacy',
    prompt: 'When prompting an LLM to write complex SQL queries across normalized database schemas, what information produces the highest query accuracy?',
    options: [
      { id: 'a', label: 'Only the table names without columns or types.' },
      { id: 'b', label: 'DDL schema statements (table names, columns, data types, primary/foreign keys) along with 2-3 sample rows and explicit database dialect (PostgreSQL vs Snowflake).' },
      { id: 'c', label: 'A screenshot of the company logo.' },
      { id: 'd', label: 'Asking the AI to guess the database structure from intuition.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_28',
    section: 'literacy',
    prompt: 'What is the purpose of "Meta-Prompting" in prompt optimization workflows?',
    options: [
      { id: 'a', label: 'Writing prompts about social media advertising.' },
      { id: 'b', label: 'Using an advanced LLM to systematically generate, critique, and refine prompt instructions for a smaller or specialized downstream task model.' },
      { id: 'c', label: 'A prompt that crashes the server intentionally.' },
      { id: 'd', label: 'A prompt written in HTML meta tags.' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'prac_lit_29',
    section: 'literacy',
    prompt: 'In RAG applications, what is "Context Stuffing" and what failure mode does it introduce?',
    options: [
      { id: 'a', label: 'Stuffing thousands of raw text chunks indiscriminately into the context window, causing hallucination, cost inflation, and attention dilution.' },
      { id: 'b', label: 'Filling database tables with random numerical zeros.' },
      { id: 'c', label: 'Using too many emojis in user messages.' },
      { id: 'd', label: 'Overheating the GPU hardware.' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'prac_lit_30',
    section: 'literacy',
    prompt: 'What does "ReAct" (Reasoning + Acting) prompt orchestration combine in agentic execution?',
    options: [
      { id: 'a', label: 'Interleaved cycles of Thought (verbal reasoning), Action (tool execution), and Observation (inspecting tool output) to solve complex goals step-by-step.' },
      { id: 'b', label: 'React.js frontend library components with CSS stylesheets.' },
      { id: 'c', label: 'Chemical reaction simulation formulas.' },
      { id: 'd', label: 'Real-time video streaming processing.' },
    ],
    correctOptionId: 'a',
  },
];


