import { CertQuestion } from '../types';

export const WEBMETHODS_AUTOMATION_QUESTIONS: CertQuestion[] = [
  {
    id: 'wm_aut_01',
    section: 'automation',
    prompt: 'In Universal Messaging (UM), what is the fundamental architectural difference between a Channel and a Queue?',
    options: [
      { id: 'a', label: 'Channels support publish/subscribe messaging where multiple subscribers receive a copy of each event; Queues implement point-to-point delivery where each event is consumed by exactly one subscriber' },
      { id: 'b', label: 'Channels only store messages in RAM; Queues only store messages in relational database tables' },
      { id: 'c', label: 'Queues require SSL/TLS certificates; Channels do not support encryption' },
      { id: 'd', label: 'Channels are deprecated and replaced exclusively by Apache Kafka connectors in webMethods 10.15' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_02',
    section: 'automation',
    prompt: 'When creating an Integration Server Messaging Trigger subscribed to a Universal Messaging channel, what is the difference between "Concurrent" and "Serial" execution mode?',
    options: [
      { id: 'a', label: 'Concurrent writes messages to disk; Serial keeps messages in memory' },
      { id: 'b', label: 'Concurrent processes multiple published documents simultaneously using a pool of worker threads; Serial processes messages strictly one-at-a-time in FIFO order per trigger' },
      { id: 'c', label: 'Serial triggers require XA two-phase commit database transactions' },
      { id: 'd', label: 'Concurrent triggers can only invoke Java services; Serial triggers can only invoke Flow services' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_aut_03',
    section: 'automation',
    prompt: 'How is "Exactly-Once" document delivery guaranteed in a webMethods Integration Server messaging trigger?',
    options: [
      { id: 'a', label: 'By increasing the JVM heap memory to prevent garbage collection pauses' },
      { id: 'b', label: 'By executing the trigger service twice and comparing the resulting XML hashes' },
      { id: 'c', label: 'By maintaining a document history database or cluster cache where unique document UUIDs are tracked within a specified time-to-live (TTL)' },
      { id: 'd', label: 'By enforcing single-threaded execution across all cluster nodes' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_aut_04',
    section: 'automation',
    prompt: 'In webMethods JDBC Adapter, which adapter service template allows developers to execute dynamic queries with optional WHERE clause filters constructed at runtime based on pipeline inputs?',
    options: [
      { id: 'a', label: 'SelectSQL (Standard Select)' },
      { id: 'b', label: 'CustomSQL' },
      { id: 'c', label: 'StoredProcedure' },
      { id: 'd', label: 'DynamicSQL' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_aut_05',
    section: 'automation',
    prompt: 'What type of JDBC Adapter connection must be used when coordinating database operations with Universal Messaging in a unified, atomic two-phase commit (2PC) transaction?',
    options: [
      { id: 'a', label: 'com.wm.adapter.wmjdbc.connection.JDBCXAConnection (XA_TRANSACTION)' },
      { id: 'b', label: 'com.wm.adapter.wmjdbc.connection.JDBCConnection (NO_TRANSACTION)' },
      { id: 'c', label: 'com.wm.adapter.wmjdbc.connection.LOCAL_TRANSACTION' },
      { id: 'd', label: 'com.wm.adapter.wmjdbc.connection.DIRECT_SOCKET' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_06',
    section: 'automation',
    prompt: 'In the JDBC Adapter, what is the key difference between a "PollingNotification" and an "InsertNotification"?',
    options: [
      { id: 'a', label: 'PollingNotification uses an external FTP server to download SQL files' },
      { id: 'b', label: 'PollingNotification periodically queries a database table using a timestamp or status column, whereas InsertNotification uses a database trigger and buffer table to detect newly inserted rows' },
      { id: 'c', label: 'InsertNotification only works with IBM DB2 databases; PollingNotification works with Oracle' },
      { id: 'd', label: 'PollingNotification publishes JMS events; InsertNotification publishes HTTP webhooks' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_aut_07',
    section: 'automation',
    prompt: 'When parsing large CSV or fixed-width text files in webMethods, which component defines the structure, records, and delimiter rules?',
    options: [
      { id: 'a', label: 'WSDL Document Definition' },
      { id: 'b', label: 'IS XML Schema' },
      { id: 'c', label: 'Flat File Schema (and optional Flat File Dictionary)' },
      { id: 'd', label: 'EDIFFSchema definition' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_aut_08',
    section: 'automation',
    prompt: 'Which built-in service from the WmFlatFile package is used to parse a Flat File stream or string into an IS Document based on a Flat File Schema?',
    options: [
      { id: 'a', label: 'pub.flatFile:createSchema' },
      { id: 'b', label: 'pub.flatFile:validateFlatFile' },
      { id: 'c', label: 'pub.file:getFile' },
      { id: 'd', label: 'pub.flatFile:convertToValues' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_aut_09',
    section: 'automation',
    prompt: 'In webMethods SAP Adapter (WmSAP), what communication protocol is used to receive Intermediate Documents (IDocs) and Business Application Programming Interfaces (BAPIs) from SAP ECC / S/4HANA systems?',
    options: [
      { id: 'a', label: 'SAP Java Connector (JCo) using RFC / tRFC / qRFC protocols' },
      { id: 'b', label: 'Standard SOAP 1.2 over JMS' },
      { id: 'c', label: 'ODBC database drivers' },
      { id: 'd', label: 'Direct TCP socket stream without authentication' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_10',
    section: 'automation',
    prompt: 'In SAP Adapter integration, what is the role of the "SAP Transaction ID (TID)" when receiving transactional RFCs (tRFC)?',
    options: [
      { id: 'a', label: 'It specifies the SAP GUI user license key' },
      { id: 'b', label: 'It guarantees idempotency and exactly-once processing by recording the TID in the WmSAP transaction store before executing the Flow service' },
      { id: 'c', label: 'It encrypts the SAP payload with RSA-4096' },
      { id: 'd', label: 'It determines the database table where SAP records are written' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_aut_11',
    section: 'automation',
    prompt: 'What happens when a JDBC Adapter connection pool reaches its "Maximum Pool Size" and all connections are currently in use by active threads?',
    options: [
      { id: 'a', label: 'The Integration Server immediately terminates with an OutOfMemoryError' },
      { id: 'b', label: 'The adapter service drops the incoming transaction without throwing an exception' },
      { id: 'c', label: 'Subsequent requests wait up to the "Block Timeout" for a connection to be released; if none becomes available, a ConnectionException is thrown' },
      { id: 'd', label: 'The connection pool automatically routes queries to Universal Messaging instead' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_aut_12',
    section: 'automation',
    prompt: 'In webMethods CloudStreams, what is the primary architecture used to connect to SaaS applications such as Salesforce, Workday, or ServiceNow?',
    options: [
      { id: 'a', label: 'Direct JDBC database querying into SaaS cloud databases' },
      { id: 'b', label: 'Corba IDL interfaces' },
      { id: 'c', label: 'Local XML file batch transfers' },
      { id: 'd', label: 'CloudStreams Cloud Connectors leveraging OpenAPI/REST or SOAP APIs with built-in OAuth2 token lifecycle management and connection pooling' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_aut_13',
    section: 'automation',
    prompt: 'In webMethods messaging, what is a "Dead Letter Queue" (DLQ) or "Dead Letter Channel"?',
    options: [
      { id: 'a', label: 'A designated channel or queue where unprocessable, poison, or expired messages are routed after exhausting maximum retry attempts' },
      { id: 'b', label: 'A temporary cache used to store messages during server reboot' },
      { id: 'c', label: 'A queue used exclusively for archiving audit logs to cold storage' },
      { id: 'd', label: 'An obsolete webMethods Broker feature that is not supported in Universal Messaging' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_14',
    section: 'automation',
    prompt: 'When configuring a messaging trigger in webMethods, what does the "Retry on Error" configuration accomplish for transient network failures?',
    options: [
      { id: 'a', label: 'It resets the Integration Server JVM heap memory' },
      { id: 'b', label: 'It allows the trigger to suspend document processing and automatically retry the service invocation based on a configured retry count and backoff interval when an ISRuntimeException is thrown' },
      { id: 'c', label: 'It logs the error to the console and marks the message as completed' },
      { id: 'd', label: 'It deletes the message permanently from Universal Messaging' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_aut_15',
    section: 'automation',
    prompt: 'In webMethods messaging triggers, what type of exception must a Flow service throw to trigger the built-in trigger retry mechanism rather than failing immediately?',
    options: [
      { id: 'a', label: 'java.lang.NullPointerException' },
      { id: 'b', label: 'com.wm.app.b2b.server.ServiceException with fatal status' },
      { id: 'c', label: 'com.wm.app.b2b.server.ISRuntimeException (Transient Error)' },
      { id: 'd', label: 'java.io.IOException' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_aut_16',
    section: 'automation',
    prompt: 'What is the role of Terracotta Server Array (TSA) in a clustered webMethods Integration Server environment?',
    options: [
      { id: 'a', label: 'To compile Flow services into native assembly instructions' },
      { id: 'b', label: 'To manage DNS host names for HTTP clients' },
      { id: 'c', label: 'To generate synthetic EDI test messages' },
      { id: 'd', label: 'To provide distributed in-memory state, distributed caching, session replication, and cluster-wide document locking across all IS nodes' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_aut_17',
    section: 'automation',
    prompt: 'In webMethods Business Process Management (BPM) and Designer Process Engine, what mechanism ensures that asynchronous response messages are routed to the correct running process instance?',
    options: [
      { id: 'a', label: 'Correlation IDs mapped in the Receive step' },
      { id: 'b', label: 'Client IP address tracking' },
      { id: 'c', label: 'HTTP Session Cookies' },
      { id: 'd', label: 'JVM Thread IDs' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_18',
    section: 'automation',
    prompt: 'Which adapter package provides integration capabilities with IBM MQ (WebSphere MQ) queues and topics within webMethods Integration Server?',
    options: [
      { id: 'a', label: 'WmJDBC' },
      { id: 'b', label: 'WmMQAdapter (or WmJMS with IBM MQ JMS provider)' },
      { id: 'c', label: 'WmSAP' },
      { id: 'd', label: 'WmCloudStreams' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_aut_19',
    section: 'automation',
    prompt: 'In Universal Messaging Enterprise Manager, what is a "Data Group" configured on a channel?',
    options: [
      { id: 'a', label: 'A database table partition in Oracle' },
      { id: 'b', label: 'A user security group in LDAP' },
      { id: 'c', label: 'A clustering and storage allocation mechanism that dictates how event data is physically distributed, serialized, and stored across disk drives' },
      { id: 'd', label: 'A graphical user interface layout configuration' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_aut_20',
    section: 'automation',
    prompt: 'When working with webMethods Microservices Runtime (MSR), what lightweight configuration approach is used to externalize environment-specific settings (database URLs, passwords, ports) in Docker / Kubernetes deployments?',
    options: [
      { id: 'a', label: 'Editing binary .class files directly in the Docker image' },
      { id: 'b', label: 'Hardcoding variables in Flow MAP steps' },
      { id: 'c', label: 'Manual web browser administration after container startup' },
      { id: 'd', label: 'Application Configuration Properties (application.properties / YAML) and Environment Variable substitution' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_aut_21',
    section: 'automation',
    prompt: 'In webMethods JDBC Adapter, what is the function of the "BatchInsertSQL" adapter service template?',
    options: [
      { id: 'a', label: 'To insert multiple records into a database table in a single atomic network roundtrip for high-performance bulk operations' },
      { id: 'b', label: 'To execute background schema migrations on the database server' },
      { id: 'c', label: 'To create new database users and grant privileges' },
      { id: 'd', label: 'To export database tables to CSV format' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_22',
    section: 'automation',
    prompt: 'In Universal Messaging, what protocol does the `nsp://` connection URL represent?',
    options: [
      { id: 'a', label: 'Network Service Protocol over unencrypted HTTP' },
      { id: 'b', label: 'Nirvana Socket Protocol over standard TCP socket connection' },
      { id: 'c', label: 'Named Socket Pipes on Windows' },
      { id: 'd', label: 'Native Simple Protocol over UDP broadcast' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_aut_23',
    section: 'automation',
    prompt: 'In Universal Messaging, what protocol prefix is used when connecting via TLS/SSL encrypted Nirvana Socket Protocol?',
    options: [
      { id: 'a', label: 'https://' },
      { id: 'b', label: 'ssl://' },
      { id: 'c', label: 'nhps:// or nsps://' },
      { id: 'd', label: 'tcps://' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_aut_24',
    section: 'automation',
    prompt: 'In webMethods Designer, what is an "Adapter Notification" primarily used for?',
    options: [
      { id: 'a', label: 'Sending SMS alerts to system administrators' },
      { id: 'b', label: 'Showing popup notifications in the Designer IDE' },
      { id: 'c', label: 'Logging audit messages to the operating system syslog' },
      { id: 'd', label: 'Monitoring an external backend resource (like a database or SAP system) for data events and automatically publishing an IS Document when an event occurs' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_aut_25',
    section: 'automation',
    prompt: 'What is the purpose of the "Suspend Trigger" administrative action in webMethods Integration Server Administrator?',
    options: [
      { id: 'a', label: 'It halts document retrieval and execution for the trigger without deleting the trigger configuration or losing queued messages in Universal Messaging' },
      { id: 'b', label: 'It permanently deletes the trigger service from the file system' },
      { id: 'c', label: 'It purges all unconsumed events from Universal Messaging' },
      { id: 'd', label: 'It disconnects the Integration Server from the database' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_26',
    section: 'automation',
    prompt: 'In webMethods Task Engine, what is a "Human Task" in the context of BPM integration?',
    options: [
      { id: 'a', label: 'A manual script executed in the Linux terminal' },
      { id: 'b', label: 'A workflow activity requiring human interaction, review, or approval through a web-based task interface (My webMethods Server / MWS)' },
      { id: 'c', label: 'An automated cron job that runs without user intervention' },
      { id: 'd', label: 'A Flow service that requires developer debugging at runtime' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_aut_27',
    section: 'automation',
    prompt: 'What tool in the webMethods suite is used to configure, administer, and monitor Universal Messaging realms, clusters, channels, and queues?',
    options: [
      { id: 'a', label: 'Software AG Command Central' },
      { id: 'b', label: 'Integration Server Administrator web console' },
      { id: 'c', label: 'Universal Messaging Enterprise Manager (nEnterpriseManager)' },
      { id: 'd', label: 'Trading Networks Console' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_aut_28',
    section: 'automation',
    prompt: 'In webMethods Flat File Schema, what is a "Record Identifier"?',
    options: [
      { id: 'a', label: 'The primary key integer generated by an Oracle sequence' },
      { id: 'b', label: 'The MAC address of the server sending the file' },
      { id: 'c', label: 'The SHA-256 hash of the entire flat file' },
      { id: 'd', label: 'A specific string or character sequence at a fixed position in a line (e.g., "HDR", "DTL", "TRL") that identifies which record definition to apply when parsing the line' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_aut_29',
    section: 'automation',
    prompt: 'What is the purpose of configuring "Join Conditions" (All or Any) in a webMethods messaging trigger?',
    options: [
      { id: 'a', label: 'To allow the trigger to wait for multiple distinct published document types before firing the target service' },
      { id: 'b', label: 'To perform SQL JOIN operations across multiple relational databases' },
      { id: 'c', label: 'To merge two Git repositories into a single branch' },
      { id: 'd', label: 'To link multiple Integration Server nodes into an OS-level cluster' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_30',
    section: 'automation',
    prompt: 'In webMethods, what is the role of WmART (Adapter Runtime)?',
    options: [
      { id: 'a', label: 'To render 3D graphics in the Designer UI' },
      { id: 'b', label: 'To provide a standardized underlying framework for all webMethods adapters (JDBC, SAP, MQ) to manage connection pooling, transaction coordination, and notification life cycles' },
      { id: 'c', label: 'To generate automated code documentation in HTML format' },
      { id: 'd', label: 'To act as an HTTP load balancer in front of Integration Server' },
    ],
    correctOptionId: 'b',
  },
];
