import { CertQuestion } from '../types';

export const WEBMETHODS_AUTOMATION_QUESTIONS: CertQuestion[] = [
  {
    id: 'wm_aut_01',
    section: 'automation',
    prompt: 'In Universal Messaging (UM), what is the fundamental architectural difference between a Channel and a Queue?',
    options: [
      { id: 'a', label: 'Channels support publish/subscribe messaging where multiple subscribers receive a copy of each event; Queues implement point-to-point delivery where each event is consumed by exactly one subscriber' },
      { id: 'b', label: 'Channels only store messages in RAM; Queues only store messages in relational databases' },
      { id: 'c', label: 'Queues require SSL/TLS certificates; Channels do not support encryption' },
      { id: 'd', label: 'Channels are deprecated and replaced by Apache Kafka connectors in webMethods 10.15' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_02',
    section: 'automation',
    prompt: 'When creating an Integration Server Messaging Trigger subscribed to a Universal Messaging channel, what is the difference between "Concurrent" and "Serial" execution mode?',
    options: [
      { id: 'a', label: 'Concurrent processes multiple published documents simultaneously using a pool of worker threads; Serial processes messages strictly one-at-a-time in FIFO order per trigger' },
      { id: 'b', label: 'Concurrent writes messages to disk; Serial keeps messages in memory' },
      { id: 'c', label: 'Serial triggers require XA two-phase commit database transactions' },
      { id: 'd', label: 'Concurrent triggers can only invoke Java services; Serial triggers can only invoke Flow services' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_03',
    section: 'automation',
    prompt: 'How is "Exactly-Once" document delivery guaranteed in a webMethods Integration Server messaging trigger?',
    options: [
      { id: 'a', label: 'By increasing the JVM heap memory to prevent garbage collection pauses' },
      { id: 'b', label: 'By maintaining a document history database or cluster cache where unique document UUIDs are tracked within a specified time-to-live (TTL)' },
      { id: 'c', label: 'By executing the trigger service twice and comparing the resulting XML hashes' },
      { id: 'd', label: 'By enforcing single-threaded execution across all cluster nodes' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_aut_04',
    section: 'automation',
    prompt: 'In webMethods JDBC Adapter, which adapter service template allows developers to execute dynamic queries with optional WHERE clause filters constructed at runtime based on pipeline inputs?',
    options: [
      { id: 'a', label: 'SelectSQL (Standard Select)' },
      { id: 'b', label: 'DynamicSQL' },
      { id: 'c', label: 'CustomSQL' },
      { id: 'd', label: 'StoredProcedure' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_aut_05',
    section: 'automation',
    prompt: 'What type of JDBC Adapter connection must be used when coordinating database operations with Universal Messaging in a unified, atomic two-phase commit (2PC) transaction?',
    options: [
      { id: 'a', label: 'com.wm.adapter.wmjdbc.connection.JDBCConnection (NO_TRANSACTION)' },
      { id: 'b', label: 'com.wm.adapter.wmjdbc.connection.JDBCXAConnection (XA_TRANSACTION)' },
      { id: 'c', label: 'com.wm.adapter.wmjdbc.connection.LOCAL_TRANSACTION' },
      { id: 'd', label: 'com.wm.adapter.wmjdbc.connection.DIRECT_SOCKET' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_aut_06',
    section: 'automation',
    prompt: 'Which built-in services are called to delineate and manage a local or XA transaction boundary across multiple adapter services in a Flow service?',
    options: [
      { id: 'a', label: 'pub.art.transaction:startTransaction, commitTransaction, and rollbackTransaction' },
      { id: 'b', label: 'pub.flow:beginTransaction, endTransaction, and cancelTransaction' },
      { id: 'c', label: 'pub.db:openSession, saveSession, and abortSession' },
      { id: 'd', label: 'pub.jms:initTx, completeTx, and revertTx' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_07',
    section: 'automation',
    prompt: 'In Universal Messaging, what protocol is standardly used by Integration Server clients to communicate with UM Realm Servers over high-performance sockets?',
    options: [
      { id: 'a', label: 'nsp (Nirvana Socket Protocol) or nhps (Nirvana HTTPS Socket Protocol)' },
      { id: 'b', label: 'gRPC over HTTP/3' },
      { id: 'c', label: 'AMQP 0-9-1 strictly' },
      { id: 'd', label: 'RMI / IIOP' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_08',
    section: 'automation',
    prompt: 'In webMethods SAP Adapter, which communication model is used to receive intermediate business documents (IDocs) asynchronously from an SAP ERP system into Integration Server?',
    options: [
      { id: 'a', label: 'SAP tRFC / qRFC listener registered on Integration Server via SAP JCo (Java Connector)' },
      { id: 'b', label: 'Polling SAP database tables via JDBC Adapter' },
      { id: 'c', label: 'Parsing SAP GUI screen scrapes via HTTP' },
      { id: 'd', label: 'Connecting to SAP HANA through an OData read-only feed' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_09',
    section: 'automation',
    prompt: 'What is an "Adapter Notification" in the webMethods JDBC Adapter architecture?',
    options: [
      { id: 'a', label: 'An automated email sent to DBAs when tables reach 90% capacity' },
      { id: 'b', label: 'An event-driven mechanism (polling or trigger-based) that detects row changes in database tables and automatically publishes an IS document' },
      { id: 'c', label: 'A pop-up alert displayed in Software AG Designer when SQL syntax is invalid' },
      { id: 'd', label: 'A health check metric published to Prometheus' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_aut_10',
    section: 'automation',
    prompt: 'When a webMethods trigger encounters a transient error (such as a temporary database disconnect), how can automatic retry behavior be configured?',
    options: [
      { id: 'a', label: 'By throwing a ISRuntimeException and enabling Retry Handling on the Trigger with specified max retry attempts and retry interval' },
      { id: 'b', label: 'By restarting the Integration Server operating system service' },
      { id: 'c', label: 'By placing an infinite REPEAT loop in the trigger service Catch block' },
      { id: 'd', label: 'By duplicating the document across 5 different Universal Messaging queues' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_11',
    section: 'automation',
    prompt: 'What occurs when a document in an IS Messaging Trigger exceeds its maximum retry attempts without successful processing?',
    options: [
      { id: 'a', label: 'It is routed to the configured Dead Letter Queue (DLQ) or Trigger Failure Service, and an error audit log is generated' },
      { id: 'b', label: 'It permanently crashes the Universal Messaging Realm Server' },
      { id: 'c', label: 'It silently drops the message without notification' },
      { id: 'd', label: 'It automatically reverts all Git commits made in the current release' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_12',
    section: 'automation',
    prompt: 'What tool within the Universal Messaging suite is used to visually inspect channels, monitor message lag, purge queues, and administer UM cluster realms?',
    options: [
      { id: 'a', label: 'Universal Messaging Enterprise Manager' },
      { id: 'b', label: 'Software AG Designer' },
      { id: 'c', label: 'Integration Server Administrator' },
      { id: 'd', label: 'webMethods Broker Admin GUI' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_13',
    section: 'automation',
    prompt: 'In webMethods CloudStreams, what is the role of CloudStreams Connectors and CloudStreams Provider Packages?',
    options: [
      { id: 'a', label: 'They provide pre-built SaaS integration metadata, OAuth token handling, and REST/SOAP wrappers for platforms like Salesforce, ServiceNow, and AWS' },
      { id: 'b', label: 'They stream live video feeds between Integration Server nodes' },
      { id: 'c', label: 'They replace Integration Server with AWS Lambda functions' },
      { id: 'd', label: 'They compile Flow services into C++ shared libraries' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_14',
    section: 'automation',
    prompt: 'Which service in WmPublic is invoked to send an HTTP or HTTPS request to an external REST endpoint with customized query parameters, headers, and request payload?',
    options: [
      { id: 'a', label: 'pub.client:http' },
      { id: 'b', label: 'pub.net:sendHttpRequest' },
      { id: 'c', label: 'pub.soap:invokeHttp' },
      { id: 'd', label: 'pub.rest:executeCall' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_15',
    section: 'automation',
    prompt: 'In webMethods JMS architecture, what object defines the JNDI lookup properties and connection parameters used by IS to connect to an external JMS Provider (such as IBM MQ or ActiveMQ)?',
    options: [
      { id: 'a', label: 'JMS Connection Alias' },
      { id: 'b', label: 'Flat File Schema' },
      { id: 'c', label: 'WSDL Port' },
      { id: 'd', label: 'JDBC Connection Pool' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_16',
    section: 'automation',
    prompt: 'What happens when "pub.publish:publish" is invoked in a Flow service with a publishable IS Document Type?',
    options: [
      { id: 'a', label: 'The document is formatted, serialized, and sent to the configured messaging provider (Universal Messaging or webMethods Broker)' },
      { id: 'b', label: 'The document is printed directly to an office network printer' },
      { id: 'c', label: 'The document is committed to a local SQLite database' },
      { id: 'd', label: 'The document is converted into an HTML webpage' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_17',
    section: 'automation',
    prompt: 'What is a "Publishable Document Type" in webMethods Integration Server?',
    options: [
      { id: 'a', label: 'An IS Document Type linked to an underlying Universal Messaging event type schema containing messaging metadata and time-to-live attributes' },
      { id: 'b', label: 'A document that can be viewed without logging in to the IS Admin page' },
      { id: 'c', label: 'A document formatted exclusively as PDF for download' },
      { id: 'd', label: 'A document uploaded to an open public FTP server' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_18',
    section: 'automation',
    prompt: 'In a webMethods JDBC Adapter Connection pool, what occurs if all connections in the pool are currently active and a new service requests a database connection?',
    options: [
      { id: 'a', label: 'The request blocks and waits up to the configured "Block Timeout" duration before throwing an adapter exception if no connection is freed' },
      { id: 'b', label: 'Integration Server immediately crashes and generates a core dump' },
      { id: 'c', label: 'The database query is silently dropped and returns an empty recordset' },
      { id: 'd', label: 'The transaction is automatically converted to an asynchronous JMS message' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_19',
    section: 'automation',
    prompt: 'Which service in WmPublic is used to schedule a recurring background task in Integration Server (e.g., executing a cleanup service every night at midnight)?',
    options: [
      { id: 'a', label: 'pub.scheduler:addComplexTask' },
      { id: 'b', label: 'pub.timer:scheduleInterval' },
      { id: 'c', label: 'pub.flow:delayExecution' },
      { id: 'd', label: 'pub.task:createDaemon' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_20',
    section: 'automation',
    prompt: 'What is the purpose of the "Suspend/Resume Trigger" capability in webMethods Integration Server Administrator?',
    options: [
      { id: 'a', label: 'To temporarily halt message consumption from Universal Messaging during backend maintenance without deleting the trigger configuration' },
      { id: 'b', label: 'To delete all undelivered messages from the messaging server' },
      { id: 'c', label: 'To revoke developer licenses in Software AG Designer' },
      { id: 'd', label: 'To restart the Integration Server HTTP port' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_21',
    section: 'automation',
    prompt: 'When integrating with SAP via BAPIs (Business Application Programming Interfaces) using the webMethods SAP Adapter, what adapter service template is utilized?',
    options: [
      { id: 'a', label: 'RFC / BAPI Function Adapter Service (Synchronous Request-Response)' },
      { id: 'b', label: 'Direct SQL Select Template' },
      { id: 'c', label: 'Flat File Translator' },
      { id: 'd', label: 'JMS Queue Consumer' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_22',
    section: 'automation',
    prompt: 'In Universal Messaging, what is a "Durable Subscriber"?',
    options: [
      { id: 'a', label: 'A subscriber whose subscription state and unconsumed messages are preserved across client restarts and network disconnections' },
      { id: 'b', label: 'A user account with permanent administrative privileges in UM Enterprise Manager' },
      { id: 'c', label: 'A hardware appliance with redundant power supplies' },
      { id: 'd', label: 'A client that only accepts encrypted SSL connections' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_23',
    section: 'automation',
    prompt: 'Which webMethods built-in service publishes a document to a channel and synchronously waits for a reply document on a transient response channel?',
    options: [
      { id: 'a', label: 'pub.publish:publishAndWait' },
      { id: 'b', label: 'pub.publish:deliver' },
      { id: 'c', label: 'pub.jms:sendAndForget' },
      { id: 'd', label: 'pub.flow:callAsync' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_24',
    section: 'automation',
    prompt: 'In webMethods Trigger configuration, what is a "Filter Condition"?',
    options: [
      { id: 'a', label: 'A query expression (e.g., %Order/Amount% > 5000) evaluated by the messaging layer to ensure only matching events trigger the service' },
      { id: 'b', label: 'A firewall rule blocking unauthorized IP addresses' },
      { id: 'c', label: 'An antivirus scanner for incoming attachments' },
      { id: 'd', label: 'A CSS filter applied to IS Admin pages' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_25',
    section: 'automation',
    prompt: 'What adapter service template in the JDBC Adapter executes database stored procedures with IN, OUT, and INOUT parameter mappings?',
    options: [
      { id: 'a', label: 'StoredProcedure' },
      { id: 'b', label: 'BatchInsert' },
      { id: 'c', label: 'DynamicSQL' },
      { id: 'd', label: 'ExecuteDDL' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_26',
    section: 'automation',
    prompt: 'What is the purpose of "BatchInsertSQL" in the webMethods JDBC Adapter?',
    options: [
      { id: 'a', label: 'To insert multiple database records in a single batched network round-trip for optimized throughput and reduced latency' },
      { id: 'b', label: 'To generate synthetic test data in a development database' },
      { id: 'c', label: 'To insert records into 5 different databases simultaneously' },
      { id: 'd', label: 'To automatically partition database tables' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_27',
    section: 'automation',
    prompt: 'In Universal Messaging, what feature allows distributing published events across multiple clustered UM Realm Server nodes for high-availability messaging?',
    options: [
      { id: 'a', label: 'Universal Messaging Shared Channels & Active/Active Clustering' },
      { id: 'b', label: 'DNS Round Robin without replication' },
      { id: 'c', label: 'Local SQLite database synchronization' },
      { id: 'd', label: 'Manual message file export and import' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_28',
    section: 'automation',
    prompt: 'Which service in WmPublic is used to send emails with attachments (e.g., automated error reports or invoice attachments) via SMTP?',
    options: [
      { id: 'a', label: 'pub.client:smtp' },
      { id: 'b', label: 'pub.mail:sendMail' },
      { id: 'c', label: 'pub.email:deliver' },
      { id: 'd', label: 'pub.net:sendEmail' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_29',
    section: 'automation',
    prompt: 'When a webMethods trigger uses "Join Conditions", what capability does it provide?',
    options: [
      { id: 'a', label: 'It correlates and waits for multiple distinct document types to arrive before invoking the target service (AND/OR join)' },
      { id: 'b', label: 'It joins two relational database tables using SQL INNER JOIN' },
      { id: 'c', label: 'It merges two Git repository branches during deployment' },
      { id: 'd', label: 'It concatenates two string variables into one' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_aut_30',
    section: 'automation',
    prompt: 'What is the function of the "Connection Minimum Pool Size" and "Connection Maximum Pool Size" parameters in JDBC Adapter Connections?',
    options: [
      { id: 'a', label: 'They establish the baseline number of warm connections kept open and the ceiling limit of concurrent database connections allowed' },
      { id: 'b', label: 'They define the minimum and maximum file size of SQL scripts' },
      { id: 'c', label: 'They set the minimum and maximum CPU cores allocated to JDBC drivers' },
      { id: 'd', label: 'They restrict the number of rows returned by SQL queries' },
    ],
    correctOptionId: 'a',
  },
];
