import { CertQuestion } from '../types';

export const WEBMETHODS_GROWTH_QUESTIONS: CertQuestion[] = [
  {
    id: 'wm_gro_01',
    section: 'growth',
    prompt: 'In webMethods Trading Networks (TN), what core objects define how incoming B2B business documents (e.g., EDI 850, Purchase Orders) are routed, transformed, and delivered?',
    options: [
      { id: 'a', label: 'Partner Profiles, TN Document Types, and Processing Rules' },
      { id: 'b', label: 'JDBC Adapter Connections and SQL Stored Procedures' },
      { id: 'c', label: 'Flat File Schemas and Java Source Files' },
      { id: 'd', label: 'Universal Messaging Channel Realms exclusively' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_02',
    section: 'growth',
    prompt: 'What is the role of a "Processing Rule" in webMethods Trading Networks?',
    options: [
      { id: 'a', label: 'Matches criteria (Sender, Receiver, Document Type, User Attributes) on received documents and executes defined actions like saving to TN, invoking an IS service, or queuing for delivery' },
      { id: 'b', label: 'Compiles Java services into native machine code' },
      { id: 'c', label: 'Enforces database primary key constraints' },
      { id: 'd', label: 'Generates payroll reports for IT administrators' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_03',
    section: 'growth',
    prompt: 'In B2B supply chain integrations using webMethods EDI Module, what standard electronic acknowledgement is generated to confirm receipt and syntactic validity of an ANSI X12 document?',
    options: [
      { id: 'a', label: 'Functional Acknowledgement (ANSI X12 997 / 999)' },
      { id: 'b', label: 'HTTP 204 No Content' },
      { id: 'c', label: 'SMTP Read Receipt' },
      { id: 'd', label: 'Database COMMIT acknowledgment' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_04',
    section: 'growth',
    prompt: 'What is the EDIFACT equivalent of the ANSI X12 997 Functional Acknowledgement in UN/EDIFACT standard messaging?',
    options: [
      { id: 'a', label: 'CONTRL message' },
      { id: 'b', label: 'INVOIC message' },
      { id: 'c', label: 'DESADV message' },
      { id: 'd', label: 'ORDERS message' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_05',
    section: 'growth',
    prompt: 'What secure point-to-point B2B transport protocol combining HTTP/S, S/MIME encryption, digital signatures, and Synchronous/Asynchronous MDN (Message Disposition Notification) is standard in Trading Networks?',
    options: [
      { id: 'a', label: 'AS2 (Applicability Statement 2)' },
      { id: 'b', label: 'SNMPv3' },
      { id: 'c', label: 'Telnet' },
      { id: 'd', label: 'Plain unencrypted FTP' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_06',
    section: 'growth',
    prompt: 'What is webMethods Microservices Runtime (MSR) and how does it differ from traditional Integration Server?',
    options: [
      { id: 'a', label: 'A lightweight, container-optimized edition of Integration Server designed for fast startup, low memory footprint, Docker packaging, and cloud-native Kubernetes orchestration' },
      { id: 'b', label: 'A hardware mainframe appliance sold by IBM' },
      { id: 'c', label: 'A desktop spreadsheet tool for data analysis' },
      { id: 'd', label: 'A client-side JavaScript browser library' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_07',
    section: 'growth',
    prompt: 'How is stateful caching and cluster coordination achieved across multiple active webMethods Integration Server nodes?',
    options: [
      { id: 'a', label: 'Using Terracotta distributed in-memory clustering and caching infrastructure' },
      { id: 'b', label: 'Sharing an unformatted text file on an NFS network share' },
      { id: 'c', label: 'Manually copying memory dumps over SSH every 5 minutes' },
      { id: 'd', label: 'Using browser local storage' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_08',
    section: 'growth',
    prompt: 'What is the webMethods Asset Build Environment (ABE) and what is its role in enterprise CI/CD pipelines?',
    options: [
      { id: 'a', label: 'A headless command-line build tool that extracts packages and assets from source control (Git) and compiles them into deployable build artifacts (.zip) for webMethods Deployer' },
      { id: 'b', label: 'A graphical 3D modeling tool for server rack layouts' },
      { id: 'c', label: 'A billing management system for cloud hosting fees' },
      { id: 'd', label: 'An antivirus scanner for software repositories' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_09',
    section: 'growth',
    prompt: 'Which tool in the webMethods suite automates the multi-environment deployment (DEV -> QA -> PROD) of packages, adapter connections, user accounts, and Universal Messaging assets?',
    options: [
      { id: 'a', label: 'webMethods Deployer (CLI & Web UI)' },
      { id: 'b', label: 'Software AG Designer' },
      { id: 'c', label: 'Windows File Explorer' },
      { id: 'd', label: 'Universal Messaging Enterprise Manager' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_10',
    section: 'growth',
    prompt: 'When deploying webMethods Microservices Runtime (MSR) on Kubernetes, how are environment-specific configurations (e.g., database URLs, UM endpoints) injected dynamically?',
    options: [
      { id: 'a', label: 'Using Kubernetes ConfigMaps and Secrets mapped to IS configuration variables or application.properties' },
      { id: 'b', label: 'Hardcoding production passwords into the Docker container image' },
      { id: 'c', label: 'Manually logging in to each container via SSH and editing files' },
      { id: 'd', label: 'Emailing connection strings to the container on startup' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_11',
    section: 'growth',
    prompt: 'In Trading Networks, what is an "MDN" (Message Disposition Notification) in the context of AS2 transmissions?',
    options: [
      { id: 'a', label: 'A cryptographically signed electronic receipt sent by the receiver to confirm that the AS2 payload was received intact and matches the sender MIC (Message Integrity Check)' },
      { id: 'b', label: 'An error message indicating that the receiver hard drive is full' },
      { id: 'c', label: 'A billing invoice for AS2 bandwidth consumption' },
      { id: 'd', label: 'A DNS query resolving the partner IP address' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_12',
    section: 'growth',
    prompt: 'What open-source testing framework is natively used in webMethods CI/CD pipelines to execute automated unit and integration tests against Flow and Java services?',
    options: [
      { id: 'a', label: 'WmTestSuite (built on JUnit and Ant/Maven)' },
      { id: 'b', label: 'Selenium WebDriver exclusively' },
      { id: 'c', label: 'Postman Desktop GUI only' },
      { id: 'd', label: 'JMeter without assertions' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_13',
    section: 'growth',
    prompt: 'In high-volume enterprise environments, what architectural pattern ensures that high-priority integration traffic is not starved by large batch file processing in Integration Server?',
    options: [
      { id: 'a', label: 'Configuring dedicated IS Execution Thread Pools and separate HTTP/HTTPS listening ports with allocated thread quotas' },
      { id: 'b', label: 'Running all integrations sequentially on a single thread' },
      { id: 'c', label: 'Rebooting the server whenever CPU usage exceeds 50%' },
      { id: 'd', label: 'Compressing all database tables using ZIP compression' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_14',
    section: 'growth',
    prompt: 'In webMethods Trading Networks, what is a "Custom Document Attribute"?',
    options: [
      { id: 'a', label: 'A business field (such as PO Number, Invoice Total, or Customer ID) extracted from the document payload using XPath/WQL and indexed in the TN database for tracking and search queries' },
      { id: 'b', label: 'A CSS class used to style HTML receipts' },
      { id: 'c', label: 'A file permission on the Linux operating system' },
      { id: 'd', label: 'A database table column constraint' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_15',
    section: 'growth',
    prompt: 'What is the function of "Trading Networks Archiving and Purging" utility scripts?',
    options: [
      { id: 'a', label: 'To archive old processed transaction records to historical storage and purge expired entries from operational tables to sustain database query performance' },
      { id: 'b', label: 'To delete all partner trading profiles when contracts expire' },
      { id: 'c', label: 'To remove unused Java classes from the JVM heap' },
      { id: 'd', label: 'To wipe the server operating system' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_16',
    section: 'growth',
    prompt: 'When building a containerized webMethods MSR Docker image, what is the best practice for package installation?',
    options: [
      { id: 'a', label: 'Copying pre-built, tested package folders into the /opt/softwareag/IntegrationServer/packages directory during Docker image build' },
      { id: 'b', label: 'Manually uploading ZIP files via the IS Admin UI after the container is running in production' },
      { id: 'c', label: 'Checking out source code directly inside the production pod from a public GitHub branch' },
      { id: 'd', label: 'Downloading packages over unencrypted FTP on container boot' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_17',
    section: 'growth',
    prompt: 'In webMethods Terracotta clustering, what is the "Terracotta Server Array" (TSA)?',
    options: [
      { id: 'a', label: 'The clustered server tier that manages distributed memory, data replication, and high-availability state across Integration Server nodes' },
      { id: 'b', label: 'A physical rack of hard disk drives' },
      { id: 'c', label: 'A specialized GPU accelerator for AI model training' },
      { id: 'd', label: 'A network router used for internet routing' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_18',
    section: 'growth',
    prompt: 'What is the purpose of "Large Document Handling" in webMethods Trading Networks?',
    options: [
      { id: 'a', label: 'Allows TN to stream multi-gigabyte EDI/XML documents directly to disk/storage without buffering the entire document into RAM, preventing memory exhaustion' },
      { id: 'b', label: 'Splits documents into 100 separate emails' },
      { id: 'c', label: 'Compresses files using RAR format' },
      { id: 'd', label: 'Converts documents into monochrome images' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_19',
    section: 'growth',
    prompt: 'In webMethods Deployer, what is a "Project" and "Deployment Map"?',
    options: [
      { id: 'a', label: 'A Project defines the source assets to deploy; the Deployment Map pairs source assets with specific target server clusters and applies environment substitution variables' },
      { id: 'b', label: 'A software architecture diagram created in Visio' },
      { id: 'c', label: 'A road map for IT department career growth' },
      { id: 'd', label: 'A geographical map of cloud data centers' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_20',
    section: 'growth',
    prompt: 'How can Kubernetes liveness and readiness probes be configured for webMethods Microservices Runtime (MSR)?',
    options: [
      { id: 'a', label: 'By pointing HTTP probes to the built-in health endpoint: /invoke/pub.utils:ping or custom health check Flow services' },
      { id: 'b', label: 'By pinging the node operating system via ICMP ping only' },
      { id: 'c', label: 'By querying the Universal Messaging Enterprise Manager GUI' },
      { id: 'd', label: 'By checking if the server power LED is green' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_21',
    section: 'growth',
    prompt: 'In Trading Networks, what happens if an incoming document matches multiple Processing Rules configured in the TN rule list?',
    options: [
      { id: 'a', label: 'Trading Networks executes only the first matching rule in top-to-bottom order (unless the rule is explicitly configured to continue evaluating)' },
      { id: 'b', label: 'TN crashes and rejects the document' },
      { id: 'c', label: 'TN executes all rules backwards from bottom to top' },
      { id: 'd', label: 'TN randomly selects one rule using a random number generator' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_22',
    section: 'growth',
    prompt: 'What is the role of the "SEF" (Standard Exchange Format) file in the webMethods EDI module?',
    options: [
      { id: 'a', label: 'An open-standard schema file describing the syntax, segments, elements, and codelists of specific EDI standards used to generate IS EDI Document Types' },
      { id: 'b', label: 'A cryptographic private key file used for SSH' },
      { id: 'c', label: 'A binary executable that installs Software AG Designer' },
      { id: 'd', label: 'A database export dump file' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_23',
    section: 'growth',
    prompt: 'In a high-availability Universal Messaging cluster, what protocol handles leader election and transactional state consensus among UM Realm Server nodes?',
    options: [
      { id: 'a', label: 'Raft consensus / Paxos-based cluster quorum protocol' },
      { id: 'b', label: 'Manual administrative failover command only' },
      { id: 'c', label: 'HTTP GET polling every 60 seconds' },
      { id: 'd', label: 'Broadcast UDP packets without acknowledgement' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_24',
    section: 'growth',
    prompt: 'What capability does the "pub.event:emit" service provide in modern event-driven webMethods architectures?',
    options: [
      { id: 'a', label: 'Emits structured CloudEvents-compliant business events directly to event brokers like Apache Kafka, Universal Messaging, or AWS EventBridge' },
      { id: 'b', label: 'Plays an audio beep through server hardware speakers' },
      { id: 'c', label: 'Emits smoke signals for physical data center monitoring' },
      { id: 'd', label: 'Sends SMS text messages to all system administrators' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_25',
    section: 'growth',
    prompt: 'How does webMethods Support Zero Downtime Deployments in clustered production environments?',
    options: [
      { id: 'a', label: 'Using Rolling Upgrades with package dynamic reloading, drainage of in-flight sessions via load balancers, and Terracotta cluster state persistence' },
      { id: 'b', label: 'Shutting down all production servers for 8 hours on Saturday nights' },
      { id: 'c', label: 'Deleting the production database before deployment' },
      { id: 'd', label: 'Disabling all error logging during releases' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_26',
    section: 'growth',
    prompt: 'What is the purpose of "Trading Networks Delivery Queues"?',
    options: [
      { id: 'a', label: 'To buffer outbound B2B documents destined for trading partners and deliver them asynchronously with configurable retry intervals, throttling, and schedule windows' },
      { id: 'b', label: 'To store physical shipments in partner warehouses' },
      { id: 'c', label: 'To queue print jobs in the corporate mailroom' },
      { id: 'd', label: 'To hold incoming customer service phone calls' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_27',
    section: 'growth',
    prompt: 'In webMethods Microservices Runtime, what is the role of the "packages.json" or "manifest.json" file when building autonomous containerized services?',
    options: [
      { id: 'a', label: 'Declares package dependencies, external Git repository URLs, and version tags for automated headless assembly and container building' },
      { id: 'b', label: 'Contains customer billing credit card information' },
      { id: 'c', label: 'Stores user passwords in cleartext' },
      { id: 'd', label: 'Configures desktop monitor resolutions' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_28',
    section: 'growth',
    prompt: 'When integrating with B2B partners via AS2, what is the significance of the "MIC" (Message Integrity Check) algorithm (e.g., SHA-256)?',
    options: [
      { id: 'a', label: 'A cryptographic digest calculated over the uncompressed/unencrypted payload to mathematically prove that the payload was delivered without tampering' },
      { id: 'b', label: 'A microphone test performed during partner phone calls' },
      { id: 'c', label: 'A barcode printed on warehouse shipping labels' },
      { id: 'd', label: 'A speed test measuring network bandwidth' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_29',
    section: 'growth',
    prompt: 'How does the webMethods Command Central tool assist in managing large enterprise environments?',
    options: [
      { id: 'a', label: 'Provides centralized provisioning, automated patching, configuration governance, and lifecycle management for hundreds of webMethods instances across hybrid clouds' },
      { id: 'b', label: 'Acts as a customer CRM tool for sales reps' },
      { id: 'c', label: 'Controls office smart thermostats and lighting' },
      { id: 'd', label: 'Generates PowerPoint presentations from source code' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_30',
    section: 'growth',
    prompt: 'In webMethods Trading Networks, what is the "Partner Onboarding" workflow?',
    options: [
      { id: 'a', label: 'The structured process of creating partner profiles, configuring identifiers (DUNS, AS2 IDs), uploading public X.509 certificates, and validating test EDI transactions' },
      { id: 'b', label: 'Interviewing new software engineering candidates' },
      { id: 'c', label: 'Installing Microsoft Office on partner laptops' },
      { id: 'd', label: 'Registering a business with local government authorities' },
    ],
    correctOptionId: 'a',
  },
];
