import { CertQuestion } from '../types';

export const WEBMETHODS_GROWTH_QUESTIONS: CertQuestion[] = [
  {
    id: 'wm_gro_01',
    section: 'growth',
    prompt: 'In webMethods Trading Networks (TN), what core component evaluates incoming business documents against sender, receiver, document type, and user status to determine the appropriate processing action?',
    options: [
      { id: 'a', label: 'Processing Rule' },
      { id: 'b', label: 'Trading Partner Agreement (TPA)' },
      { id: 'c', label: 'Document Attribute Definition' },
      { id: 'd', label: 'Partner Profile' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_02',
    section: 'growth',
    prompt: 'In B2B EDI integration, what is the role of an AS2 (EDIINT) Message Disposition Notification (MDN)?',
    options: [
      { id: 'a', label: 'To compress outbound EDI transactions using GZIP' },
      { id: 'b', label: 'To provide a cryptographically signed electronic receipt verifying that the receiving partner successfully received and unpacked the AS2 message (Non-Repudiation of Receipt)' },
      { id: 'c', label: 'To delete processed records from the Trading Networks database' },
      { id: 'd', label: 'To trigger an automated invoice payment in SAP' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_gro_03',
    section: 'growth',
    prompt: 'In webMethods EDI Module, which ANSI X12 transaction set represents a standard Purchase Order, and which represents an Electronic Invoice?',
    options: [
      { id: 'a', label: 'EDI 856 (PO) and EDI 810 (Invoice)' },
      { id: 'b', label: 'EDI 997 (PO) and EDI 820 (Invoice)' },
      { id: 'c', label: 'EDI 850 (Purchase Order) and EDI 810 (Invoice)' },
      { id: 'd', label: 'EDI 834 (Purchase Order) and EDI 837 (Invoice)' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_gro_04',
    section: 'growth',
    prompt: 'What is the function of a Functional Acknowledgement (X12 997 / UN/EDIFACT CONTRL) in B2B transaction processing?',
    options: [
      { id: 'a', label: 'To verify the identity of the server hosting the database' },
      { id: 'b', label: 'To restart the Integration Server cluster' },
      { id: 'c', label: 'To calculate currency exchange rates between partners' },
      { id: 'd', label: 'To report syntactical and structural acceptance or rejection of an EDI interchange or functional group back to the sender' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_gro_05',
    section: 'growth',
    prompt: 'In webMethods Trading Networks, what is a "Trading Partner Agreement" (TPA) used for?',
    options: [
      { id: 'a', label: 'To define pair-specific bilateral business parameters, split rules, and communication configurations agreed upon between two specific trading partners' },
      { id: 'b', label: 'To store legal employment contracts for software consultants' },
      { id: 'c', label: 'To license the webMethods product suite annually' },
      { id: 'd', label: 'To manage hardware maintenance schedules in data centers' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_06',
    section: 'growth',
    prompt: 'In webMethods ActiveTransfer (MFT), what is a "Virtual Folder" used for?',
    options: [
      { id: 'a', label: 'A RAM disk configured in the Linux operating system kernel' },
      { id: 'b', label: 'An abstraction layer mapping a user-friendly logical directory path exposed to SFTP/FTPS partners onto physical storage, S3 buckets, or network shares with specific access permissions' },
      { id: 'c', label: 'A temporary folder created during Git pull operations' },
      { id: 'd', label: 'A folder inside Software AG Designer for storing Java source code' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_gro_07',
    section: 'growth',
    prompt: 'When tuning Integration Server performance under heavy transaction load, what parameter controls the maximum concurrent worker threads available to process inbound requests?',
    options: [
      { id: 'a', label: 'watt.server.audit.dbQueueSize' },
      { id: 'b', label: 'com.wm.driver.jdbc.MaxPool' },
      { id: 'c', label: 'Server Thread Pool Maximum Threads (watt.server.threadPool)' },
      { id: 'd', label: 'wrapper.java.maxmemory' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_gro_08',
    section: 'growth',
    prompt: 'In webMethods DevOps automation, what is the purpose of the Asset Build Environment (ABE)?',
    options: [
      { id: 'a', label: 'To execute browser tests in Chrome headless mode' },
      { id: 'b', label: 'To monitor server CPU temperatures in real time' },
      { id: 'c', label: 'To create synthetic customer database records' },
      { id: 'd', label: 'To extract integration assets (packages, configurations, adapter connections) from source control (Git) and compile them into deployable build zip artifacts via Ant/Maven command-line scripts' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_gro_09',
    section: 'growth',
    prompt: 'In webMethods Deployer, what is a "Deployment Set" and "Deployment Map"?',
    options: [
      { id: 'a', label: 'A Deployment Set defines what assets to deploy from source systems; a Deployment Map defines where to deploy them and how to substitute environment-specific variables (like hostnames and connection strings)' },
      { id: 'b', label: 'A network diagram of physical cables connecting server racks' },
      { id: 'c', label: 'A database index table used for querying customer records' },
      { id: 'd', label: 'A Git commit log format definition' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_10',
    section: 'growth',
    prompt: 'When integrating mainframe systems (z/OS, Natural, COBOL) with webMethods, which product provides bidirectional RPC wrappers and high-performance communication with CICS and IMS?',
    options: [
      { id: 'a', label: 'WmCloudStreams' },
      { id: 'b', label: 'webMethods EntireX' },
      { id: 'c', label: 'Universal Messaging Enterprise Manager' },
      { id: 'd', label: 'Trading Networks Console' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_gro_11',
    section: 'growth',
    prompt: 'In webMethods API Portal, what is the primary role of the Developer Portal for external partners?',
    options: [
      { id: 'a', label: 'To run continuous integration builds of Java source code' },
      { id: 'b', label: 'To provide a low-level terminal interface for server administration' },
      { id: 'c', label: 'To provide self-service API discovery, interactive OpenAPI/Swagger documentation, sandbox testing, and API key registration for application developers' },
      { id: 'd', label: 'To store binary database backups' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_gro_12',
    section: 'growth',
    prompt: 'In high-availability webMethods architectures, why are Flow services typically designed to be "Stateless"?',
    options: [
      { id: 'a', label: 'Stateless services cannot connect to external databases' },
      { id: 'b', label: 'Stateless services do not support XML payload parsing' },
      { id: 'c', label: 'Stateless services cannot be invoked over HTTPS' },
      { id: 'd', label: 'Stateless services do not rely on in-memory session state between invocations, allowing any cluster node behind a load balancer to process subsequent client requests seamlessly' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_gro_13',
    section: 'growth',
    prompt: 'What enterprise integration pattern (EIP) is best implemented when transforming diverse proprietary supplier invoice formats into a single standardized internal invoice format before sending to SAP?',
    options: [
      { id: 'a', label: 'Canonical Data Model (CDM) / Normalizer' },
      { id: 'b', label: 'Point-to-Point Spaghetti Architecture' },
      { id: 'c', label: 'Direct Database Replication' },
      { id: 'd', label: 'Dead Letter Queue' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_14',
    section: 'growth',
    prompt: 'In webMethods Microservices Runtime (MSR) containerization on Kubernetes, what probes are configured to determine container health and traffic readiness?',
    options: [
      { id: 'a', label: 'Manual ping commands executed by administrators' },
      { id: 'b', label: 'Liveness and Readiness Probes querying health check REST endpoints (e.g., `/health` or custom health check Flow services)' },
      { id: 'c', label: 'FTP upload tests every 10 seconds' },
      { id: 'd', label: 'SQL SELECT count(*) queries on the audit database' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_gro_15',
    section: 'growth',
    prompt: 'In webMethods Hybrid Integration, how does webMethods.io Integration (iPaaS) connect securely to on-premises webMethods Integration Server behind a corporate firewall?',
    options: [
      { id: 'a', label: 'By placing the internal database directly on the public internet' },
      { id: 'b', label: 'By disabling corporate firewalls during business hours' },
      { id: 'c', label: 'Through the On-Premises Connectivity (OPC) Agent establishing an outbound secure TLS WebSocket tunnel to webMethods.io Cloud' },
      { id: 'd', label: 'Through unencrypted HTTP port forwarding' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_gro_16',
    section: 'growth',
    prompt: 'In webMethods Trading Networks, what happens when an incoming document matches multiple Processing Rules?',
    options: [
      { id: 'a', label: 'Trading Networks crashes and throws an OutOfMemoryError' },
      { id: 'b', label: 'Trading Networks executes all matching rules in random order' },
      { id: 'c', label: 'Trading Networks rejects the document with a duplicate rule error' },
      { id: 'd', label: 'Trading Networks evaluates rules in descending order of rule specificity and sequential rule index, executing only the first matching rule unless configured to continue evaluation' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_gro_17',
    section: 'growth',
    prompt: 'When troubleshooting JVM Garbage Collection pauses affecting webMethods Integration Server latency, what modern Java garbage collector is recommended for large heaps (>4GB) to achieve predictable low pause times?',
    options: [
      { id: 'a', label: 'Garbage-First (G1 GC) or Z Garbage Collector (ZGC)' },
      { id: 'b', label: 'Serial GC (-XX:+UseSerialGC)' },
      { id: 'c', label: 'Disabling garbage collection completely' },
      { id: 'd', label: 'Standard Parallel Old GC with default 10-minute pauses' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_18',
    section: 'growth',
    prompt: 'In webMethods ActiveTransfer Server, what feature allows automated execution of business actions (such as archiving, decrypting PGP, or notifying IS services) immediately upon completion of a file upload?',
    options: [
      { id: 'a', label: 'Manual administrator scripts' },
      { id: 'b', label: 'ActiveTransfer Event Actions (Post-Processing Events / File Trigger Actions)' },
      { id: 'c', label: 'Database triggers on the IS log database' },
      { id: 'd', label: 'Universal Messaging durable subscriptions' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_gro_19',
    section: 'growth',
    prompt: 'In webMethods Command Central (CC), what is the primary capability provided to enterprise infrastructure teams?',
    options: [
      { id: 'a', label: 'Editing graphical BPMN process models in a browser' },
      { id: 'b', label: 'Creating SQL tables in Oracle databases' },
      { id: 'c', label: 'Centralized lifecycle management, automated provisioning, configuration templating, fix patching, and health monitoring across multi-tier webMethods landscapes' },
      { id: 'd', label: 'Designing EDI mapping stylesheets' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_gro_20',
    section: 'growth',
    prompt: 'In B2B Trading Partner onboarding, what is the best practice process for adding a new EDI trading partner into webMethods Trading Networks?',
    options: [
      { id: 'a', label: 'Directly modifying the underlying SQL database tables via SQL*Plus' },
      { id: 'b', label: 'Restarting all Integration Server cluster nodes' },
      { id: 'c', label: 'Hardcoding partner DUNS numbers inside Flow BRANCH steps' },
      { id: 'd', label: 'Creating a Partner Profile in TN, configuring external IDs (DUNS, AS2 ID), importing certificates, defining TPAs, and configuring specific Processing Rules' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_gro_21',
    section: 'growth',
    prompt: 'In webMethods Trading Networks, what is a "Document Attribute" and how is it populated during document receipt?',
    options: [
      { id: 'a', label: 'A named field (e.g., SenderID, ReceiverID, TotalAmount, PONumber) extracted from the incoming payload via XPath, WQL, or custom extraction service and indexed in the TN database' },
      { id: 'b', label: 'An OS-level file permission attribute like chmod 755' },
      { id: 'c', label: 'The MAC address of the sending network card' },
      { id: 'd', label: 'A JVM compiler flag passed to the bytecode verifier' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_22',
    section: 'growth',
    prompt: 'In webMethods API Gateway, what is "API Monetization" and how is it implemented?',
    options: [
      { id: 'a', label: 'Buying and selling cryptocurrency tokens on public exchanges' },
      { id: 'b', label: 'Associating API consumption plans and quotas with billing models (e.g., pay-per-call, tiered subscription) to charge API consumers via payment provider integrations' },
      { id: 'c', label: 'Mining Bitcoin on idle Integration Server CPU cores' },
      { id: 'd', label: 'Charging developers a fee to open Software AG Designer' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_gro_23',
    section: 'growth',
    prompt: 'In an active-active Universal Messaging realm cluster, how is high availability and quorum consensus maintained during node failover?',
    options: [
      { id: 'a', label: 'Through manual reboot commands from system administrators' },
      { id: 'b', label: 'Through DNS round-robin without cluster awareness' },
      { id: 'c', label: 'Using UM Realm Clustering with Prime/Replica quorum consensus ensuring state synchronization and automatic failover' },
      { id: 'd', label: 'By storing all messages in a single shared NFS text file' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_gro_24',
    section: 'growth',
    prompt: 'What is the primary benefit of decoupling enterprise applications using webMethods Publish-Subscribe messaging over direct synchronous point-to-point REST/SOAP calls?',
    options: [
      { id: 'a', label: 'It eliminates the need for software testing' },
      { id: 'b', label: 'It reduces hardware server costs to zero' },
      { id: 'c', label: 'It makes all API calls execute in under 1 millisecond' },
      { id: 'd', label: 'Temporal decoupling, load leveling/peak shaving, independent scalability of consumers, and fault tolerance against backend downtime' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_gro_25',
    section: 'growth',
    prompt: 'In webMethods, what is the role of the "WmMonitor" package and the Process / Service Monitoring interface in MWS?',
    options: [
      { id: 'a', label: 'To track, monitor, resubmit, and analyze the real-time execution status of Flow services, B2B transactions, and BPM business processes' },
      { id: 'b', label: 'To monitor employee internet browsing history' },
      { id: 'c', label: 'To format hard drives on cluster nodes' },
      { id: 'd', label: 'To convert C# applications into Java' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_26',
    section: 'growth',
    prompt: 'What capability in webMethods Trading Networks allows administrators to re-execute a failed B2B document without requiring the external partner to retransmit the file?',
    options: [
      { id: 'a', label: 'Database drop and recreate script' },
      { id: 'b', label: 'Document Resubmit (Reprocess / Resend) from the Trading Networks or MWS Monitor console' },
      { id: 'c', label: 'Automated email request to the trading partner' },
      { id: 'd', label: 'Server wrapper restart' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_gro_27',
    section: 'growth',
    prompt: 'When designing a Disaster Recovery (DR) strategy for webMethods across two data centers (Primary and Secondary), what component requires real-time storage replication or active-passive database synchronization?',
    options: [
      { id: 'a', label: 'Designer workspace metadata files' },
      { id: 'b', label: 'Local developer workstations' },
      { id: 'c', label: 'The Core IS Databases (Audit, Trading Networks, BPM, Document History) and Universal Messaging persistent stores' },
      { id: 'd', label: 'The web browser cache on client laptops' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_gro_28',
    section: 'growth',
    prompt: 'In webMethods API Gateway, what is the purpose of the "Traffic Routing / Load Balancing" policy on an API?',
    options: [
      { id: 'a', label: 'To block all outbound internet traffic from the gateway' },
      { id: 'b', label: 'To compress database backups before archiving' },
      { id: 'c', label: 'To convert HTTP GET requests into SOAP responses' },
      { id: 'd', label: 'To distribute incoming API traffic across multiple backend endpoints using Round Robin, Weighted, or Failover routing algorithms' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_gro_29',
    section: 'growth',
    prompt: 'In webMethods, how is "Large File Handling" optimized when processing multi-gigabyte flat files or XML feeds to avoid OutOfMemoryErrors in the JVM?',
    options: [
      { id: 'a', label: 'Using Stream-based processing, Flat File Iterators (`pub.flatFile:getRecord`), and node iterators instead of loading the entire document into an in-memory IData tree' },
      { id: 'b', label: 'Increasing Java heap to 1 Terabyte' },
      { id: 'c', label: 'Converting the file to base64 string in memory' },
      { id: 'd', label: 'Splitting files using external zip tools before starting IS' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_gro_30',
    section: 'growth',
    prompt: 'In webMethods Continuous Delivery, what is the role of Command Central Composite Templates?',
    options: [
      { id: 'a', label: 'To design email newsletters for trading partners' },
      { id: 'b', label: 'Infrastructure-as-Code (IaC) YAML definitions that describe the desired topology, products, fixes, licenses, and configurations to provision and configure identical environments automatically' },
      { id: 'c', label: 'To create graphical user interface themes for Designer' },
      { id: 'd', label: 'To generate mock REST payloads for testing' },
    ],
    correctOptionId: 'b',
  },
];
