import { CertQuestion } from '../types';

export const WEBMETHODS_LITERACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'wm_lit_01',
    section: 'literacy',
    prompt: 'In webMethods Integration Server (IS), what is the "pipeline" and how is data passed between services?',
    options: [
      { id: 'a', label: 'A static relational database table that stores global variables across all client sessions' },
      { id: 'b', label: 'A transient in-memory data structure (IData object) containing input, output, and intermediate variables during service execution' },
      { id: 'c', label: 'A durable JMS topic that buffers message payloads between IS packages' },
      { id: 'd', label: 'A file-based XML cache maintained on the disk of the Integration Server node' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_02',
    section: 'literacy',
    prompt: 'When building a Flow service in Software AG Designer, which flow step is used to conditionally execute different execution paths based on variable values or Boolean expressions?',
    options: [
      { id: 'a', label: 'BRANCH' },
      { id: 'b', label: 'REPEAT' },
      { id: 'c', label: 'LOOP' },
      { id: 'd', label: 'MAP' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_03',
    section: 'literacy',
    prompt: 'In a webMethods BRANCH step, if the "Evaluate Labels" property is set to "True", how does the Integration Server evaluate the child step labels?',
    options: [
      { id: 'a', label: 'It matches the exact string value of the variable specified in the Switch property' },
      { id: 'b', label: 'It executes all child steps in parallel regardless of conditions' },
      { id: 'c', label: 'It evaluates each child label as a conditional expression (e.g., %orderTotal% > 1000 or %status% == "ACTIVE")' },
      { id: 'd', label: 'It treats labels as regular expressions against HTTP invocation headers' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_lit_04',
    section: 'literacy',
    prompt: 'What is the primary purpose of dropping unnecessary variables from the pipeline using the Pipeline Editor in a MAP step?',
    options: [
      { id: 'a', label: 'To delete records from the underlying IS relational database tables' },
      { id: 'b', label: 'To encrypt sensitive field values before transmission over HTTP' },
      { id: 'c', label: 'To automatically commit pending database adapter transactions' },
      { id: 'd', label: 'To conserve memory, prevent variable pollution, and avoid unintended inputs leaking into downstream services' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_lit_05',
    section: 'literacy',
    prompt: 'Which Java interface in the webMethods Java API is the fundamental abstraction used to construct and manipulate key-value data in the Integration Server pipeline?',
    options: [
      { id: 'a', label: 'com.wm.data.IData' },
      { id: 'b', label: 'com.softwareag.pipeline.DataMap' },
      { id: 'c', label: 'com.wm.app.b2b.server.ISContext' },
      { id: 'd', label: 'com.wm.lang.flow.FlowStream' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_06',
    section: 'literacy',
    prompt: 'When writing a custom Java service, what is the mandatory practice for managing an IDataCursor after traversing or modifying an IData object?',
    options: [
      { id: 'a', label: 'Call cursor.commit() to persist changes to the Terracotta cluster' },
      { id: 'b', label: 'Call cursor.destroy() inside a finally block to prevent native cursor memory leaks' },
      { id: 'c', label: 'Call cursor.flush() to send remaining bytes over the HTTP socket' },
      { id: 'd', label: 'No cleanup is needed because Java garbage collection automatically manages IDataCursors' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_07',
    section: 'literacy',
    prompt: 'In webMethods Flow exception handling, what standard pattern is implemented to capture runtime service errors and execute compensation logic?',
    options: [
      { id: 'a', label: 'A SEQUENCE step with Exit on SUCCESS (Try), followed by a SEQUENCE step with Exit on DONE (Catch)' },
      { id: 'b', label: 'A REPEAT step configured with Count = 0 and Exit on ERROR' },
      { id: 'c', label: 'A parent SEQUENCE step with Exit on SUCCESS, containing a Try SEQUENCE (Exit on FAILURE) and a Catch SEQUENCE (Exit on DONE)' },
      { id: 'd', label: 'An interceptor Java filter registered in server.cnf' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_lit_08',
    section: 'literacy',
    prompt: 'Which built-in service is called in the Catch block of a Flow service to extract full error diagnostics, including error message, service call stack, and pipeline dump?',
    options: [
      { id: 'a', label: 'pub.flow:debugLog' },
      { id: 'b', label: 'pub.flow:clearPipeline' },
      { id: 'c', label: 'pub.event:publishError' },
      { id: 'd', label: 'pub.flow:getLastError' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_lit_09',
    section: 'literacy',
    prompt: 'In webMethods Flow services, what is the behavior of the EXIT step when configured with "Signal = FAILURE" and "Exit from = $flow"?',
    options: [
      { id: 'a', label: 'It immediately terminates the entire top-level Flow service and throws a ServiceException with the specified failure message' },
      { id: 'b', label: 'It restarts the current loop iteration from the beginning' },
      { id: 'c', label: 'It ignores the error and continues to the next sequential step' },
      { id: 'd', label: 'It pauses the Integration Server thread for 30 seconds before retrying' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_10',
    section: 'literacy',
    prompt: 'What is the function of the LOOP flow step in Software AG Designer?',
    options: [
      { id: 'a', label: 'To repeatedly execute child steps until a specified mathematical condition is met' },
      { id: 'b', label: 'To iterate over each element of a String List, Document List, or Object List in the pipeline' },
      { id: 'c', label: 'To keep an HTTP connection alive indefinitely' },
      { id: 'd', label: 'To poll an external SFTP server on a scheduled cron interval' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_11',
    section: 'literacy',
    prompt: 'When configuring a REPEAT step in a Flow service, what does the "Repeat on" property determine?',
    options: [
      { id: 'a', label: 'The maximum memory limit allowed before aborting the loop' },
      { id: 'b', label: 'The number of parallel threads allocated to the repeat block' },
      { id: 'c', label: 'Whether child steps re-execute upon SUCCESS or upon FAILURE of the child steps' },
      { id: 'd', label: 'The network protocol used to retry downstream service requests' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_lit_12',
    section: 'literacy',
    prompt: 'In webMethods Flow variable substitution, what syntax is used within string properties or transformers to resolve the runtime value of variable "customerID"?',
    options: [
      { id: 'a', label: '${customerID}' },
      { id: 'b', label: '#customerID#' },
      { id: 'c', label: '{{customerID}}' },
      { id: 'd', label: '%customerID%' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_lit_13',
    section: 'literacy',
    prompt: 'Which built-in service is commonly used to parse an incoming raw XML string into an XML Node prior to document conversion?',
    options: [
      { id: 'a', label: 'pub.xml:xmlStringToXMLNode' },
      { id: 'b', label: 'pub.string:toXML' },
      { id: 'c', label: 'pub.schema:validateXML' },
      { id: 'd', label: 'pub.json:jsonStringToXML' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_14',
    section: 'literacy',
    prompt: 'After generating an XML Node with pub.xml:xmlStringToXMLNode, which service converts the XML Node into a structured webMethods IData Document (IS Document)?',
    options: [
      { id: 'a', label: 'pub.xml:xmlNodeToStream' },
      { id: 'b', label: 'pub.xml:xmlNodeToDocument' },
      { id: 'c', label: 'pub.document:normalizeDocument' },
      { id: 'd', label: 'pub.flatFile:convertToIData' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_15',
    section: 'literacy',
    prompt: 'What is the purpose of an "IS Schema" created from an XSD (XML Schema Definition) in Software AG Designer?',
    options: [
      { id: 'a', label: 'To configure JDBC database connection pooling parameters' },
      { id: 'b', label: 'To define user authentication credentials in the LDAP server' },
      { id: 'c', label: 'To define structural constraints, data types, and business rules for validating XML documents via pub.schema:validate' },
      { id: 'd', label: 'To compile Java bytecode directly into the Linux kernel' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_lit_16',
    section: 'literacy',
    prompt: 'When parsing incoming JSON payloads in webMethods 10.x, which built-in service parses a JSON string or stream directly into an IS Document?',
    options: [
      { id: 'a', label: 'pub.xml:documentToJSON' },
      { id: 'b', label: 'pub.string:jsonParser' },
      { id: 'c', label: 'pub.mime:parseJSON' },
      { id: 'd', label: 'pub.json:jsonStringToDocument' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_lit_17',
    section: 'literacy',
    prompt: 'What configuration file in the package directory (`IntegrationServer/packages/<PackageName>/`) contains package dependencies, version info, and startup/shutdown service declarations?',
    options: [
      { id: 'a', label: 'manifest.v3' },
      { id: 'b', label: 'package.json' },
      { id: 'c', label: 'server.cnf' },
      { id: 'd', label: 'service.idf' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_18',
    section: 'literacy',
    prompt: 'What happens when a package in webMethods Integration Server has a declared dependency on another package that is disabled or missing?',
    options: [
      { id: 'a', label: 'Integration Server crashes and refuses to start' },
      { id: 'b', label: 'The dependent package fails to load and is flagged with a dependency warning or error in the Package Manager' },
      { id: 'c', label: 'Integration Server automatically downloads the missing package from public Maven central' },
      { id: 'd', label: 'The dependent package is automatically converted into a C++ binary' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_19',
    section: 'literacy',
    prompt: 'In webMethods Integration Server, what is a "Startup Service" configured in a package manifest?',
    options: [
      { id: 'a', label: 'A service executed whenever an HTTP client sends a POST request' },
      { id: 'b', label: 'A service that executes in a background thread only when the server CPU is below 10%' },
      { id: 'c', label: 'A service that executes automatically when the package is loaded or reloaded during server startup' },
      { id: 'd', label: 'A service that compiles all Java classes in the WmRoot directory' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_lit_20',
    section: 'literacy',
    prompt: 'Which built-in service allows a Flow service to invoke another service asynchronously without blocking the calling thread?',
    options: [
      { id: 'a', label: 'pub.flow:invokeDirect' },
      { id: 'b', label: 'pub.flow:repeat' },
      { id: 'c', label: 'pub.client:http' },
      { id: 'd', label: 'pub.flow:spawn' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_lit_21',
    section: 'literacy',
    prompt: 'When using `pub.flow:debugLog`, what log level should be selected for messages that are intended to be recorded in the server.log file under default logging settings?',
    options: [
      { id: 'a', label: 'Level 0, 1, or 2 (Fatal, Error, Warn/Info depending on server log level configuration)' },
      { id: 'b', label: 'Level 10 (Trace only)' },
      { id: 'c', label: 'Level 99 (Diagnostic memory dump)' },
      { id: 'd', label: 'Level -1 (Disabled)' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_22',
    section: 'literacy',
    prompt: 'What is the purpose of the "Scope" property in a MAP or SEQUENCE step in Software AG Designer?',
    options: [
      { id: 'a', label: 'To restrict the step execution to specific geographic IP ranges' },
      { id: 'b', label: 'To restrict the pipeline visible to the step to only a specified child Document, preventing unintended side effects' },
      { id: 'c', label: 'To enforce ACID transaction isolation level SERIALIZABLE on the database' },
      { id: 'd', label: 'To convert the service execution into a native microservice container' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_23',
    section: 'literacy',
    prompt: 'In webMethods Flow services, what is a "Transformer" inside a MAP step?',
    options: [
      { id: 'a', label: 'An electrical hardware sensor connected to the server chassis' },
      { id: 'b', label: 'A specialized adapter connection for Apache Kafka clusters' },
      { id: 'c', label: 'A service (e.g., string concatenation or math operation) invoked directly within the MAP step to transform specific inputs into outputs without altering the global pipeline structure' },
      { id: 'd', label: 'A shell script invoked in the underlying Linux operating system' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_lit_24',
    section: 'literacy',
    prompt: 'Which webMethods built-in package is protected, contains core server administration services, and should NEVER have custom business services created inside it?',
    options: [
      { id: 'a', label: 'WmJDBC' },
      { id: 'b', label: 'WmPublic' },
      { id: 'c', label: 'WmART' },
      { id: 'd', label: 'WmRoot' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_lit_25',
    section: 'literacy',
    prompt: 'Which built-in package in webMethods Integration Server contains officially supported public utility services accessible across all custom packages?',
    options: [
      { id: 'a', label: 'WmPublic' },
      { id: 'b', label: 'WmRoot' },
      { id: 'c', label: 'WmPrivate' },
      { id: 'd', label: 'WmCore' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_26',
    section: 'literacy',
    prompt: 'What is the primary function of `pub.date:formatDate` in webMethods Flow services?',
    options: [
      { id: 'a', label: 'To synchronize the hardware BIOS clock with an NTP server' },
      { id: 'b', label: 'To convert a date string or Date object from an input pattern (e.g., yyyy-MM-dd) into an output pattern (e.g., dd/MM/yyyy HH:mm:ss)' },
      { id: 'c', label: 'To set the expiration date of an SSL/TLS certificate' },
      { id: 'd', label: 'To schedule a cron trigger for message processing' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_27',
    section: 'literacy',
    prompt: 'When invoking a REST service or external HTTP endpoint in webMethods, which built-in service is utilized?',
    options: [
      { id: 'a', label: 'pub.soap:invoke' },
      { id: 'b', label: 'pub.file:getFile' },
      { id: 'c', label: 'pub.client:http' },
      { id: 'd', label: 'pub.remote:invoke' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_lit_28',
    section: 'literacy',
    prompt: 'In webMethods Designer, what is the significance of the "Validate Input" and "Validate Output" properties on a Flow service signature?',
    options: [
      { id: 'a', label: 'They compile the Flow service into a native C++ shared library' },
      { id: 'b', label: 'They execute an antivirus scan on the incoming payload' },
      { id: 'c', label: 'They verify the database connection pool health before invoking the service' },
      { id: 'd', label: 'They enforce strict runtime data validation against the defined input/output document structure and data types' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_lit_29',
    section: 'literacy',
    prompt: 'What is the main advantage of creating and referencing an "IS Document Type" rather than creating ad-hoc record definitions across multiple Flow services?',
    options: [
      { id: 'a', label: 'It creates a reusable canonical data model ensuring consistency, schema validation, and refactoring safety across all integration services' },
      { id: 'b', label: 'It compresses pipeline payloads using GZIP algorithms automatically' },
      { id: 'c', label: 'It bypasses Integration Server ACL security checks' },
      { id: 'd', label: 'It converts JSON payloads into COBOL copybooks at runtime' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_30',
    section: 'literacy',
    prompt: 'In webMethods server administration, where are Integration Server JVM parameters (such as -Xms, -Xmx, GC algorithm settings) configured?',
    options: [
      { id: 'a', label: 'In the webMethods Designer Preferences dialog' },
      { id: 'b', label: 'In the custom_wrapper.conf or setenv.bat / setenv.sh configuration file' },
      { id: 'c', label: 'In the manifest.v3 file of the WmPublic package' },
      { id: 'd', label: 'In the Trading Networks partner profile configuration screen' },
    ],
    correctOptionId: 'b',
  },
];
