import { CertQuestion } from '../types';

export const WEBMETHODS_LITERACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'wm_lit_01',
    section: 'literacy',
    prompt: 'In webMethods Integration Server (IS), what is the "pipeline" and how is data passed between services?',
    options: [
      { id: 'a', label: 'A static database table that stores global variables across all client sessions' },
      { id: 'b', label: 'A transient in-memory data structure (IData object) containing input, output, and intermediate variables during service execution' },
      { id: 'c', label: 'A durable JMS topic that buffers message payloads between IS packages' },
      { id: 'd', label: 'A file-based XML cache maintained on the disk of the Integration Server node' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_02',
    section: 'literacy',
    prompt: 'When building a Flow service in Software AG Designer, which flow step is used to conditionally execute different execution paths based on variable values or Boolean expressions?',
    options: [
      { id: 'a', label: 'BRANCH' },
      { id: 'b', label: 'REPEAT' },
      { id: 'c', label: 'LOOP' },
      { id: 'd', label: 'MAP' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_03',
    section: 'literacy',
    prompt: 'In a webMethods BRANCH step, if the "Evaluate Labels" property is set to "True", how does the Integration Server evaluate the target child step labels?',
    options: [
      { id: 'a', label: 'It matches the exact string value of the variable specified in the Switch property' },
      { id: 'b', label: 'It evaluates each child label as a conditional expression (e.g., %orderTotal% > 1000 or %status% == "ACTIVE")' },
      { id: 'c', label: 'It executes all child steps in parallel regardless of condition' },
      { id: 'd', label: 'It treats labels as regular expressions against the service invocation header' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_04',
    section: 'literacy',
    prompt: 'What is the primary purpose of dropping unnecessary variables from the pipeline using the Pipeline Editor in a MAP step?',
    options: [
      { id: 'a', label: 'To delete records from the underlying IS relational database tables' },
      { id: 'b', label: 'To conserve memory, prevent variable pollution, and avoid unintended inputs leaking into downstream services' },
      { id: 'c', label: 'To encrypt sensitive field values before transmission over HTTP' },
      { id: 'd', label: 'To automatically commit pending database adapter transactions' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_05',
    section: 'literacy',
    prompt: 'Which Java interface in the webMethods Java API is the fundamental abstraction used to construct and manipulate key-value data in the Integration Server pipeline?',
    options: [
      { id: 'a', label: 'com.wm.data.IData' },
      { id: 'b', label: 'com.softwareag.pipeline.DataMap' },
      { id: 'c', label: 'com.wm.app.b2b.server.ISContext' },
      { id: 'd', label: 'com.wm.lang.flow.FlowStream' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_06',
    section: 'literacy',
    prompt: 'When writing a custom Java service, what is the mandatory practice for managing an IDataCursor after traversing or modifying an IData object?',
    options: [
      { id: 'a', label: 'Call cursor.commit() to persist changes to the Terracotta cluster' },
      { id: 'b', label: 'Call cursor.destroy() inside a finally block to prevent native cursor memory leaks' },
      { id: 'c', label: 'Call cursor.flush() to send remaining bytes over the HTTP socket' },
      { id: 'd', label: 'No cleanup is needed because Java garbage collection automatically manages IDataCursors' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_07',
    section: 'literacy',
    prompt: 'In webMethods Flow exception handling, what standard pattern is implemented to capture runtime service errors and handle compensation logic?',
    options: [
      { id: 'a', label: 'A SEQUENCE step with Exit on SUCCESS (Try), followed by a SEQUENCE step with Exit on DONE (Catch)' },
      { id: 'b', label: 'A parent SEQUENCE step with Exit on SUCCESS, containing a Try SEQUENCE (Exit on FAILURE) and a Catch SEQUENCE (Exit on DONE)' },
      { id: 'c', label: 'A REPEAT step configured with Count = 0 and Exit on ERROR' },
      { id: 'd', label: 'An interceptor Java filter registered in server.cnf' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_08',
    section: 'literacy',
    prompt: 'Which built-in service is called in the Catch block of a Flow service to extract full error diagnostics, including error message, service call stack, and dump pipeline?',
    options: [
      { id: 'a', label: 'pub.flow:debugLog' },
      { id: 'b', label: 'pub.flow:getLastError' },
      { id: 'c', label: 'pub.flow:clearPipeline' },
      { id: 'd', label: 'pub.event:publishError' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_09',
    section: 'literacy',
    prompt: 'What represents the top-level unit of structural deployment, lifecycle management, and dependency configuration in webMethods Integration Server?',
    options: [
      { id: 'a', label: 'Solution Namespace' },
      { id: 'b', label: 'Package' },
      { id: 'c', label: 'Flow Module' },
      { id: 'd', label: 'Deployment EAR' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_10',
    section: 'literacy',
    prompt: 'What is the role of the manifest.v3 file located in an Integration Server package directory?',
    options: [
      { id: 'a', label: 'Stores user passwords and database connection strings in hashed format' },
      { id: 'b', label: 'Defines package metadata, version numbers, package dependencies, and startup/shutdown service hooks' },
      { id: 'c', label: 'Holds the pre-compiled Java bytecode for all flow services in the package' },
      { id: 'd', label: 'Contains runtime log events generated during service execution' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_11',
    section: 'literacy',
    prompt: 'In Software AG Designer, what is the difference between an IS Document Type and an IS Document Reference?',
    options: [
      { id: 'a', label: 'A Document Type defines a standalone structure; a Document Reference creates a reusable pointer referencing an existing Document Type' },
      { id: 'b', label: 'A Document Type is used exclusively for JSON; Document References are used exclusively for XML' },
      { id: 'c', label: 'Document References store data at runtime; Document Types only exist at compile time' },
      { id: 'd', label: 'Document Types can only be accessed by Java services; Document References by Flow services' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_12',
    section: 'literacy',
    prompt: 'Which flow step is used to iterate over elements of a Document List (array of IData) or String List?',
    options: [
      { id: 'a', label: 'BRANCH' },
      { id: 'b', label: 'LOOP' },
      { id: 'c', label: 'REPEAT' },
      { id: 'd', label: 'MAP' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_13',
    section: 'literacy',
    prompt: 'When configuring a LOOP step over an input array, what must be specified in the "In-array" property?',
    options: [
      { id: 'a', label: 'The exact number of iterations as an integer constant' },
      { id: 'b', label: 'The fully qualified pipeline path to the Document List or Array variable to iterate over' },
      { id: 'c', label: 'The SQL SELECT statement that fetches rows from the database' },
      { id: 'd', label: 'The JMS queue destination where array items are published' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_14',
    section: 'literacy',
    prompt: 'How does the REPEAT flow step differ fundamentally from the LOOP flow step in webMethods?',
    options: [
      { id: 'a', label: 'REPEAT executes child steps repeatedly based on a count or until a SUCCESS/FAILURE condition is met, while LOOP iterates over an existing array' },
      { id: 'b', label: 'REPEAT can only execute Java services, whereas LOOP can execute Flow services' },
      { id: 'c', label: 'REPEAT spawns separate asynchronous background threads for each repetition' },
      { id: 'd', label: 'REPEAT is deprecated and replaced by MAP steps in webMethods 10.x' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_15',
    section: 'literacy',
    prompt: 'In webMethods Flat File parsing, what object defines the hierarchical structure, record identifiers, delimiters, and field positions of fixed-width or delimited text files?',
    options: [
      { id: 'a', label: 'Flat File Dictionary & Flat File Schema' },
      { id: 'b', label: 'XML Document Type' },
      { id: 'c', label: 'WSDL PortType' },
      { id: 'd', label: 'JMS Destination Map' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_16',
    section: 'literacy',
    prompt: 'Which built-in service in the WmFlatFile package is executed to convert an input stream or flat file string into an IS Document based on a defined Flat File Schema?',
    options: [
      { id: 'a', label: 'pub.flatFile:convertToString' },
      { id: 'b', label: 'pub.flatFile:convertToValues' },
      { id: 'c', label: 'pub.flatFile:validateFlatFile' },
      { id: 'd', label: 'pub.flatFile:parseStream' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_17',
    section: 'literacy',
    prompt: 'What built-in service converts a raw JSON string into a strongly-typed webMethods IS Document in the pipeline?',
    options: [
      { id: 'a', label: 'pub.json:jsonStringToDocument' },
      { id: 'b', label: 'pub.xml:xmlStringToXMLNode' },
      { id: 'c', label: 'pub.string:jsonToRecord' },
      { id: 'd', label: 'pub.mime:createMimeData' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_18',
    section: 'literacy',
    prompt: 'What occurs when an IS Flow service invokes "pub.flow:setResponse" with a custom response string and contentType header?',
    options: [
      { id: 'a', label: 'It terminates the entire Integration Server JVM process' },
      { id: 'b', label: 'It sends the specified payload and content-type header directly back to the HTTP client, bypassing default pipeline serialization' },
      { id: 'c', label: 'It redirects the request to a fallback Universal Messaging queue' },
      { id: 'd', label: 'It writes the string into the server error log table' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_19',
    section: 'literacy',
    prompt: 'In webMethods namespace naming conventions, what delimiter is used to separate package folder hierarchies from the service name (e.g., com.company.orders:createOrder)?',
    options: [
      { id: 'a', label: 'Forward slash (/)' },
      { id: 'b', label: 'Colon (:)' },
      { id: 'c', label: 'Double hyphen (--)' },
      { id: 'd', label: 'Dot (.) throughout the entire identifier' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_20',
    section: 'literacy',
    prompt: 'When parsing large multi-gigabyte XML or Flat Files in Integration Server, which architectural pattern prevents OutOfMemoryError (OOM)?',
    options: [
      { id: 'a', label: 'Loading the entire document as a java.lang.String into pipeline memory' },
      { id: 'b', label: 'Using Stream-based parsing with node iterators (pub.xml:getXMLNodeIterator) to process records incrementally without loading the full tree' },
      { id: 'c', label: 'Enabling Java assertions in server.bat' },
      { id: 'd', label: 'Increasing the HTTP connection timeout to 3600 seconds' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_21',
    section: 'literacy',
    prompt: 'What is the function of "pub.flow:savePipeline" and "pub.flow:restorePipeline" built-in services in webMethods development?',
    options: [
      { id: 'a', label: 'They encrypt the pipeline and send it to an external HSM' },
      { id: 'b', label: 'They serialize and persist the current pipeline state to disk during debugging/testing and restore it to recreate test scenarios' },
      { id: 'c', label: 'They synchronize package assets with remote Git repositories' },
      { id: 'd', label: 'They commit database transactions in distributed 2-phase commits' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_22',
    section: 'literacy',
    prompt: 'In Integration Server, what is a "Startup Service" defined within package configuration?',
    options: [
      { id: 'a', label: 'A service executed automatically by Integration Server whenever the package is loaded or IS starts up' },
      { id: 'b', label: 'A cloud microservice deployed to IBM Cloud Satellite' },
      { id: 'c', label: 'A scheduled cron trigger that executes every 60 seconds' },
      { id: 'd', label: 'A health check probe queried by Kubernetes load balancers' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_23',
    section: 'literacy',
    prompt: 'What is the purpose of an "IS Schema" in Software AG webMethods?',
    options: [
      { id: 'a', label: 'A DDL script that generates Oracle database tables' },
      { id: 'b', label: 'An Integration Server asset created from an XML Schema Definition (XSD) used to validate XML documents against business constraints' },
      { id: 'c', label: 'A configuration file containing Universal Messaging realm server URLs' },
      { id: 'd', label: 'A CSS stylesheet used for webMethods Administrator UI themes' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_24',
    section: 'literacy',
    prompt: 'Which service in WmPublic is used to evaluate an XML node against an IS XML Schema and report structural or datatype validation errors?',
    options: [
      { id: 'a', label: 'pub.schema:validate' },
      { id: 'b', label: 'pub.xml:validateXML' },
      { id: 'c', label: 'pub.flow:validatePipeline' },
      { id: 'd', label: 'pub.string:validateFormat' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_25',
    section: 'literacy',
    prompt: 'In a MAP step, what occurs when a developer creates a "Copy" link from a String variable to an Integer variable?',
    options: [
      { id: 'a', label: 'The Flow compiler rejects the link with a fatal build error' },
      { id: 'b', label: 'Integration Server attempts runtime type coercion, parsing the string into an integer if valid or assigning the object directly' },
      { id: 'c', label: 'The target Integer variable is initialized to 0 unconditionally' },
      { id: 'd', label: 'Integration Server creates a new JMS transaction' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_26',
    section: 'literacy',
    prompt: 'What is the significance of the "WmPublic" package in webMethods Integration Server?',
    options: [
      { id: 'a', label: 'A public community package downloaded from GitHub for open-source utilities' },
      { id: 'b', label: 'The core built-in system package containing essential services for flow control, XML/JSON parsing, cryptography, file I/O, and string manipulation' },
      { id: 'c', label: 'A web server package that hosts external REST APIs' },
      { id: 'd', label: 'A legacy package deprecated after the IBM acquisition' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_27',
    section: 'literacy',
    prompt: 'When configuring a REST V2 descriptor in webMethods, what HTTP methods are standardly mapped to CRUD operations?',
    options: [
      { id: 'a', label: 'POST (Create), GET (Read), PUT/PATCH (Update), DELETE (Delete)' },
      { id: 'b', label: 'CONNECT (Create), TRACE (Read), OPTIONS (Update), HEAD (Delete)' },
      { id: 'c', label: 'GET for all operations with an action parameter in the query string' },
      { id: 'd', label: 'INVOKE (Create), FETCH (Read), MODIFY (Update), PURGE (Delete)' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_lit_28',
    section: 'literacy',
    prompt: 'What tool within the webMethods suite provides the centralized web console to administer packages, monitor server threads, configure ports, and manage security certificates?',
    options: [
      { id: 'a', label: 'Software AG Designer' },
      { id: 'b', label: 'Integration Server Administrator (IS Admin Console)' },
      { id: 'c', label: 'Universal Messaging Enterprise Manager' },
      { id: 'd', label: 'webMethods Trading Networks Console' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_29',
    section: 'literacy',
    prompt: 'In webMethods Flow programming, what is the effect of invoking "pub.flow:debugLog"?',
    options: [
      { id: 'a', label: 'It sends an instant notification email to the server administrator' },
      { id: 'b', label: 'It writes a developer-specified message and severity level to the IS server log (server.log)' },
      { id: 'c', label: 'It halts service execution and pauses the thread until a debugger attaches' },
      { id: 'd', label: 'It outputs the pipeline as an HTML table in the client browser' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_lit_30',
    section: 'literacy',
    prompt: 'What is a "Transformer" in a webMethods MAP step?',
    options: [
      { id: 'a', label: 'An embedded service (such as a string manipulation or math service) mapped directly within the MAP step to transform inputs before assignment' },
      { id: 'b', label: 'A hardware appliance used for load balancing Integration Server nodes' },
      { id: 'c', label: 'An EDI translator component located exclusively inside Trading Networks' },
      { id: 'd', label: 'A Java bytecode optimizer that speeds up Flow service execution' },
    ],
    correctOptionId: 'a',
  },
];
