import { CertQuestion } from '../types';

export const WEBMETHODS_PRIVACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'wm_prv_01',
    section: 'privacy',
    prompt: 'In webMethods Integration Server security architecture, what is an "Execute ACL" assigned to a folder or service?',
    options: [
      { id: 'a', label: 'An Access Control List that defines which user groups have permission to invoke or execute the target service' },
      { id: 'b', label: 'An operating system firewall rule restricting TCP port traffic' },
      { id: 'c', label: 'A database grant allowing SQL EXECUTE on stored procedures' },
      { id: 'd', label: 'A Git branch protection rule preventing direct commits' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_02',
    section: 'privacy',
    prompt: 'What is the security consequence if a service in Integration Server has its Execute ACL set to "Anonymous"?',
    options: [
      { id: 'a', label: 'The service cannot be executed by anyone, including administrators' },
      { id: 'b', label: 'The service can be invoked by any client without providing authentication credentials' },
      { id: 'c', label: 'The service automatically encrypts all pipeline inputs with AES-256' },
      { id: 'd', label: 'The service is hidden from the Software AG Designer package navigator' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_prv_03',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, which policy category is configured to validate incoming JSON Web Tokens (JWT) signed by an external identity provider (IdP like Okta or Azure AD)?',
    options: [
      { id: 'a', label: 'XML Threat Protection Policy' },
      { id: 'b', label: 'Outbound HTTP Header Injection Policy' },
      { id: 'c', label: 'Identify & Authorize (JWT / OAuth2 Token Validation Policy)' },
      { id: 'd', label: 'Static Mock Response Policy' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_prv_04',
    section: 'privacy',
    prompt: 'What security mechanism in Integration Server allows secure storage and dynamic lookup of sensitive credentials (e.g., API keys, database passwords) without hardcoding them in Flow services?',
    options: [
      { id: 'a', label: 'Storing credentials in plain text inside server.cnf' },
      { id: 'b', label: 'Writing passwords into the comments section of MAP steps' },
      { id: 'c', label: 'Passing credentials in HTTP URL query parameters' },
      { id: 'd', label: 'Outbound Passwords & Centralized Keystore / Password Manager via "pub.security.outboundPasswords"' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_prv_05',
    section: 'privacy',
    prompt: 'When configuring Mutual TLS (mTLS / 2-way SSL) on an Integration Server HTTPS port, which store contains the trusted Certificate Authority (CA) certificates used to verify incoming client certificates?',
    options: [
      { id: 'a', label: 'Truststore' },
      { id: 'b', label: 'Keystore' },
      { id: 'c', label: 'JDBC Connection Pool' },
      { id: 'd', label: 'Universal Messaging Audit Log' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_06',
    section: 'privacy',
    prompt: 'Which store in webMethods contains the server private key and server identity certificate presented to clients during the SSL/TLS handshake?',
    options: [
      { id: 'a', label: 'Truststore' },
      { id: 'b', label: 'Keystore' },
      { id: 'c', label: 'ACL Repository' },
      { id: 'd', label: 'Terracotta Cache' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_prv_07',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, what is the primary role of the "Threat Protection" policy category?',
    options: [
      { id: 'a', label: 'To compress outbound JSON responses using Brotli algorithms' },
      { id: 'b', label: 'To compile Java bytecode directly into container images' },
      { id: 'c', label: 'To guard APIs against SQL injection, JSON/XML depth and payload size attacks, and malicious regular expressions' },
      { id: 'd', label: 'To replicate API definitions across cloud providers automatically' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_prv_08',
    section: 'privacy',
    prompt: 'How can developers prevent sensitive consumer PII (e.g., Credit Card Numbers, SSNs) from being displayed in plaintext inside server error logs and audit databases?',
    options: [
      { id: 'a', label: 'By disabling server error logging entirely across the cluster' },
      { id: 'b', label: 'By renaming pipeline variables to arbitrary 3-character abbreviations' },
      { id: 'c', label: 'By storing logs exclusively in plain text flat files' },
      { id: 'd', label: 'By configuring Pipeline Variable Masking / Redaction in service auditing settings and logging configurations' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_prv_09',
    section: 'privacy',
    prompt: 'In webMethods Enterprise Gateway architecture, how does the "Reverse Invoke" connection model enhance DMZ perimeter security?',
    options: [
      { id: 'a', label: 'The Internal Integration Server initiates outbound persistent connections to the DMZ Gateway Server, eliminating the need to open inbound firewall ports into the internal secure network' },
      { id: 'b', label: 'The DMZ server opens direct SSH tunnels into the internal database' },
      { id: 'c', label: 'Clients communicate directly with internal servers over raw UDP' },
      { id: 'd', label: 'It replaces all HTTPS certificates with asymmetric PGP keypairs' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_10',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, what policy is used to protect backend services from denial-of-service (DoS) attacks by limiting the number of API calls per second or minute per consumer?',
    options: [
      { id: 'a', label: 'CORS Headers Policy' },
      { id: 'b', label: 'Rate Limiting / Throttling Policy (Spike Arrest / Tiered Traffic Management)' },
      { id: 'c', label: 'Schema Validation Policy' },
      { id: 'd', label: 'Data Transformation Policy' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_prv_11',
    section: 'privacy',
    prompt: 'Which webMethods component provides centralized user management, single sign-on (SSO), and role-based permissions integrated with corporate LDAP / Active Directory servers?',
    options: [
      { id: 'a', label: 'Universal Messaging Enterprise Manager' },
      { id: 'b', label: 'WmFlatFile package' },
      { id: 'c', label: 'My webMethods Server (MWS) Central User Management' },
      { id: 'd', label: 'Asset Build Environment (ABE)' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_prv_12',
    section: 'privacy',
    prompt: 'When auditing a Flow service in webMethods Integration Server, what auditing option records pipeline data when a service fails, allowing developers to inspect failure payloads in WmMonitor?',
    options: [
      { id: 'a', label: 'Audit on Start Only' },
      { id: 'b', label: 'Disable Auditing' },
      { id: 'c', label: 'Purge on Error' },
      { id: 'd', label: 'Audit on Error with "Include Pipeline" enabled' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_prv_13',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, what is the function of the "IP Address Filter" policy?',
    options: [
      { id: 'a', label: 'To whitelist authorized client IP addresses or CIDR blocks and block unauthorized IP addresses before requests reach backend services' },
      { id: 'b', label: 'To dynamically change the Integration Server host IP address' },
      { id: 'c', label: 'To resolve DNS records for external SaaS endpoints' },
      { id: 'd', label: 'To encrypt HTTP packet IP headers with TLS 1.3' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_14',
    section: 'privacy',
    prompt: 'What is the purpose of the "Master Password" in webMethods Integration Server security configuration?',
    options: [
      { id: 'a', label: 'To log into the Linux host as root' },
      { id: 'b', label: 'To encrypt and protect all internal keystore passwords, outbound passwords, and sensitive server configuration secrets stored in config files' },
      { id: 'c', label: 'To provide a universal backdoor password for all REST APIs' },
      { id: 'd', label: 'To set the database administrator password in Oracle' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_prv_15',
    section: 'privacy',
    prompt: 'In webMethods HTTPS port configuration, what setting is required to enforce that incoming HTTP clients MUST present a valid X.509 client certificate during the TLS handshake?',
    options: [
      { id: 'a', label: 'Client Authentication = "No"' },
      { id: 'b', label: 'Client Authentication = "Request"' },
      { id: 'c', label: 'Client Authentication = "Require" (Mutual TLS / 2-Way SSL)' },
      { id: 'd', label: 'Enable CORS = "True"' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_prv_16',
    section: 'privacy',
    prompt: 'Which built-in service in the WmPublic package allows developers to generate cryptographic digital signatures (e.g., RSA-SHA256) over payload data?',
    options: [
      { id: 'a', label: 'pub.string:hash' },
      { id: 'b', label: 'pub.math:addFloats' },
      { id: 'c', label: 'pub.flow:tracePipeline' },
      { id: 'd', label: 'pub.security.pkcs7:sign (or pub.security.keystore:signData)' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_prv_17',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, how does Cross-Origin Resource Sharing (CORS) policy protect web browsers interacting with APIs?',
    options: [
      { id: 'a', label: 'By defining allowed origins, HTTP methods, and headers permitted to invoke the API from browser-based Single Page Applications (SPAs)' },
      { id: 'b', label: 'By blocking all non-HTTPS web traffic across the entire enterprise' },
      { id: 'c', label: 'By caching database query responses in local browser cookies' },
      { id: 'd', label: 'By converting XML payloads to HTML tables automatically' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_18',
    section: 'privacy',
    prompt: 'In Integration Server, what is a "Diagnostic Port" (or Quiesce Port) used for during emergency administration?',
    options: [
      { id: 'a', label: 'A public port used for external marketing webhooks' },
      { id: 'b', label: 'A dedicated internal administrative port configured with restricted ACLs that remains accessible even when primary HTTP listener ports are exhausted or paused' },
      { id: 'c', label: 'A port dedicated to streaming video files' },
      { id: 'd', label: 'A port that only processes EDI 850 documents' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_prv_19',
    section: 'privacy',
    prompt: 'What type of attack does the "XML Bomb / Billion Laughs" attack represent, and how does webMethods XML Threat Protection mitigate it?',
    options: [
      { id: 'a', label: 'A physical explosion inside the server rack mitigated by cooling fans' },
      { id: 'b', label: 'An SQL injection attack mitigated by parameterized queries' },
      { id: 'c', label: 'An exponential entity expansion attack designed to exhaust JVM heap memory, mitigated by restricting DTD processing and maximum entity expansion depth' },
      { id: 'd', label: 'A network packet sniffing attack mitigated by IPsec' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_prv_20',
    section: 'privacy',
    prompt: 'In webMethods security audits, what is the role of the "Audit Log Database" (IS Core Audit Pool)?',
    options: [
      { id: 'a', label: 'Storing temporary developer Git branches' },
      { id: 'b', label: 'Buffering Universal Messaging durable subscriber states' },
      { id: 'c', label: 'Hosting the webMethods Designer installation binaries' },
      { id: 'd', label: 'Persisting immutable records of service execution status, user logins, security errors, and transaction lifecycle milestones for compliance verification' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_prv_21',
    section: 'privacy',
    prompt: 'When using OAuth 2.0 in webMethods Integration Server, which token endpoint is invoked by clients to obtain an access token using Client Credentials Grant?',
    options: [
      { id: 'a', label: 'pub.oauth:getAccessToken (or /invoke/pub.oauth/getToken via HTTP POST)' },
      { id: 'b', label: 'pub.client:http' },
      { id: 'c', label: 'pub.security:login' },
      { id: 'd', label: 'pub.flow:spawn' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_22',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, what is the difference between "Authentication" and "Authorization"?',
    options: [
      { id: 'a', label: 'Authentication encrypts data at rest; Authorization encrypts data in transit' },
      { id: 'b', label: 'Authentication verifies the identity of the calling consumer; Authorization verifies whether that authenticated identity has permission to invoke the specific API or resource' },
      { id: 'c', label: 'Authentication is for SOAP APIs; Authorization is for REST APIs' },
      { id: 'd', label: 'Authentication runs on the DMZ; Authorization runs on the internal database' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_prv_23',
    section: 'privacy',
    prompt: 'What happens when a client certificate presented during mTLS handshake is found in the Certificate Revocation List (CRL) configured in Integration Server Truststore?',
    options: [
      { id: 'a', label: 'The server accepts the connection but logs a warning' },
      { id: 'b', label: 'The server prompts the user for a password fallback' },
      { id: 'c', label: 'The TLS handshake is immediately rejected and the socket connection is terminated' },
      { id: 'd', label: 'The request is forwarded to an unencrypted HTTP port' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_prv_24',
    section: 'privacy',
    prompt: 'In webMethods Designer, what is the purpose of setting "List ACL" on a folder in the package navigator?',
    options: [
      { id: 'a', label: 'To specify which database tables can be queried by the folder' },
      { id: 'b', label: 'To restrict which network subnets can access the folder' },
      { id: 'c', label: 'To automatically generate HTML documentation for services in the folder' },
      { id: 'd', label: 'To control which user groups can view the folder and its contents in Designer and Package Navigator' },
    ],
    correctOptionId: 'd',
  },
  {
    id: 'wm_prv_25',
    section: 'privacy',
    prompt: 'Which encryption standard is recommended for securing Integration Server internal keystores in modern production environments (webMethods 10.x)?',
    options: [
      { id: 'a', label: 'PKCS#12 (.p12 / .pfx) using strong AES-256 cipher suites' },
      { id: 'b', label: 'Legacy DES with 56-bit keys' },
      { id: 'c', label: 'Plain text XML files' },
      { id: 'd', label: 'MD5 checksum hashes' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_26',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, what is the purpose of the "Data Masking" policy applied on outbound API responses?',
    options: [
      { id: 'a', label: 'To convert JSON responses into XML before sending to clients' },
      { id: 'b', label: 'To obscure sensitive response fields (such as credit cards or personal identifiers) using regex replacement or asterisks before returning data to external consumers' },
      { id: 'c', label: 'To compress payloads with GZIP' },
      { id: 'd', label: 'To add copyright notices to the HTTP response header' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_prv_27',
    section: 'privacy',
    prompt: 'When exposing REST APIs on Integration Server, what security vulnerability occurs if input parameters from URL query strings are concatenated directly into SQL queries inside a Java service?',
    options: [
      { id: 'a', label: 'Cross-Site Scripting (XSS)' },
      { id: 'b', label: 'Buffer Overflow' },
      { id: 'c', label: 'SQL Injection (SQLi)' },
      { id: 'd', label: 'Server-Side Request Forgery (SSRF)' },
    ],
    correctOptionId: 'c',
  },
  {
    id: 'wm_prv_28',
    section: 'privacy',
    prompt: 'How does webMethods Integration Server protect against replay attacks when validating WS-Security (WSS) SOAP headers?',
    options: [
      { id: 'a', label: 'By rejecting requests that do not include a client IP address' },
      { id: 'b', label: 'By maintaining an in-memory or database cache of Message Nonces and validating the Nonce and Timestamp window' },
      { id: 'c', label: 'By requiring all SOAP clients to run on the same local subnet' },
      { id: 'd', label: 'By encrypting the entire HTTP TCP packet at Layer 3' },
    ],
    correctOptionId: 'b',
  },
  {
    id: 'wm_prv_29',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, what is the function of "Scopes" in an OAuth2 access token configuration?',
    options: [
      { id: 'a', label: 'To define fine-grained permission boundaries (e.g., read:orders, write:payments) limiting what operations an authenticated application can perform' },
      { id: 'b', label: 'To specify the geographic region of the client' },
      { id: 'c', label: 'To set the maximum CPU core allocation for the request' },
      { id: 'd', label: 'To configure the database schema name for the transaction' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_30',
    section: 'privacy',
    prompt: 'In webMethods security administration, what is the best practice for configuring administrative access to the Integration Server Administrator console (`http://host:5555`) in production?',
    options: [
      { id: 'a', label: 'Leave default Administrator password unchanged for ease of maintenance' },
      { id: 'b', label: 'Enable Anonymous access on port 5555' },
      { id: 'c', label: 'Disable the primary HTTP port, enforce HTTPS with strong TLS ciphers, change the Administrator password, integrate with corporate SSO/MFA, and restrict port access to management subnets' },
      { id: 'd', label: 'Run Integration Server without any network ports configured' },
    ],
    correctOptionId: 'c',
  },
];
