import { CertQuestion } from '../types';

export const WEBMETHODS_PRIVACY_QUESTIONS: CertQuestion[] = [
  {
    id: 'wm_prv_01',
    section: 'privacy',
    prompt: 'In webMethods Integration Server security architecture, what is an "Execute ACL" assigned to a folder or service?',
    options: [
      { id: 'a', label: 'An Access Control List that defines which user groups have permission to invoke the service' },
      { id: 'b', label: 'An operating system firewall rule restricting network ports' },
      { id: 'c', label: 'A database grant allowing SQL EXECUTE on stored procedures' },
      { id: 'd', label: 'A Git branch protection rule preventing direct commits' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_02',
    section: 'privacy',
    prompt: 'What is the consequence if a service in Integration Server has its Execute ACL set to "Anonymous"?',
    options: [
      { id: 'a', label: 'The service can be invoked by any client without providing authentication credentials' },
      { id: 'b', label: 'The service cannot be executed by anyone, including administrators' },
      { id: 'c', label: 'The service automatically encrypts all pipeline inputs with AES-256' },
      { id: 'd', label: 'The service is hidden from the Software AG Designer package navigator' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_03',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, which policy is configured to validate incoming JSON Web Tokens (JWT) signed by an external identity provider (IdP like Okta or Azure AD)?',
    options: [
      { id: 'a', label: 'Identify & Authorize (JWT / OAuth2 Token Validation Policy)' },
      { id: 'b', label: 'XML Threat Protection Policy' },
      { id: 'c', label: 'Outbound HTTP Header Injection Policy' },
      { id: 'd', label: 'Static Mock Response Policy' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_04',
    section: 'privacy',
    prompt: 'What security mechanism in Integration Server allows secure storage and dynamic lookup of sensitive credentials (e.g., API keys, database passwords) without hardcoding them in Flow services?',
    options: [
      { id: 'a', label: 'Outbound Passwords & Centralized Keystore / Password Manager via "pub.security.outboundPasswords"' },
      { id: 'b', label: 'Storing plain text credentials in server.cnf' },
      { id: 'c', label: 'Writing passwords into the comments section of MAP steps' },
      { id: 'd', label: 'Passing credentials in HTTP URL query parameters' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_05',
    section: 'privacy',
    prompt: 'When configuring Mutual TLS (mTLS / 2-way SSL) on an Integration Server HTTPS port, which store contains the trusted Certificate Authority (CA) certificates used to verify incoming client certificates?',
    options: [
      { id: 'a', label: 'Truststore' },
      { id: 'b', label: 'Keystore' },
      { id: 'c', label: 'JDBC Connection Pool' },
      { id: 'd', label: 'Universal Messaging Audit Log' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_06',
    section: 'privacy',
    prompt: 'Which store in webMethods contains the server private key and server identity certificate presented to clients during the SSL/TLS handshake?',
    options: [
      { id: 'a', label: 'Keystore' },
      { id: 'b', label: 'Truststore' },
      { id: 'c', label: 'ACL Repository' },
      { id: 'd', label: 'Terracotta Cache' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_07',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, what is the role of the "Threat Protection" policy category?',
    options: [
      { id: 'a', label: 'To guard APIs against SQL injection, JSON/XML depth and payload size attacks, and malicious regular expressions' },
      { id: 'b', label: 'To enforce employee clock-in times in the office' },
      { id: 'c', label: 'To scan developer laptops for unapproved software' },
      { id: 'd', label: 'To backup git repositories to tape storage' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_08',
    section: 'privacy',
    prompt: 'How can developers prevent sensitive consumer PII (e.g., Credit Card Numbers, SSNs) from being displayed in plaintext inside server error logs and audit databases?',
    options: [
      { id: 'a', label: 'By configuring Pipeline Variable Masking / Redaction in service auditing settings and logging configurations' },
      { id: 'b', label: 'By turning off server error logging entirely' },
      { id: 'c', label: 'By renaming variables to random 3-letter strings' },
      { id: 'd', label: 'By storing logs in Microsoft Excel format' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_09',
    section: 'privacy',
    prompt: 'Which service in WmPublic is used to encrypt data using symmetric algorithms like AES with a secure secret key?',
    options: [
      { id: 'a', label: 'pub.security:encrypt' },
      { id: 'b', label: 'pub.crypto:hashData' },
      { id: 'c', label: 'pub.string:obfuscate' },
      { id: 'd', label: 'pub.flow:lockVariable' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_10',
    section: 'privacy',
    prompt: 'What is the purpose of the "Deny by Default" port configuration model in webMethods Integration Server?',
    options: [
      { id: 'a', label: 'All incoming HTTP/HTTPS requests to the port are rejected unless explicitly allowed by access mode and IP whitelist filters' },
      { id: 'b', label: 'The server denies all outgoing emails during weekends' },
      { id: 'c', label: 'The port only accepts traffic on local subnet 127.0.0.1' },
      { id: 'd', label: 'Database queries are blocked if they exceed 100 rows' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_11',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, which policy ensures that client applications do not exceed a designated number of API requests within a specific time window (e.g., 500 requests/minute)?',
    options: [
      { id: 'a', label: 'Rate Limiting & Throttling Policy' },
      { id: 'b', label: 'Payload Compression Policy' },
      { id: 'c', label: 'CORS Header Enforcement Policy' },
      { id: 'd', label: 'Schema Validation Policy' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_12',
    section: 'privacy',
    prompt: 'When integrating with enterprise LDAP or Microsoft Active Directory, what component in Integration Server enables centralized corporate authentication for IS users and administrator roles?',
    options: [
      { id: 'a', label: 'Central User Management (CUM) & LDAP / Active Directory Directory Service Configuration' },
      { id: 'b', label: 'Local users.cnf file editing' },
      { id: 'c', label: 'Hardcoding Active Directory passwords in Flow services' },
      { id: 'd', label: 'Universal Messaging Enterprise Manager' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_13',
    section: 'privacy',
    prompt: 'What is the function of "pub.security:generateHMAC" in the webMethods security library?',
    options: [
      { id: 'a', label: 'Generates a Hash-based Message Authentication Code to verify data integrity and authenticity using a shared cryptographic key' },
      { id: 'b', label: 'Generates random user passwords for the Administrator account' },
      { id: 'c', label: 'Calculates the round-trip latency of HTTP requests' },
      { id: 'd', label: 'Creates a digital watermark on PDF invoices' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_14',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, what is an "API Plan" (or API Tier)?',
    options: [
      { id: 'a', label: 'A commercial packaging model that bundles API access with defined SLA limits, rate quotas, and monetization rules for registered developer applications' },
      { id: 'b', label: 'A Gantt chart documenting project delivery milestones' },
      { id: 'c', label: 'A network diagram illustrating Kubernetes pods' },
      { id: 'd', label: 'An architectural review checklist' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_15',
    section: 'privacy',
    prompt: 'What security risk is introduced if developers leave "Save Pipeline" services enabled in production code without proper access controls?',
    options: [
      { id: 'a', label: 'Sensitive customer data in the pipeline is serialized to the server file system in unencrypted format, risking unauthorized data exfiltration' },
      { id: 'b', label: 'The Integration Server CPU usage permanently locks at 100%' },
      { id: 'c', label: 'All database tables are dropped automatically' },
      { id: 'd', label: 'The SSL certificate expires prematurely' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_16',
    section: 'privacy',
    prompt: 'Which webMethods built-in service produces cryptographic digital signatures over input byte arrays using a private key from an IS Keystore?',
    options: [
      { id: 'a', label: 'pub.security.keystore:signData' },
      { id: 'b', label: 'pub.string:hashString' },
      { id: 'c', label: 'pub.flow:validateToken' },
      { id: 'd', label: 'pub.client:authDigest' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_17',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, what policy allows cross-origin web applications in browser environments to make API calls by returning appropriate Access-Control-Allow-Origin headers?',
    options: [
      { id: 'a', label: 'Cross-Origin Resource Sharing (CORS) Policy' },
      { id: 'b', label: 'JSON Threat Protection Policy' },
      { id: 'c', label: 'IP Filtering Policy' },
      { id: 'd', label: 'Kerberos Negotiation Policy' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_18',
    section: 'privacy',
    prompt: 'What is the purpose of the "Read ACL" and "Write ACL" assigned to an Integration Server package?',
    options: [
      { id: 'a', label: 'They determine which developer user groups in Software AG Designer can view or edit the source code and assets of the package' },
      { id: 'b', label: 'They restrict database SELECT and INSERT statements executed by the package' },
      { id: 'c', label: 'They define disk read/write quotas on the host operating system' },
      { id: 'd', label: 'They configure file permissions on FTP servers' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_19',
    section: 'privacy',
    prompt: 'When auditing service execution in Integration Server, where are service audit records and pipeline dumps persisted?',
    options: [
      { id: 'a', label: 'In the centralized IS Audit Database (ISCOREAUDIT / WMSA) configured via database connection pools' },
      { id: 'b', label: 'In local browser cookies' },
      { id: 'c', label: 'In unencrypted temporary text files in /tmp' },
      { id: 'd', label: 'Directly in the source control Git repository' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_20',
    section: 'privacy',
    prompt: 'Which security feature in webMethods prevents Cross-Site Request Forgery (CSRF) attacks against the Integration Server Administrator web console?',
    options: [
      { id: 'a', label: 'CSRF Token Defense Filter and SameSite Cookie policies configured in server.cnf' },
      { id: 'b', label: 'Disabling password requirements on the Administrator account' },
      { id: 'c', label: 'Running Integration Server on port 80 exclusively' },
      { id: 'd', label: 'Using plain HTTP instead of HTTPS' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_21',
    section: 'privacy',
    prompt: 'What is the role of the "pub.security:digest" service in WmPublic?',
    options: [
      { id: 'a', label: 'Generates one-way cryptographic message digests (hashes) using algorithms like SHA-256 or SHA-512' },
      { id: 'b', label: 'Summarizes log files into a daily PDF report' },
      { id: 'c', label: 'Compacts pipeline memory by purging unused variables' },
      { id: 'd', label: 'Defragments database indexes' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_22',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, what is "API Analytics & Audit Logging"?',
    options: [
      { id: 'a', label: 'Real-time telemetry capturing API consumption metrics, response latencies, error codes, and consumer identities for compliance and dashboards' },
      { id: 'b', label: 'An automated code formatting tool for JavaScript' },
      { id: 'c', label: 'A service that automatically submits tax forms' },
      { id: 'd', label: 'A backup tool for developer local workstations' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_23',
    section: 'privacy',
    prompt: 'How is Role-Based Access Control (RBAC) enforced for Integration Server administration tasks?',
    options: [
      { id: 'a', label: 'By creating custom User Groups with granular functional privileges (e.g., Service Execution, Package Management, Server Monitoring) in IS Admin' },
      { id: 'b', label: 'By giving all developers root SSH access to the host server' },
      { id: 'c', label: 'By sharing a single Administrator password across the entire team' },
      { id: 'd', label: 'By disabling user authentication on internal networks' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_24',
    section: 'privacy',
    prompt: 'When configuring an HTTPS Port on Integration Server, why is it critical to disable legacy SSLv3 and early TLS versions (TLS 1.0/1.1)?',
    options: [
      { id: 'a', label: 'To protect against known cryptographic vulnerabilities (such as POODLE and BEAST) and comply with PCI-DSS / HIPAA security standards' },
      { id: 'b', label: 'To reduce RAM consumption on the server' },
      { id: 'c', label: 'To allow older web browsers from 2005 to connect' },
      { id: 'd', label: 'To decrease network bandwidth by 50%' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_25',
    section: 'privacy',
    prompt: 'In webMethods, what is an "IP Access List" configured on an IS Port?',
    options: [
      { id: 'a', label: 'A security rule set specifying allowed (whitelist) or denied (blacklist) client IP address ranges for incoming connections to that port' },
      { id: 'b', label: 'A list of corporate DNS server IP addresses' },
      { id: 'c', label: 'A routing table for outgoing SMTP emails' },
      { id: 'd', label: 'A configuration file containing Universal Messaging cluster IPs' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_26',
    section: 'privacy',
    prompt: 'Which service in WmPublic is used to decode Base64 encoded strings (such as Authorization header tokens or encrypted payloads)?',
    options: [
      { id: 'a', label: 'pub.string:base64Decode' },
      { id: 'b', label: 'pub.crypto:unmask' },
      { id: 'c', label: 'pub.flow:unpackString' },
      { id: 'd', label: 'pub.code:decryptAscii' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_27',
    section: 'privacy',
    prompt: 'What is the purpose of "Outbound TLS Client Authentication" in webMethods Integration Server?',
    options: [
      { id: 'a', label: 'Allows IS to present its own client certificate to external secure servers when invoking outbound HTTPS, FTPS, or AS2 endpoints' },
      { id: 'b', label: 'Forces all external servers to authenticate against IS LDAP' },
      { id: 'c', label: 'Encrypts hard drives on the host operating system' },
      { id: 'd', label: 'Generates SSL certificates automatically without a Certificate Authority' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_28',
    section: 'privacy',
    prompt: 'In webMethods API Gateway, what policy enables transforming sensitive response payloads by removing internal fields before delivering the response to public consumers?',
    options: [
      { id: 'a', label: 'Outbound Payload Transformation & Field Redaction Policy' },
      { id: 'b', label: 'Rate Limiting Policy' },
      { id: 'c', label: 'CORS Header Policy' },
      { id: 'd', label: 'IP Whitelist Policy' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_29',
    section: 'privacy',
    prompt: 'How does webMethods handle expired SSL/TLS certificates configured in Keystores and Truststores?',
    options: [
      { id: 'a', label: 'IS logs certificate expiration warnings in server.log and rejects TLS handshakes if certificate validation fails' },
      { id: 'b', label: 'IS automatically creates a new self-signed certificate and replaces it on disk' },
      { id: 'c', label: 'IS silently ignores expiration dates forever' },
      { id: 'd', label: 'IS sends a payment request to the Certificate Authority' },
    ],
    correctOptionId: 'a',
  },
  {
    id: 'wm_prv_30',
    section: 'privacy',
    prompt: 'What is the security function of "pub.security.keystore:verifySignature"?',
    options: [
      { id: 'a', label: 'Validates a digital signature against the original payload and a public certificate from an IS Truststore' },
      { id: 'b', label: 'Verifies the physical signature on a paper contract' },
      { id: 'c', label: 'Checks if a user password matches security complexity rules' },
      { id: 'd', label: 'Scans source code for potential security bugs' },
    ],
    correctOptionId: 'a',
  },
];
